Home work 1
polis-mail-ru/2020-highload-dht pull request #1
Opened 2020-09-25 12:21 UTC by art241111

2020-09-28 08:23 UTC, lamtev reviewed
Было ли проведено нагрузочное тестирование и профилирование с последующим анализом полученных результатов? Судя по [заданию на 1-й этап](https://github.com/polis-mail-ru/2020-highload-dht#%D1%8D%D1%82%D0%B0%D0%BF-1-http--storage-deadline-2020-09-30) эта часть является обязательной

2020-09-29 09:27 UTC, lamtev requested changes
В дополнение к уже сделанному необходимо:
1. Провести нагрузочное тестирование сервиса и выполнить профилирование
2. Добавить оптимизации
3. Повторить пункт 1 и сравнить результаты
4. Оформить отчет с результатами по пунктам 1 - 3 в формате Markdown

2020-09-29 09:34 UTC, art241111 commented
> В дополнение к уже сделанному необходимо:
> 
> 1. Провести нагрузочное тестирование сервиса и выполнить профилирование
> 2. Добавить оптимизации
> 3. Повторить пункт 1 и сравнить результаты
> 4. Оформить отчет с результатами по пунктам 1 - 3 в формате Markdown

Хорошо, постараюсь сегодня сделать, к сожалению не успевал сделать до этого

2020-09-29 18:42 UTC, art241111 commented
> В дополнение к уже сделанному необходимо:
> 
> 1. Провести нагрузочное тестирование сервиса и выполнить профилирование
> 2. Добавить оптимизации
> 3. Повторить пункт 1 и сравнить результаты
> 4. Оформить отчет с результатами по пунктам 1 - 3 в формате Markdown

Добавил папку с изображениями и небольшой анализ. К сожалению, не знаю как можно улучшить, так как БД на удивление отрабатывает хорошо, а тот случай, когда она требует много ресурсов - исправить сложно.

2020-10-03 00:12 UTC, lamtev requested changes
> К сожалению, не знаю как можно улучшить

По твоему флейм-графу **get.svg** видно, что значительную часть времени занимает чтение данных с диска. Нужно подумать, как можно иногда избегать чтений с диска и брать данные из памяти

По профилированию:
К сожалению, отчет слишком краткий. Нет профилирования в режиме ALLOC. Судя по `put.svg`, запись на диск вообще не происходила. Думаю, было выполнено слишком мало вставок в `dao` (`flushThreshold` не был достигнут)

Что нужно было сделать и отразить в отчете:

1. С помощью `wrk2` обстрелять сервис сначала `PUT` методами. Под нагрузкой выполнить профилирование (CPU + ALLOC). Посмотреть также на вывод `wrk2` - latency distribution
2. Аналогично с `GET` (по уже наполненному данными хранилищу)
3. Оптимизировать узкие места
4. Повторить пункты 1 и 2, и сравнить результаты с тем, что было до оптимизаций

2020-10-03 09:01 UTC, art241111 commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandlers.java
> +            final ByteBuffer duplicate = value.duplicate();
Мне показалось, что это хорошая практика, чтобы случайно не испортить данные в бд..

2020-10-03 09:02 UTC, art241111 commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandlers.java
> +    public Response setGetHandler() {
Хорошо, исправлю. Просто я это воспринял как setter для строки "v0/entity".

2020-10-03 09:05 UTC, art241111 commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandlers.java
> +public class EntityHandlers {
Спасибо, буду знать!

2020-10-03 10:19 UTC, art241111 commented
> > К сожалению, не знаю как можно улучшить
> 
> По твоему флейм-графу **get.svg** видно, что значительную часть времени занимает чтение данных с диска. Нужно подумать, как можно иногда избегать чтений с диска и брать данные из памяти
> 
> По профилированию:
> К сожалению, отчет слишком краткий. Нет профилирования в режиме ALLOC. Судя по `put.svg`, запись на диск вообще не происходила. Думаю, было выполнено слишком мало вставок в `dao` (`flushThreshold` не был достигнут)
> 
> Что нужно было сделать и отразить в отчете:
> 
> 1. С помощью `wrk2` обстрелять сервис сначала `PUT` методами. Под нагрузкой выполнить профилирование (CPU + ALLOC). Посмотреть также на вывод `wrk2` - latency distribution
> 2. Аналогично с `GET` (по уже наполненному данными хранилищу)
> 3. Оптимизировать узкие места
> 4. Повторить пункты 1 и 2, и сравнить результаты с тем, что было до оптимизаций

Подскажите, пожалуйста, что делать, если график alloc выводит нормально (они как раз и были приложены) а CPU выводить пустой граф? 
![image](https://user-images.githubusercontent.com/39194008/94989122-0b156580-057b-11eb-97a4-43f01c70eb66.png)

2020-10-03 10:53 UTC, lamtev commented
> Подскажите, пожалуйста, что делать, если график alloc выводит нормально (они как раз и были приложены) а CPU выводить пустой граф?
> ![image](https://user-images.githubusercontent.com/39194008/94989122-0b156580-057b-11eb-97a4-43f01c70eb66.png)

Пришли плз целиком какие команды `wrk` и `async-profiler` выполнялись:

```zsh
$ wrk2 -t1 -c1 ...
```

```zsh
$ ./profiler.sh ...
```

2020-10-03 11:03 UTC, lamtev commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandlers.java
> +            final ByteBuffer duplicate = value.duplicate();
Ну вот собственно это и был вопрос: можно ли обойтись без дублирования и при этом ничего не сломать, естественно. Зависит от реализации `dao`. Это не было призывом к тому, чтобы просто убрать `duplicate()`

2020-10-03 11:06 UTC, lamtev requested changes
code climate говорит, что остались неиспользованные импорты, нужно поправить

2020-10-03 11:06 UTC, lamtev commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandler.java
> +            logger.error("NoSuchElementException in getting {} from dao", key);
Отсутствие в базе запрашиваемых данных является штатной ситуацией, никак не ошибкой. Уровень логгирования `ERROR` здесь не нужен

2020-10-03 11:06 UTC, lamtev commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandler.java
> +    public Response handlerGetRequest() {
Точно `handler`, а не `handle` ? Вроде выполняем обработку, а не возвращаем обработчик

2020-10-03 11:30 UTC, art241111 commented
> > Подскажите, пожалуйста, что делать, если график alloc выводит нормально (они как раз и были приложены) а CPU выводить пустой граф?
> > ![image](https://user-images.githubusercontent.com/39194008/94989122-0b156580-057b-11eb-97a4-43f01c70eb66.png)
> 
> Пришли плз целиком какие команды `wrk` и `async-profiler` выполнялись:
> 
> ```shell
> $ wrk2 -t1 -c1 ...
> ```
> 
> ```shell
> $ ./profiler.sh ...
> ```

./profiler.sh -d 30 -e cpu -f cpu2.svg 6557
wrk -t1 -c1 -d10m -R2000 -s put.lua --latency  http://127.0.0.1:8080

2020-10-03 11:36 UTC, art241111 commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandlers.java
> +            final ByteBuffer duplicate = value.duplicate();
Подскажите пожалуйста, на будущие. В каких случаях стоит создавать дубликацию, а в каких нет? 
Как я понимаю, у меня возвращается значение из DAO и если там передается не ссылка на объект, а уже продублированная или новая переменная, то мне не нужно делать дубликат, но если мне просто возвращается значение из очереди, то лучше сделать дубликат. Правильно я понимаю?

2020-10-03 11:38 UTC, art241111 commented
> > > Подскажите, пожалуйста, что делать, если график alloc выводит нормально (они как раз и были приложены) а CPU выводить пустой граф?
> > > ![image](https://user-images.githubusercontent.com/39194008/94989122-0b156580-057b-11eb-97a4-43f01c70eb66.png)
> > 
> > 
> > Пришли плз целиком какие команды `wrk` и `async-profiler` выполнялись:
> > ```shell
> > $ wrk2 -t1 -c1 ...
> > ```
> > 
> > 
> > ```shell
> > $ ./profiler.sh ...
> > ```
> 
> ./profiler.sh -d 30 -e cpu -f cpu2.svg 6557 (процесс смотрю через VisualVM)
> wrk -t1 -c1 -d10m -R2000 -s put.lua --latency http://127.0.0.1:8080

2020-10-03 21:57 UTC, lamtev commented on src/main/java/ru/mail/polis/service/art241111/lua/put.lua
> +    path = "/v0/entity?id=key" .. counter .. "&replicas=3/3"
Вопрос не снят

2020-10-03 22:24 UTC, lamtev commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandlers.java
> +            final ByteBuffer duplicate = value.duplicate();
Когда `ByteBuffer` читается, его состояние изменяется (`position` сдвигается). Например, после полного прочтения `postition` указывает в конец. При попытке повторного чтения будет прочитано 0 байтов. Метод `duplicate()` позволяет получить новый `ByteBuffer` со своим собственным состоянием (`position`, ...), но сами байты будут пошарены между ними двумя. Чтение из дублированного буфера не будет приводить к изменению состояния исходного.
Поэтому, если может возникнуть ситуация, когда один буфер может быть прочитан более 1 раза, тогда можно решить эту проблему с помощью `duplicate()`. При параллельном чтении из одного буфера, логично, также стоит делать `duplicate()` на каждый поток.

Вообще в целом, `ByteBuffer` довольно хорошо документирован, рекомендую поизучать. Как устроен внутри. Как изменяется состояние при выполнении каких операций и тд

2020-10-03 22:27 UTC, lamtev commented
> ./profiler.sh -d 30 -e cpu -f cpu2.svg 6557 (процесс смотрю через VisualVM)
> wrk -t1 -c1 -d10m -R2000 -s put.lua --latency http://127.0.0.1:8080

Вроде норм. Не могу сказать в чем дело, с таким не сталкивался. Может были какие-то сообщения в логах об ошибках, которые подскажут в чем дело?

2020-10-03 22:31 UTC, lamtev approved these changes
Реализация ОК. 
5 баллов есть. Для большего нужно разобраться с профилированием

2020-10-04 09:12 UTC, art241111 commented
> > ./profiler.sh -d 30 -e cpu -f cpu2.svg 6557 (процесс смотрю через VisualVM)
> > wrk -t1 -c1 -d10m -R2000 -s put.lua --latency http://127.0.0.1:8080
> 
> Вроде норм. Не могу сказать в чем дело, с таким не сталкивался. Может были какие-то сообщения в логах об ошибках, которые подскажут в чем дело?

Вроде получилось добавив еще раз echo и запустив с root правами. Сейчас оформлю отчет

2020-10-04 10:48 UTC, art241111 commented on src/main/java/ru/mail/polis/service/art241111/lua/put.lua
> +    path = "/v0/entity?id=key" .. counter .. "&replicas=3/3"
Не смог найти об этом информацию( 
Взял из лекции и не проверил.

2020-10-05 11:42 UTC, lamtev commented
@art241111 по отчету не вполне понятно, какие оптимизации были выполнены. И уже можно было смотреть? Прошу нажимать кнопку request review, чтобы я видел, что пора смотреть

2020-10-05 11:49 UTC, art241111 commented
> @art241111 по отчету не вполне понятно, какие оптимизации были выполнены. И уже можно было смотреть? Прошу нажимать кнопку request review, чтобы я видел, что пора смотреть

Убрал логгер :) Я, к сожалению, не знаю как можно еще улучшить 

Прошу прощения, не знал о такой кнопке

2020-10-05 13:07 UTC, lamtev requested changes
Флейм графы и аутпут `wrk`для PUT и GET после "оптимизаций" перепутаны местами

2020-10-05 13:07 UTC, lamtev commented on src/main/java/ru/mail/polis/service/art241111/handlers/EntityHandler.java
> +            logger.error("IOException in getting {} from dao", key);
Проглядел: исключение лучше тоже логгировать, чтобы можно было локализовать проблему:
```java
logger.error("IOException in getting {} from dao", key, e);
```
В остальных местах тоже

2020-10-05 13:22 UTC, lamtev approved these changes

2020-10-05 13:23 UTC, lamtev commented
Принято

2020-10-05 13:23 UTC, closed without merging