Stage 4
polis-mail-ru/2020-highload-dht pull request #101
Opened 2020-10-20 00:09 UTC by JavaUnchained

Отчёт по профилированию в процессе.

2020-10-20 18:26 UTC, JavaUnchained commented
# Проифилирование нагрузки 4-го этапа
Нагрузочное тестирование с помощью wrk2 (код скрипта использовался из stage 1).
На данном этапе стреляем в 64 соединения и 4 потока.

## Анализ PUT-запросов и сравнение с реализацией прошлого этапа
#### Результаты wrk
Мы до замеров производительности понимаем, что результаты рандеву хеширования будут дольше чем по модулю,
по этому чтобы у данного подхода не задирались последние процентили мы пытаемся подобрать оптимальную нагрузку для него.

Обстрел начинался с 50000 запросов в секунуду (оптимальная нагрузка прошлого этапа) и постипенно снижалась до тех пор,
пока 99.999% процентиль не перестал уходить выше 100мс.

Исходя из подхода описанного выше мы подобрали нагрузку в 35 тыс. запросов\секунду.

wrk -t4 -c64 -d20s -s proffiling/lua-scripts/put.lua -R35000 --latency http://127.0.0.1:8080

Учитывая что мы достаточно прогрели наш сервис подбором значений, нам достаточно мерить от 20 секунд, для получения
достоверного результата.

##### Рандеву хеширование
Результаты нагрузки:

    Running 20s test @ http://127.0.0.1:8080
    4 threads and 64 connections
    Thread calibration: mean lat.: 65.052ms, rate sampling interval: 366ms
    Thread calibration: mean lat.: 65.670ms, rate sampling interval: 363ms
    Thread calibration: mean lat.: 64.378ms, rate sampling interval: 360ms
    Thread calibration: mean lat.: 63.440ms, rate sampling interval: 357ms
    Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.95ms     8.17ms  71.68ms   94.70%
    Req/Sec     8.76k   123.96     9.25k    91.67%
    Latency Distribution (HdrHistogram - Recorded Latency)
     50.000%    1.93ms
    75.000%    2.70ms
    90.000%    4.72ms
    99.000%   50.62ms
    99.900%   63.26ms
    99.990%   69.50ms
    99.999%   71.36ms
    100.000%   71.74ms

    Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)
       0.134     0.000000            1         1.00
       1.066     0.100000        34819         1.11
       1.328     0.200000        69485         1.25
       1.537     0.300000       104300         1.43
       1.731     0.400000       138896         1.67
       1.935     0.500000       173588         2.00
       2.051     0.550000       191159         2.22
       2.175     0.600000       208436         2.50
       2.319     0.650000       225812         2.86
       2.487     0.700000       243142         3.33
       2.703     0.750000       260377         4.00
       2.841     0.775000       269077         4.44
       3.013     0.800000       277811         5.00
       3.227     0.825000       286451         5.71
       3.509     0.850000       295103         6.67
       3.929     0.875000       303798         8.00
       4.251     0.887500       308132         8.89
       4.723     0.900000       312468        10.00
       5.559     0.912500       316797        11.43
       6.775     0.925000       321132        13.33
       8.599     0.937500       325482        16.00
      10.311     0.943750       327640        17.78
      14.063     0.950000       329811        20.00
      19.295     0.956250       331981        22.86
      24.943     0.962500       334150        26.67
      30.239     0.968750       336321        32.00
      32.511     0.971875       337409        35.56
      34.495     0.975000       338490        40.00
      36.991     0.978125       339576        45.71
      40.255     0.981250       340660        53.33
      45.375     0.984375       341756        64.00
      47.231     0.985938       342291        71.11
      48.735     0.987500       342832        80.00
      49.951     0.989062       343370        91.43
      51.135     0.990625       343925       106.67
      52.319     0.992188       344466       128.00
      52.863     0.992969       344728       142.22
      53.535     0.993750       345009       160.00
      54.143     0.994531       345279       182.86
      54.943     0.995313       345548       213.33
      55.967     0.996094       345811       256.00
      56.543     0.996484       345948       284.44
      57.407     0.996875       346088       320.00
      58.303     0.997266       346222       365.71
      59.039     0.997656       346356       426.67
      60.223     0.998047       346491       512.00
      60.927     0.998242       346560       568.89
      61.631     0.998437       346626       640.00
      62.239     0.998633       346698       731.43
      62.719     0.998828       346761       853.33
      63.327     0.999023       346829      1024.00
      63.711     0.999121       346867      1137.78
      63.967     0.999219       346897      1280.00
      64.287     0.999316       346931      1462.86
      64.799     0.999414       346967      1706.67
      65.279     0.999512       346998      2048.00
      65.599     0.999561       347015      2275.56
      65.919     0.999609       347034      2560.00
      66.495     0.999658       347051      2925.71
      66.879     0.999707       347067      3413.33
      67.583     0.999756       347083      4096.00
      67.775     0.999780       347091      4551.11
      68.031     0.999805       347101      5120.00
      68.671     0.999829       347108      5851.43
      68.927     0.999854       347117      6826.67
      69.311     0.999878       347127      8192.00
      69.439     0.999890       347130      9102.22
      69.503     0.999902       347136     10240.00
      69.631     0.999915       347139     11702.86
      69.759     0.999927       347144     13653.33
      69.887     0.999939       347146     16384.00
      69.951     0.999945       347148     18204.44
      70.207     0.999951       347152     20480.00
      70.335     0.999957       347153     23405.71
      70.463     0.999963       347155     27306.67
      70.655     0.999969       347158     32768.00
      70.655     0.999973       347158     36408.89
      70.719     0.999976       347160     40960.00
      70.719     0.999979       347160     46811.43
      70.783     0.999982       347161     54613.33
      71.231     0.999985       347162     65536.00
      71.295     0.999986       347163     72817.78
      71.295     0.999988       347163     81920.00
      71.359     0.999989       347164     93622.86
      71.359     0.999991       347164    109226.67
      71.551     0.999992       347166    131072.00
      71.551     0.999993       347166    145635.56
      71.551     0.999994       347166    163840.00
      71.551     0.999995       347166    187245.71
      71.551     0.999995       347166    218453.33
      71.551     0.999996       347166    262144.00
      71.551     0.999997       347166    291271.11
      71.551     0.999997       347166    327680.00
      71.743     0.999997       347167    374491.43
      71.743     1.000000       347167          inf
    #[Mean    =        3.948, StdDeviation   =        8.170]
    #[Max     =       71.680, Total count    =       347167]
    #[Buckets =           27, SubBuckets     =         2048]
    ----------------------------------------------------------
    698608 requests in 20.00s, 55.30MB read
    Requests/sec:  34930.63
    Transfer/sec:      2.77MB

##### По модулю
Результаты нагрузки:

    Running 20s test @ http://127.0.0.1:8080
    4 threads and 64 connections
    Thread calibration: mean lat.: 2.055ms, rate sampling interval: 10ms
    Thread calibration: mean lat.: 2.057ms, rate sampling interval: 10ms
    Thread calibration: mean lat.: 2.040ms, rate sampling interval: 10ms
    Thread calibration: mean lat.: 2.098ms, rate sampling interval: 10ms
    Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.85ms    5.19ms  54.75ms   96.38%
    Req/Sec     9.24k     1.15k   13.78k    75.80%
    Latency Distribution (HdrHistogram - Recorded Latency)
    50.000%    1.83ms
    75.000%    2.47ms
    90.000%    3.43ms
    99.000%   36.96ms
    99.900%   44.10ms
    99.990%   49.63ms
    99.999%   54.33ms
    100.000%   54.78ms

    Detailed Perce [...]

2020-10-26 03:20 UTC, lamtev requested changes
## Реализация

Оставил замечания, рекомендации и вопросы

## Профилирование

Все хорошо, принято. Вот немного комментариев:

> Анализируя результаты двух разных подходов к шардированиб мы видим, что результат рандеву хеширования выполняются с большей задержкой, больше на 30% от классического подхода.

Реализация Рандеву подхода сейчас содержит некоторые лишние операции, можно сделать оптимальнее, и тогда хотя бы на небольшом числе нод результат может быть будет получше

> Анализ графиков и их построение будет проводиться только для основного решения (по модулю). Так как рандеву является бонусным.

Что, неинтересно было попрофилировать, посмотреть какие места "тормозят" по сравнению с реализацией "по модулю"?

2020-10-26 21:59 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +                log.error("No such value key {}.", key);
Сделал уровня info.

2020-10-26 22:00 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +    private static final Logger log = LoggerFactory.getLogger(ServiceImpl.class);
Исправил

2020-10-26 22:00 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +    private final Map<String,HttpClient> nodesClient = new HashMap<>();
Исправил

2020-10-26 22:01 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        final Future<?> future = service.submit(() -> {
Не оправданно, исправил )

2020-10-26 22:05 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +        final int[] hashes = new int[allNodes.length];
Заинлайнил в цикле.

2020-10-26 22:16 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +                        .setUncaughtExceptionHandler((t, e) -> log.error("Error in async_worker-{}:",t,e))
Исправил

2020-10-26 22:18 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +    private String checkIdAndReturnTargetNode(@Param(value = "id", required = true) final String id,
Убрал

2020-10-26 22:18 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +            throw new RuntimeException(e);
Убрал

2020-10-26 22:19 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        if (future.isCancelled()) log.error("Status. Task cancelled");
Исправил

2020-10-26 22:20 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +     * Constructor for modular topology implementation.
Очепятался, исправил

2020-10-26 22:20 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +            throw new RuntimeException("Current not is invalid.");
Исправил

2020-10-26 22:21 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +            throw new RuntimeException("Hash code can't be equals null");
Исправил

2020-10-26 22:21 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ModHashingImpl.java
> +            throw new RuntimeException("Current not is invalid.");
Исправил

2020-10-26 22:22 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +                        log.error("Unsupported method");
Повысил для info

2020-10-26 22:22 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        service.shutdown();
Добавил

2020-10-26 22:23 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +                log.error("Method get. Can't find value by this key ", e);
Сделал info )

2020-10-26 22:25 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        httpServerConfig.queueTime = 10;
В лекции что-то так делали. Изначально queueTime небыло, но когда появился краш на тесте, мне посоветовали установить queueTime.

2020-10-26 22:29 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +            request.addHeader("Forwarding");
Исправил

2020-10-26 22:35 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        service.execute(() -> {
Добавил

2020-10-26 22:39 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        httpServerConfig.queueTime = 10;
Убрал

2020-10-26 22:49 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +                    .setCompactionPriority(CompactionPriority.MinOverlappingRatio);
Убрал, оставив только основные. Но вряд-ли именно это влияет. Потому что все эти настройки взяты из документации по rocksDB, как оптимальные настройки по умолчанию без легаси

2020-10-26 22:56 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +                    default:
Добавил

2020-10-26 23:08 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +                    session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Убрал

2020-10-31 15:20 UTC, lamtev commented
Будут еще исправления или можно смотреть?

2020-11-01 13:29 UTC, JavaUnchained reviewed
> Будут еще исправления или можно смотреть?

Опять перестали приходить уведомления с гита. Все замечания исправил, в течении 20 минут добавлю flame-графы для рандеву, и стрельну wrk по исправленной версии

2020-11-01 13:29 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +            nodeIdentifier[i] = allNodes[i].chars().sum();
исправил

2020-11-01 13:29 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +            nodeIdentifier[i] = allNodes[i].chars().sum();
исправил

2020-11-01 13:29 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +            nodeIdentifier[i] = allNodes[i].chars().sum();
вынес в конструктор вычисление хешей нод

2020-11-01 13:29 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +    public String identifyByKey(final ByteBuffer key) {
сделал его принимающим byte[]

2020-11-01 16:19 UTC, JavaUnchained commented on proffiling/stage4/results.md
> +Анализируя результаты двух разных подходов к шардированиб мы видим, что результат рандеву хеширования
Да, и правда очень даже лучше )

2020-11-01 16:26 UTC, JavaUnchained commented
Добавил флейм графы для рандеву [в этот файл](https://github.com/JavaUnchained/2020-highload-dht/blob/master/proffiling/stage4/newdata.md) . В целом ситуация улучшилась для обоих реализаций, стала ниже задержка и поднял Rate с 35 000 до 45 000, по этому там же ещё результаты wrk и общее заключение по скорости работы обоих реализаций. Сами флеймграфы для рандеву анализировал с точки зрения затрат на хеширование. По итогу мы тратим больше памяти но занимаем меньше процессорного времени.

2020-11-02 12:19 UTC, lamtev requested changes
Остались недочеты, лучше все-таки поправить. Можно не перепрофилировать

2020-11-02 12:19 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +            nodesAndHashes.put(entry.getValue().putBytes(key).hash().hashCode(), entry.getKey());
а точно можно Hasher переиспользовать?

2020-11-02 12:19 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +    final Map<String, Hasher> nodeHashes;
в принципе, можно ведь обойтись отсортированным массивом

2020-11-02 12:19 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +            } catch (RejectedExecutionException e) {
RejectedExecutionException выбрасывается методом service.execute. Текущая обработка некорректна

2020-11-02 12:19 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        return topology.identifyByKey(id.getBytes(UTF_8));
убрали ByteBuffer, хорошо. но в теории id.getBytes тоже можно только в 1 месте делать, а не в нескольких, как это сейчас происходит. чтобы уже по максимуму минимизировать копирования

2020-11-02 12:19 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        httpServerConfig.maxWorkers = Runtime.getRuntime().availableProcessors();
воркеры не используются, а значит эта настройка не нужна

2020-11-02 12:19 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +    final Map<String, Hasher> nodeHashes;
и можно в методе identifyByKey 1 раз обходить массив и определять текущий минимум, который в итоге будет результатом

2020-11-02 18:23 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        httpServerConfig.maxWorkers = Runtime.getRuntime().availableProcessors();
убрал

2020-11-02 18:51 UTC, JavaUnchained reviewed
Пофиксил

2020-11-02 18:51 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +            nodesAndHashes.put(entry.getValue().putBytes(key).hash().hashCode(), entry.getKey());
Сделал интовую мапу

2020-11-02 18:51 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +            } catch (RejectedExecutionException e) {
Исправил

2020-11-02 18:51 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +        return topology.identifyByKey(id.getBytes(UTF_8));
Вынес в отдельную переменную

2020-11-02 18:51 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +    final Map<String, Hasher> nodeHashes;
Согласен, у нас есть массив нод, который отсортирован, я завёл ещё один массив и считаю хеши в него, порядок нод в таком случае детерминирован. В identifyByKey идёт массив вместо мапы. Если я конечно правильно понял.

2020-11-03 16:07 UTC, lamtev approved these changes
> Согласен, у нас есть массив нод, который отсортирован, я завёл ещё один массив и считаю хеши в него, порядок нод в таком случае детерминирован. В identifyByKey идёт массив вместо мапы. Если я конечно правильно понял.

Я там еще имел ввиду, что можно определять минимум без TreeMap, а прямо в цикле, обновляя текущий минимум на каждой итерации, если потребуется.
```java
int min = Integer.MAX_VALUE;
for (...) {
  //compute
  ...
  if (curr < min) {
    min = curr;
  }
}
```

В отчете увидел:

> Это говорит нам о том что мы работаем с нативными posix сокетами linux. Важно заметить что они синхронные. Забавно то что мы даже можем найти, к примеру команду send_msg

На самом деле, блокирующие сокеты там только в HttpClient. При ответе на респонс там должны быть неблокирующие сокеты

2020-11-03 16:09 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/RendezvousHashingImpl.java
> +    final List<Integer> nodeHashes;
ну и наверное лучше уж int[]. В упакованных типах тут нет необходимости

2020-11-03 16:11 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/SharedAsyncServiceImpl.java
> +            exceptionIOHandler(session, "Method get. IO exception. ", e);
Вроде на предыдущих итерациях ревью говорил, что лучше хэндлить IOException от dao и от session раздельно. И во втором случае не делать повторную отправку ответа

2020-11-04 16:20 UTC, lamtev commented
Принято с некоторыми замечаниями

2020-11-04 16:20 UTC, closed without merging