Homework4
polis-mail-ru/2020-highload-dht pull request #102
Opened 2020-10-20 06:35 UTC by Marashov-Alexander

2020-10-20 07:37 UTC, Marashov-Alexander commented
Результаты профилирования будут добавлены чуть позже

2020-10-20 13:57 UTC, incubos requested changes
- Ждём результатов профилирования
- Есть ряд небольших замечаний по коду

2020-10-20 13:57 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +        BasicConfigurator.configure();
Зачем это? У нас же `logback`.

2020-10-20 13:57 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +    public String primaryFor(@NotNull final ByteBuffer key) {
С нетерпением ждём результатов профилирования работы этого метода.

2020-10-20 13:57 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +        return nodes.iterator();
Вообще у `Iterator` есть метод `remove()`, а мы отдаём его наружу...

2020-10-20 13:57 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +    final Collection<String> nodes;
Почему поля не `private`? Предполагается дать соседям доступ к ним?

2020-10-20 13:57 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +            final HttpClient httpClient = new HttpClient(new ConnectionString(node + "?timeout=100"));
Таймаут лучше вынести в параметр конструктора или константу.

2020-10-20 18:43 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +    public String primaryFor(@NotNull final ByteBuffer key) {
Спасибо за замечания, каждое я исправил.
Что касается primaryFor: 
* вынес hashCode ключа отдельно, чтобы он не считался единожды
* осознал, что x.hashCode() + y.hashCode() в этой задаче значительно хуже, чем (x + y).hashCode(), поэтому продолжил вычисление хеша по строковому алгоритму, как будто бы у нас имя ноды - это суффикс ключа.
* при помощи профилирования увидел, что реализация этого метода на стримах потребляет очень много памяти: в 3 раза больше, чем работа DAO при PUT запросе

2020-10-20 18:47 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +    public String primaryFor(@NotNull final ByteBuffer key) {
Получается, что лучше переписать на более низкоуровневых коллекциях и без стримов?

2020-10-20 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +    final Collection<String> nodes;
Нет, это досадная невнимательность(
Исправил

2020-10-20 18:53 UTC, Marashov-Alexander commented
> * Ждём результатов профилирования
> * Есть ряд небольших замечаний по коду

Добавил результаты профилирования в папку profiler/homework4

2020-10-22 12:22 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +    public String primaryFor(@NotNull final ByteBuffer key) {
> Получается, что лучше переписать на более низкоуровневых коллекциях и без стримов?

Да, это очень горячий код -- его имеет смысл оптимизировать за счёт устранения лишних абстракций и аллокаций. Welcome to highload :)

2020-10-22 12:59 UTC, incubos requested changes
- Нужно пооптимизировать `Topology`
- Профилировать надо без `-t`
- Залейте, пожалуйста, отчёт в MarkDown и вставьте ссылки на соответствующие SVG-результаты профилирования
- LUA-скрипты должны быть закоммичены
- Наконец, есть большое подозрение, что исследовался **кластер из одной ноды** (запускали `Server`, а не `Cluster`?), поскольку в результатах профилирования я не нашёл работу `HttpClient` -- надо переделать

2020-10-22 12:59 UTC, incubos commented on profiler/homework4/results.txt
> +../../IdeaProjects/wrk2/wrk2/wrk -c64 -d 5m -R 2000 -s ../../IdeaProjects/wrk2/wrk2/putS.lua --latency http://localhost:8080
LUA-скрипт надо бы закоммитить в проект.

2020-10-22 12:59 UTC, incubos commented on profiler/homework4/results.txt
> +../../IdeaProjects/wrk2/wrk2/wrk -c64 -d 5m -R 2000 -s ../../IdeaProjects/wrk2/wrk2/getS.lua --latency http://localhost:8080
LUA-скрипт должен быть закоммичен в проект.

2020-10-22 12:59 UTC, incubos commented on profiler/homework4/review.txt
> +PUT and GET locks:
Здесь и ниже нужно профилировать без разбивки по потокам (без опции `-t`), иначе сложно анализировать FlameGraphы.

2020-10-22 12:59 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
>          final Stream<Map.Entry<Integer, String>> sortedStream = nodes.stream()
Давайте просто `for` напишем? Зачем этот стримоз?

2020-10-25 10:46 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
>          final Stream<Map.Entry<Integer, String>> sortedStream = nodes.stream()
Добрый вечер!
Замечания по коду исправил, но по профилированию дела обстоят не очень.
Все тесты 4 этапа проходят, обстрел PUT-методами с помощью wrk2 проходит нормально, но как только начинается GET-обстрел, то сервер начинает извергать UncaughtException, порождённые в недрах чтения данных из SSTable.
Хотел заняться отладкой программы, но тут полетел линукс. Переустановил его заново - на следующий день такая же ошибка, система не запускается.
Попробовал обнаружить баг через основную систему (windows) - никаких ошибок при GET запросах не вылезает, даже при чтении из SSTable.
В четверг вернусь в СПб и буду разбираться с основного компьютера на линуксе, а пока тогда приступаю к выполнению пятого этапа :(

2020-10-25 13:09 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
>          final Stream<Map.Entry<Integer, String>> sortedStream = nodes.stream()
ОК, ждём.

2020-10-25 13:16 UTC, incubos requested changes
Есть замечания и ждём исправлений.

2020-10-25 13:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +        final NodeKeyPair[] pairs = new NodeKeyPair[nodes.length];
Вы здесь ищете ноду с минимальным значением hash code. Зачем хранить этот массив, да ещё и сортировать за `O(n log n)`? Просто итерируйтесь линейно, считайте hash code и, если он меньше, запоминайте ноду.
В общем, нужно пооптимизировать.

2020-10-27 10:50 UTC, incubos commented
> Есть замечания и ждём исправлений.

Ожидать исправление до конца дня или принимаем за меньшие баллы?

2020-10-27 12:00 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +        final NodeKeyPair[] pairs = new NodeKeyPair[nodes.length];
Ой, да, это было очень глупо с моей стороны. 
Реализовал через приоритетную очередь поиск top-k элементов: пригодится для следующего этапа)

2020-10-27 12:01 UTC, Marashov-Alexander commented
> > Есть замечания и ждём исправлений.
> 
> Ожидать исправлений до конца дня или принимаем за меньшие баллы?

Спасибо за ожидание!
Исправил замечание с неоптимальным поиском + готов выкладывать пятый этап :)

2020-10-27 18:23 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/topologies/RendezvousTopology.java
> +        final NodeKeyPair[] pairs = new NodeKeyPair[nodes.length];
И для поиска одной ноды добавил поиск по массиву :)

2020-10-28 09:59 UTC, incubos commented
Принято.

2020-10-28 09:59 UTC, closed without merging