Task 4
polis-mail-ru/2020-highload-dht pull request #104
Opened 2020-10-20 12:15 UTC by MrSandman5

2020-10-24 11:11 UTC, vaddya requested changes
Было неожиданно увидеть свой код в чужом PR, сначала даже подумал, что открыл репозиторий прошлого года. Хотелось бы узнать причину такого большого числа совпадений.

2020-10-24 11:11 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/clustering/ConsistentHashingTopology.java
> +public class ConsistentHashingTopology<T> implements Topology<T> {
Почему это с точностью до переименования переменных совпадает с [решением прошлого года](https://github.com/polis-mail-ru/2019-highload-dht/pull/86/files#diff-1666be19246e478638d2964f7aa2a5d8d1b12c4205c803edd478d85f806ea8f3R13)?

2020-10-24 11:11 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/clustering/BasicTopology.java
> +public class BasicTopology<T> implements Topology<T> {
Почему это с точностью до переименования переменных совпадает с [решением прошлого года](https://github.com/polis-mail-ru/2019-highload-dht/pull/86/files#diff-98ac1e61132cc79cd4a959cfb2d1872056393eac4e4f0c14c4ecd9ff8921c9aeR12)?

2020-10-24 11:11 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +public final class ServiceImpl extends HttpServer implements Service {
Почему весь класс очень сильно похож на [решение прошлого года](https://github.com/polis-mail-ru/2019-highload-dht/pull/86/files#diff-f1539e3c73d21d39918a3d8df3d4cbab8375d6fa235df45b3b34fa7de4c12de5R35)?

2020-10-24 14:17 UTC, MrSandman5 commented
Признаю, что слишком много совпадений. За последнюю неделю пришлось очень много работать на работе + семейные обстоятельства.
Понимаю, что это не оправдание, поэтому согласен на урезание баллов.

2020-10-24 16:10 UTC, vaddya commented
Можете сранить результаты профилирования с прошлым этапом? Стало ли быстрее/медленее? Что с максимальным числом запросов?

2020-10-25 12:48 UTC, vaddya requested changes
Принято с штрафом за списывание.

2020-10-25 12:48 UTC, closed without merging