Stage 4
polis-mail-ru/2020-highload-dht pull request #105
Opened 2020-10-20 13:16 UTC by Igor-Manikhin

Отчёт в процессе

2020-10-21 09:05 UTC, Igor-Manikhin commented
Отчёт по профилированию был выложен вчера.

2020-10-29 00:29 UTC, lamtev requested changes
## Реализация

Оставил несколько в основном стилевых замечаний

## Профилирование

Задержки говорят о том, что нагрузка была высоковата. То есть по факту пропускная способность в отчете завышена.

Ну и странно, почему вдруг для PUT задержки стали выше, чем для GET. Хотя в прошлом этапе было наоборот. Есть идеи почему так?

2020-10-29 00:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +                                  @NotNull final Request request) {
Форматирование поехало

2020-10-29 00:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +                                  @NotNull final String keyCluster,
Название параметра не очень. "Ключевой кластер" - явно не то, что нужно

2020-10-29 00:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +            log.error("NoSuchElement get error: ", error);
отсутствие в базе значения - это не ошибка, а нормальная ситуация

2020-10-29 00:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/Topology.java
> +    private final String id;
совершенно не "говорящее" название. лучше переименовать, чтобы было понятно, что это такое

2020-10-29 00:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/Topology.java
> +        Collections.sort(this.nodes);
Вообще у `List` есть метод `sort`. `Collections.sort(List)` как раз его и вызывает

2020-10-29 00:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +    private final Logger log = LoggerFactory.getLogger(AsyncServiceImpl.class);
Лучше сделать логгер статическим

2020-10-29 00:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new AsyncServiceImpl(port, dao, nodes, countWorkers, 1024, 100);
оптимистичное значение для таймаута, наверное)

2020-10-29 18:35 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +                                  @NotNull final Request request) {
Исправлено.

2020-10-29 18:35 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +                                  @NotNull final String keyCluster,
Исправлено.

2020-10-29 18:35 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +            log.error("NoSuchElement get error: ", error);
Исправлено.

2020-10-29 18:35 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/Topology.java
> +    private final String id;
Исправлено.

2020-10-29 18:35 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/Topology.java
> +        Collections.sort(this.nodes);
Исправлено.

2020-10-29 18:35 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +    private final Logger log = LoggerFactory.getLogger(AsyncServiceImpl.class);
Исправлено.

2020-10-29 18:36 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new AsyncServiceImpl(port, dao, nodes, countWorkers, 1024, 100);
Исправлено.

2020-10-29 18:39 UTC, Igor-Manikhin commented
При профилировании я несколько раз прогревал свою рабочую машинку и каждый раз были разные результаты. Я указал в отчёте наиболее лучшие результаты. Одна из возможных причин, почему это так происходило - слабое железо в машинке.

2020-10-29 18:41 UTC, Igor-Manikhin commented
При повторной подаче pull request'a - не проходит travis, поскольку сейчас там ещё и тесты для 5 и 6 этапов. При первой подаче тесты проходили.

2020-10-31 15:06 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new AsyncServiceImpl(port, dao, nodes, countWorkers, 1024, 100);
стало 40 - еще более оптимистично. если ноды будут не на одной машине подняты, то довольно часто запросы будут не укладываться в 40 мс

2020-10-31 15:08 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/AsyncServiceImpl.java
> +        } catch (NoSuchElementException message) {
message?

2020-10-31 15:08 UTC, lamtev approved these changes

2020-10-31 15:09 UTC, lamtev commented
Принято

2020-10-31 15:09 UTC, closed without merging

2020-10-31 15:22 UTC, Igor-Manikhin commented
Сори, не обратил внимания на это. Будет исправлено.