Stage 4
polis-mail-ru/2020-highload-dht pull request #106
Opened 2020-10-20 15:27 UTC by s3ponia

2020-10-29 00:45 UTC, lamtev requested changes
## Реализация

Оставил замечания

## Профилирование

Еще смотрю

2020-10-29 00:45 UTC, lamtev commented on src/test/java/ru/mail/polis/dao/PersistenceTest.java
> +                }
Это чит, такого быть не должно

2020-10-29 00:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +        }
Такой легкий запрос не стоит обрабатывать на экзекюторе. То что RejectedExecutionException отлавливается - нужно перенести в обработку полноценных запросов - там как раз этого нет. Ну и ответ должен быть 503 Service Unavailable

2020-10-29 00:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +            this.es.execute(runFunction);
RejectedExecutionException нужно ловить

2020-10-29 00:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +            proxy(node, session, request);
тоже нужно на экзекютор увести

2020-10-29 00:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +            session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Сюда можно попасть как при dao.get, так и при session.sendResponse. Если пришли из session.sendResponse, тогда будет выполнена попытка повторно отправить ответ

2020-10-29 00:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +
таких изменений в референсных файлах стоит избегать

2020-10-29 10:53 UTC, s3ponia commented on src/test/java/ru/mail/polis/dao/PersistenceTest.java
> +                }
Это я пытался дебажить. просто забыл убрать

2020-10-29 11:05 UTC, s3ponia commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +            session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Можно исправить просто поменяв кэтчи местами конечно)) Но просто есть ли еще проблемы кроме того что лишний раз пытается ответ отправить?

2020-10-29 11:17 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +            session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Еще проблем нет. Проблема именно в повторной отправке ответа. А ведь там уже и сокет мог быть закрыт

2020-10-31 15:19 UTC, lamtev commented
Оставил [фидбэк по профилированию](https://github.com/polis-mail-ru/2020-highload-dht/pull/106#pullrequestreview-519222669)

Недочеты в обработке IOException лучше устранить и в дальнейшем обрабатывать правильно

2020-10-31 15:19 UTC, lamtev commented
Принято

2020-10-31 15:19 UTC, closed without merging