Stage 4
polis-mail-ru/2020-highload-dht pull request #107
Opened 2020-10-20 16:04 UTC by Basta123

2020-10-24 10:56 UTC, vaddya requested changes
Немного замечаний по реализации.

Профилирование ОК, хоть и на `CpuPut.svg` видно C2 компилятор, значит недостаточно прогрели код перед профилированием, учтите это на следующих этапах, пожалуйста.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        final Topology<String> t = new TopologyImpl(topology, "http://localhost:" + port);
Давайте нормальное имя `topology` дадим.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/TopologyImpl.java
> +    private final String[] nodes;
Может более высокоуровневый `List` будем использовать? Хоть и не принципиально, но лучше использовать коллекции, а не массивы. Можно обратиться к Effective Java, 2nd Edition
by Joshua Bloch, Item 25: Prefer lists to arrays.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +        execService.shutdown();
У экзекьютора еще надо вызвать `awaitTermination`.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +        if (id == null || id.isEmpty()) {
Он же помечен как `@NotNull`?

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +    public AsyncHttpServerImpl(final HttpServerConfig config,
Ставьте всем параметрам тогда `@NotNull`, а то не понятно как интерпретировать отсутствие аннотации -- то ли может, то ли не может.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +            log.error(ARRAY_IS_FULL, e);
Сообщения для логгера обычно не выносят в константы.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                final HttpClient client = new HttpClient(new ConnectionString(node + "?timeout=1000"));
Лучше избегать литералов в коде, давайте вынесем значение таймаута в константу?

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +        execService = new ThreadPoolExecutor(numWorkers,
Принято в конструкторе использовать `this.` при присваивании.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +            } catch (IOException e) {
```java
dao.upsert(key, value);
...
httpSession.sendResponse(response);
```
И первая, и третья строки могут бросить `IOException`. Но исключение из первой строки мы хотим поймать и вернуть клиенту 500, это явно ошибка на стороне DAO. А исключение из третьей строки нужно только залогировать, потому что нам явно не удается отправить ответ (сокет закрыт?) и нет смысла отправлять ещё один. Предлагаю разделить эти два сценария обоработки ошибок через разные `catch`-блоки.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/Utils.java
> +        acceptorConfig.reusePort = true;
Можете как-то прокомментировать этот параметр и два выше?

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/Utils.java
> +        httpServerConfig.maxWorkers = Runtime.getRuntime().availableProcessors();
Мы не используем воркеров на стороне `one-nio`, у нас свой экзекьютор. Поэтому в `httpServerConfig` нужно задать только число селекторов (`selectors`).

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +    private void makeAct(@NotNull final Action action) {
`makeAction` или `act`. А вообще, проще это перенести внутрь `executeAsync`.

2020-10-24 10:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                                 final HttpSession httpSession) throws IOException {
`@NotNull`?

2020-10-25 09:59 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +            } catch (IOException e) {
ок, с get и delete также сделать?

2020-10-25 10:18 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/Utils.java
> +        acceptorConfig.reusePort = true;
с помощью параметра httpServerConfig.queueTime = 10 мы создаем искусственную задержку, его стоит убрать.
остальные два параметра нужны больше для оптимизации и увеличения производительности. Нам на последней лекции говорили, что reusePort позволяет сразу нескольким потокам слушать порт, а deferAccept позволяет сказать приложению о том, что создалось новое соединение только после того как придут реальные данные.

2020-10-25 10:25 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +    private void makeAct(@NotNull final Action action) {
если перенести тело метода makeAct в executeAsync, то codeclimate будет ругаться на вложенные try-catch :(
поэтому сделал это в отдельном методе

2020-10-25 11:17 UTC, Basta123 commented
ru.mail.polis.service.ThreeNodeTest > unreachableRF() FAILED
Трэвис прогоняет тесты 5 этапа, хотя код написан для четвертого этапа и из-за этого он не проходит, поэтому прошу не обращать на это внимание.

2020-10-25 13:31 UTC, vaddya requested changes

2020-10-25 13:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        final Topology<String> t = new ModularTopology(topology, "http://localhost:" + port);
Все еще переменная называется `t`, а не `topology`.

2020-10-25 13:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/ModularTopology.java
> +    private final String[] nodes;
Все еще используется массив, а не `List`

2020-10-25 13:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +            request.addHeader("Forwarding");
An [HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) consists of its case-insensitive name followed by a colon (:), then by its value.

2020-10-25 13:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +    public void deleteValueByKey(@Param(value = "id", required = true) final String id,
Если используете `required = true`, то этот параметр точно не `null`, поэтому нужно вернуть аннотацию `@NotNull`. И учесть в `isIdValid`, что `id` всегда точно не `null`.

2020-10-25 13:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +    private static final String HTTP_CLIENT_TIMEOUT_100 = "?timeout=100";
Я имел ввиду, что нужно само значение (100) сделать константой (`private static final int TIMEOUT = 100`), а при формировании `url` уже добавлять `?timeout=`. Но ладно, и так пойдет. Уберите только `_100` из имени переменной, пожалуйста.

2020-10-25 18:22 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        final Topology<String> t = new ModularTopology(topology, "http://localhost:" + port);
думал вы имеете в виду название самого класс поменять на ModularTopology.

2020-10-25 19:29 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +    public void deleteValueByKey(@Param(value = "id", required = true) final String id,
понял, сделал.

2020-10-25 19:30 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/ModularTopology.java
> +    private final String[] nodes;
поменял на динамический массив.

2020-10-25 21:25 UTC, vaddya approved these changes
Минорные замечания, поправьте к следующему этапу, пожалуйста.

Принято.

2020-10-25 21:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/ModularTopology.java
> +        final ArrayList<String> arrayNodes = (ArrayList<String>)this.nodes;
Что-то не то здесь делаете, `new ArrayList<>(nodes)` делает ровно то, что вам нужно.

2020-10-25 21:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                              final HttpSession httpSession) throws IOException {
`@NotNull`

2020-10-25 21:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                                 final HttpSession httpSession) throws IOException {
`@NotNull`

2020-10-25 21:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                     final HttpSession httpSession) throws IOException {
`@NotNull`

2020-10-25 21:25 UTC, closed without merging

2020-10-26 04:26 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/ModularTopology.java
> +        final ArrayList<String> arrayNodes = (ArrayList<String>)this.nodes;
понял, поправлю, но в этом случае возможно немного криво сделал, не знаю как сделать более оптимально.
Сначала я создаю `List<String> nodes `
затем инициализирую его в конструкторе `this.nodes = new ArrayList<>(nodes);`
потом в методе `getAllNodes()` пишу `final ArrayList<String> arrayNodes = (ArrayList<String>)this.nodes`, то есть явно преобразовываю `List` к `ArrayList` для того чтобы дальше из него вызвать метод clone, которого нет у List.
Затем я вызываю у объекта типа `ArrayList` метод clone, который возвращает тип `Object`, который я явно привожу к ArrayList, а затем его уже возвращаю. Да, знаю, что не совсем оптимально) но я не понял как сделать это более просто.

2020-10-26 04:28 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                     final HttpSession httpSession) throws IOException {
поправил

2020-10-26 07:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/ModularTopology.java
> +        final ArrayList<String> arrayNodes = (ArrayList<String>)this.nodes;
Этот способ применим к массивам. Для того, чтобы скопировать коллекцию, используется конструктор соотвествуюего классаб, который принимат `Collection`. Поэтому все тело этого метода должно быть просто `return new ArrayList<>(nodes);`.

2020-10-26 07:30 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +            request.addHeader("Forwarding");
Я имел ввиду не убрать совсем, а заменить на правильный хедер в формате `Header-name: header-value`. Например, в лекции был пример с `request.addHeader("X-Proxy-For: " + node);`