Stage 5
polis-mail-ru/2020-highload-dht pull request #109
Opened 2020-10-23 22:29 UTC by StasyanOi

2020-11-01 20:38 UTC, lamtev commented
Похоже, что в этом ПР стали появляться коммиты из 6 этапа. Это усложнит ревью 🙁. В этой ветке нужно оставить только коммиты 5 этапа

2020-11-01 20:49 UTC, lamtev commented
> Похоже, что в этом ПР стали появляться коммиты из 6 этапа. Это усложнит ревью 🙁. В этой ветке нужно оставить только коммиты 5 этапа

@StasyanOi прошу обратить внимание

Наверное, довольно просто будет чекаутнуться в новую ветку от этой. А в этой через ребейз дропнуть лишнее и зафорспушить

2020-11-02 12:33 UTC, lamtev commented
> > Похоже, что в этом ПР стали появляться коммиты из 6 этапа. Это усложнит ревью 🙁. В этой ветке нужно оставить только коммиты 5 этапа
> 
> @StasyanOi прошу обратить внимание
> 
> Наверное, довольно просто будет чекаутнуться в новую ветку от этой. А в этой через ребейз дропнуть лишнее и зафорспушить

@StasyanOi В ПР 5 этапа не должно быть реализации 6 этапа. И нужно поправить то, что обнаружил код климат

2020-11-03 20:01 UTC, StasyanOi commented
@lamtev, сделал hard reset и force push на самый ранний этап для этой ветки.  Теперь только для 5 этапа код есть

2020-11-09 23:39 UTC, lamtev requested changes
## Реализация

1. Не очень хорошо продуманный и переусложненный дизайн
    * совершенно неуместное наследование в *Server
    * очень много всего полезного выполняется в Util
2. Много мест, где выбрано не оптимальное решение по времени/памяти
    * активно используется Stream API. У Joshua Bloch есть совет **Use streams judiciously**. Особенно актуально для курса по highload
    * излишний парсинг строк
    * не везде правильно выбраны используемые структуры данных
3. Java doc чисто чтобы не было замечаний code climate. Ясности не вносит. Хотя можно было бы отразить тонкости реализации
4. Прошу все-таки замечания с прошлых этапов фиксить и недочеты не тащить в новый этап

## Профилирование

Результаты профилирования подкрепляют многие замечания, связанные с перформансом. Например, как на CPU, так и на ALLOC флейм-графах можно заметить, что довольно много сжирает java/util/stream/*

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +public class CustomServer extends FrameServer {
Вся эта иерархия не по делу. Усложняла процесс ревью. Ну и присутствует дублирование. Например, GetMethodServer.getReplicaGetResponse и PutGetDeleteMethodServer.getPutReplicaResponse практически идентичны 
![image](https://user-images.githubusercontent.com/10428179/98606599-94e1ec80-22f8-11eb-9d5b-6631269fde14.jpeg)

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                                             final Integer ack,
Лучше int, чтобы избежать анбоксинга несколько раз далее

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                                                      final Map<Integer, String> nodeMapping) {
Не нужен весь nodeMapping здесь, достаточно from

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                                             final Map<Integer, String> nodeMapping) {
Не нужен весь nodeMapping здесь, достаточно from

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                                                      final Integer ack,
int

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +            newPath = path + "?" + queryString + "&reps=false";
Можно обойтись без добавления новых параметров в http api. наличие специального заголовка будет означать, что такой запрос уже не нужно никуда проксировать дальше

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/PutGetDeleteMethodServer.java
> +    }
Практически дублирует GetMethodServer. getReplicaGetResponse

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +                .map(clientRequest -> {
А зачем сначала что-то упаковывать, чтобы далее это распаковать?

2020-11-09 23:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +        noRepRequest.addHeader("Host: localhost:" + thisServerPort);
Ноды могут быть развернуты на разных железках, и может получиться, что все localhost:8080

2020-11-11 13:30 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/Mapper.java
> +        buffer.clear();
Переделал метод, теперь нету побочных эффектов.

2020-11-11 13:31 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomExecutor.java
> +    }
Убрал

2020-11-11 13:31 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomExecutor.java
> +    }
Убрал ненужный метод

2020-11-11 13:32 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +    private static synchronized long getNanosSync() {
Для синхронизации получения времени, но сейчас оно уже не нужно

2020-11-11 13:37 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +public final class Merger {
ResponseMerger переделал

2020-11-11 13:51 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +    public static Pair<byte[], byte[]> getTimestamp(final byte[] body) {
Новая логика теперь, этот метод убран.

2020-11-11 13:52 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +     * @return - pair of timestamp and pure body.
Уже переделано

2020-11-11 13:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +    protected static final List<String> replicationDefaults = Arrays.asList("1/1", "2/2", "2/3", "3/4", "3/5");
Переделал

2020-11-11 13:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +    protected Map<String, HttpClient> httpClientMap;
Перевел все возможные поля в final в этом классе.

2020-11-11 13:55 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +        noRepRequest.addHeader("Host: localhost:" + thisServerPort);
Переделал отправку

2020-11-11 13:55 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +                .map(clientRequest -> {
Тоже переделал

2020-11-11 13:56 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/PutGetDeleteMethodServer.java
> +    }
Все ненужные слои убрал

2020-11-11 15:07 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                                                      final Integer ack,
переделал

2020-11-11 15:15 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                                             final Map<Integer, String> nodeMapping) {
Переделал

2020-11-11 15:15 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                                                      final Map<Integer, String> nodeMapping) {
Переделал

2020-11-11 15:15 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                                             final Integer ack,
Переделал

2020-11-11 15:15 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +public class CustomServer extends FrameServer {
Убрал лишние классы

2020-11-11 15:16 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                        .collect(Collectors.toList());
Переделал на цикл

2020-11-11 15:16 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +        this.dao = dao;
Все на циклы переделал.

2020-11-11 15:19 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                        .filter(response -> response.getHeader("Time: ") != null)
Новый класс сделал с константой

2020-11-11 15:20 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +    private Response getProxy(final Request request, final int node, final ByteBuffer id) {
Переделано

2020-11-11 15:21 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +                .collect(Collectors.joining());
Переделал циклы

2020-11-11 15:22 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +                .map(String::valueOf)
уже убрал стрим

2020-11-11 15:23 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +                .mapToObj(value -> (char) value)
этот стрим убрал

2020-11-11 15:43 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        return System.nanoTime();
Могу сделать миллисекунды, не проблема.

2020-11-11 16:18 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                responseHttp = entries.get(entries.size() - 1).getValue();
Этот сегмент переделан

2020-11-11 16:19 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        return responseHttp;
Переделал

2020-11-11 16:20 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +    public static Pair<Integer, Integer> ackFromPair(final Request request,
Пары везде уже убрал

2020-11-11 16:22 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +            final String[] ackFromReal = ackFrom.orElseGet(() -> new String[]{"4", String.valueOf(nodeMapping.size())});
Переделал расчёт реп фактора

2020-11-11 16:22 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        return new Pair<>(ack, from);
Пары все убрал

2020-11-11 16:25 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +        final Map<Integer, String> nodeMappingTemp = new TreeMap<>();
Здесь дерево нужно для того чтобы обеспечивать одну и ту же структуру нод для репликаций.

2020-11-11 23:26 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +            newPath = path + "?" + queryString + "&reps=false";
Тут это одинаково по сути

2020-11-11 23:27 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        hash = hash < 0 ? -hash : hash;
Переделал без abs

2020-11-11 23:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        return timestamp;
Сериализация не понятно работает с 8-ю байтами. Поэтому строкой взял.

2020-11-11 23:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +    public void getRep(final @Param("id") String idParam, final HttpSession session) {
Убрал эндпоинты для репликации

2020-11-11 23:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    }
Переделал

2020-11-12 07:46 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +            from = Integer.parseInt(Iterables.get(Splitter.on('/').split(replicas), 1));
добавил обработку

2020-11-12 13:26 UTC, StasyanOi commented
@lamtev, мне не много пофиксить осталось. До завтра доделаю по максимому

2020-11-12 19:46 UTC, StasyanOi commented
@lamtev, по максимому все исправил включая формат timestamp. Новые тесты из 7-го этапа валят билд

2020-11-12 19:49 UTC, StasyanOi commented
@incubos, пофиксил timestamp - новые тесты билд валят (не совсем понял как их убрать у меня их нету ни локально, ни в репо). В принципе всё

2020-11-13 17:17 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +public final class Util {
Я его разделю на следующих этапах по возможности.

2020-11-13 17:18 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +    protected Map<Integer, String> nodeMapping;
По возможности вынесу её, но она по идее на месте в классе сервера.

2020-11-18 20:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +        final Map<Integer, String> nodeMappingTemp = new TreeMap<>();
Строки 47-48:
```java
final ArrayList<String> urls = new ArrayList<>(topology);
 urls.sort(String::compareTo);
```

Массив отсортирован. Он одинаково отсортируется на всех репликах

2020-11-18 20:32 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        return hash < 0 ? -hash : hash;
Зачем, когда на лекции был предложен отличный вариант?

2020-11-18 20:34 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +        if (Util.validRF(replicationParam)) {
Не очень понял, зачем 2 раза парсить: 1 раз при проверке, потом еще раз при формировании AckFrom. Ну ладно

2020-11-18 20:37 UTC, lamtev commented
Принято

2020-11-18 20:37 UTC, closed without merging