Task_1 init
polis-mail-ru/2020-highload-dht pull request #11
Opened 2020-09-27 15:41 UTC by nik27090

2020-09-27 17:03 UTC, nik27090 commented
Нагрузочное тестирование в процессе

2020-09-29 19:20 UTC, nik27090 commented
ридми в процессе

2020-10-03 00:56 UTC, lamtev requested changes
Реализация - ОК

По профилированию:
1. Стоит настроить уровень логгирования, чтобы не видеть в профилировщике как большая часть CPU/ALLOC уходит на логгирование
2. > Слишком поздно запустил теcтирование, инкремент ключа сильно вырос и большая часть ключей по запросам не найдена

    Да, об этом свидетельствует стектрейс с `NoSuchElementException` в `cpu/get.svg`. Есть подозрение, что база была совершенно пустой, потому что кроме `NoSuchElementException` ничего на флейм-графе и не видно :( Это совершенно неправильно. Какой смысл замерять лэйтенси и профилировать в таком случае? Нужно сначала хорошенько заполнить базу данными, чтобы обязательно дынные были сброшены на диск. И только после этого нужно обстреливать `GET`ами
3. Судя по `cpu/put.svg` флашей на диск не было, как это замечено в отчете

Нужно повторить профилирование под нагрузкой, не допуская всех вот этих ошибок. И было бы здорово добавить в Markdown отчет сразу флейм-графы и вывод `wrk`

2020-10-03 20:22 UTC, lamtev approved these changes

2020-10-03 20:23 UTC, lamtev commented
Принято

2020-10-03 20:23 UTC, closed without merging