Stage #5
polis-mail-ru/2020-highload-dht pull request #111
Opened 2020-10-26 06:26 UTC by ScriptoMax

[Отчёт](https://github.com/ScriptoMax/2020-highload-dht/blob/stage_5/resources/report.md) к аналитическому заданию

2020-10-30 10:51 UTC, incubos requested changes
В целом, всё хорошо, но есть ряд замечаний, которые хотелось бы устранить, в частности, реализация проксирования в случае кластера из нескольких нод стала **синхронной**, в то время как обработка отпроксированных запросов осталась **асинхронной**. Всё должно быть асинхронным, ибо мы развиваем наработки предыдущих этапов, а не отказываемся от них (можно не перестреливать, достаточно пройти тесты).

2020-10-30 10:51 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/Value.java
> +        return new Value(false, -1, null);
Можно сделать singleton, чтобы не аллоцировать каждый раз.

2020-10-30 10:51 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceUtils.java
> +    public static String[] getNodeReplica(
Зачем этот метод? Разве `Topology.replicasFor()` недостаточно? Здесь мы по сути делегируем ему и половину параметров даже не используем.

2020-10-30 10:51 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationFactor.java
> +            session.sendError(Response.BAD_REQUEST, REPLIFACTOR_ERROR_LOG);
Разве в случае этих `sendError()` здесь и выше мы не должны прокинуть ошибку наверх, а не возвращать какой-то `ReplicationFactor`?

2020-10-30 10:51 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +            switch (req.getMethod()) {
Т.е. асинхронность у нас осталась только в случае кластеров из одно ноды? Что мешает сделать также в случае `topology.getClusterSize() > 1` выше? На этом этапе мы не хотим терять достоинства, которые предоставляет асинхронность. Доработаете?

2020-10-30 10:51 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +public class ReplicationLsm {
Хотелось бы увидеть здесь или где-то ещё JavaDoc, проясняющий текущий дизайн, в частности, распределение обязанностей между `ReplicationLsm` и `RepliServiceImpl`, которые шарят между собой топологию и пулы соединений.

2020-10-31 18:51 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/Service.java
> +
Благодарю за рекомендацию - замечание устранено

2020-10-31 18:51 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/Value.java
> +        return new Value(false, -1, null);
замечание устранено

2020-10-31 18:53 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceUtils.java
> +    public static String[] getNodeReplica(
полностью с Вами согласен, но по версии code climate индекс Cognitive Complexity предельно допустимый на 1 пункт. Других кандидатов для рефакторинга не нашёл

2020-10-31 18:54 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationFactor.java
> +            session.sendError(Response.BAD_REQUEST, REPLIFACTOR_ERROR_LOG);
замечание устранено

2020-10-31 19:12 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +            switch (req.getMethod()) {
Признаться, первоначально я не воспринял задание как связанное с реализацией асинхронности для всей работы с базой, поэтому методы для одного узла перенёс из предыдущих этапов, а для нескольких так и оставил как в недавнем прошлом. Не нашёл даже визуальных противоречий на расстоянии ладони, выглядит действительно нелепо. После ревью внёс правки и в код, и в отчёт (любопытно, что результаты кластера с репликацией в режиме GET-запросов не просто оказались на энное число миллисекунд лучше - они превзошли даже статистику времён отклика прошлого этапа). Объяснил эту сенсацию (личную) как мог, хотя с учётом наметившегося ранее убывания быстродействия такого эффекта не ожидал

2020-10-31 19:12 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +public class ReplicationLsm {
замечание устранено

2020-10-31 19:20 UTC, ScriptoMax commented
Выполнены правки кода и отчёта по итогам предыдущей проверки. Пожалуйста, проведите повторное ревью результатов.

2020-11-01 11:00 UTC, incubos commented
Принято.

2020-11-01 11:00 UTC, closed without merging