Task5
polis-mail-ru/2020-highload-dht pull request #112
Opened 2020-10-26 10:08 UTC by s3ponia

2020-11-01 11:14 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    Iterator<Table.ICell> iteratorRaw(@NotNull ByteBuffer from) throws IOException;
Тут когда `ICell` прорастает в интерфейсе, его можно уже вытащить из `Table` (ибо класс `Table` - это некоторая деталь реализации, и не очень хорошо, что она прорастает в интерфейсе). Да и сигнатуры будут проще.

2020-11-01 11:15 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    Iterator<Table.ICell> iteratorRaw(@NotNull ByteBuffer from) throws IOException;
Может быть, `cellsIterator`? А то `raw` уж как-то не очень понятно.

2020-11-01 11:15 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/DAO.java
> +     * Provides iterator (possibly empty) over {@link Record}s starting at "from" key (inclusive)
Жавадок расходится с реальностью.

2020-11-01 11:16 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/DAO.java
> +     * Inserts or updates value by given key.
Тоже жавадок не отражает всю суть.

2020-11-01 11:17 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/DAO.java
> +     * Inserts or updates value by given key.
Не отражает суть.
Можно понять двояко - удаляет, если ключ с таким таймстемпом или кладет могилку с указанным таймстемпом?

2020-11-01 11:18 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/s3ponia/Table.java
> +    interface ICell extends Comparable<ICell> {
А нам точно нужен этот интерфейс?
У него не одна единственная реализация?

2020-11-01 11:23 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +public final class AsyncServiceUtility {
Если присмотреться, тут почти во все методы передается `AsyncService`.
И по сути все методы так или иначе декорируют (добавляют новую функциональность поверх существующих методов `AsyncService`). См. [паттерн Декоратора](https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D0%BA%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F))

Будет проще и понятнее, если `AsyncService` будет полем класса `ReplicatedService` или `ClusterService` (или еще как-то назвать, чтобы отражалась суть, что здесь не один сервис, а целая пачка, которая как-то между собой кординируется). Синтаксически даже сигнатуры методов упростятся - не нужно будет передавать `AsyncService` везде.

2020-11-01 11:25 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +                final var time = Long.parseLong(header.value);
А вдруг там не long оказался и мы получим NumberFormatException?

2020-11-01 11:26 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +            if (parsed == null) return;
Какой ответ клиент в этот момент получит? Просто незакомпличенный запрос, который просто будет висеть?

2020-11-01 11:29 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +                service.es.execute(
Мне кажется, не очень хорошо, что мы лезем в поля класса `AsyncService`. Почему мы вообще знать, что у него там пул? Все эти детали реализации нужно спрятать. Ну или если нам здесь нужен свой ExecutionService, то пусть это будет свойство этого класса (если мы сделаем из него декоратор, то ExecutorService благополучно ляжет рядом с AsyncService полем класса).

2020-11-01 11:31 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +            AsyncService.logger.error("Bad replicas param {}", replicas);
Ну и в чужой логгер не очень хорошо лезть. Лучше завести свой.

2020-11-01 11:35 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +public final class Utility {
Класс-помойка на 250 строк.
Тут и компаратор, и структура HTTP-заголовка, и конфигурация репликации. 
Хорошая практика - когда класс решает ровно одну задачу и решает ее хорошо.
Тут можно все разнести и упростить.

2020-11-01 11:35 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static class Header {
Этот класс можно вынести в outer class `HttpHeader`, в него же утащить константы-имена наших кастомных заголовков.

2020-11-01 11:36 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static class ReplicationConfiguration {
Это тоже благополучно вытаскивается в самостоятельный outer class.

2020-11-01 11:37 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +                return null;
Тут бы в лог сообщить, что  распарсить не удалось и какое именно значение не удалось распарсить.

2020-11-01 11:39 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static boolean isHomeInReplicas(@NotNull final String homeNode,
Я правильно понимаю, что это просто `List.contains(homeNode)`?

2020-11-01 11:40 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +     * Getting DeadFlagTimeStamp from Table.Value.
Странный коммент. Мы ведь берем не из value, а из респонса?

2020-11-01 11:42 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +                                                         @NotNull final List<Response> futureResponses) {
А почему это фьюче-респонсы? Это ведь `one.nio.http.Response` - уже готовый объект, тут нет никакого "результата, который будет вычислен позже".

2020-11-01 11:43 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static List<Table.Value> getValuesFromFutures(@NotNull final ReplicationConfiguration configuration,
По сути мы просто преобразуем Response в Table.Value, без всяких фьюч.

2020-11-01 11:43 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static Comparator<Table.Value> valueResponseComparator() {
Этому компаратору самое место в классе `Table.Value`

2020-11-01 11:44 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static Map<String, HttpClient> urltoClientFromSet(@NotNull final String homeNode,
Это можно утащить в тот класс, где это используется. Скорее всего, такое построение делается вовсе один раз.

2020-11-01 11:46 UTC, dormidon commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +        if (Utility.validateId(id)) {
Выглядит так, что при хорошем ID мы возвращаем ошибку :)

2020-11-01 11:47 UTC, dormidon commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +                    logger.error("Error in raw getting.", ioException);
А тут клиентский запрос будет закомпличен?

2020-11-01 11:48 UTC, dormidon commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +        if (parsed == null) return;
И тут клиент тоже не получит закомпличенного запроса?

2020-11-01 11:50 UTC, dormidon commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +    public final DAO dao;
Все эти поля ниже должны стать `private`, если сделать правильное распределение обязанностей между `AsyncService` и `AsyncServiceUtility`. Более того, в этих классах даже есть определенное дублирование кода.

2020-11-01 11:59 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +        public final int from;
В урле удобно называть так кратко параметры, но вот в коде этот `from` не особо.
Я бы рекомендовал `from` переименовать в `replicas`, а `ack` в `acks` - их же все же потенциально несколько.

2020-11-01 12:11 UTC, dormidon commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +     * AsyncService's constructor.
Спасибо, Кэп!

2020-11-01 12:24 UTC, dormidon commented
Про отчет. 
1. Там в обоих случаях стрельба шла путами? Или в чем отличие?
2. >Соответственно время ухудшилось в два раза из-за того что необходимо слать 2 прокси запроса а не один.

А разве запросы шлются последовательно, а не параллельно? Очень странное увеличение в два раза.

2020-11-01 12:26 UTC, dormidon requested changes
См. комменты.

2020-11-02 23:42 UTC, s3ponia commented on src/main/java/ru/mail/polis/dao/s3ponia/Table.java
> +    interface ICell extends Comparable<ICell> {
Ну там была есть еще реализация в DiskTable

2020-11-02 23:42 UTC, s3ponia commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +public final class AsyncServiceUtility {
Ну это последствия кодстайла и ограничения на количество строк в файле))

2020-11-02 23:45 UTC, s3ponia commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +                                                         @NotNull final List<Response> futureResponses) {
Раньше был фьюче-респонсом) Потом все драматично поменялось

2020-11-02 23:47 UTC, s3ponia commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static Map<String, HttpClient> urltoClientFromSet(@NotNull final String homeNode,
Ограничение на количество строк в файле)

2020-11-04 09:51 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static Map<String, HttpClient> urltoClientFromSet(@NotNull final String homeNode,
Так я как раз и предлагаю разнести на несколько файлов.

2020-11-04 09:54 UTC, dormidon commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +public final class AsyncServiceUtility {
Так если мы сделаем текущий класс оберткой для Dao, то количество строк здесь практически не поменяется. 
Ограничение на количество строк как раз способствует тому, чтобы делать небольшие классы, каждый из которых выполняет одну четко обозначенную роль. Всяким хелперам и утилити-помойкам не место рядом с хорошими классами :)

2020-11-04 11:06 UTC, dormidon commented
Без исправленных замечаний готов 7 баллов проставить.
Ждать исправлений или и так сойдет? :)

2020-11-08 12:35 UTC, dormidon approved these changes

2020-11-08 12:36 UTC, dormidon approved these changes

2020-11-08 12:36 UTC, closed without merging