Stage5
polis-mail-ru/2020-highload-dht pull request #113
Opened 2020-10-26 12:31 UTC by mariarheon

2020-11-19 20:43 UTC, lamtev requested changes
# Реализация

Критичный недочет: future.get на потоках селектора

# Профилирование

В целом норм. Отмечен недочет в реализации, но почему-то он не был исправлен

2020-11-19 20:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +            logger.error(BAD_REPL_PARAM, ex);
клиент прислал некорректный запрос - не ошибка

2020-11-19 20:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                response = answer.get();
Тут нужно дождаться ack самых быстрых ответов. Но наверное, в 5-м этапе текущее решение было приемлемо.

2020-11-19 20:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                response = answer.get();
А вот выполнять лишнее на потоках селектора нельзя уже с 3-го этапа. Нужно поправить

2020-11-25 16:01 UTC, lamtev commented
Почти неделю нет активности. Планируется исправлять упомянутые в ревью недочеты?

2020-11-25 16:03 UTC, mariarheon commented
> Почти неделю нет активности. Планируется исправлять упомянутые в ревью недочеты?

Да, завтра-послезавтра планирую поправить.

2020-11-29 07:04 UTC, lamtev commented
Принято

2020-11-29 07:04 UTC, closed without merging