Stage5
polis-mail-ru/2020-highload-dht pull request #114
Opened 2020-10-26 14:17 UTC by KateMoreva

2020-10-26 19:34 UTC, KateMoreva commented
Результаты профилирования будут добавлены в ближайшее время.

2020-10-27 18:36 UTC, KateMoreva commented
### PUT запросы
-t1 -c64 -d5m -R2000 -s ./wrk/put.lua --latency http://localhost:8080

**CPU**
<img src = "https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/862fdf19ee88618001ef2724ee350e045dbf30aa/tests/stage5/cpuPut2000_c64_t1_60s.svg">

Running 1m test @ http://localhost:8080
  1 threads and 64 connections
  Thread calibration: mean lat.: 1.837ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.78ms    0.89ms  17.07ms   87.16%
    Req/Sec     2.11k   320.81     4.78k    76.37%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.63ms
 75.000%    2.06ms
 90.000%    2.60ms
 99.000%    5.88ms
 99.900%    9.47ms
 99.990%   15.03ms
 99.999%   17.06ms
100.000%   17.09ms
  119711 requests in 1.00m, 7.65MB read
Requests/sec:   1995.17
Transfer/sec:    130.54KB

**Alloc**
<img src = "https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/862fdf19ee88618001ef2724ee350e045dbf30aa/tests/stage5/allocPut2000_c64_t1_60s.svg">

Running 1m test @ http://localhost:8080
  1 threads and 64 connections
  Thread calibration: mean lat.: 1.763ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.85ms    1.04ms  21.26ms   92.05%
    Req/Sec     2.11k   395.89     6.11k    77.98%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.68ms
 75.000%    2.07ms
 90.000%    2.66ms
 99.000%    6.86ms
 99.900%   10.85ms
 99.990%   18.80ms
 99.999%   20.22ms
100.000%   21.28ms
  119713 requests in 1.00m, 7.65MB read
Requests/sec:   1995.16
Transfer/sec:    130.54KB

**Lock**
<img src ="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/862fdf19ee88618001ef2724ee350e045dbf30aa/tests/stage5/lockPut2000_c64_t1_60s.svg">

Running 1m test @ http://localhost:8080
  1 threads and 64 connections
  Thread calibration: mean lat.: 1.568ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.67ms    0.87ms  15.22ms   86.03%
    Req/Sec     2.11k   311.10     4.89k    80.10%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.55ms
 75.000%    2.00ms
 90.000%    2.52ms
 99.000%    3.88ms
 99.900%   11.71ms
 99.990%   14.02ms
 99.999%   14.98ms
100.000%   15.23ms
  119710 requests in 1.00m, 7.65MB read
Requests/sec:   1995.14
Transfer/sec:    130.54KB

### GET запросы
-t1 -c64 -d5m -R2000 -s ./wrk/get.lua --latency http://localhost:8080

**CPU**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/862fdf19ee88618001ef2724ee350e045dbf30aa/tests/stage5/cpuGet2000_c64_t1_60s.svg">

Running 1m test @ http://localhost:8080
  1 threads and 64 connections
  Thread calibration: mean lat.: 1.738ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.72ms  596.73us  12.81ms   71.15%
    Req/Sec     2.11k   244.12     3.44k    72.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.64ms
 75.000%    2.02ms
 90.000%    2.53ms
 99.000%    3.22ms
 99.900%    5.55ms
 99.990%    7.98ms
 99.999%   10.93ms
100.000%   12.81ms
  119710 requests in 1.00m, 11.99MB read
Requests/sec:   1995.16
Transfer/sec:    204.56KB

**Alloc**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/862fdf19ee88618001ef2724ee350e045dbf30aa/tests/stage5/allocGet2000_c64_t1_60s.svg">

Running 1m test @ http://localhost:8080
  1 threads and 64 connections
  Thread calibration: mean lat.: 1.750ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.73ms  582.98us  19.06ms   80.00%
    Req/Sec     2.11k   281.68     4.44k    63.17%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.66ms
 75.000%    2.01ms
 90.000%    2.33ms
 99.000%    3.29ms
 99.900%    6.55ms
 99.990%   14.60ms
 99.999%   17.57ms
100.000%   19.07ms
  119712 requests in 1.00m, 11.99MB read
Requests/sec:   1995.18
Transfer/sec:    204.56KB

**Lock**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/862fdf19ee88618001ef2724ee350e045dbf30aa/tests/stage5/lockGet2000_c64_t1_60s.svg">

Running 1m test @ http://localhost:8080
  1 threads and 64 connections
  Thread calibration: mean lat.: 1.730ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.71ms  599.00us  12.36ms   70.29%
    Req/Sec     2.11k   218.68     3.40k    70.33%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.65ms
 75.000%    2.02ms
 90.000%    2.54ms
 99.000%    3.15ms
 99.900%    5.36ms
 99.990%   10.01ms
 99.999%   11.89ms
100.000%   12.37ms
  119716 requests in 1.00m, 11.99MB read
Requests/sec:   1995.22
Transfer/sec:    204.57KB

Полные результаты представлены [тут ](https://github.com/polis-mail-ru/2020-highload-dht/blob/862fdf19ee88618001ef2724ee350e045dbf30aa/tests/stage5/results.md)

2020-11-01 22:22 UTC, KateMoreva commented
PUT

Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.96ms    6.06ms  50.37ms   92.52%
    Req/Sec   659.64     71.73     1.40k    79.51%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.10ms
 75.000%    2.08ms
 90.000%    4.45ms
 99.000%   31.95ms
 99.900%   40.38ms
 99.990%   47.17ms
 99.999%   49.98ms
100.000%   50.40ms
  2398768 requests in 1.00m, 153.27MB read
Requests/sec:  40033.58
Transfer/sec:      2.56MB
GET

2020-11-02 08:25 UTC, vaddya requested changes
Есть вопросы по реализации. Прошу прощения за задержку с ревью.

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/Replicas.java
> +        final int confirmation = Integer.parseInt(params.get(0));
Может `ack` для единообразия?

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/ModuleTopology.java
> +        while (result.size() < replicas.getFrom()) {
Учитывая, что мы не валидируем число `from` реплик, то, кажется, мы спокойно можем тут зациклиться навсегда, если `from` больше, чем число нод в нашем кластере.

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final Map<Response, Integer> responses = new ConcurrentSkipListMap<>(Comparator.comparing(this::getStatus));
Почему `ConcurrentSkipListMap`? Тут же последовательный код. И я не понял смысл этого отображения.. У `Response` же не переоопределен даже `equals`/`hashCode`, зачем его как ключ использовать. Поможете разобраться?

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        try {
Может весь этот метод выразить через следующий?

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        return response.getHeaders()[0];
Надеждее как-то на числовой статус ориентироваться, а не на порядок хедеров..

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +    private static final Logger log = LoggerFactory.getLogger(MySimpleHttpServer.class);
Не тот класс.

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +            handleResponse(session, Response.INTERNAL_ERROR);
Как будто мы потенциально тут можем второй ответ отправлять, если попадем сюда из ветки `else`.

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +                        || replicas == null ? Replicas.quorum(nodeClients.size() + 1) : Replicas.parser(replicas);
Нужно ли кворум создавать на каждый запрос? Может, закэшируем один объект и будем использовать во всех запросах?

2020-11-02 08:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        final List<Response> result = replication(requestHelper.putEntity(key, request), request, key, replicas)
Я правильно понял, что мы всегда делаем запросы к локальному хранилищу? Даже если, например, `2/3` и мы не являемся праймари нодой для ключа?

2020-11-02 10:15 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final Map<Response, Integer> responses = new ConcurrentSkipListMap<>(Comparator.comparing(this::getStatus));
Мне показалось, что будет удобнее использовать Map, а ConcurrentSkipListMap был выбран больше для однообразия

2020-11-02 10:17 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final Map<Response, Integer> responses = new ConcurrentSkipListMap<>(Comparator.comparing(this::getStatus));
А чем удобнее? Как простой контейнер для списка ответов? Я может не до конца понял, что `maxCount` вообще бывает не равный единице?

2020-11-02 10:27 UTC, KateMoreva commented
> Есть вопросы по реализации. Прошу прощения за задержку с ревью.

Спасибо большое за замечания, кажется, все поправила.

2020-11-02 10:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final Map<Response, Integer> responses = new ConcurrentSkipListMap<>(Comparator.comparing(this::getStatus));
Вопрос все еще актуален.

2020-11-02 10:33 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        final List<Response> result = replication(requestHelper.putEntity(key, request), request, key, replicas)
Еще акутально.

2020-11-02 10:34 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/ModuleTopology.java
> +        while (result.size() < replicas.getFrom()) {
Обернуть `if`-ом и вернуть пустой список, кажется, не очень хорошим решением. Это ошбика запроса и она просто проглаывается тем, что вы возвращаете пустой список праймери нод. Нужно проверять входные параметры и бросать исключение.

2020-11-02 10:35 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +                session.sendResponse(new Response(response, Response.EMPTY));
А почему тут тоже не использовать `sendLoggedResponse`?

2020-11-02 10:37 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        final List<Response> result = replication(requestHelper.putEntity(key, request), request, key, replicas)
Получается, что да, надо вывести определение праймари до обращения к хранилищу.

2020-11-02 15:42 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +                session.sendResponse(new Response(response, Response.EMPTY));
Забыла, спасибо.

2020-11-02 15:45 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/ModuleTopology.java
> +        while (result.size() < replicas.getFrom()) {
Исправила, теперь при запросе на большее число нод, чем реально есть бросается 400.

2020-11-02 15:46 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        final List<Response> result = replication(requestHelper.putEntity(key, request), request, key, replicas)
Исправила, теперь метод вызывается только на праймари ноде.

2020-11-02 15:54 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final Map<Response, Integer> responses = new ConcurrentSkipListMap<>(Comparator.comparing(this::getStatus));
Реализовала без Map, немного подправив логику ответов. Теперь используется дополнительный заголовок, по которому можно определить статус данных (могила / реальное значение).

2020-11-03 12:50 UTC, vaddya approved these changes
По профилированию ОК, по реализации минорные замечения.

Принято.

2020-11-03 12:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/ModuleTopology.java
> +            while (result.size() < replicas.getFrom()) {
Кажется, сделали проверку на стороне вызывающего кода, но добавили странный отступ для цикла :)

Все равно выглядит немножко не безопасно, потому что если (вдруг) появится еще одно место, откуда вызывается этот метод, но без проверки того, что нод в кластере не меньше, чем `replicas.from`, то код здесь зациклиться, это звучит опасно. Лучше проверять инварианты на входные параметры в самом методе.

2020-11-03 12:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final Cell cell;
А зачем отделять объявление переменной и присваивание?

2020-11-03 12:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +    private static final String PROXY_HEADER = "X-Proxy-For:";
Тоже может пробел после `:` добавить?

2020-11-03 12:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +    private static final String TOMBSTONE = "Tombstone: ";
А точно нужен отдельный флаг для этого?
Можно ли считать, что если на `GET` возвращается 404, но с таймстемпом > 0, то это могилка? Хоть и этот подход тоже рабочий, можно оставить.

2020-11-03 12:51 UTC, closed without merging

2020-11-03 13:14 UTC, KateMoreva commented
> По профилированию ОК, по реализации минорные замечения.
> 
> Принято.

Спасибо большое, все замечания будут исправлены в реализации 6ого этапа.