Stage 5
polis-mail-ru/2020-highload-dht pull request #115
Opened 2020-10-26 21:03 UTC by suhova

2020-10-27 00:04 UTC, suhova commented
[Результаты профилирования](https://github.com/suhova/2020-highload-dht/blob/stage5/reports/stage5.md)

2020-11-01 14:23 UTC, dormidon commented
По отчету:
1. Цифры обстрела GET-ами и PUT-ами совпадают один-в-один. Там точно не копипаста?
2. > Рост времени по-сравнению с предыдущим этапом

Цифры в отчете говорят, что произошло как раз падение, разве нет?
3. Если я правильно понял задание, то нужно еще посравнивать между собой производительность при различных комбинациях ack/from.

2020-11-01 14:33 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Consensus.java
> +                if (Boolean.parseBoolean(response.getHeader(TOMBSTONE))) {
Это не всегда верно, что если хоть с одной реплики пришла могилка, то запись удалена.
У этой могилки тоже есть версия, и если версия могилки старее, чем версия живого значения, то нужно брать живое значение.
Логика в случае Last write wins тупая - берем значение с самой свежей версией. Если там могила - то данных нет, не могила - возвращаем данные.

2020-11-01 14:37 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Consensus.java
> +    public static Response get(final List<Response> responses, final int ack) {
Здесь и везде корректнее не `ack`, а `acks` - их же не одно, а несколько подтверждений в общем случае.

2020-11-01 14:39 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Consensus.java
> +                if (Boolean.parseBoolean(response.getHeader(TOMBSTONE))) {
Легко представить сценарий, когда сначала по ключу пришло удаление, оно успешно осело на одном из трёх узлов, потом пришло создание по тому же ключу, успешно осело на двух других узлах. А при чтении мы прочитали значения со всех трех узлов - одну могилку (но уже неактуальную) и два живых значения.

2020-11-01 14:40 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Consensus.java
> +    private static Response simpleResponse(final List<Response> responses,
Я бы называл что-то вроде `successIfEnoughAcks` или что-то в этом духе.

2020-11-01 14:40 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/DAOServiceMethods.java
> +    private static final Logger logger = LoggerFactory.getLogger(MoribundService.class);
А точно логгер другого класса тут используем?

2020-11-01 14:42 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/DAOServiceMethods.java
> +    public static Response get(@NotNull final String id, @NotNull final DAO dao) {
Мне кажется, проще "обернуть" DAO этим классом (сделать его полем класса и передать в конструкторе), нежели чем передавать в каждом методе.

2020-11-01 14:42 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +public class MoribundService extends HttpServer implements Service {
Отчего такое грустное название?

2020-11-01 14:43 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +    private static final String PROXY_HEADER = "PROXY";
static-поля обычно идут до non-static. Странно, что никакой бот не поругался.

2020-11-01 14:45 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +        this.ackDefault = fromDefault / 2 + 1;
Тут это выглядит как магия.
Мб у самой `Topology` сделать метод `quorumSize()`, который будет вычислять размер кворума?

2020-11-01 14:45 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +                throw new IllegalArgumentException("Duplicate node!");
Написать бы в сообщение название узла, который дублируется.

2020-11-01 14:48 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +    public void sendProxyResponse(final String id, final HttpSession session, final Request request) {
По названию кажется, будто мы что-то проксируем.
А на самом деле мы как раз является конечным обработчиком запроса. 
Предлагаю как-то модифицировать название метода.

2020-11-01 14:52 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +                responses.add(proxy(node, request));
Я правильно понимаю, что мы тут последовательно в блокирующем режиме проходимся по соседним нодам?
Т.е. пока не получили ответ от одной, к следующей не переходим?

2020-11-01 14:54 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +                responses.add(proxy(node, request));
Уточнил, на этом этапе такое поведение нормально. 
Дальше будем оптимизировать :)

2020-11-01 14:59 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Replica.java
> +public class Replica {
Это ведь не совсем реплика. Реплика - это "роль" узла в кластере. 
В данном случае это `Replication`, скорее.

2020-11-01 15:00 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Replica.java
> +    private final int from;
Я бы назвал параметры `acks` и `replicas`. 
`from` без описания задания из Ридми смотрится очень странно)

2020-11-01 15:01 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Replica.java
> +        return new Replica(Integer.parseInt(values.get(0)), Integer.parseInt(values.get(1)));
Тут ведь может быть NumberFormatException.
Его бы тоже лучше отловить и бросить внятную ошибку с примером ввода, на котором мы сломались.

2020-11-01 15:01 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Replica.java
> +    public static Replica of(@NotNull final String replica) {
`String replica` я бы переименовал в `String replicationSpec`

2020-11-01 15:03 UTC, dormidon requested changes
См. комменты.

2020-11-01 15:10 UTC, suhova commented on src/main/java/ru/mail/polis/service/suhova/Consensus.java
> +                if (Boolean.parseBoolean(response.getHeader(TOMBSTONE))) {
Тогда не понятно, зачем в задании существует примечание в скобках 
> 404 Not Found, если ни одна из ack реплик, вернувших ответ, не содержит данные (либо данные удалены хотя бы на одной из ack ответивших реплик)

А так логика last write wins ясна, переделаю этот момент. Тесты проходились при обоих вариантах работы с могилками, поэтому оставила версию из задания)

2020-11-01 15:25 UTC, suhova commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +                responses.add(proxy(node, request));
Да, это вроде бы и нужно решить на 6 этапе

2020-11-01 15:38 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Consensus.java
> +                if (Boolean.parseBoolean(response.getHeader(TOMBSTONE))) {
Да, не самое точное примечание, сейчас его поправим.

А то, что тесты проходили - это плохие тесты :(

2020-11-01 16:36 UTC, suhova commented
[Результаты профилирования](https://github.com/suhova/2020-highload-dht/blob/stage5/reports/stage5.md)
Время для get-ов и правда не оттуда скопировала:( Новое время стало чуть больше, но в среднем всё равно на 10-15% больше прошлого этапа.

По цифрам как раз на каждом персентиле да и в среднем время ответа увеличилось как для put, так и для get.
> Цифры в отчете говорят, что произошло как раз падение, разве нет?

Ответ Вадима по поводу того, с какими параметрами измерять:
> Нагружаете любую ноду PUTами, затем GETами (по дефолту с кворумом). В каждом случае после прогрева профилируете cpu/alloc/lock. Сравниваете с результатами предыдущего этапа.
Либо нагружаете отдельно PUT и GET с replicas=1/3; перезапускаете, чтобы очистить БД; нагружаете PUT и GET с replicas=2/3; сравниваете результаты между собой.

Я выбрала первый вариант и сравнивала время с предыдущим этапом (latency 4 стадии приведены)

2020-11-01 16:51 UTC, suhova commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +public class MoribundService extends HttpServer implements Service {
Можно, пожалуйста, хоть его не переименовывать?) Пока оно лучше всего описывает логику сервиса.

2020-11-02 07:49 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +public class MoribundService extends HttpServer implements Service {
Да я не настаиваю, просто интересна была мотивация :)

2020-11-02 07:54 UTC, dormidon commented on src/main/java/ru/mail/polis/service/suhova/Consensus.java
> +            if (isDeleted || count == count404) {
Тут ведь до сих пор получается, что если встретилась хоть одна могилка, то запись считается удаленной. 
Нужно упростить тут всю логику:
1. Собираем все "осмысленные" ответы
2. Если их недостаточно, возвращаем Not enough replicas
3. Если достаточно, возвращаем самое свежее состояние (если данные - то данные, если могила, то 404, если во всех ответах нет данных - то тоже 404)

2020-11-02 08:14 UTC, dormidon approved these changes
👍

2020-11-02 08:16 UTC, closed without merging