Hw5
polis-mail-ru/2020-highload-dht pull request #116
Opened 2020-10-26 23:16 UTC by re1nex

Профилирование в процессе , открыл пока для тестов и codeclimate

2020-10-29 08:01 UTC, re1nex commented on profile_info/report.md
> +На 50% старая реализация получилась быстрее, но >75% новая реализация начинает обгонять, возможно связано с тем, что один из запросов выполняется синхронно и с тем, что JIT компиляция обработала боль
Тут имел ввиду локально, а не синхронно , и после вчерашней лекции понял , что JIT видимо результат плохого прогрева , хотя странно, вроде подождал

2020-10-30 15:33 UTC, incubos requested changes
Есть ряд замечаний, предложений и вопросов, требующих реакции.

2020-10-30 15:33 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyReplicaService.java
> +        final int ack = from / 2 + 1;
Можно было бы сделать просто ещё один конструктор в `ReplicaInfo` от размера кластера.

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +./wrk  -c64 -d3m -R2000 -s put.lua --latency http://127.0.0.1:8081
Здесь лучше использовать Markdown-вёрстку:
```
Моноширинный код
```

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +По средним показателяи новая реализация в 1,3 раза медленнее, т.к. запись происходит сразу на несколько нод , а не просто переадресация как в случае старой реализации. Но на 99.999% начинает обгонять
Помимо среднего обычно смотрят на 99% и 99.9%.

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +![image](https://github.com/re1nex/2020-highload-dht/blob/hw4/profile_info/with%20replica/put/cpu.svg)
Почему-то в отчёте [не отображается](https://github.com/polis-mail-ru/2020-highload-dht/blob/c80abf8278bcf12703382d434b20332e55ea8714/profile_info/report.md).

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +Количество сэмплов относящихся к сервису увеличилось на 6 %. 28 % занимает управление репликами (их переадресация на другие ноды, вставка в локальное хранилище) 12 % занимают запросы от родительской
Как говорилось на последнем занятии, мы не можем судить об общих требованиях к ресурсам CPU на основе FlameGraph, а лишь к распределению потребления ресурсов между разными частями кода.

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +![image](https://github.com/re1nex/2020-highload-dht/blob/hw4/profile_info/with%20replica/put/alloc.svg)
Тоже не отображается в отчёте.

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +На 50% старая реализация получилась быстрее, но >75% новая реализация начинает обгонять, возможно связано с тем, что один из запросов выполняется синхронно и с тем, что JIT компиляция обработала боль
А разве должно было стать быстрее? Мы обновляем несколько реплик и ждём ответа ото всех из них. Вот в следующем этапе...

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +Больше кода обработано JIT компилятором. Больше сэмплов относящихся к сервису (на 10 %), что ожидаемо т.к. больше запросов нужно обрабатывать.
Это вы про жёлтенькое справа? Так может быть, стоило прогреть подольше?

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +Больше кода обработано JIT компилятором. Больше сэмплов относящихся к сервису (на 10 %), что ожидаемо т.к. больше запросов нужно обрабатывать.
Можете конкретнее описать, на что мы теперь тратим сэмплы CPU? И какую долю это занимает от обработки запросов? Это же анализ результата вашей работы.

2020-10-30 15:33 UTC, incubos commented on profile_info/report.md
> +Также как и спуть количество локов у селекторов стало больше, т.к. и запросов стало больше.
Почему их стало больше? Нагрузка ведь та же и на каждый запрос вы создаёте одну задачу в `Executor`.

2020-10-30 16:02 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/DAO.java
> +        return iter.next().getValue();
добавлю проверку

2020-10-30 16:04 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiController.java
> +            sendErrorResponse(session, Response.INTERNAL_ERROR);
ой , заменю на метод

2020-10-30 16:04 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiController.java
> +            response.addHeader(ApiController.GENERATION + value.getTimestamp());
уберу

2020-10-30 16:06 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiController.java
> +                response.addHeader(ApiController.TOMBSTONE);
перенесу

2020-10-30 16:07 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiController.java
> +                    id, request.getBody(), e.getCause());
заменю

2020-10-30 16:08 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiController.java
> +        request.addHeader(ApiController.PROXY_FOR);
хорошо , сделаю так

2020-10-30 16:10 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiController.java
> +                        get(id));
внутри handleResponses есть проверка на то есть локальная реплика или нет

2020-10-30 16:10 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyReplicaService.java
> +public class AsyncTopologyReplicaService extends BaseAsyncService {
хорошо , добавлю

2020-10-30 16:10 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyReplicaService.java
> +        final int ack = from / 2 + 1;
сделаю

2020-10-30 16:12 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/MergeUtils.java
> +                    hasTombstone = true;
ну так написано в readme , мне тоже показалось это странным , поправлю

2020-10-30 16:15 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ReplicaInfo.java
> +        if (ack > from || ack <= 0) {
ну мы не можем запросить ответ от большего числа нод , чем есть , ну и от 0 и меньше не имеет смысла

2020-10-30 16:17 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        for (int i = 0; i < 4; i++) {
исправлю

2020-10-30 16:17 UTC, re1nex commented on profile_info/report.md
> +./wrk  -c64 -d3m -R2000 -s put.lua --latency http://127.0.0.1:8081
хорошо , добавлю

2020-10-30 16:18 UTC, re1nex commented on profile_info/report.md
> +![image](https://github.com/re1nex/2020-highload-dht/blob/hw4/profile_info/with%20replica/put/cpu.svg)
проверю ссылку

2020-10-30 16:19 UTC, re1nex commented on profile_info/report.md
> +Количество сэмплов относящихся к сервису увеличилось на 6 %. 28 % занимает управление репликами (их переадресация на другие ноды, вставка в локальное хранилище) 12 % занимают запросы от родительской
поправлю

2020-10-30 16:20 UTC, re1nex commented on profile_info/report.md
> +На 50% старая реализация получилась быстрее, но >75% новая реализация начинает обгонять, возможно связано с тем, что один из запросов выполняется синхронно и с тем, что JIT компиляция обработала боль
да меня тоже это удивило , наверное перестреляю и посмотрю еще visual vm

2020-10-30 16:20 UTC, re1nex commented on profile_info/report.md
> +Больше кода обработано JIT компилятором. Больше сэмплов относящихся к сервису (на 10 %), что ожидаемо т.к. больше запросов нужно обрабатывать.
прогревал минуту , но видимо надо больше

2020-10-30 16:23 UTC, re1nex commented on profile_info/report.md
> +Также как и спуть количество локов у селекторов стало больше, т.к. и запросов стало больше.
но каждый запрос это ведь по сути сейчас как 2 вопроса

2020-10-31 16:01 UTC, re1nex commented
Перестрелял get подольше , теперь выглядит более похоже на правду , возможно в тот раз когда стрелял какой-то процесс запустился и повлиял на результаты

2020-11-01 11:11 UTC, incubos commented
Принятно с небольшими замечаниями.

2020-11-01 11:11 UTC, closed without merging