Task 5
polis-mail-ru/2020-highload-dht pull request #117
Opened 2020-10-27 07:51 UTC by PolinaShneider

2020-11-02 08:53 UTC, vaddya requested changes
Есть вопросы по реализации. Прошу прощения за задержку с ревью.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationFactor.java
> +        if (Integer.parseInt(delimitValues.get(0)) < 1 || Integer.parseInt(delimitValues.get(1)) < 1) {
Может объединим как-нибудь эти два `if`-а с одинаковым телом? И не хочется `paseInt` для одного и того же параметра несколько раз делать,.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationFactor.java
> +            session.sendError(Response.BAD_REQUEST, RF_ERROR);
Есть ощущение, что `ReplicationFactor` в целом ничего не должен знать о сессии и работе с ней. Правильнее было бы просто бросать исключение при неверных параметрах, а там в вызывающем коде уже пусть разбираются, что с этим делать.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationFactor.java
> +        return nodeReplicas == null ? replicationFactor : ReplicationFactor.createReplicationFactor(
Этот код точно нужно выносить в отдельный метод? Он по сути ничего не делает, кроме проброса параметров в конструктор и фоллбэка на дефолт в случае `null`. Возможно, это гармоничнее будет просто встроить в место вызова.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationHandler.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ReplicationHandler.class);
Тут и в других местах: логгер принято называть `log`, так как не константа.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationHandler.java
> +            final Map<String, HttpClient> nodesToClients,
`@NotNull`?

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceImpl.java
> +        if (topology.getSize() > 1) {
Может прокомментировать как-то разделение на `multiple`/`single`? Нельзя ли второе выразить как кластер из одной ноды, которая отвественная за все ключи?

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceImpl.java
> +        exec.execute(() -> {
Здесь может прилететь RejectedExecutionException из-за ограниченной очереди, и клиент не получит никакого ответа.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +        return new Value(true, timestamp, ByteBuffer.allocate(0));
Может переиспользовать пустой буффер между всеми объектами? И вопрос, может нам хватит `timestamp` + `buffer`, чтобы выразить три возможных состояния? Без `isValueDeleted`.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Topology.java
> +        this.clusterNodes = new ArrayList<>(nodes);
Нужно отсортировать еще, а то на разных нодах кластера порядок может оказаться разным.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Topology.java
> +        return this.clusterNodes.size();
Либо везде `this` используйте, либо только в конструкторе, либо нигде. Консистентно в общем.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Topology.java
> +    String[] getReplicas(@NotNull final ByteBuffer id, final int numOfReplicas) {
Может `List` заиспользуем?

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Topology.java
> +        final String[] nodeReplicas = new String[numOfReplicas];
Нет проверки, что у нас вообще в кластере есть столько нод, сколько запрашивают. В итоге они могут дублироваться в результате.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(Value.class);
Не стоит в `data`-классы (которые только хронять данные, по идее) тащить логгер. Бросайте исключение с внятным сообщением наружу.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +            throw new IOException();
Нужно сообщение.

2020-11-02 08:53 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +    public static Value composeFromBytes(final byte[] bytes) {
Хм, а можем как-нибудь обойтиесь без сериализации `Value`? Кажется, что `timestamp` можно просто передать через HTTP-хедер, а `isValueDeleted` и вовсе не нужен.

2020-11-04 17:20 UTC, PolinaShneider commented on src/main/java/ru/mail/polis/service/Value.java
> +    public static Value composeFromBytes(final byte[] bytes) {
Комменты поправила кроме этого. Погуглила — так и не поняла, что это за хедер. Буду благодарна за наводку. И что не так с isValueDeleted?

2020-11-04 17:24 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +    public static Value composeFromBytes(final byte[] bytes) {
Можно свой HTTP-хедер возвращать в ответе при проксировании запроса и класть туда, например, `timestamp`. Насчет `isValueDeleted`: по идее, можно считать, что если на `GET` возвращается 404, но с таймстемпом, то это могилка, а если без таймстемпа, то значение просто отсутствует.

2020-11-06 22:28 UTC, PolinaShneider commented
К сожалению, не все замечания удалось поправить малой архитектурной кровью. Получилось процентов на 90. Можете посмотреть PR еще раз?

2020-11-08 17:59 UTC, vaddya requested changes
Еще немного.

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationFactor.java
> +        final int from = Integer.parseInt(delimitValues.get(1));
Нам не прилетит тут `OutOfBoundsException`?

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationHandler.java
> +                replCounter++;
Мне кажется, или это равно `values.size()`?

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceImpl.java
> +            if (topology.getSize() == 1) {
Я так и не понял, надо ли это отдельно обрабатывать? Мы не можем считать, что в этом случае у нас кластер из одной ноды, которая ответственна за все ключи и всегда обращается к своему ДАО? Не смог убедить себя, что что-то сломается в этом случае.

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceImpl.java
> +        } catch (RejectedExecutionException e) {
Хорошо, что ловите, но может это словить и залогировать прямо внутри `runExecutor`? Не забудьтье при этом вернуть клиенту вернуть хоть какой-то ответ (500, наверное).

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceImpl.java
> +            log.error(e.getMessage());
В логгер можно отпарвлять прямо `e`, без вынимания сообщения, чтобы стектрейс тоже вывелся. Ну и можно добавить осмысленное сообщение о том, что сервер не справляется.

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceUtils.java
> +        return isForwardedRequest ? new HashSet<>(ImmutableSet.of(
Нужно ли оборачивать в `HashSet`?

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +        return ByteBuffer.allocate(0);
Такой буфер можно константой сделать чтобы не плодить лишние объекты.

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceUtils.java
> +        return addTimestampHeader(response, value.getTimestamp());
Нужно ли клиенту отдавать таймстемп?

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceUtils.java
> +        return timestamp == null ? -1 : Long.parseLong(timestamp);
Может не распарситься, кстати, и вылетит `NumberFormatException`.

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceUtils.java
> +        if (values.size() == 1) {
Точно нужно отдельный `if` для эотго делать?  Или это оптимизация?

2020-11-08 17:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +        final short isDeleted = isValueDeleted ? (short) 1 : (short) -1;
Остался последний шаг для того, чтобы не класть в body ничего, кроме самого значения. Давайте определять удалено значение или нет по коду ответа + таймстемпу:
- `404 и есть хедер с ts` -> ключ удален (могилка)
- `404 без ts` -> ключ не удален (нет могилки)

2020-11-08 18:15 UTC, PolinaShneider commented on src/main/java/ru/mail/polis/service/ReplicationServiceUtils.java
> +        if (values.size() == 1) {
Это оптимизация. Но, согласна, увеличивает размер кода, и ухудшает понятность. Уберу

2020-11-10 22:25 UTC, PolinaShneider commented
Остатки замечаний поправила

2020-11-11 18:00 UTC, PolinaShneider commented
Закинула буквально одну косметическую правку (уже пожалела об этом 😅) — тесты упали. В трависе уже новый этап, видимо. Я бы хотела заканчивать согласовывать этот и поправить шестой этап с учетом последних правок пятого.

2020-11-11 18:12 UTC, vaddya approved these changes
Ладно, тут все замечания вроде поправили, профилирование ОК. Пойдемте к следующему этапу.

Принято.

2020-11-11 18:12 UTC, closed without merging