stage 5
polis-mail-ru/2020-highload-dht pull request #119
Opened 2020-10-27 12:07 UTC by stakenschneider

2020-11-02 09:28 UTC, vaddya requested changes
Есть вопросы по реализации. Прошу прощения за задержку с ревью.

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/Coordinator.java
> +                            .put(ENTITY_HEADER + id, request.getBody(), PROXY_HEADER);
Почему бы просто не проксировать запрос через `clinet.invoke(request)`, как в асинхронном сервисе?

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/Nodes.java
> +    public String[] replicas(final int count, @NotNull final ByteBuffer key) {
Может вернем `Set`?

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/Nodes.java
> +            res[j] = clusterNode.get(index);
Нет проверки, что у нас в кластере есть хотя бы `count` нод. В итоге могут появиться дублирующиеся ноды в результате.

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/Replica.java
> +        final String rem = value.replace("=", "");
Это, кажется, надо делать где-то в моменте парсинга запроса, а в не при создании RF.

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/Replica.java
> +            session.sendError(BAD_REQUEST, "Wrong ReplicaFactor");
Кажется, что класс `Replica` не должен ничего знать о работе с сессией. Лучше выбросить наружу исключение.

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/TimestampRecord.java
> +        if (responses.size() == 1) return responses.get(0);
Это точно нужно выносить как частный случай? Код в `else` ветке не подойдет?

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +                e.printStackTrace();
Не стоит.

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +        if (proxied || nodes.getNodes().size() > 1) {
Может прокомментировать как-то разделение на одна-нода/много-нод? Нельзя ли второе выразить как кластер из одной ноды, которая отвественная за все ключи?

2020-11-02 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/Coordinator.java
> +                return new Response(Response.OK, mergedResp.toBytes());
Может попробуем избавиться от ситуации, при которой у нас разный формат боди в ответе в зависиомсти от того, проксирован запрос или нет? Например, `timestamp` можно передать через HTTP-хедер при проксировании, а `RecordType`, кажется, можно определить по статусу ответа и по таймстемпу (например, `timestamp == -1` при отсутствии ключа и `timestamp > 0`, если ключ удален).

2020-11-10 19:17 UTC, vaddya commented
Будете фиксить замечания или на следующий этап переходим?

2020-11-10 20:29 UTC, stakenschneider commented
> Будете фиксить замечания или на следующий этап переходим?

Соре, сейчас же поправлю все.

2020-11-12 21:19 UTC, vaddya commented
Any updates?

2020-11-12 21:20 UTC, stakenschneider commented
> Any updates?

я исправила все замечания, что смогла

2020-11-12 21:21 UTC, vaddya commented
> > Any updates?
> 
> я исправила все замечания, что смогла

А, жмите следующий раз кнопку "Re-request review", плз :)

2020-11-12 21:36 UTC, vaddya commented
По ощущениям во время исправления замечаний что-то сломалось, на моей машине сейчас 23 теста падают, у вас как?

2020-11-16 10:24 UTC, vaddya commented
Фиксов нет, в 6 этапе их все равно придется сделать. Но зеленый билд был, 5 баллов.

2020-11-16 10:24 UTC, closed without merging