stage 1
polis-mail-ru/2020-highload-dht pull request #12
Opened 2020-09-27 20:26 UTC by stakenschneider

2020-09-28 01:59 UTC, stakenschneider commented
"Анализ" полученных результатов [тут](https://github.com/stakenschneider/2020-highload-dht/blob/stage-1/profiling/stage_1/results.md).

2020-09-30 18:03 UTC, vaddya commented on build.gradle.kts
> +    compile("org.rocksdb", "rocksdbjni", "6.2.2")
Выбор 6.2.2 (сентябрь 2019 года) чем-то обусловлен? 6.11.x уже пару месяцев как доступна, может обновим?
https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni

2020-09-30 18:13 UTC, stakenschneider commented on build.gradle.kts
> +    compile("org.rocksdb", "rocksdbjni", "6.2.2")
Немного. Я это задание делала в сентябре 2019. Пофиксила в e5c20c497bd1870cbfbd25067ffaa9855ebaab5e.

2020-09-30 18:17 UTC, vaddya commented
У меня что-то некоторые тесты не проходят. Может быть, особенности моей машины.

![Uploading Screen Shot 2020-09-30 at 21.16.52.png…]()

2020-09-30 18:55 UTC, vaddya requested changes
Реализация ОК, осталось тесты поправить, там надо с компаратором разобраться (если совсем не получится, можно обратно на 6.2.2 откатиться). Отличный отчет о профилировании. Круто, что уже было сделано в несколько потоков и то, что результаты были проанализированы.

2020-09-30 21:06 UTC, stakenschneider commented
> Реализация ОК, осталось тесты поправить, там надо с компаратором разобраться (Rocks теперь сравнивают ключи как unsigned byte). Отличный отчет о профилировании. Круто, что уже было сделано в несколько соединений и то, что результаты были проанализированы. Отмечу только, что 99%-перцентиль в 16 секунд это слишком и похоже на слишком высокую нагрузку, лучше поменьше запросов, но в пределах нескольких секунд.

Насколько важно переходить на 6.11? Просто, если честно, мне совсем не интересно байты и байтбуфферы конвертировать, а с первого взгляда, там придется немало посидеть для перехода на новую версию Rocks DB, а сильного велью с этого шага я не вижу. Перешли они с 6.8.1  у меня на 6.7.3 (Mar 25, 2020) все работает без правок.

2020-09-30 21:09 UTC, vaddya commented
Согласен, давайте оставим 6.7.3

> > Реализация ОК, осталось тесты поправить, там надо с компаратором разобраться (Rocks теперь сравнивают ключи как unsigned byte). Отличный отчет о профилировании. Круто, что уже было сделано в несколько соединений и то, что результаты были проанализированы. Отмечу только, что 99%-перцентиль в 16 секунд это слишком и похоже на слишком высокую нагрузку, лучше поменьше запросов, но в пределах нескольких секунд.
> 
> Насколько важно переходить на 6.11? Просто, если честно, мне совсем не интересно байты и байтбуфферы конвертировать, а с первого взгляда, там придется немало посидеть для перехода на новую версию Rocks DB, а сильного велью с этого шага я не вижу. Перешли они с 6.8.1 у меня на 6.7.3 (Mar 25, 2020) все работает без правок.

2020-09-30 21:10 UTC, stakenschneider commented
> Согласен, давайте оставим 6.7.3
> 
> > > Реализация ОК, осталось тесты поправить, там надо с компаратором разобраться (Rocks теперь сравнивают ключи как unsigned byte). Отличный отчет о профилировании. Круто, что уже было сделано в несколько соединений и то, что результаты были проанализированы. Отмечу только, что 99%-перцентиль в 16 секунд это слишком и похоже на слишком высокую нагрузку, лучше поменьше запросов, но в пределах нескольких секунд.
> > 
> > 
> > Насколько важно переходить на 6.11? Просто, если честно, мне совсем не интересно байты и байтбуфферы конвертировать, а с первого взгляда, там придется немало посидеть для перехода на новую версию Rocks DB, а сильного велью с этого шага я не вижу. Перешли они с 6.8.1 у меня на 6.7.3 (Mar 25, 2020) все работает без правок.

Спасибо :)
А не намекнете, как реализацию улучшить?

2020-09-30 21:16 UTC, vaddya commented
> А не намекнете, как реализацию улучшить?

Тут пока всего несколько классов с логикой, в которых все хорошо. Дальше с репликацией и кворумами будет интереснее, будет простор для оптимизаций и улучшений 😊

2020-09-30 21:45 UTC, stakenschneider commented
> > А не намекнете, как реализацию улучшить?
> 
> Тут пока всего несколько классов с логикой, в которых все хорошо. Дальше с репликацией и кворумами будет интереснее, будет простор для оптимизаций и улучшений 😊
> 
> Обновите только, пожалуйста, версию в зависимостях, чтобы сборка прошла

Спасибо)
Она уже прошла в 171c7937eb2ac1f225606e4bb9e60e6dec91367e.

2020-10-01 09:59 UTC, vaddya requested changes
Накинул по мелочи (в основном, по стилю), предлагаю добить и переходить к следующим этапам

2020-10-01 09:59 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/NoSuchElementLite.java
> +public class NoSuchElementLite extends NoSuchElementException {
Принято, что экспшены имеют суффикс `Exception`

2020-10-01 09:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/ServiceImplementation.java
> +public class ServiceImplementation extends HttpServer implements Service {
`Implementation` обычно сокращают до `Impl`

2020-10-01 09:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/ServiceImplementation.java
> +                case Request.METHOD_GET: {
По стайл гайдам (например, [Google](https://google.github.io/styleguide/javaguide.html#s4.8.4-switch)) выражения внутри ветки кейс не оборачивают в скоуп (`{}`). Это бывает нужно, чтобы ввести область для переменных, но здесь все прозрачно и можно обойтись без них

2020-10-01 09:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/ServiceImplementation.java
> +    ) {
Такой перенос не характерен для Java (скорее для какого-нибудь JS/TS) -- скобки оставляют на строке с последним параметром

2020-10-01 09:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/ServiceImplementation.java
> +            return new Response(Response.INTERNAL_ERROR, Response.EMPTY);
Может залогируем такие ситуации? Пригодится в будущих этапах

2020-10-01 09:59 UTC, vaddya commented on wrk/delete.lua
> +end
Лучше стараться во всех файлах оставлять в конце [пустую строку](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

2020-10-01 09:59 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/RocksDAO.java
> +            throw new IOException("", exception);
Немного непривычно выглядит пустое сообщение, может хотя бы `"Compaction error"`?

2020-10-01 10:30 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/ServiceImpl.java
> +            log.info(ex.getMessage());
Так мы потеряем весь стектрейс исключения, правильнее
`log.error("Some meaningful error message", ex)`;

И лучше разнести эти две ветки catch, потому что `NoSuchElementLiteException` это более-менее нормальная ситуация для сервера -- по ключу просто ничего не лежит, а `IOException` это какая-то внтуренняя ошибка и правильнее вернуть 500.

2020-10-01 10:32 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/ServiceImpl.java
> +        log.info("bad request");
Тянет на уровень `warn`/`error`, и было бы неплохо залогировать еще и путь, для которого у нас нет хендлера

2020-10-01 11:03 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/ServiceImpl.java
> +    private static Logger log = Logger.getLogger(ServiceImpl.class.getName());
Статические поля должны быть выше пропертей. И `log` можно сделать финальным, не знаю, почему код клаймет не ругнулся

2020-10-01 11:03 UTC, vaddya approved these changes
Принято

Как намучаетесь с `java.util.logging`, попробуйте `log4j` или `slf4j`. Не придется передавать уровень логирования параметром, и можно будет плейсхолдеры использовать вместо хаков с `concat` или `Supplier<String>` 🙂

2020-10-01 12:07 UTC, closed without merging

2020-10-01 12:07 UTC, stakenschneider commented
> Принято
> 
> Как намучаетесь с `java.util.logging`, попробуйте `log4j2` или `slf4j`. Не придется передавать уровень логирования параметром, и можно будет плейсхолдеры использовать вместо хаков с `concat` или `Supplier<String>` 🙂

Спасибо за замечания :)