Stage5
polis-mail-ru/2020-highload-dht pull request #121
Opened 2020-10-27 15:17 UTC by dariaGap

2020-10-30 16:38 UTC, incubos requested changes
Есть ряд замечаний, предложений и вопросов, требующих реакции.

2020-10-30 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/service/dariagap/ClusterServiceImpl.java
> +        HttpClient client;
Лучше передвинуть ближе к месту использования.

2020-10-30 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/service/dariagap/ClusterServiceImpl.java
> +                ? new Replicas(topology.size()) : new Replicas(replicas);
Можно сделать `new Replicas(topology.size())` полем и не аллоцировать каждый раз, ибо для фиксированного размера кластера никогда не меняется.

2020-10-30 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/service/dariagap/ClusterServiceImpl.java
> +                break;
Тут `break` не нужен.

2020-10-30 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/service/dariagap/ClusterServiceImpl.java
> +            request.addHeader(PROXY_HEADER);
`Request` лучше клонировать/копировать перед модификацией, иначе проксирование к каждой ноде будет добавлять очередной заголовок. Может под отладчиком проверить.

2020-10-30 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/util/Replicas.java
> +    private Long freshTimestamp = 0L;
Здесь тоже все boxed-типы нужно заменить на примитивы.

2020-10-30 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/util/Replicas.java
> +    private final Logger log = LoggerFactory.getLogger(Replicas.class);
Почему не `static`?

2020-10-30 16:38 UTC, incubos commented on src/main/java/ru/mail/polis/util/Replicas.java
> +        if (freshData.length == 0
Нужно ли в этом условии анализировать размер `freshData`?

2020-10-30 16:38 UTC, incubos commented on doc/Stage5.md
> +По результатам нагрузочного тестирования видно, что скорость обработки запросов по сравнению с предыдущим этапом замедляется незначительно (в 1 - 1.16 раз), что может объясняться меньшей очередью зап
"незначительно" на основе какого именно показателя? Обычно смотрят на 99% и 99.9%.

2020-10-30 16:38 UTC, incubos commented on doc/Stage5.md
> +Падение производительности объясняется необходимостью обращения к двум репликам вместо одной, следовательно, добавляются затраты на проксирование запросов, ожидание обработки в каждой из реплик и обр
Наверное, к **трём репликам**, а не к двум?

2020-10-30 16:38 UTC, incubos commented on doc/Stage5.md
> +Падение производительности объясняется необходимостью обращения к двум репликам вместо одной, следовательно, добавляются затраты на проксирование запросов, ожидание обработки в каждой из реплик и обр
К **трём репликам**, а не к одной?

2020-11-01 14:48 UTC, dariaGap commented
Замечания устранены. Проведите, пожалуйста, повторное ревью.

2020-11-02 09:28 UTC, incubos commented
Принято с небольшими замечаниями.

2020-11-02 09:28 UTC, closed without merging