Task 5
polis-mail-ru/2020-highload-dht pull request #122
Opened 2020-10-27 17:38 UTC by nik27090

2020-10-27 19:53 UTC, nik27090 commented
Билдится уже час:(
Локально все тесты проходят, если что)

2020-10-27 21:05 UTC, nik27090 commented
бесконечный CI ((

2020-11-01 15:07 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    Cell getCell(@NotNull final ByteBuffer key) throws IOException;
Тут бы доку для красоты, для чего именно такой метод нужен, что аж кишки наружу выставляет.

2020-11-01 15:07 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> +        final long flushSize = (long)(MAX_HEAP * 0.1);
А чем MAX_HEAP / 10 хуже?

2020-11-01 15:10 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/nik27090/DAOImpl.java
> +        final List<Iterator<Cell>> filesIterators = new ArrayList<>();
А разве мы тут не должны тоже потобезопасно собирать эти итераторы, как в `getAliveCells`?
Вообще методы ведь очень похоже - и тот, и тот нам собирает правильную пачку ячеек. В одном случае только могилки фильтруются. Мб как-то переиспользовать? Заодно и логику блокировок переиспользуем.

2020-11-01 15:15 UTC, dormidon commented on src/main/java/ru/mail/polis/service/nik27090/DaoHelper.java
> +        result.forEach(resp -> {
А для чего мы считаем количество респонсов?
У нас ведь респонсы уникальные? Или это типа группировка по OK/NoFound/Error и т.д.?
Но даже она нам не особо пригодится.
Если мы реализуем LastWriteWins, то мы берем не те респонсы, которые _чаще_ всего встречаются, а значение того респонса, который _самый свежий_. Отсюда и "last" в Last write wins.

2020-11-01 15:16 UTC, dormidon commented on src/main/java/ru/mail/polis/service/nik27090/DaoHelper.java
> +                maxCount = entry.getValue();
Этот maxCount тут не нужен, он делает некорректным разрешение конфлитка при Last Write Wins.

2020-11-01 15:19 UTC, dormidon commented on src/main/java/ru/mail/polis/service/nik27090/HttpHelper.java
> +            sendResponse(session, new Response(Response.GATEWAY_TIMEOUT, Response.EMPTY));
Мб само сообщение с `Not enough replicas...` тоже в HTTP-ответ засунуть, а то там безликий гейтвейт-таймаут будет, ничего не понятно ведь.

2020-11-01 15:22 UTC, dormidon approved these changes
См. комменты.

2020-11-01 15:23 UTC, dormidon requested changes
См. комменты.

2020-11-03 20:24 UTC, nik27090 commented
Не ожиданно долго искал баг в шестой дз (около 4 часов), проше еще часик сверх дедлайна

2020-11-03 20:39 UTC, nik27090 commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> +        final long flushSize = (long)(MAX_HEAP * 0.1);
Так исторически сложилось. Было проще экспереметировать (max_heap * 0.1) -> (max_heap * 1.2) и тд
Оптимизация записи одного символа))

2020-11-03 20:59 UTC, nik27090 commented on src/main/java/ru/mail/polis/service/nik27090/DaoHelper.java
> +        result.forEach(resp -> {
Согласен, пофиксил

2020-11-03 20:59 UTC, nik27090 commented on src/main/java/ru/mail/polis/service/nik27090/DaoHelper.java
> +                maxCount = entry.getValue();
фиксед

2020-11-03 21:04 UTC, nik27090 commented on src/main/java/ru/mail/polis/service/nik27090/HttpHelper.java
> +            sendResponse(session, new Response(Response.GATEWAY_TIMEOUT, Response.EMPTY));
фиксед

2020-11-03 21:09 UTC, nik27090 commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    Cell getCell(@NotNull final ByteBuffer key) throws IOException;
фиксед

2020-11-03 21:09 UTC, nik27090 commented on src/main/java/ru/mail/polis/dao/nik27090/DAOImpl.java
> +        final List<Iterator<Cell>> filesIterators = new ArrayList<>();
Это буду уже фиксить в следуйщей дз, тут надо подумать... Кажется у меня большие проблемы из-за это в 6 дз

2020-11-04 09:42 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/nik27090/DAOImpl.java
> +        final List<Iterator<Cell>> filesIterators = new ArrayList<>();
Ну это серьёзное замечание, даже не косметика, а явный concurrency-баг.
Но если пофиксим, то норм.

2020-11-04 09:46 UTC, dormidon commented
Наша система поиска заимствований нашла интересные моменты:
![image](https://user-images.githubusercontent.com/727478/98095204-50d78d80-1e9b-11eb-9761-54e35443b2a1.png)
![image](https://user-images.githubusercontent.com/727478/98095226-592fc880-1e9b-11eb-926e-731afe5472ed.png)
и много другого.
Выглядит так, что DaoHelper практически полностью скопирован у Кати с MyRequestHelper.
Не надо так делать. В ведомость идет 4 балла - отнимаю 5 за такое заимствование и 1 за явный непофикшенный concurrency-баг.
Если заимствования будут повторяться, будет вообще 0 баллов за задание.

2020-11-04 09:47 UTC, closed without merging