Homework5
polis-mail-ru/2020-highload-dht pull request #123
Opened 2020-10-27 17:53 UTC by Marashov-Alexander

2020-10-28 09:13 UTC, incubos requested changes
360 строк для одного класса -- это действительно много. Рефакторить будете?

2020-10-28 10:32 UTC, Marashov-Alexander commented
> 360 строк для одного класса -- это действительно много. Рефакторить будете?

Да, берусь

2020-10-30 16:43 UTC, incubos commented
> > 360 строк для одного класса -- это действительно много. Рефакторить будете?
> 
> Да, берусь

2 дня прошло, нехорошо.

2020-11-01 09:10 UTC, Marashov-Alexander commented
> > > 360 строк для одного класса -- это действительно много. Рефакторить будете?
> > 
> > 
> > Да, берусь
> 
> 2 дня прошло, нехорошо.

Отрефакторил.
При профилировании под большой нагрузкой вылетали ошибки, стал дебажить - нашёл concurrent-баг в SSTable. 
Теперь даю нагрузку в 1000 запросов в секунду - после пары минут работы начинает сыпать таймаутами.
Можете подсказать, на какой участок в коде мне стоит обратить внимание?

2020-11-01 11:15 UTC, incubos commented
> > > > 360 строк для одного класса -- это действительно много. Рефакторить будете?
> > > 
> > > 
> > > Да, берусь
> > 
> > 
> > 2 дня прошло, нехорошо.
> 
> Отрефакторил.
> При профилировании под большой нагрузкой вылетали ошибки, стал дебажить - нашёл concurrent-баг в SSTable.
> Теперь даю нагрузку в 1000 запросов в секунду - после пары минут работы начинает сыпать таймаутами.
> Можете подсказать, на какой участок в коде мне стоит обратить внимание?

С ходу непонятно. Надо втыкать везде логи, перехватывать и логгировать все ошибки. Может быть, даже 1000 многовато? И всё начинает таймаутиться при интенсивных `flush`?

2020-11-02 06:44 UTC, Marashov-Alexander commented
> > > > > 360 строк для одного класса -- это действительно много. Рефакторить будете?
> > > > 
> > > > 
> > > > Да, берусь
> > > 
> > > 
> > > 2 дня прошло, нехорошо.
> > 
> > 
> > Отрефакторил.
> > При профилировании под большой нагрузкой вылетали ошибки, стал дебажить - нашёл concurrent-баг в SSTable.
> > Теперь даю нагрузку в 1000 запросов в секунду - после пары минут работы начинает сыпать таймаутами.
> > Можете подсказать, на какой участок в коде мне стоит обратить внимание?
> 
> С ходу непонятно. Надо втыкать везде логи, перехватывать и логгировать все ошибки. Может быть, даже 1000 многовато? И всё начинает таймаутиться при интенсивных `flush`?

Добрый день, спасибо за ответ!
Добавил логов - стало видно, что очередь задач доходит до отправки запросов попросту позже, чем происходит таймаут ожидания от нод (1 секунда). То есть сначала нода скажет, что ей никто не ответил, а уже через какое-то время начинают выполняться задачи отправки запросов.
Для решения проблемы добавил отдельный executorService для проксирования запросов на другие ноды - и сервер справился с нагрузкой в 1000 запросов в секунду. Однако 100% запросов по результатам WRK укладываются в 70 мс, что навеевает мысль о далеком несовершенстве реализации :)

2020-11-02 06:45 UTC, Marashov-Alexander commented
> > > > > > 360 строк для одного класса -- это действительно много. Рефакторить будете?
> > > > > 
> > > > > 
> > > > > Да, берусь
> > > > 
> > > > 
> > > > 2 дня прошло, нехорошо.
> > > 
> > > 
> > > Отрефакторил.
> > > При профилировании под большой нагрузкой вылетали ошибки, стал дебажить - нашёл concurrent-баг в SSTable.
> > > Теперь даю нагрузку в 1000 запросов в секунду - после пары минут работы начинает сыпать таймаутами.
> > > Можете подсказать, на какой участок в коде мне стоит обратить внимание?
> > 
> > 
> > С ходу непонятно. Надо втыкать везде логи, перехватывать и логгировать все ошибки. Может быть, даже 1000 многовато? И всё начинает таймаутиться при интенсивных `flush`?
> 
> Добрый день, спасибо за ответ!
> Добавил логов - стало видно, что очередь задач доходит до отправки запросов попросту позже, чем происходит таймаут ожидания от нод (1 секунда). То есть сначала нода скажет, что ей никто не ответил, а уже через какое-то время начинают выполняться задачи отправки запросов.
> Для решения проблемы добавил отдельный executorService для проксирования запросов на другие ноды - и сервер справился с нагрузкой в 1000 запросов в секунду. Однако 100% запросов по результатам WRK укладываются в 70 мс, что навеевает мысль о далеком несовершенстве реализации :)
Сейчас займусь профилированием

2020-11-02 09:32 UTC, incubos requested changes
Можно ревьюить?

2020-11-02 09:38 UTC, Marashov-Alexander commented
> Можно ревьюить?
Я сейчас занимаюсь написанием отчёта по работе, код больше не меняю)

2020-11-02 09:41 UTC, Marashov-Alexander commented
> Можно ревьюить?

Кстати, насчёт скорости ответов: при нагрузке заметил, что со временем может происходить heap overflow. После уменьшения значения FlashThreshold проблема исчезла, сервер стал работать значительно быстрее, даже 2000 запросов обработал без проблем

2020-11-02 11:24 UTC, Marashov-Alexander commented
> Можно ревьюить?

Так, теперь точно готово

2020-11-03 12:18 UTC, incubos requested changes
Хорошая реализация. Интересно реализован параллельный опрос реплик и сериализация `Value` средствами `one-nio`.
Тем не менее, есть ряд небольших замечаний и одно -- критичное (про tombstone).

2020-11-03 16:12 UTC, Marashov-Alexander commented on profiler/homework5/analysis.md
> +Если сравнивать результаты нагрузки с этапом 4, то прирост ожидания ответа put метода вырос практически в два раза: с 8 мс на 4 этапе до 9-16 мс (100% ответов).
Учту, спасибо :)

2020-11-03 16:18 UTC, Marashov-Alexander commented on profiler/homework5/analysis.md
> +используется два экземпляра: один для выполнения локальных задач, другой - для осуществления проксирования на другие ноды.
Изначально реализовал всё на одном executorService, но даже при относительно невысокой нагрузке (1000 запросов в секунду) сервер через какое-то время начинал сыпать ответами с кодом 504. После добавления огромного количества логов выяснилось, что запросы "пользователей" забивали executorService так быстро, что пока очередь доходила до выполнения задач проксирования, то уже происходил таймаут ожидания анализа ответов (1 секунда).
Иными словами, ожидание начиналось "мгновенно", а проксирование начинало выполняться через время, большее секунды.
Добавление второго executorService решило проблему. Теперь сервер даже при 2000 запросов в секунду чувствует себя не очень плохо)

2020-11-03 16:19 UTC, Marashov-Alexander commented on profiler/homework5/analysis.md
> +    16% - на работу метода ValidatedParameters.validateParameters (большая часть этого: работа splitToList - 9.45%),
Да, сейчас займусь

2020-11-03 16:22 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/analyzers/ResponseAnalyzerGet.java
> +        return tombstoneValue != null
Полностью согласен с Вами, это некорректная реализация, сейчас займусь исправлением.
Меня смутила формулировка задания:
> HTTP GET /v0/entity?id=<ID>[&replicas=ack/from] -- получить данные по ключу <ID>. Возвращает:
> ...
> 404 Not Found, если ни одна из ack реплик, вернувших ответ, не содержит данные <b>(либо данные удалены хотя бы на одной из ack ответивших реплик)</b>
> ...
Видимо, не так понял)

2020-11-03 16:23 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/analyzers/ResponseAnalyzerGet.java
> +            return new Response(Response.NOT_FOUND, Response.EMPTY);
Хорошо, займусь исправлением

2020-11-03 16:41 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/analyzers/SimpleResponseAnalyzer.java
> +    protected void privateAccept(final Boolean isSuccess) {
Добрый вечер!
SimpleResponseAnalyzer отвечает за PUT и DELETE ответы, в которых достаточно всего два возможных значения - успех операции (true) и неудача (false).
Однако в данном случае не могу использовать примитив boolean, так как ResponseAnalyzer (от которого наследуюсь) - шаблонный класс

2020-11-03 17:15 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/analyzers/ResponseAnalyzerGet.java
> +                final boolean flag = count == maxCount && value.compareTo(correctValue) > 0;
Да. Исправил :)

2020-11-03 17:16 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/DaoManager.java
> +        } catch (final IOException | NoSuchElementException e) {
Действительно так лучше, спасибо!

2020-11-03 17:17 UTC, Marashov-Alexander commented on profiler/homework5/analysis.md
> +    16% - на работу метода ValidatedParameters.validateParameters (большая часть этого: работа splitToList - 9.45%),
Написал через линейный поиск символа по строке с помощью indexOf()

2020-11-03 17:18 UTC, Marashov-Alexander commented on profiler/homework5/analysis.md
> +PUT
Понял. Можно я со следующего ДЗ начну использовать эти возможности?

2020-11-05 11:01 UTC, incubos commented on profiler/homework5/analysis.md
> +PUT
Да.

2020-11-05 11:08 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/analyzers/ResponseAnalyzerGet.java
> +        return tombstoneValue != null
Наша недоработка. Пофиксил описание задания.

2020-11-05 11:09 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/analyzers/SimpleResponseAnalyzer.java
> +    protected void privateAccept(final Boolean isSuccess) {
Да, не заметил.

2020-11-05 11:17 UTC, incubos commented
Принято с замечанием, которое можно поправить в следующем этапе.

2020-11-05 11:17 UTC, closed without merging

2020-11-05 11:22 UTC, Marashov-Alexander commented
> Принято с замечанием, которое можно поправить в следующем этапе.

Спасибо за ревью!
Вы говорите про tombstone замечание?
Если да, то я залил изменения на этот счёт. Видимо, просто забыл отписаться.
Если нет, то можете, пожалуйста, повторно указать?