Stage 5
polis-mail-ru/2020-highload-dht pull request #127
Opened 2020-10-28 10:47 UTC by gogun

2020-10-28 11:12 UTC, incubos commented
Дедлайн уже наступил.

2020-10-28 11:25 UTC, gogun commented
> Дедлайн уже наступил.

Я понимаю, но рекомендации кодклимата и ревью все равно же надо получить.

2020-10-28 12:19 UTC, incubos commented
> > Дедлайн уже наступил.
> 
> Я понимаю, но рекомендации кодклимата и ревью все равно же надо получить.
> Или на рабочий код после дедлайна ревью уже не будет?

По общим правилам до дедлайна должны и тесты проходить, и замечания CodeClimate должны быть пофикшены. На это всё даётся целая неделя. В качестве исключения поревьюим, но максимум уже 5 баллов из 10.

2020-10-28 13:16 UTC, gogun commented
> > > Дедлайн уже наступил.
> > 
> > 
> > Я понимаю, но рекомендации кодклимата и ревью все равно же надо получить.
> > Или на рабочий код после дедлайна ревью уже не будет?
> 
> По общим правилам до дедлайна должны и тесты проходить, и замечания CodeClimate должны быть пофикшены. На это всё даётся целая неделя. В качестве исключения поревьюим, но максимум уже 5 баллов из 10.

Хорошо, спасибо, сейчас исправлю codeclimate и добавлю результаты нагрузочного тестирования.

2020-11-10 20:08 UTC, vaddya requested changes
Замечения/предложения по реализации.

2020-11-10 20:08 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            response = Response.ok(Response.EMPTY);
Как-то логичнее выглядит `404`, а не `200`.

2020-11-10 20:08 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +        responses.removeIf((e) -> e.getStatus() == 500);
Больше похоже на логику, которую должен делать `MergeResponses`.

2020-11-10 20:08 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/MergeResponses.java
> +public class MergeResponses {
Интересный подход. Более по джавовому было бы назвать класс существительным, например `ResponseMerger`.

2020-11-11 10:01 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +        executorService.execute(() -> {
Я прокидываю его выше `throws RejectedExecutionException` и ловлю уже там

2020-11-11 10:40 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            response = Response.ok(Response.EMPTY);
Согласен, но у меня написано так, что в случае 404 данные не найдены и на мерже просто считается кол-во таких ответов, а если 200, то надо найти последнюю версию среди таких и разобраться могилка это или нет и дальше уже клиенту выкинуть 404, если могила.

2020-11-11 12:06 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +        } catch (IOException | InterruptedException | PoolException | HttpException e) {
Codeclimate против(

2020-11-11 12:16 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        for (final String tmp : list) {
Не очень понял как...

2020-11-11 12:41 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        for (final String tmp : list) {
В начало первого цикла добавить 
```java
if (i == list.size()) {
    i = 0;
}
```

2020-11-11 12:45 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            response = Response.ok(Response.EMPTY);
Я понимаю, но 200 с пустым боди мне все равно не нравится :( 

Давайте пожертвуем немного простотой мерджа во имя консистентности: нет значения -- возвращаем 404.

2020-11-11 12:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        for (int i = list.indexOf(node); i < count; i++) {
Не решено все же. Подход, который вы реализовали -- рабочий. Но он немного противоречит логике работы нашего сервиса. В текущей реализации кажется, что у ключа есть какая то primary/master/главная нода, и N реплик. На самом деле, мы используем leaderless (Dynamo-style) подход, который используется в Cassandra. Поэтому все же нужно заменить использование пары методов `get` + `getReplNodes` на один метод `primaryFor(key)`, который будет сразу возвращать `Set` нод.

2020-11-11 12:56 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        for (int i = list.indexOf(node); i < count; i++) {
И еще нет проверки, что у нас в кластере вообще есть столько нод.

2020-11-11 12:57 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        return Arrays.asList(new TreeSet<>(circle.values()).toArray(new String[0]));
Мы это будем делать каждрый раз для определения списка нод для ключа? Нет ощущения, что это прям хорошо отсветит на флейм графах?

2020-11-11 12:58 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        final Set<String> set = new TreeSet<>(circle.values());
Может не стоит лишних перекопирований делать?

2020-11-11 12:59 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        for (final String tmp : list) {
Логично, но я уже перешел на `Set` и цикл foreach)
Сейчас перепишу на итераторы.

2020-11-11 13:05 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        final Set<String> set = new TreeSet<>(circle.values());
Перенес в конструктор, теперь сет уникальных нод с кольца получаю один раз.

2020-11-11 13:22 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        for (int i = list.indexOf(node); i < count; i++) {
Вроде поправил

2020-11-11 13:24 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        final Set<String> set = new TreeSet<>(circle.values());
А параметр конструктора `Collection<String> nodes` это не то, что вы хотите полуичить? :)

2020-11-11 13:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +            return new HashSet<>();
На такое обычно исключения бросают.

2020-11-11 13:29 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +            if (node.equals(startNode) || !nodes.isEmpty()) {
Как то не эффективно получается. Может попробуем сделать через `circle.tailMap(hash).values().iterator()`?

2020-11-11 13:33 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        final Set<String> set = new TreeSet<>(circle.values());
блин....
именно оно

2020-11-11 13:34 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            response = Response.ok(Response.EMPTY);
поправил

2020-11-12 12:52 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +            if (node.equals(startNode) || !nodes.isEmpty()) {
Подправил, но без костыля все равно не обошлось...

2020-11-12 15:44 UTC, vaddya requested changes
По реализации чуть-чуть еще. 
По профилированию: 700 мс многовато, уменьшайте нагрузку, пока хотя бы в пределах 100 мс не будете. Лучше перепрофилировать, потому что в 6 этапе надо будет оценить эффект от перехода к асинхронному клиенту.

2020-11-12 15:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                replicasFactor = ReplicasFactor.quorum(request.getParameter("replicas").substring(1));
Если заглянуть внутрь, то видно, что `request.getParameter` каждый раз заново разбирает строку, лучше это сделать один раз. И строковый литерал лучше вынести в константу.

2020-11-12 15:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +        } catch (IOException | InterruptedException | PoolException | HttpException e) {
Лучше залогировать, чтобы понять, какая ошибка.

2020-11-12 15:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            response.addHeader(TOMBSTONE_HEADER + true);
В целом, этот заголовок и не нужен, хватает статуса ответа и таймстемпа:
- Есть ключ -> `200` и `ts`
- Удален ключ -> `404` и `ts`
- Нет ключа -> `404` без `ts` (или с `ts == -1`)

Но этот подход тоже рабочий, просто несколько избычтоный.

2020-11-12 15:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        this.uniqueValues = new TreeSet<>(nodes);
А если в какой-то момент добавится еще одна нода в кластер?

2020-11-12 15:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +    public Set<String> primaryFor(@NotNull final ByteBuffer key, final int count) {
Какой-то очень сложный метод получился :( 

Есть подозрение, что все, что вы хотите, можно примерно выразить через
```java
final var hash = hash(key);
final var result = new HashSet<String>();
var it = ring.tailMap(hash).values().iterator();
while (result.size() < rf.from()) {
    if (!it.hasNext()) {
        it = ring.values().iterator();
    }
    result.add(it.next());
}
return result;
```

Попробуйте, пожалуйста, отрефакторить, а то сложно разобраться, не говоря уже о том, чтобы убедиться, что оно работает корректно (тестов-то на топологию нет).

2020-11-12 15:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ReplicasFactor.java
> +        this.from = Integer.parseInt(askFrom.get(1));
Вообще, кидать наружу `IndexOutOfBoundsException` как-то не очень. Лучше отловить это исключение и пробросить `InvalidParameterException`. Тогда в вызывающем коде придется ловить только его.

2020-11-13 08:46 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ReplicasFactor.java
> +        this.from = Integer.parseInt(askFrom.get(1));
codeclimate не очень любит если ловим один эксепшнт, а прокидываем другой `New exception is thrown in catch block, original stack trace may be lost `

2020-11-13 08:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ReplicasFactor.java
> +        this.from = Integer.parseInt(askFrom.get(1));
Дак вы не теряйте, передавайте исходное исключение в конструктор нового :)

2020-11-13 08:53 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ReplicasFactor.java
> +        this.from = Integer.parseInt(askFrom.get(1));
у `InvalidParameterException` есть конструктор только по `String`

2020-11-13 08:54 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ReplicasFactor.java
> +        this.from = Integer.parseInt(askFrom.get(1));
могу `getMessage()` из `IndexOutOfBoundsException` прокинуть, но не знаю как на это codeclimate будет смотреть

2020-11-13 08:55 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ReplicasFactor.java
> +        this.from = Integer.parseInt(askFrom.get(1));
<img width="409" alt="Screen Shot 2020-11-13 at 11 54 44" src="https://user-images.githubusercontent.com/15687094/99048809-18c10080-25a7-11eb-9f03-c10f596d6fe0.png">

2020-11-13 09:21 UTC, gogun commented
Вроде все поправил, сейчас перепрофилирую, заново надо проанализировать flamegraph'ы или только новые закинуть?

2020-11-13 09:23 UTC, vaddya commented
> Вроде все поправил, сейчас перепрофилирую, заново надо проанализировать flamegraph'ы или только новые закинуть?

Ну если увидите что-нибудь интересное на них, то напишите.

2020-11-13 10:29 UTC, gogun commented
Подправил отчет, добавил 3 новых флеймграфа, в отчете изменил вывод wrk2. get не трогал и так до 100мс.

2020-11-13 10:41 UTC, vaddya approved these changes
Профилирование ОК, осталось добить хэширование, доделайте в 6 этапе, пожауйлста.

2020-11-13 10:41 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +                iterator = uniqueValues.iterator();
Поле `uniqueValues` вам не нужно совсем, потому что там хранятся исходные ноды, а не кольцо виртуальных нод (в чем и есть идея алгоритма consistent hashing).

2020-11-13 10:41 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        return circle.size();
Разве это настоящий размер кластера? В кольце хранится `nodes * vnodes` значений.

2020-11-13 10:41 UTC, closed without merging

2020-11-13 16:41 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +                iterator = uniqueValues.iterator();
Все, понял, спасибо