Task6
polis-mail-ru/2020-highload-dht pull request #128
Opened 2020-10-31 14:21 UTC by s3ponia

2020-11-21 17:51 UTC, lamtev requested changes
# Реализация

Нужно переосмыслить то, как пользоваться CompletableFuture

Обычно любая операция с суффиксом Async, если не передать свой ExecutorService, будет выполняться на ForkJoinPool.commonPool, что почти наверняка не является ожидаемым поведением. Так нужно помнить передавать свой экзекютор

Также стоит понимать, что нет смысла в том, чтобы всегда выполнять над результатом предыдущей фючи действия асинхронно, что засабмитит в underlying экзекютор новую задачу. Соответственно появятся накладные расходы как минимум в локах BlockingQueue. Бывают случаи, когда стоит выполнять асинхронно, например, когда это какая-то долгая операция, и при этом не хочется надолго занимать экзекютор. Тогда асинхронное выполнение позволит выполнить на экзекюторе другие засабмиченные в него задачи.

# Профилирование

1. Отчет не содержит никаких пояснений к графикам и таблицам.
2. После исправлений реализации нужно будет заново профилировать, т.к. картина должна поменяться
3. На первом флейм графе видно, что процесс не прогрет

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +            @NotNull final AsyncService service) throws IOException {
Не очень хорошо тащить в утилитный класс AsyncService. Да и еще читать его instance-field'ы

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +            @NotNull final AsyncService service) throws IOException {
Много в методы аргументов передается. Наверное, лучше конвертировать класс из утилитного в обычный, и в конструктор передавать ему те поля AsyncService, которые нужны

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +public final class AsyncServiceUtility {
И из основного AsyncService и отсюда выполняется отправка ответов клиентам, что как-то не очень, потому что получается, что 2 сущности ответственны за одну логику. Стоит получше подумать над тем, что должно выполняться в AsyncService, а что можно делегировать другим классам

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/dao/DAO.java
> +            final long timeStamp) throws IOException;
Это еще, наверное, изменения внесенные в прошлых этапах. Можно было не расширять интерфейс, а скрыть добавление/извлечение таймстемпов в реализации

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +                        .whenCompleteAsync((c, t) -> handlingUpsertResult(session, t))
1. Нужна ли здесь асинхронность? Код из лямбды будет засабмичен в executor service
2. Все методы с суффиксом Async, если в них не передать executor service, выполняют работу на глобальном ForkJoinPool.commonPool(). Стоит об этом помнить, и в случае, когда асинхронность нужна, обязательно передавать свой экзекютор. 

Касается многих мест в данном решении

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +            if (parsed == null) return;
очень похоже на то, что клиент не получит ответа вовсе, если отправит запрос с плохим rf

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +    }
И без того класс получился довольно длинным и отвечающим много за что. Чего бы не вынести это в отдельный файл, как было на лекции в демо?

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static final String PROXY_HEADER = "X-Proxy-From";
Уже довольно давно не рекомендуется собственные заголовки называть с префиксом `X-`

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +            new Utility.ReplicationConfiguration(3, 5)
Тоже не код 6-го этапа. Но довольно странно что эти дефолтные кворумы захардкожены. А если кластер будет создан более чем с 5 нодами? Кворумы довольно просто вычисляются, нет никакого смысла их так хранить. (`from / 2 + 1`)

2020-11-21 17:51 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +                c.stream().min(Utility.valueResponseComparator()))
min находится без стримов c помощью Collections.min с меньшими накладными расходами

2020-11-21 22:32 UTC, s3ponia commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +                        .whenCompleteAsync((c, t) -> handlingUpsertResult(session, t))
Хорошо. Исправил

2020-11-21 22:33 UTC, s3ponia commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +            @NotNull final AsyncService service) throws IOException {
Ну это была претензия и на прошлом этапе) Но он проверился и исправлялся уже после этого и я подумал, что лучше оставить как есть

2020-11-21 22:35 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/AsyncServiceUtility.java
> +            @NotNull final AsyncService service) throws IOException {
Лучше исправления с прошлых этапов подтягивать

2020-11-21 22:36 UTC, s3ponia commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static final String PROXY_HEADER = "X-Proxy-From";
А это на что-то влияет? Просто неочень понятно почему именно запрещено

2020-11-21 22:39 UTC, s3ponia commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +            new Utility.ReplicationConfiguration(3, 5)
В задании просто не написано про то что может быть больше нод поэтому я просто захардкодил) Но сейчас исправлю

2020-11-21 22:40 UTC, s3ponia commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +                c.stream().min(Utility.valueResponseComparator()))
Ну не знаю насколько это критично когда у нас нод в любом случае неочень много

2020-11-21 22:43 UTC, lamtev commented on src/main/java/ru/mail/polis/s3ponia/Utility.java
> +    public static final String PROXY_HEADER = "X-Proxy-From";
Никто не говорит, что запрещено. Просто [стандарт](https://tools.ietf.org/html/rfc6648#section-3) не рекомендует так больше делать. Стандартам стоит следовать. Некоторые причины так же описаны в данном документе, если интересно

2020-11-22 12:16 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/AsyncService.java
> +            new Utility.ReplicationConfiguration(3, 5)
Не инженерный подход

2020-11-23 12:42 UTC, lamtev commented
@s3ponia Все исправлено, и можно смотреть? Просто ревью не было повторно запрошено

2020-11-23 16:36 UTC, s3ponia commented
> @s3ponia Все исправлено, и можно смотреть? Просто ревью не было повторно запрошено

Нужно еще нагрузочное тестирование провести еще раз. Поэтому не запросил повторный ревью

2020-11-29 06:52 UTC, lamtev commented
Принято

2020-11-29 06:52 UTC, closed without merging