Stage6
polis-mail-ru/2020-highload-dht pull request #129
Opened 2020-11-01 09:41 UTC by mariarheon

2020-11-05 12:40 UTC, incubos requested changes
Есть ряд критичных замечаний. Ждём исправлений и прохождения тестов.

2020-11-05 12:40 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/ReplicasResponseComposer.java
> +    public void addResponse(final Response response, final int ackCount) {
Вы здесь просто выбираете первый успешный ответ и не принимаете во внимание отметки времени, верно? Добавил тестов. Теперь сборка не проходит. Надо исправлять.

2020-11-08 22:29 UTC, incubos requested changes
Есть небольшие замечания и вопросы.

2020-11-08 22:29 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/Record.java
> +    private byte[] key;
Может, сделать все поля `final` и инициализировать через `private` конструктор? Получится классический потоко-безопасный immutable класс.

2020-11-08 22:29 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/Record.java
> +        if (RecordState.values()[response.get()] == RecordState.REMOVED) {
А вдруг `ArrayIndexOutOfBounds`?

2020-11-08 22:29 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/Record.java
> +        if (RecordState.values()[response.get()] == RecordState.REMOVED) {
Ещё из интересного: `Enum.values()` **каждый раз** аллоцирует новый массив.

2020-11-08 22:29 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/Record.java
> +        final int byteSize = 1;
`Byte.BYTES`?

2020-11-08 22:29 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/Record.java
> +        final int longSize = 8;
`Long.BYTES`?

2020-11-08 22:29 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/Record.java
> +    private ByteBuffer combineValue() {
`serialize()`?

2020-11-08 22:29 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/ReplicasResponseComposer.java
> +                    || (!responseRecord.wasNotFound()
Нужно ли это условие `wasNotFound()`?  Т.е. более свежие "могилы", накрывающие более старое значение, мы будем игнорировать?

2020-11-09 08:49 UTC, mariarheon commented on src/main/java/ru/mail/polis/service/mariarheon/ReplicasResponseComposer.java
> +                    || (!responseRecord.wasNotFound()
Нет, игнорирования более свежих "могил" не происходит. Мы игнорируем ответы от реплик, которые ни разу не сталкивались с указанным ключом. Если это первый ответ от некой реплики, то неважно, какой мы получили ответ, используем его в качестве стартового значения для this.record (даже если запись не была найдена). Условие (!responseRecord.wasNotFound()) будет проверяться только в том случае, если this.record != null. То есть только в том случае, когда хотя бы одна реплика выдала некий ответ. В этом случае, мы хотим сменить ответ только в случае, если данная реплика нашла значение по запрошенному ключу. Примечание: в качестве такого значения может быть информация о том, что запись с этим ключом была удалена. wasNotFound() - отвечает true, если записи на реплике не было, и false - если запись на реплике хранится, включая ситуацию, при которой хранится лишь метаинформация о том, что запись уже удалена.

2020-11-10 10:53 UTC, incubos commented
Принято.

2020-11-10 10:53 UTC, closed without merging