Stage6
polis-mail-ru/2020-highload-dht pull request #130
Opened 2020-11-02 18:41 UTC by zvladn7

2020-11-21 13:57 UTC, lamtev requested changes
# Реализация 

1. Оставил комментарии/вопросы об необходимости асинхронности в некоторых местах 
2. Видимо есть баг, из-за которого иногда на потоках селектора может выполняться больше работы, чем хотелось бы
3. Плюс можно поправить замечания, тянущиеся с прошлого этапа

# Профилирование

1. Части локов на BlockingQueue удастся избежать, если поправить замечания по реализации
2. Самое главное - нет в отчете сравнения задержек с предыдущим этапом

2020-11-21 13:57 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/ConflictResolver.java
> +                    results.add(v);
Получился такой дизайн кода, при котором довольно непросто понять, что на каком потоке должно выполняться. Я в этом месте поставил брейк поинт, и увидел, что это иногда выполняется на потоке селектора. Нужно поправить этот баг. Вот стэк:
<img width="630" alt="Screenshot 2020-11-21 at 16 43 35" src="https://user-images.githubusercontent.com/10428179/99878771-b4daaf80-2c18-11eb-8cb3-13947c11c675.png">

2020-11-22 10:15 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceHelper.java
> +                .thenApplyAsync(v -> new Response(v.iterator().next(), Response.EMPTY), es);
Нет, не может. Поскольку ситуация, когда `ack` равен 0 является исключительной, она тут же обрабатывается `AsyncService` и отдает ответ. Следовательно, можно ожидать, что здесь будет по крайней мере один элемент. А если не наберется нужное количество реплик, то данный код не выполнится, так как предыдущий `CompletionStage` не завершится нормально.

2020-11-22 10:15 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceHelper.java
> +                return localResponse.thenApplyAsync(ResponseValue::toProxyResponse, es);
Смысла сабмитить задачу асинхронно действительно нет. Теперь она синхронная.

2020-11-22 10:15 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ConflictResolver.java
> +        final AtomicInteger failures = new AtomicInteger(futures.size() - ack + 1);
поправил, да, не совсем понятно получилось)

2020-11-22 10:17 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ConflictResolver.java
> +                    results.add(v);
Тоже поправил. Проблема была в том, что вы как раз таки указали выше, разные задачи заканчивались на разных потоках), поэтому выполнение `whenComplete` также было на разных потоках. Теперь все ок, работает всегда на worker'ах.

2020-11-22 10:18 UTC, zvladn7 commented
Реализацию поправил, сейчас также поправлю отчёт

2020-11-22 13:28 UTC, zvladn7 commented
[обновил анализ нагрузочного тестирования](https://github.com/polis-mail-ru/2020-highload-dht/blob/16f36f2d4cf6e47e846d9aa47cb48dc4bd3fa02d/report/hw6.md)

2020-11-22 14:40 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        if (future.whenCompleteAsync((r, t) -> {
Тут для чего async ?

2020-11-22 14:40 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/ConflictResolver.java
> +            if (nextFuture.whenCompleteAsync((v, t) -> {
Тут тоже есть сомнения в необходимости async на es

2020-11-22 14:40 UTC, lamtev commented on report/hw6.md
> +2.74% занимает ForkJoinWorkerThread, который занимается постановкой на выполнение CompletableFuture
ForkJoinWorkerThread по идее быть не должно после того, как все асинхронные операции начали на собственном экзекуторе выполнять

2020-11-23 08:34 UTC, zvladn7 commented on report/hw6.md
> +2.74% занимает ForkJoinWorkerThread, который занимается постановкой на выполнение CompletableFuture
Не удается найти почему он может возникать. В стеке виден whenComplete в AsyncService, но, поставив брейкпоинт в дебаге, при успешном выполнении все выполняется на воркерах.
![image](https://user-images.githubusercontent.com/47724127/99941416-0d2bc180-2d7f-11eb-9306-1859bbd673ba.png)

А если нет значения и выбрасывается исключение, то мы как раз попадаем на ForkJoinWorkerThread. И стек очень похож, на то, что есть на флейм графе. Видимо, это именно тот случай.
![image](https://user-images.githubusercontent.com/47724127/99941758-9f33ca00-2d7f-11eb-8ff4-3bedd8452405.png)

2020-11-23 08:36 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        if (future.whenCompleteAsync((r, t) -> {
Здесь на самом деле необходимость в нем отпала после того, как я изначально обернул выполнение запроса в задачу, поставленную на ExecutorService. Забыл убрать после этого. Сейчас же убрал и выполнение внутри whenComplete осталось также на воркерах.

2020-11-25 19:35 UTC, lamtev approved these changes

2020-11-25 19:35 UTC, lamtev commented
Принято

2020-11-25 19:35 UTC, closed without merging