Stage 6
polis-mail-ru/2020-highload-dht pull request #131
Opened 2020-11-02 18:58 UTC by StasyanOi

2020-11-08 19:02 UTC, incubos requested changes
Имеется ряд вопросов и замечаний, в т.ч. по заметно переусложнённому дизайну. Ждём реакции и исправлений.

2020-11-08 19:02 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +                            .thenApplyAsync(Util::getOneNioResponse)
Зачем это преобразование? Почему сразу не работать с оригинальными ответами?

2020-11-09 13:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/FrameServer.java
> +            return httpClient.invoke(request);
Переделал, думал, что только отсылки репликам надо переводить на новую логику.

2020-11-10 10:57 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/FrameServer.java
> +            return httpClient.invoke(request);
Что ещё оставалось на `HttpClient`? Он фигурировал в профилях.

2020-11-10 11:01 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/FrameServer.java
> +            return httpClient.invoke(request);
Больше ничего - только эти 2 метода пользуются клиентом. Я пока не переделывал профили. Сейчас рефакторю код.
![image](https://user-images.githubusercontent.com/36096614/98665768-25eaaf00-235d-11eb-9905-30c27d797d97.png)

2020-11-10 11:08 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/FrameServer.java
> +            return httpClient.invoke(request);
@incubos оставалось только routeRequestToRemoteNode на старом HttpClient

2020-11-10 13:28 UTC, incubos requested changes
Не все замечания поправлены.

2020-11-10 13:28 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        final int hash = Math.abs(Arrays.hashCode(idArray));
`Math.abs()` может вернуть отрицательное число.

2020-11-10 13:28 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        noRepRequest.addHeader("Host: localhost:" + thisServerPort);
Зашивать `localhost` неправильно: вдруг кластер запустят в распределённом режиме.

2020-11-10 13:28 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +            if (size == 1) {
Почему не `from / 2 + 1`? Если в кластере будет больше 5 нод? Мы же пишем сервис общего назначения, а не компонент для прохождения тестов.

2020-11-10 13:28 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +public class CustomServer extends OverridedServer {
Честно говоря, `Overrided` тоже ни о чём не говорит.

2020-11-10 13:28 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +            final Pair<byte[], byte[]> bodyTimestamp = getTimestamp(bytes);
Может, лучше POJO типа `TimestampedBody` с двумя полями `body` и `timestamp`?

2020-11-10 13:28 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +        } catch (NoSuchElementException | IOException e) {
Возвращать `NOT_FOUND` при `IOException` неправильно.

2020-11-10 13:28 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +        tempNodeMapping.remove(node);
Можете всё-таки пояснить эту логику? Мы копируем все ноды, а потом удаляем локальную `node`?

2020-11-10 13:28 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +        final Map<Integer, String> tempNodeMapping = new TreeMap<>(nodeIndexToUrlMapping);
Вообще в процессе ревью этого PR вспоминается твит всемирноизвестного инженера: https://twitter.com/mjpt777/status/1324010382189563906 ;)

2020-11-10 13:58 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +        tempNodeMapping.remove(node);
Да, чтобы получить нелокальные, на которые можно реплики высылать

2020-11-10 14:00 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        final int hash = Math.abs(Arrays.hashCode(idArray));
На следующей строке подправляю при таком раскладе

2020-11-10 14:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                resps.forEach(pair -> map.put(pair.getValue0(), pair.getValue1()));
Переделал

2020-11-10 15:32 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +        final Map<Integer, String> tempNodeMapping = new TreeMap<>(nodeIndexToUrlMapping);
Я пытаюсь

2020-11-11 13:15 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/FrameServer.java
> +            return httpClient.invoke(request);
Все запросы должны идти через новый `HttpClient`. Или я что-то не так понял в коде?

2020-11-11 13:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +        tempNodeMapping.remove(node);
Дополнительное копирование это не очень эффективно. Представляете, сколько мы памяти выделяем по сравнению с размером обрабатываемого запроса от клиента?

2020-11-11 13:49 UTC, incubos requested changes
Всё ещё есть замечания (и не все старые исправлены). Будете исправлять или примем за меньшее число баллов и будем двигаться дальше?

2020-11-11 13:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> -    private Util() {
Почему он перестал быть singleton? У него же нет состояния.

2020-11-11 13:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> -    public static Response responseWithNoBody(final String requestType) {
Почему все методы перестали быть `static`?

2020-11-11 13:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +    public synchronized byte[] getTimestampInternal() {
Зачем здесь `synchronized`?

2020-11-11 13:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        final String nanos = String.valueOf(System.nanoTime());
Не очень эффективная сериализация. Можно выделить массив `byte[8]` и вынуть каждый байт из `long`.

2020-11-11 13:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        final String nanos = String.valueOf(System.nanoTime());
Время `System.nanoTime()` имеет смысл только в пределах одной JVM -- см. JavaDoc. А у нас распределённый кластер (хоть тесты и запускаются в рамках одной JVM). Лучше использовать `currentTimeMillis()`.

2020-11-11 13:49 UTC, incubos commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    private final Util util;
См. комментарии к классу `Util`. Непонятно, почему он перестал быть утильным и стал полем `DAOImpl`.

2020-11-11 13:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +public class Merger {
От него наследуются?

2020-11-11 13:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> -    public static Response mergeGetResponses(final List<Response> responses,
Почему методы стали нестатическими? Состояния у класса нет.

2020-11-12 08:09 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> -    public static Response mergeGetResponses(final List<Response> responses,
Только убрать по максимому статические классы.

2020-11-12 08:09 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +public class Merger {
Нет

2020-11-12 08:10 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        final String nanos = String.valueOf(System.nanoTime());
Переделал

2020-11-12 08:11 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +    public synchronized byte[] getTimestampInternal() {
уже убрано, старая реализация

2020-11-12 08:25 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    private final Util util;
Вернул его в Утильные классы. Рефакторил код просто

2020-11-12 08:25 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> -    public static Response responseWithNoBody(final String requestType) {
Уже все снова статик

2020-11-12 08:25 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> -    private Util() {
Уже вернул в предыдущее состояние

2020-11-12 08:26 UTC, StasyanOi commented on build.gradle.kts
> +    compile("org.javatuples:javatuples:1.2")
Убрал

2020-11-12 08:26 UTC, StasyanOi commented on reports/stage6/put.lua
> +    wrk.body = "123"
Добавил мутирующее тело

2020-11-12 08:27 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomExecutor.java
> +                new LinkedBlockingQueue<>(100));
Сделал класс на константы

2020-11-12 08:27 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +                final List<Pair<Long, Response>> resps = Stream.concat(emptyResponses.stream(), goodResponses.stream())
переделал

2020-11-12 08:27 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +        final List<Response> emptyResponses = responses.stream()
тоже переделал

2020-11-12 08:27 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Merger.java
> +        final List<Response> goodResponses = responses.stream()
переделал

2020-11-12 08:27 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/FrameServer.java
> +public class FrameServer extends PutDeleteGetMethodServer {
уже убрал

2020-11-12 08:28 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/FrameServer.java
> +public class FrameServer extends PutDeleteGetMethodServer {
убрал, уже другие классы

2020-11-12 08:28 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +    protected final List<String> replicationDefaults = Arrays.asList("1/1", "2/2", "2/3", "3/4", "3/5");
выпилил

2020-11-12 08:28 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +    protected Map<String, HttpClient> httpClientMap;
убрал уже

2020-11-12 08:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +    protected Logger logger = LoggerFactory.getLogger(CustomServer.class);
переделал

2020-11-12 08:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +        final Map<Integer, String> nodeMappingTemp = new TreeMap<>();
переделал

2020-11-12 08:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +        final Map<String, HttpClient> clients = new HashMap<>();
уже выпилелно

2020-11-12 08:30 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/ConstantsServer.java
> +            if (urls.get(i).contains(String.valueOf(super.port))) {
переделал

2020-11-12 08:30 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +public class CustomServer extends FrameServer {
Уже убрал эти классы

2020-11-12 08:30 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/DeleteGetMethodServer.java
> +            final Pair<Integer, Integer> ackFrom = getRF(request, nodeMapping);
Переделал

2020-11-12 08:30 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/DeleteGetMethodServer.java
> +        return Util.ackFromPair(request, replicationDefaults, nodeMapping);
Переделал

2020-11-12 08:31 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/FrameServer.java
> +            return httpClient.invoke(request);
@incubos, сейчас все запросы через новый клиент да.

2020-11-12 08:32 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +            tempNodeMapping.remove(node);
Чтобы получить все остальные ноды на которые можно отсылать реплики

2020-11-12 08:33 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +                .map(nodeHost -> new Pair<>(
уже убрано

2020-11-12 08:33 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/internal/GetMethodServer.java
> +                            .thenApplyAsync(Util::getOneNioResponse)
Чтобы можно было переиспользовать мердж ответов

2020-11-12 08:33 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        noRepRequest.addHeader("Host: localhost:" + thisServerPort);
переделал

2020-11-12 08:33 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +            if (size == 1) {
переделал

2020-11-12 08:34 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +public class CustomServer extends OverridedServer {
переделал

2020-11-12 08:34 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +            final Pair<byte[], byte[]> bodyTimestamp = getTimestamp(bytes);
Уже добавил такой класс.

2020-11-12 08:34 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +        } catch (NoSuchElementException | IOException e) {
Вынес в отдельный catch блок

2020-11-12 10:10 UTC, StasyanOi commented
@incubos, пофиксил по максимому все кроме создание timestamp, там какая-то сериализация непонятная если его пихать в хэдер. Я это доделаю на следующих этапах

2020-11-12 11:04 UTC, incubos commented
> @incubos, мне осталось доделать создание timestamp не ставьте оценку пока что плиз

ОК, ждём.

2020-11-12 11:05 UTC, incubos commented
Упс, прошу прощения, я вам случайно подмёрджил тесты 7 этапа. Удалите `SingleRangeTest.java` из этого PR?

2020-11-12 19:50 UTC, StasyanOi commented
@incubos, пофиксил timestamp - новые тесты билд валят (не совсем понял как их убрать у меня их нету ни локально, ни в репо). В принципе всё

2020-11-18 11:49 UTC, incubos commented
Принято.

2020-11-18 11:49 UTC, closed without merging