Hw6
polis-mail-ru/2020-highload-dht pull request #132
Opened 2020-11-02 23:36 UTC by re1nex

2020-11-03 08:34 UTC, re1nex commented
наконец поправил тесты, нагрузочное тестирование и рефакторинг в процессе

2020-11-04 06:07 UTC, re1nex commented
Сделал коммиты с пустой строкой, для того, чтобы перезапустить проверку , формальные правила дедлайна вроде не нарушаются, т.к. до дедлайна реализация проходила тесты и замечания были исправлены , но постараюсь больше так не затягивать

2020-11-05 18:19 UTC, incubos requested changes
Обновлённый набор тестов не проходит. Ждём исправлений.

2020-11-08 23:26 UTC, incubos requested changes
Есть ряд вопросов и замечаний, требующих исправления.

2020-11-08 23:26 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/ApiControllerImpl.java
> +    private final Map<String, HttpClient> nodeToClient;
`HttpClient` из `one-nio` на 6 этапе уже не должен упоминаться.

2020-11-08 23:26 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/ApiUtils.java
> +            @NotNull final HttpClient client,
Мы же переключились на `java.net.http.HttpClient`?

2020-11-08 23:26 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncApiControllerImpl.java
> +        this.client = java.net.http.HttpClient.newBuilder()
Почему fully qualified?

2020-11-08 23:26 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncApiControllerImpl.java
> +                break;
Лучше вернуть ошибку, а не проигнорировать непонятный HTTP-метод.

2020-11-08 23:26 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncApiControllerImpl.java
> +        if (topology.removeLocal(nodes)) {
Вообще модифицировать входящую коллекцию -- плохая практика, чреватая хитрыми багами.

2020-11-08 23:26 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/MergeUtils.java
> +                                            final boolean isPut) {
Может, вместо `boolean isPut` использовать `expectedStatus` (`CREATED`/`ACCEPTED`)? Для общности и лучшего понимания.

2020-11-08 23:26 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/ResponseBuilder.java
> +        response.addHeader(ApiUtils.GENERATION + ": " + generation);
В случае `onlyStatus` заголовок всегда равен `0`?

2020-11-09 07:21 UTC, re1nex commented on profile_info/report.md
> +Количество сэмплов селекторов one.nio уменьшилось до 8%, т.к. теперь еще добавились селекторы HttpClient (10%) . 12% ушло на ForkJoinWorkerThread, внутри которого выполнялся upsert в dao(4%). На пул
видимо так , поищу тогда в коде и перестреляю , спасибо

2020-11-09 07:27 UTC, re1nex commented on profile_info/report.md
> +Но на 99 % новая реализация в 10 раз обгоняет старую, возможно в этот момент очередь и переполнилась и старая реализация замедлилиась.
видимо невнимательно смотрел, переделаю

2020-11-09 07:31 UTC, re1nex commented on profile_info/report.md
> +Но на 99 % новая реализация в 10 раз обгоняет старую, возможно в этот момент очередь и переполнилась и старая реализация замедлилиась.
ну мы синхронно опрашиваем все ноды каждый раз в старой реализации , поэтому мне показалось, что задержка может быть связана с тем, что задачи будут накапливаться в пуле экзекьютеров

2020-11-09 07:35 UTC, re1nex commented on profile_info/report.md
> +По аллокациям на селекторы уходит приблизительно столько же, но еще 2% уходит на менеджер селекторов нового клиента, появились новый расходы на ForkJoinWorkerThread (14%), на ComplatableFuture(7%), н
да, я тут это и имел ввиду , что теперь появились аллокации  с ComplatableFuture и ForkJoinWorkerThread , добавлю тогда еще результаты visual vm

2020-11-09 07:37 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/DAOResultCode.java
> +    NOT_FOUND
ой,  делал для старых версий , но сейчас убрал их, уберу и enum

2020-11-09 07:37 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiControllerImpl.java
> +    private final Map<String, HttpClient> nodeToClient;
это для 5 этапа, я оставил предыдущую версию , чтобы с ней сравниваться

2020-11-09 07:38 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncApiControllerImpl.java
> +        this.client = java.net.http.HttpClient.newBuilder()
поправлю

2020-11-09 07:38 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncApiControllerImpl.java
> +                break;
добавлю

2020-11-09 07:39 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncApiControllerImpl.java
> +        if (topology.removeLocal(nodes)) {
хорошо, сделаю копию

2020-11-09 07:39 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/MergeUtils.java
> +                                            final boolean isPut) {
переделаю

2020-11-09 07:43 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ResponseBuilder.java
> +        response.addHeader(ApiUtils.GENERATION + ": " + generation);
да

2020-11-10 13:32 UTC, incubos requested changes
Ждём исправлений по результатам обсуждений.

2020-11-11 14:05 UTC, incubos requested changes
У нас явно просела производительность. На профилях присутствуют следы common `ForkJoinPool`, которого быть не должно. Есть ряд замечаний по коду.
Предлагаю принять этап за меньшее число баллов и двигаться дальше или будете разбираться и фиксить?

2020-11-11 14:05 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/ApiUtils.java
> +                return -1;
Может, кинуть исключение?

2020-11-11 14:11 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiUtils.java
> +        if (completableFuture == null) {
я просто не совсем понимаю как isCancelled может быть не блокирующим , сделал это, чтобы на проверку не ругалось

2020-11-11 14:15 UTC, re1nex commented
> У нас явно просела производительность. На профилях присутствуют следы common `ForkJoinPool`, которого быть не должно. Есть ряд замечаний по коду.
> Предлагаю принять этап за меньшее число баллов и двигаться дальше или будете разбираться и фиксить?

я везде заменил на async с указанием экзекьюторов , и внутри ForkJoinPool внутренних операций именно моих не увидел , почитал про фьючи , думал что норм , но если нет,то я бы все же поразбирался еще ,т.к. и баллов немного и так , да и в следующем этапе все равно понадобится

2020-11-11 14:17 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ApiUtils.java
> +                return -1;
заменю

2020-11-11 14:18 UTC, re1nex commented on profile_info/report.md
> +Requests/sec:    532.01
а это может быть связано с 64 потоками ? если да, то наверное стоит на меньшем числе смотреть

2020-11-11 17:20 UTC, re1nex commented on profile_info/report.md
> +  64 threads and 64 connections
нет , хотя это было странно

2020-11-12 11:03 UTC, incubos commented
> я везде заменил на async с указанием экзекьюторов , и внутри ForkJoinPool внутренних операций именно моих не увидел , почитал про фьючи , думал что это норм , но если нет,то я бы все же поразбирался еще ,т.к. и баллов немного и так , да и в следующем этапе все равно понадобится . по коду увидел только одно замечание сейчас

ОК, ждём.

2020-11-12 11:06 UTC, incubos commented
Упс, прошу прощения, я вам случайно подмёрджил тесты 7 этапа. Удалите `SingleRangeTest.java` из этого PR?

2020-11-12 17:40 UTC, re1nex commented
> Упс, прошу прощения, я вам случайно подмёрджил тесты 7 этапа. Удалите `SingleRangeTest.java` из этого PR?

хорошо

2020-11-13 07:42 UTC, re1nex commented
Решил проблему с производительностью , оказалось очередь забивалась быстро и бросалось reject exception , увеличил размер очереди , убрал лишние конвертации ) сделал так чтобы codeclimate не ругался на дублирование в этом случае ) в процессе изучения проблемы с форк джойн

2020-11-14 15:05 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/MergeUtils.java
>          final int statusCode = ApiUtils.getStatusCodeFromStatus(statusOk);
тут проверку не ставил , т.к. это старая версия сервиса и боялся , что codeclimate будет ругаться на дубликат, надеюсь это не критично, могу в принципе просто убрать из пр старую версию , если это нужно

2020-11-18 11:52 UTC, incubos commented
Принято.

2020-11-18 11:52 UTC, closed without merging