Task 6
polis-mail-ru/2020-highload-dht pull request #133
Opened 2020-11-03 00:02 UTC by PolinaShneider

2020-11-03 19:13 UTC, PolinaShneider commented
Пока без исправлений предыдущего этапа. Так как ревью было в понедельник утром, замечания по репликам поправить не успела — исправлю на днях.

2020-11-10 19:13 UTC, vaddya commented
Добьем сначала #117, чтобы не дублировать замечения?

2020-11-10 19:23 UTC, PolinaShneider commented
Да, хорошо. У меня там при последних исправлениях пара тестов падала. Сюда закинула "зеленую" реализацию, чтобы не проворонить дедлайн. Сначала поправлю там.

2020-11-12 00:04 UTC, PolinaShneider commented
Часть правок с прошлого этапа внесла. Хотела спросить, как быть с сериализацией Value. На прошлом этапе из body Response я убрала все лишнее, передавая timestamp через хэдер. В этом этапе у меня фигурирует HttpResponse (ответ от асинхронного клиента), которому свой заголовок так просто не добавить. Нормальна ли ввиду этого сериализация Value? Пока альтернатив не вижу.

2020-11-12 08:04 UTC, vaddya commented
> Часть правок с прошлого этапа внесла. Хотела спросить, как быть с сериализацией Value. На прошлом этапе из body Response я убрала все лишнее, передавая timestamp через хэдер. В этом этапе у меня фигурирует HttpResponse (ответ от асинхронного клиента), которому свой заголовок так просто не добавить. Нормальна ли ввиду этого сериализация Value? Пока альтернатив не вижу.

А зачем добавлять заголовок в `HttpResponse`? А в `HttpRequest` можно легко добавить через `HttpRequest.Builder#header()`.

2020-11-16 10:30 UTC, vaddya commented
Уже можно смотреть или еще домерживаете 5-ый этап?

2020-11-16 10:47 UTC, PolinaShneider commented
Еще в процессе. Небольшой рефакторинг случился. К завтрашнему дню точно будет готово

2020-11-16 20:51 UTC, PolinaShneider commented
@vaddya готово

2020-11-17 18:44 UTC, vaddya requested changes
Есть замечания по реализации и огромный вопрос по хендлерам.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceImpl.java
> +            final HttpClient client = HttpClient.newBuilder()
Есть ли смысл тогда заводить разные клиенты? Они же все одинаковые и работают на одном и том же экзекьюторе

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationHandler.java
> +            replicationFactor = replicas == null ? ReplicationFactor.getQuorum(topology.getSize()) :
На самом деле кворумный RF можно создать один раз и переиспользовать его во всех запросах, где не указан параметр `replicas`.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceUtils.java
> +    static Set<String> getNodeReplica(
Этот метод точно нуежн? Он так с виду больше параметров получает, чем инакпсулирует логики.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/handlers/GetBodyHandler.java
> +public final class GetBodyHandler implements HttpResponse.BodyHandler<Value> {
Можете объяснить, почему ваше решение вплоть до имен переменных совпадает с [соседним](https://github.com/polis-mail-ru/2020-highload-dht/pull/134/files#diff-39d075ef8dfa59a12a1a5033c85455e58eec3efe60141b3e50b11d069437ef70R11)? Относится и к другим `BodyHandler`-ам.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationHandler.java
> +        final String id = req.getParameter("id");
Вы же уже в `ReplicationHandler.handle` распарсили параметры?

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceUtils.java
> +    static long getTimestamp(final Response response) throws NumberFormatException {
Вроде не используется нигде.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +    private static ByteBuffer EMPTY_BUFFER = ByteBuffer.allocate(0);
`final`?

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +        return buffer == null;
Может это правильнее понимать по отрицательному таймстемпу? И избавиться от потенциального `null` поля.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Value.java
> +            return ReplicationServiceUtils.addTimestampHeader(response, value.getTimestamp());
Тоже есть сомнения, что это надо выносить в метод. Используется всего 2 раза, при этом внутри всего 1 строка. То есть строку вызова можно просто заменить на содержимое метода и станет только понятнее.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceUtils.java
> +final class ReplicationServiceUtils {
С точки зрения дизайна, кажется, что это лишний класс. `syncValues`, который скорее `mergeValues`, можно смело перенести в класс `Value`, а остальные просто не нужны.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Runner.java
> +interface Runner {
Какой-то франкенштейн из `Runnable`, `Supplier`, `Provider` и `Executable`, который еще и `IOException` бросает. Самым адекватным названием, кажется, будет `ResponseProvider.get` или `ResponseSupplier.get`, но можно еще подумать.

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationServiceImpl.java
> +        final boolean isForwardedRequest = req.getHeader(FORWARD_REQUEST_HEADER) != null;
Нужно ли эту проверку делать здесь, если результат все равно передается в `handle`? Может это и сделать там?

2020-11-17 18:44 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ReplicationHandler.java
> +                final Response result = future.get();
То есть мы будем всегда ждать ответы от всех нод? А если, например, `PUT` с `replicas=2/3`, мы разве не можем сформировать ответ, дождавшись двух самых быстрых ответов?

2020-11-17 18:51 UTC, PolinaShneider commented on src/main/java/ru/mail/polis/service/handlers/GetBodyHandler.java
> +public final class GetBodyHandler implements HttpResponse.BodyHandler<Value> {
Хэндлеры делала как в видео. Их логику сложно написать как-то иначе. Возможно, то решение тоже по видео сделано.

2020-11-17 19:02 UTC, PolinaShneider commented on src/main/java/ru/mail/polis/service/ReplicationHandler.java
> +        final String id = req.getParameter("id");
Это да. Думала, можно достать параметры из req на месте, чтобы передавать меньше аргументов. Хотя с другой стороны, парсинг — дополнительные вычислительные операции. Поправлю.

2020-11-17 19:03 UTC, vaddya commented on src/main/java/ru/mail/polis/service/handlers/GetBodyHandler.java
> +public final class GetBodyHandler implements HttpResponse.BodyHandler<Value> {
Ну да, ок, просмотрел, что на лекции это показывали.

2020-11-19 17:32 UTC, PolinaShneider commented
@vaddya замечания исправлены

2020-11-19 18:28 UTC, PolinaShneider commented
Ой, новые результаты профилирования не закинула. 5 мин.

2020-11-19 18:40 UTC, PolinaShneider commented
Все, профилирование исправило. Сервис стал работать значительно быстрее.

2020-11-21 10:45 UTC, vaddya approved these changes
Вроде все хорошо. Профилирование ОК. Отлично, что работать стало быстрее.

2020-11-21 10:45 UTC, closed without merging