Task 6
polis-mail-ru/2020-highload-dht pull request #134
Opened 2020-11-03 10:05 UTC by MrSandman5

2020-11-08 17:23 UTC, vaddya requested changes
Есть замечания по реализации.

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +    @SuppressWarnings("FutureReturnValueIgnored")
Давайте не будем использовать `@SuppressWarning`.

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +                .thenApplyAsync(r -> ResponseUtils.emptyResponse(Response.CREATED), executor);
Нужно ли второй раз указывать экзекьютор? Почему не подходит `thenApply`?

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +                result.add(CompletableFuture.supplyAsync(
Запросы к ДАО в методах`replicasX` полностью совпадают с `SimpleRequests`, может можно это зарефакторить?

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/clustering/ConsistentHashingTopology.java
> +        return topology;
Нужно сделать защитное копирование, так как вы наружу отдаете изменяемую коллекцию, от которой зависит корректное функционирование инстанса.

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/clustering/ConsistentHashingTopology.java
> +            throw new IllegalArgumentException("Number of nodes is bigger than from!");
Исключение бросаете, но нигде его не ловите.

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/replication/ReplicasFactor.java
> +        return new ReplicasFactor(Integer.parseInt(params.get(0)), Integer.parseInt(params.get(1)));
Тут может вылететь `NumberFormatException`.

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/utils/FuturesUtils.java
> +    @SuppressWarnings("FutureReturnValueIgnored")
Давайте стараться не использовать `SuppressWarnings`.

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/replication/Entry.java
> +        return entries.stream()
Можете словами описать по какому критерию выбирается результат?

2020-11-08 17:23 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/handlers/GetBodyHandler.java
> +                final String ofTimestampValue = okTimestamp.orElse(null);
Если знаем, что значение есть, можно вызывать `get`.

2020-11-09 09:06 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/replication/Entry.java
> +        return entries.stream()
Я имел ввиду комментом отписать.

2020-11-09 09:31 UTC, vaddya requested changes
Нужно доработать обработку ошибок.

2020-11-09 09:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +            return new HashSet<>();
Ну вернем пустой список, а клиент то что получит? Надо явно проверить допустимость запрашиваемой топологии и если что вернуть 400.

2020-11-09 09:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/handlers/GetBodyHandler.java
> +                final String ofTimestampValue = okTimestamp.orElse(null);
Проверку на присутствие хедера надо вернуть. Я имел ввиду, что после проверки можно вызывать `okTimestamp.get()`, а не `okTimestamp.orElse(null)`.

2020-11-09 09:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/handlers/GetBodyHandler.java
> +                final String notFoundTimestampValue = notFoundTimestamp.orElse(null);
Тут тоже можно просто `.get()`.

2020-11-09 09:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/replication/ReplicasFactor.java
> +        final int fromParam = Integer.parseInt(params.get(1));
`IndexOutOfBoundException`?

2020-11-09 09:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/replication/ReplicasFactor.java
> +    public static ReplicasFactor parser(@NotNull final String replicas) throws NumberFormatException {
А снаружи никто не ловит `NumberFormatException`.

2020-11-09 09:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/clustering/ConsistentHashingTopology.java
> +            throw new IllegalArgumentException("Number of nodes is bigger than from!");
И сообщение неверное.

2020-11-09 09:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +                                : Objects.requireNonNull(replicasPut(id, request.getBody(), replicasFactor)));
Может `@NotNull` пометить просто? Вроде там всегда не налл.

2020-11-09 09:31 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +        return FuturesUtils.atLeastAsync(result, replicasFactor.getAck(), executor)
А что будет, если не соберется достаточно успешных ответов?

2020-11-09 14:17 UTC, MrSandman5 commented on src/main/java/ru/mail/polis/service/mrsandman5/handlers/GetBodyHandler.java
> +                final String notFoundTimestampValue = notFoundTimestamp.orElse(null);
Codeclimate говорит, что нельзя
![image](https://user-images.githubusercontent.com/17435000/98552370-6db2fd00-22af-11eb-92c4-e69b4d92f968.png)
И принимает на веру только такой вариант

2020-11-09 14:25 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/handlers/GetBodyHandler.java
> +                final String notFoundTimestampValue = notFoundTimestamp.orElse(null);
Можно попробовать заиспользовать `responseInfo.headers().firstValueAsLong()`, может не будет ругаться.

2020-11-09 15:25 UTC, MrSandman5 commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +        return FuturesUtils.atLeastAsync(result, replicasFactor.getAck(), executor)
Должно выводится 504, но проблема с get
Если в этом случае у нас пустое Value, тогда когда различить, когда в этом случае 404, а когда 504?

2020-11-09 15:43 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +        return FuturesUtils.atLeastAsync(result, replicasFactor.getAck(), executor)
Не очень понял в чем проблема. У нас есть нода координатор, которая получает запрос от клиента и собирает ответы от других нод.

2020-11-09 16:51 UTC, MrSandman5 commented on src/main/java/ru/mail/polis/service/mrsandman5/ServiceImpl.java
> +        return FuturesUtils.atLeastAsync(result, replicasFactor.getAck(), executor)
Проблема в том, что при получении исключения из Future я всегда получаю только 404, так как реакция на absent()-значения всегда NOT_FOUND.
![image](https://user-images.githubusercontent.com/17435000/98570850-eb353800-22c4-11eb-98ee-0d417079d3a4.png)

2020-11-10 19:07 UTC, vaddya requested changes
Финальное

2020-11-10 19:07 UTC, vaddya commented on highload-analysis.md
> +Возвращение к использованию отдельного *ExecutorService* вместо встроенного в onenio улучшило нагрузочные характеристики сервиса. Теперь сервис может обрабатывать большее количество любых запросов за
> может обрабатывать большее количество

А в цифрах это сколько? Сколько было/стало?

2020-11-10 21:42 UTC, vaddya approved these changes
Остались еще места, где не хватает валидации входных данных.

Профилирование ОК. Принято с небольшими замечаниями.

2020-11-10 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mrsandman5/clustering/ConsistentHashingTopology.java
> +        while (result.size() < replicasFactor.getFrom()) {
Все равно нет проверки, что `topology.size >= rf.from`. Если такое случится, то вы попадете в вечный цикл, потому что в результирующем сете никогда не будет запрашиваемое число нод (их просто нет столько).

2020-11-10 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/utils/FuturesUtils.java
> +    public static <T> CompletableFuture<Collection<T>> atLeastAsync(
Если представить, что `futures.size < successes`, то фьюча, которую вы здесь вернете, никогда ни выполнится, ни зафейлится.

2020-11-10 21:42 UTC, closed without merging