Stage 6
polis-mail-ru/2020-highload-dht pull request #135
Opened 2020-11-03 11:37 UTC by makaryb

Добрый день!

Отправляю решение к этапу 6.

## 1. Нагрузка

### 1.1 PUT:

`wrk2 -t64 -c64 -d2m -R* -s put.lua --latency http://127.0.0.1:8080`

В сравнении с версией предыдущего этапа (синий):

![output-put-all](https://user-images.githubusercontent.com/36387962/97976370-a9475600-1ddb-11eb-9c09-da9de683d870.png)

Видно, что в данном случае реализация выдерживает задаваемую нагрузку в 10k rate и по сравнению с версией предыдущего этапа - держит те же персентили.

### 1.2 GET:

`wrk2 -t64 -c64 -d2m -R* -s get.lua --latency http://127.0.0.1:8080`

В сравнении с версией предыдущего этапа (синий):

_Нагрузка в 3k rate_:

![output-get3k-all](https://user-images.githubusercontent.com/36387962/97979125-b23a2680-1ddf-11eb-97dc-3fde9777cc4b.png)

_Нагрузка в 10k rate_:

![output-get10k-all](https://user-images.githubusercontent.com/36387962/97979139-b5cdad80-1ddf-11eb-865d-4e936228681b.png)

Видно, что в случае 3k rate - показатели стали существенно лучше, хотя время ответа все еще высокое. В случае 10k rate - показатели почти не изменились, но стали лучше. По наблюдаемым данным можно сделать вывод, что есть прирост пропускной способности.

## 2. Профилирование

### 2.1 PUT:

`sudo ./profiler.sh -d 30 -f /tmp/put-cpu.svg <PID>`

_CPU_:

![put-cpu](https://user-images.githubusercontent.com/36387962/97976301-8a48c400-1ddb-11eb-9343-c7610f7c9ce7.png)

Можно видеть, что Worker'ы заняли большую часть времени работы: _~60%_ в целом: CompletableFuture и работа с сетью, а также обработка задач, которые были переданы во Future (upserting, doUpsert).

_alloc_:

![put-alloc](https://user-images.githubusercontent.com/36387962/97976306-8d43b480-1ddb-11eb-8ffd-6da7cffce101.png)

Можно видеть выделение памяти для работы с сетью, CompletableFuture.

_lock_:

![put-lock](https://user-images.githubusercontent.com/36387962/97976318-916fd200-1ddb-11eb-8912-b2e46dab3f0a.png)

Видно, что блокировались при обработке запросов и ответов с добавленным на данном этапе HttpClient. Также блокировались при работе с взаиможействием между потоками: CompletableFuture.

### 2.2 GET:

`sudo ./profiler.sh -d 30 -f /tmp/get-cpu.svg <PID>`

_CPU_:

![get-cpu](https://user-images.githubusercontent.com/36387962/97976342-9896e000-1ddb-11eb-83ce-93ae4c58e19d.png)

Видно, что время также заняли работа с сетью и CompletableFuture. Большую часть времени вновь заняло SortedStringTable.iterator.

_alloc_:

![get-alloc](https://user-images.githubusercontent.com/36387962/97976351-9d5b9400-1ddb-11eb-84a2-77d47b282e0c.png)

Можно видеть, что больше всего памяти аллоцировалось при работе с сетью и CompletableFuture.

_lock (PUT+GET)_:

![get-lock](https://user-images.githubusercontent.com/36387962/97976359-a2b8de80-1ddb-11eb-8814-e58c5542b772.png)

Видно, что блокировались при обработке запросов и ответов с добавленным на данном этапе HttpClient. Блокировались при взаимодействии между потоками: CompletableFuture

2020-11-21 14:31 UTC, lamtev requested changes
# Реализация

Оставил замечания по асинхронности и по ForkJoinPool

# Профилирование

В целом все ОК. Отлично, что по сравнению с предыдущим этапом задержка уменьшилась

Ну и на флейм-графах виден ForkJoinPool, что должно было навести на мысли)

2020-11-21 14:31 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/NewTopology.java
> +                                    - Math.pow(2, HASH_BITS - 1)
Степени двойки лучше получать через сдвиги, чем через арифметику над числами с плавающей точкой

2020-11-21 14:31 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/ReplicaWorker.java
> +        CompletableFuture.runAsync(() -> {
В основном все методы, содержащие суффикс Async, если не передать в них ExecutorService, выполняют работу асинхронно на глобальном ForkJoinPool.commonPool. Этот ForkJoinPool может использоваться стандартной библиотекой, например, Collection.parallelStream(). Поэтому лучше выполнять асинхронную работу в CompletableFuture на своем экзекуторе

2020-11-21 14:31 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/ReplicaWorker.java
> +        }).thenComposeAsync(handled -> getResponses(replicas, mir, topology, javaNetHttpClient)
Даже если CompletableFuture (CF) с runAsyncIfReplicasContainNode выполнялась на нашем экзекуторе, то thenComposeAsync выполнится на ForkJoinPool.commonPool. Если делаешь что-то асинхронно, то стоит не забывать передавать экзекутор.

Ну и вообще стоит задуматься о том, где эта асинхронность необходима. Выполнение чего-то async на CF будет сабмитить новую операцию на экзекутор. Что, например, будет приводить к локам на BlockingQueue.

Если нет необходимости в том, чтобы заново сабмитить на экзекутор операцию, то лучше этого и не делать, а продолжать синхронно на том же потоке из этого же экзекутора

Это относится по сути ко всему данному классу

2020-11-21 14:31 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/FuturesWorker.java
> +            } else if (!result.isDone() && value != null) {
с учетом проверки на `result.isDone()` исключается возможность получения более чем ack ответов.

На лекции показывался подход, при котором при достижении ack ответов выполнялся `result.complete(responses)`, но при этом в `responses` еще могли попасть ответы хотя бы от части оставшихся нод. По идее преимущество такого подхода в том, что в дополнительных ответах сверх ack может быть более свежее значение, например. В принципе, оставшиеся фючи же не отменяются, и уже отправленные другим нодам запросы тоже не отменяются. Почему бы и не воспользоваться данными, полученными от них, если они тоже успели уложиться в таймаут. Это не обязательно переделывать, просто для справки)

2020-11-26 00:29 UTC, makaryb commented on src/main/java/ru/mail/polis/service/boriskin/ReplicaWorker.java
> +        }).thenComposeAsync(handled -> getResponses(replicas, mir, topology, javaNetHttpClient)
Если во все методы, содержащие суффикс Async, передать текущий Executor Service и убрать здесь асинхронность и продолжать синхронно на том же потоке из этого же экзекутора, то следующая картина (оранжевый) в сравнении с предыдущей реализацией этого этапа (синий), для _GET_:

![output-get-all](https://user-images.githubusercontent.com/36387962/100293926-56099300-2f96-11eb-90a6-c61e2141989f.png)

Это лучший и наиболее стабильный результат, которого удалось добиться за несколько прогонов. ~ На 80-х % всегда взлетает.

В случае с _PUT_ все стабильно хорошо:

![output-put-all](https://user-images.githubusercontent.com/36387962/100294031-a3860000-2f96-11eb-8a05-c9ba20fc9af0.png)

[Здесь профили](https://github.com/makaryb/2020-highload-dht/tree/feature/task6/profiling_results_stage6/new/final): sendResponseIfExpectedAcksReached все еще на ForkJoinPool.

В случае, если оставить здесь Async и определить на текущий Executor, то с _GET_ картина печальная по сравнению с реализацией до исправления:

![output-get-all-async](https://user-images.githubusercontent.com/36387962/100294250-56eef480-2f97-11eb-82f9-df0d37ef3a4a.png)

На [флейм-графах](https://github.com/makaryb/2020-highload-dht/tree/feature/task6/profiling_results_stage6/new/with_async_on_cur_executor) ForkJoinPool нет.

2020-11-26 00:32 UTC, makaryb commented on src/main/java/ru/mail/polis/service/boriskin/FuturesWorker.java
> +            } else if (!result.isDone() && value != null) {
Спасибо

2020-11-29 08:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/ReplicaWorker.java
> +        }).thenComposeAsync(handled -> getResponses(replicas, mir, topology, javaNetHttpClient)
Грустно, что так вышло. Много факторов на это могло повлиять:
1) возможно баг в реализации
2) железо
3) из того, что заметил: избыточная асинхронность еще осталась: сначала задачи напрямую в executor добавляются, а потом еще через механизм CompletableFuture асинхронно
4) ну и, конечно, можно поизучать профили, найти, где узкое место

При желании можно найти проблему и довести до состояния, при котором не будет таких резких взлётов в районе 80 перцентиля

2020-11-29 08:39 UTC, lamtev commented
Принято

2020-11-29 08:39 UTC, closed without merging