Stage #6
polis-mail-ru/2020-highload-dht pull request #136
Opened 2020-11-03 11:40 UTC by ScriptoMax

Сравнение и анализ результатов смежных этапов приведены в [отчёте](https://github.com/ScriptoMax/2020-highload-dht/blob/stage_6/resources/report.md)

2020-11-08 20:19 UTC, incubos requested changes
Есть ряд вопросов и критичных замечаний, требующих исправлений, в т.ч. по дизайну решения и неоптимальному взаимодействию с репликами.
Асинхронная реализация не должна стать **настолько** медленнее (даже на слабом железе). Нужно разбираться -- результаты профилирования указывают на явную проблему с постоянным созданием потоков в процессе обработки запросов.

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationFactor.java
> +            session.sendError(Response.BAD_REQUEST, REPLIFACTOR_ERROR_LOG);
Как снаружи узнают, что мы уже отправили ошибку и запрос обрабатывать не нужно? Зачем передавать `session` сюда и смешивать парсинг `ReplicationFactor` и обработку ошибок?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +    private final Map<String, HttpClient> nodesToClients;
Как мы выяснили выше, пул `HttpClient`ов уже не нужен.

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        if (futures.isEmpty()) {
Что это за случай такой?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var all = CompletableFuture.allOf(futures.toArray(new CompletableFuture<?>[0]));
Здесь мы заблокируемся, пока **каждая** из `futures` не вычислится -- не самый оптимальный подход.

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                    session.sendResponse(futUtils.execGetWithFutures(values, asks, futures, nodes, ack));
Зачем повторять то, что было в `thenAccept()`?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                    session.sendError(Response.GATEWAY_TIMEOUT, FutureUtils.GET_COMPLETION_ERROR_LOG);
Что это за случай? Нужен ли он?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                    session.sendError(Response.GATEWAY_TIMEOUT, FutureUtils.GET_COMPLETION_ERROR_LOG);
Всё должно быть единообразно для любого положительного числа реплик.

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        if (futures.isEmpty()) {
Как может быть `isEmpty()`?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var all = CompletableFuture.allOf(futures.toArray(new CompletableFuture<?>[0]));
Снова ждём все ответы?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                session.sendResponse(futUtils.execUpsertWithFutures(quant, count, futures));
Зачем это?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        if (futures.isEmpty()) {
См. комменты выше.

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                session.sendResponse(futUtils.execDeleteWithFutures(quant, count, futures));
Всё ещё непонятно, зачем это.

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        final String id = req.getParameter("id=");
Если `null`?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        final String id = req.getParameter("id=");
Если проверили выше по стеку, может, передать его в качестве параметра?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +            };
Скобка уехала на другую строку.

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        futUtils.setForwardedRequest(isForwardedRequest);
Может обойтись без setterов? Например, разбить класс на forwarded и local реализации?

2020-11-08 20:19 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        futUtils.setForwardedRequest(isForwardedRequest);
Кажется, что будет выглядеть проще.

2020-11-10 14:06 UTC, incubos requested changes
Всё ещё есть ряд замечаний. Осталась проблема производительности, связанная с ожиданием результатов от **всех** реплик.

2020-11-10 14:06 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var allFutures = CompletableFuture.anyOf(futures.toArray(new CompletableFuture<?>[0]));
Почему `anyOf()`?

2020-11-10 14:06 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var allFutures = CompletableFuture.anyOf(futures.toArray(new CompletableFuture<?>[0]));
С `allOf()` ещё было понятно, но почему `anyOf()`?

2020-11-10 14:06 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var allFutures = CompletableFuture.allOf(futures.toArray(new CompletableFuture<?>[0]));
С `allOf()` ещё было понятно, но почему `anyOf()`?

2020-11-11 05:27 UTC, ScriptoMax commented on README.md
> -# 2020-highload-dht
не совсем понимаю, о какой целевой версии идёт речь. Требуется перенести полное содержимое из readme upstream-репозитория? Возможно, этот текст оправданно и вовсе удалить - с глаз долой, с гитхаба вон.

2020-11-11 05:35 UTC, ScriptoMax commented on resources/report.md
> +На очередном этапе курсового проекта конфигурация серверного кластера, реализующая базовый контроль репликаций, подверглась расширению, нацеленному на поддержку асинхронного Java-клиента (экземпляр <
за трое суток латаний и фиксинга второй показатель выдал нулевую динамику. Да, деградация впечатляет так же, как и сложность всей казуистики с futures

2020-11-11 05:35 UTC, ScriptoMax commented on resources/report.md
> +./profiler.sh -d 60 -e cpu -f /path/to/output/folder/flame_output_cpu.svg --title "Sample image title" <server_process_pid>
позволяет воспроизвести полную структуру команды

2020-11-11 05:36 UTC, ScriptoMax commented on resources/report.md
> +./profiler.sh -d 60 -e alloc -f /path/to/output/folder/flame_output_alloc.svg --title "Sample image title" <server_process_pid>
позволяет воспроизвести полную структуру команды

2020-11-11 05:36 UTC, ScriptoMax commented on resources/report.md
> +./profiler.sh -d 60 -e lock -f /path/to/output/folder/flame_output_lock.svg --title "Sample image title" <server_pid>
позволяет воспроизвести полную структуру команды

2020-11-11 05:37 UTC, ScriptoMax commented on resources/report.md
> +Выводы нагрузочного тестирования в режиме симуляции PUT-запросов демонстрируют многократное ухудшение быстродействия на уровне узла кластера с асинхронным клиентом. Увеличение средней задержки более
Спасибо, последую Вашему указанию при подготовке следующего отчёта

2020-11-11 05:44 UTC, ScriptoMax commented on resources/report.md
> +В реализации кластера с асинхронным клиентом структура задач процессора, выполняемых на уровне потоков, расширяется за счёт обработчиков сценариев с отложенными проверкой и возвратом результатов. Про
и с удалением проблемного метода релевантные метрики не выглядят лучше. Кажется, корень бед кроется в недостатке асинхронного выполнения ```sendResponse``` для передачи результата из методов класса ```ReplicationLSM```. Порождаются ли в этих случаях новые потоки, так пока и не понял (да и нет уверенности, что  эта догадка отражает реальность)

2020-11-11 05:55 UTC, ScriptoMax commented on resources/report.md
> +Используя приведённый профиль, ключевыми факторами, определяющими структурные особенности аллокаций в варианте с асинхронным клиентом, следует назвать вызовы основных и вспомогательных методов работы
По существу, я бы непременно рассмотрел все детали аллокаций и блокировок, будь на соответствующих графах нечто напоминающее наименования методов, а не только названия пакетов ```util``` и ```concurrent```. Мне то ли неведомо, как эти изображения подвергаются расширению, то ли другой визуализации в данном случае (именно в текущем случае отображения выводов сэмплирования) получить попросту не удастся

2020-11-11 05:59 UTC, ScriptoMax commented on resources/report.md
> +Профиль событий параллелизма показывает, что контроль взаимоисключений в реализации с асинхронным клиентом осуществляется вне контекста операций, связанных с исполнением основного кода на Java, т.е.
Вероятно, некоторый эффект ускорения вычислений может быть достигнут за счёт использования concurrency-коллекций, с которыми я не особо дружу, но на перспективность дружбы с которыми Вы указали в одной из следующих реплик.

2020-11-11 06:00 UTC, ScriptoMax commented on resources/report.md
> +Профиль событий параллелизма показывает, что контроль взаимоисключений в реализации с асинхронным клиентом осуществляется вне контекста операций, связанных с исполнением основного кода на Java, т.е.
Вероятно, некоторый эффект ускорения вычислений может быть достигнут за счёт использования concurrency-коллекций, с которыми я не особо дружу, но на перспективность дружбы с которыми Вы указали в одной из следующих реплик.

2020-11-11 06:00 UTC, ScriptoMax commented on resources/report.md
> +Сравнение конфигураций в режиме чтения воспроизводит результаты, полученные в ходе заполнения БД записями. Повышение средней задержки по итогам настройки асинхронного клиента достигло 60-кратной разн
Спасибо, последую Вашему указанию при подготовке следующего отчёта

2020-11-11 06:01 UTC, ScriptoMax commented on resources/report.md
> +Профили, сформированные в режиме чтения, подтверждают влияние методов, поддерживающих операции с futures на базе <em>Java Concurrency</em>. В соответствии с релевантной логикой, окончание цепочки выз
привёл комментарий к идентичному замечанию в одной из предыдущих реплик

2020-11-11 06:06 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncConnectUtils.java
> +public class AsyncConnectUtils implements HttpResponse<byte[]> {
сугубо индивидуальный выбор с учётом а) лучшего понимания операций над response в данной реализации и б) наихудшего понимания тех же операций в нынешнем мейнстриме

2020-11-11 06:07 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +     * evaluates request proxy status in boolean terms.
устранено корректировкой указанной строки

2020-11-11 06:08 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +    public void setForwardedRequest(final boolean isForwardedRequest) {
устранено полным удалением метода

2020-11-11 06:08 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +                .timeout(Duration.ofSeconds(ServiceFactory.CONNECTION_TIMEOUT))
устранено

2020-11-11 06:08 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +                if (future.get().body().length == 0) {
101-ая удалена

2020-11-11 06:11 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +        quant.set(incrementFutureCount(quant, 201, futures));
устранено с модификацией тела метода

2020-11-11 06:11 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +        if (quant.get() >= futures.size() || quant.get() >= count) {
устранил, свёл к равенству

2020-11-11 06:11 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +        if (quant.get() >= futures.size() || quant.get() >= count) {
устранил, свёл к равенству

2020-11-11 06:11 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +        if (quant.get() >= futures.size() || quant.get() >= count) {
устранил, свёл к равенству

2020-11-11 06:12 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +                if (future.get().statusCode() == returnCode) {
168-170 удалены

2020-11-11 06:12 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +        return CompletableFuture.supplyAsync(() -> {
устранено полным удалением метода

2020-11-11 06:12 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/FutureUtils.java
> +            AsyncConnectUtils response;
именно так

2020-11-11 06:13 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +            final HttpClient client = HttpClient.newBuilder()
устранено, операции проводятся с единичным объектом

2020-11-11 06:25 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +        boolean isForwardedRequest = false;
устранено в соответствии с указанием

2020-11-11 06:26 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +        if (isForwardedRequest || topology.getNodes().size() > 1) {
исключил первое условие, при исключении второго массово валятся тесты

2020-11-11 06:27 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +            final ByteBuffer key = ByteBuffer.wrap(id.getBytes(StandardCharsets.UTF_8));
только для прохождения тестов  в SingleNodeTest

2020-11-11 06:28 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationFactor.java
> +            LOGGER.error("Either one of factors is missing or both don't exist");
устранено, причина события приводится в качестве аргумента конструктора исключения

2020-11-11 06:28 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationFactor.java
> +            final ReplicationFactor repliFactor,
устранено в соответствии с указанием

2020-11-11 06:29 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationFactor.java
> +            session.sendError(Response.BAD_REQUEST, REPLIFACTOR_ERROR_LOG);
попробовал ловить за пределами данного метода - массово повалились тесты (видимо, это костыль)

2020-11-11 06:30 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +    private final Map<String, HttpClient> nodesToClients;
устранено, операции проводятся с единичным объектом

2020-11-11 06:31 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        if (futures.isEmpty()) {
нерационально перестраховался, проверку исключил

2020-11-11 06:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var all = CompletableFuture.allOf(futures.toArray(new CompletableFuture<?>[0]));
полностью удалил Completable-элементы из фрагмента, сохранил вызовы ```sendResponse```. Динамика быстродействия - ноль

2020-11-11 06:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                    session.sendResponse(futUtils.execGetWithFutures(values, asks, futures, nodes, ack));
костыль удалён

2020-11-11 06:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                    session.sendError(Response.GATEWAY_TIMEOUT, FutureUtils.GET_COMPLETION_ERROR_LOG);
устранено, проверка исключена

2020-11-11 06:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        if (futures.isEmpty()) {
нерационально перестраховался, проверку исключил

2020-11-11 06:35 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var all = CompletableFuture.allOf(futures.toArray(new CompletableFuture<?>[0]));
полностью удалил Completable-элементы из фрагмента, сохранил вызовы ```sendResponse```. Динамика быстродействия - ноль

2020-11-11 06:35 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                session.sendResponse(futUtils.execUpsertWithFutures(quant, count, futures));
костыль удалён

2020-11-11 06:36 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        if (futures.isEmpty()) {
нерационально перестраховался, проверку исключил

2020-11-11 06:36 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +                session.sendResponse(futUtils.execDeleteWithFutures(quant, count, futures));
костыль удалён

2020-11-11 06:36 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        final String id = req.getParameter("id=");
исправлено согласно указанию

2020-11-11 06:36 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +            };
спасибо, поправил

2020-11-11 06:37 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        futUtils.setForwardedRequest(isForwardedRequest);
исправил манипулированием аргументами, сеттер удалён

2020-11-11 06:39 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +    public static final int TIMEOUT = 1;
исправлено согласно указанию

2020-11-11 06:40 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +            nodesToClients.put(node, client);
устранено, операции проводятся с единичным объектом

2020-11-11 11:08 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +            final ByteBuffer key = ByteBuffer.wrap(id.getBytes(StandardCharsets.UTF_8));
При грубом удалении самой проверки (с сохранением кода в ветке ```else```) валится тест ```RespectFileFolder```, в случае добавления вызова only-метода в multiple проходится без ошибок. Определения методов, связанных с уже несуществующей веткой, удалил, а прежние multiples переименовал с учётом текущей роли

2020-11-11 11:30 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var allFutures = CompletableFuture.anyOf(futures.toArray(new CompletableFuture<?>[0]));
один из череды экспериментов с Completable-методами, не более

2020-11-11 11:30 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var allFutures = CompletableFuture.anyOf(futures.toArray(new CompletableFuture<?>[0]));
один из череды экспериментов с Completable-методами, не более

2020-11-11 11:31 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ReplicationLsm.java
> +        var allFutures = CompletableFuture.allOf(futures.toArray(new CompletableFuture<?>[0]));
один из череды экспериментов с Completable-методами, не более

2020-11-11 11:35 UTC, ScriptoMax commented
попытаюсь изобрести рецепт перформанс-улучшений в течение среды, от более поздних взрывов кода прорывов ждать не приходится

2020-11-11 12:55 UTC, ScriptoMax commented
Как ни пытаюсь разглядеть причины проблемы с избыточностью ответов (т.е. с получением ответов со всех узлов), всё время прихожу к выводу, что методы класса ```FutureUtils``` позволяют прервать обработку futures сразу по достижении ```ack``` (с проверкой условия через ```countSuccesses```). И то ли какие-то детали полностью упущены, то ли дело в том, как вызываются ```sendResponse``` в ```ResplicationLSM```, а не в подсчёте ответов.

2020-11-12 09:52 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +            final ByteBuffer key = ByteBuffer.wrap(id.getBytes(StandardCharsets.UTF_8));
Это же ваш код. Код тестов у вас тоже есть. Я имел в виду оставить только `invokeHandlerByMethod(id, req, session);` и убрать `if` и `else`-ветку.
В теории всё (проксирование, сбор ответов, разрешение конфликтов и т.д.) должно работать одинаково для **любого** размера кластера, включая, 1, а здесь частный случай для кластера размером 1 выделен зачем-то отдельно. Если без частного случая тесты не проходят, значит, есть какой-то баг.

2020-11-12 09:59 UTC, incubos commented
Принято с замечаниями. Если тесты не сможете починить, возьмите в качестве основы для следующего этапа (range-запросы) ваше синхронное решение (на базе `HttpClient` из `one-nio`).

2020-11-12 09:59 UTC, closed without merging