Stage6
polis-mail-ru/2020-highload-dht pull request #137
Opened 2020-11-03 12:17 UTC by gogun

2020-11-10 20:12 UTC, vaddya commented
Сначала закроем #127.

2020-11-13 13:02 UTC, vaddya commented
Надо примержить 5-ый этап сюда, чтобы замечания не дублировать.

2020-11-13 19:48 UTC, gogun commented
Подмержил 5й этап

2020-11-17 11:38 UTC, vaddya requested changes
Предлагаю немного изменить реализацию.

2020-11-17 11:38 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/GetBodyHandler.java
> +final class GetBodyHandler implements HttpResponse.BodyHandler<Response> {
Кажется, что правильным здесь было бы абстрагироваться от `one.nio.http.Response`, создав свой дата класс, который будет держать внутри себя информацию о байтовом значении, таймстемпе и статусе (ключ есть, ключ удален -- могилка, ключа нет). Потому что сейчас мы вроде отказались от `one-nio` клиента, но при этом вся ваша логика завязана на нем: вы подперли костылем так, будто асинхронный клиент возвращает вам `one-nio` ответ. Лучше будет все же использовать свой класс.

2020-11-17 11:38 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ResponseMerger.java
> +public class ResponseMerger {
И тогда будет не `ResponseMerger`, а `EntryMerger`, или как-то так.

2020-11-17 11:38 UTC, vaddya commented on src/test/java/ru/mail/polis/service/ShardingTest.java
> -import static org.junit.jupiter.api.Assertions.*;
Это изменение точно нужно? Код клаймет вроде не проверяет тестовые классы.

2020-11-17 11:38 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +    private final java.net.http.HttpClient client;
Можем избавиться от fully qualified name?

2020-11-17 11:38 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                replicasFactor = ReplicasFactor.quorum(topology.all().size());
Кворум у нас не меняется, может не будем для каждого запроса зановго создавать? Нужно учитывать, что в вашей реализации вызов `topology.all()` совсем не бесплатен.

2020-11-17 11:38 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                replicasFactor = ReplicasFactor.quorum(replicaFactor);
А если я передам строку `1/3` или `3/3`, это тоже кворум будет? :)

2020-11-17 11:38 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +        replNodes.forEach((node) -> responsesFuture.add(proxy(node, request)));
Такое более естественно бы выразилось в терминах стримов. Взять ноды для ключа, отобразить каждую ноду в фьючу и собрать в список. Но на ваше усмотрение.

2020-11-18 13:52 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                replicasFactor = ReplicasFactor.quorum(replicaFactor);
не очень понял, метод `quorum` просто парсит строку.

2020-11-18 14:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                replicasFactor = ReplicasFactor.quorum(replicaFactor);
Название метода не соответствует смыслу -- кворум это вполне определенное число реплик в зависимости от размера кластера. А здесь вы парсите строку, которая может быть не кворумом, например `1/3` или `3/3`. Названия `parse`, `from` и др. лучше подойдут.

2020-11-18 15:49 UTC, vaddya requested changes
Давайте немного переделаем `Entry`. Сейчас он уж больно похож на `Response`, хотя задача у него в другом. Он ближе к DAO уровню и похож на `Value`/`Cell`. Про HTTP-коды ответов он точно знать не должен.

2020-11-18 15:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                replicasFactor = ReplicasFactor.parseReplicaFactor(replicaFactor);
Вы делите этот объект между всеми запросами? Это же должно быть локальной переменной для запроса. Когда я говорил, что квоурм можно переиспользовать, я имел ввиду, что когда в запросе не указан RF, мы можем переиспользовать один RF `quorum`.

2020-11-18 15:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                .collect(Collectors.toCollection(ArrayList::new));
`Collectors.toList()`?

2020-11-18 15:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    public Response getResponse() {
`toResponse`? А то кажется, что это геттер для поля.

2020-11-18 15:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    private final int status;
Есть ощущение, что у `Entry` может быть ровно три статуса (которые лучше описать через `enum`, а не `int`), которые я описывал в прошлый раз:
- Present
- Removed
- Absent

Сейчас же у вас смешались HTTP-коды ответов и состояние ключа, это не очень правильно.

2020-11-18 15:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/PutDeleteBodyHandler.java
> +                return HttpResponse.BodySubscribers.replacing(entry);
Есть ощущение, что `Entry` нам нужен только на `GET`-запросах, чтобы выбрать самое последнее. А на `PUT`/`DELETE` нам по идее нужно просто знать, что запрос выполнился. Будет лучше:
- `HttpResponse.BodyHandler<Void>`
- `HttpResponse.BodySubscribers.discarding()` для body
- Бросать исключение, если запрос зафейлился

Можете пересмотреть лайвкодинг 6-го этапа, там есть про это.

2020-11-18 15:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        var iterator = values.iterator();
Давайте везде `var`, или нигде.

2020-11-21 09:43 UTC, vaddya commented
Добьете за выходные? Надо бы 6-ой этап завершить уже.

2020-11-25 21:00 UTC, vaddya requested changes
Надо доработать.

2020-11-25 21:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ServiceUtils.java
> +            entry = new Entry(Entry.ABSENT, Entry.EMPTY_DATA, Status.ABSENT);
Лучше заменить использование конструктора на использование говорящих методов:
`Entry.absent()`, `Entry.removed(ts)`, `Entry.present(data, ts)`. А то получается, что вы передаете в конструктор много лишних параметров.

2020-11-25 21:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ServiceUtils.java
> +            entry = new Entry(Entry.ABSENT, ServiceUtils.getArray(value.getData()), Status.PRESENT);
Не понятно, значение есть, и даже не tombstone, а в коде `Entry.ABSENT`.

2020-11-25 21:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Status.java
> +public enum Status {
Без контекста вообще не понятно что за статус. Он должен быть внутри класса `Value`, тогда понятно, что означает `Value.Status.REMOVED`.

2020-11-25 21:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/PutDeleteBodyHandler.java
> +            throw new RejectedExecutionException("cant");
Плохое сообщение.

2020-11-25 21:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/EntryMerger.java
> +            final long timestamp = ((Entry) entry).getTimestamp();
Можете объяснить, в чем смысл дженерика `<T>`, если вы в коде потом делаете безуснове приведение к `Entry`?

2020-11-25 21:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/EntryMerger.java
> +    private Entry getLatest(final Entry entry, final Entry latestResponse, final long timestamp) {
Какой-то странный набор параметров: `entry.getTimestamp()` не используется, зато передается отдельным параметром.

2020-11-25 21:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    public Entry(final long timestamp,
Плохой дизайн класса. Он поддерживает ряд инвариантов (например, что при `Status.ABSENT` таймстемп `-1`), но при это никак не проверяется. Или, например, то, что при `Status.REMOVED` и `Status.ABSENT` тело пустое, а при `Status.PRESENT` не пустое. Это надо ли валидировать в конструкторе, либо, что лучше, сделать приватный конструктор и добавить набор статических методов для каждого состояния, которые не будут принимать лишних параметров.

2020-11-25 21:00 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    public void setTimestamp(final long timestamp) {
Лучше стараться делать immutable классы, то есть классы без сеттеров. Это не всегда возможно, но в данном случае это будет правильным решением. Про пользу неизменяемых классов можно почитать [тут](https://dzone.com/articles/immutability-in-java).

2020-11-25 21:51 UTC, vaddya requested changes
Последнее

2020-11-25 21:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    private Status status;
`final`?

2020-11-25 21:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +        return new Entry(Entry.EMPTY_TIMESTAMP, Entry.EMPTY_DATA, Status.ABSENT);
Можно заметить, что пустое значение может быть синглтоном, потому что не зависит ни от `ts`, ни от `body`, поэтому лучше вынести объект в статическую переменную и возвращать его отсюда.

2020-11-25 21:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    public enum Status {
Лучше сделать это приватной частью, деталью реалищации. И добавить метод `isRemoved` для `mergeGetResponses`.

2020-11-25 21:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    public Status getStatus() {
По идее, эта деталь реализации не нужна снаружи этого класса, если добавить метод `isRemoved`.

2020-11-25 22:14 UTC, vaddya approved these changes
Запушьте последний фикс плз.

Принято.

2020-11-25 22:14 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    public static boolean isRemoved(final Entry latestResponse) {
А нельзя это методом класса сделать? :)
И геттер статуса можно будет совсем убрать.

2020-11-25 22:14 UTC, closed without merging

2020-11-25 22:41 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/Entry.java
> +    public static boolean isRemoved(final Entry latestResponse) {
сделал!