Stage6
polis-mail-ru/2020-highload-dht pull request #139
Opened 2020-11-03 17:17 UTC by KateMoreva

2020-11-03 20:22 UTC, KateMoreva commented
В реализации была допущена ошибка(и), из-за которой не получилось достичь выигрыша по времени при обработке запросов, и которая вызывает ConcurrentModificationException: null при первых N запросах к серверу. 

Ошибка будет найдена и исправлена в ближайшее время.

Результаты тестирования данной реализации:

### PUT запрсы

-t64 -c64 -d60s -R2000 -s ./wrk/put.lua --latency http://localhost:8080

**CPU**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/28d6e190a1c9f5f04756e50e38c28bdc5547e854/tests/stage6/cpuPut2000_c64_t64_60s.svg">

**Alloc**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/28d6e190a1c9f5f04756e50e38c28bdc5547e854/tests/stage6/allocPut2000_c64_t64_60s.svg">

**Lock**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/28d6e190a1c9f5f04756e50e38c28bdc5547e854/tests/stage6/lockPut2000_c64_t64_60s.svg">


Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.83ms    0.89ms  17.30ms   88.28%
    Req/Sec    33.03     48.83   111.00     68.54%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.70ms
 75.000%    2.05ms
 90.000%    2.54ms
 99.000%    5.45ms
 99.900%   10.94ms
 99.990%   15.59ms
 99.999%   16.62ms
100.000%   17.31ms
  120027 requests in 1.00m, 7.67MB read
Requests/sec:   2001.50
Transfer/sec:    130.96KB

### GET запросы

-t64 -c64 -d60s -R2000 -s ./wrk/get.lua --latency http://localhost:8080

**CPU**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/28d6e190a1c9f5f04756e50e38c28bdc5547e854/tests/stage6/cpuGet2000_c64_t64_60s.svg">

**Alloc**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/28d6e190a1c9f5f04756e50e38c28bdc5547e854/tests/stage6/allocGet2000_c64_t64_60s.svg">

**Lock**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/28d6e190a1c9f5f04756e50e38c28bdc5547e854/tests/stage6/lockGet2000_c64_t64_60s.svg">

Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.77ms    0.91ms  18.94ms   94.81%
    Req/Sec    33.06     48.89   111.00     68.53%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.66ms
 75.000%    1.96ms
 90.000%    2.23ms
 99.000%    5.76ms
 99.900%   13.20ms
 99.990%   16.75ms
 99.999%   18.69ms
100.000%   18.96ms
  120008 requests in 1.00m, 8.06MB read
Requests/sec:   2002.26
Transfer/sec:    137.67KB

2020-11-07 00:03 UTC, KateMoreva commented
Нагрузочное тестирование было проведено повторно, тк  реализация претерпела изменения. Так, например, было убрано повторное хождение в dao при get запросе, которое было видно на предыдущих flame graph. 

### PUT

-t64 -c64 -d60s -R2000 -s ./wrk/put.lua --latency http://localhost:8080

**CPU**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/699a920151fd29a16e61f2d3939fc4e108e1532e/tests/stage6/cpuPut2000_c64_t64_60s2.svg">
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.86ms    1.53ms  18.22ms   78.44%
    Req/Sec    32.47     44.22   111.00     76.40%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    2.42ms
 75.000%    3.73ms
 90.000%    4.65ms
 99.000%    8.26ms
 99.900%   13.84ms
 99.990%   17.06ms
 99.999%   17.95ms
100.000%   18.24ms
  120030 requests in 1.00m, 7.67MB read
Requests/sec:   2001.29
Transfer/sec:    130.94KB

Отправка ответа 3.47%
replication 5.04%
DAO.upsert 1.71%

**Alloc**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/699a920151fd29a16e61f2d3939fc4e108e1532e/tests/stage6/allocPut2000_c64_t64_60s2.svg">
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.52ms    2.65ms  22.46ms   75.54%
    Req/Sec    32.04     35.27   133.00     84.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    6.69ms
 75.000%    7.82ms
 90.000%    9.00ms
 99.000%   14.71ms
 99.900%   18.98ms
 99.990%   21.39ms
 99.999%   22.43ms
100.000%   22.48ms
  120019 requests in 1.00m, 7.67MB read
Requests/sec:   2001.41
Transfer/sec:    130.95KB

Работа селекторов 37.6%
Отправка ответа 5.28%
DAO.upsert 6.83%

**Lock**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/699a920151fd29a16e61f2d3939fc4e108e1532e/tests/stage6/lockPut2000_c64_t64_60s2.svg">
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.95ms    2.68ms  23.31ms   75.47%
    Req/Sec    31.99     31.69   117.00     91.12%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    7.09ms
 75.000%    8.09ms
 90.000%    9.51ms
 99.000%   15.10ms
 99.900%   18.35ms
 99.990%   22.70ms
 99.999%   23.31ms
100.000%   23.33ms
  120018 requests in 1.00m, 7.67MB read
Requests/sec:   2002.36
Transfer/sec:    131.01KB

Блокировка CompletableFuture занимает 30%
6% держит executor service 
Планировщик client 45.58%
16.03% client


### GET

-t64 -c64 -d60s -R2000 -s ./wrk/get.lua --latency http://localhost:8080

**CPU**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/699a920151fd29a16e61f2d3939fc4e108e1532e/tests/stage6/cpuGet2000_c64_t64_60s2.svg">
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.04ms    1.89ms  23.18ms   86.22%
    Req/Sec    32.77     47.16   111.00     67.21%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    2.53ms
 75.000%    3.72ms
 90.000%    5.09ms
 99.000%   10.90ms
 99.900%   17.89ms
 99.990%   21.47ms
 99.999%   22.93ms
100.000%   23.20ms
  120027 requests in 1.00m, 8.06MB read
Requests/sec:   2002.94
Transfer/sec:    137.72KB

Работа селекторов 8.84%
Отправка ответа 6.65%
DAO.getCell 2.69%
replication 5.73%

**Alloc**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/699a920151fd29a16e61f2d3939fc4e108e1532e/tests/stage6/allocGet2000_c64_t64_60s2.svg">
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.70ms    2.13ms  22.00ms   76.69%
    Req/Sec    32.55     45.31   111.00     69.37%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    3.64ms
 75.000%    4.90ms
 90.000%    5.83ms
 99.000%   11.72ms
 99.900%   15.53ms
 99.990%   18.01ms
 99.999%   18.85ms
100.000%   22.01ms
  120041 requests in 1.00m, 8.06MB read
Requests/sec:   2002.10
Transfer/sec:    137.66KB

Работа селекторов 16.47%
Отправка ответа 7.28%
DAO.getCell 7.23%
replication 19.52%

**Lock** 
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/699a920151fd29a16e61f2d3939fc4e108e1532e/tests/stage6/lockGet2000_c64_t64_60s2.svg">
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.82ms    2.24ms  26.16ms   77.85%
    Req/Sec    32.54     44.45   111.00     73.18%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    3.80ms
 75.000%    5.10ms
 90.000%    6.00ms
 99.000%   11.77ms
 99.900%   18.43ms
 99.990%   24.38ms
 99.999%   25.95ms
100.000%   26.17ms
  120029 requests in 1.00m, 8.06MB read
Requests/sec:   2002.12
Transfer/sec:    137.66KB

Блокировка локального запроса занимает 28.11%
7.60% держит executor service 
Планировщик client 40%
22.94% client

Блокировка локального запроса занимает 28.11% 7.60% держит executor service Планировщик client 40% 22.94% client
Ухудшения по количеству обработанных заявок, по сравнению с предыдущем этапом, нет.
Среднее время ответов на get запросы возросло примерно в 1.6 раз, на put запросы в 1.2 раза. Stdev стало немного лучше.

Полные результаты приведены [тут](https://github.com/polis-mail-ru/2020-highload-dht/blob/699a920151fd29a16e61f2d3939fc4e108e1532e/tests/stage6/results2.md)

2020-11-08 18:50 UTC, vaddya requested changes
Замечания по реализации.

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            requestHelper.sendLoggedResponse(context.getSession(), new Response(Response.BAD_REQUEST, Response.EMPTY));
Давайте явно `return` напишем? Тогда не придется дефолтное значение для `nodes` задавать.

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final List<ResponseValue> results = new ArrayList<>();
Ой-ей. Вы пытаетесь работать с непотокобезопасной коллекцией из асинхронного кода (из лямбды). Прямой путь к конкарренси багам.

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        return timestamp == null ? -1 : Long.parseLong(timestamp);
Может не распарситься и вылететь `NumberFormatException`. Лучше сделать бронейбоно и выловить исключение.

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +                getLocalResults(action, results);
Почему бы не вернуть `CompletableFuture` из `getLocalResults`?

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        final List<CompletableFuture<ResponseValue>> results = new ArrayList<>(nodes.size());
Если уж задавать дефолтное значение, то тут это скорее `Replicas.from`.

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        switch (request.getMethod()) {
Отступы съехали.

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final AtomicInteger numberOfErrors = new AtomicInteger(-1);
Логичнее, наверное, с нуля начать.

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +    private final java.net.http.HttpClient client;
Почему fully qualified name?

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final CompletableFuture<ResponseValue> resultsFuture = new CompletableFuture<>();
Можно использовать `future.thenApply()` и не создавать самостоятельно новую фьючу. И лучше внятное название дать, что за фьюча (`responses` или типа того).

2020-11-08 18:50 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/Replicas.java
> +        final int from = Integer.parseInt(params.get(1));
Можем получить `IndexOutOfBoundException`.

2020-11-09 13:58 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +    private final java.net.http.HttpClient client;
Переводила на java.net.http.HttpClient постепенно, забыла поправить после удаления клиента из one.nio.

2020-11-09 13:58 UTC, KateMoreva commented
> Замечания по реализации.

Спасибо за замечания, все поправила.

2020-11-09 14:47 UTC, vaddya requested changes
Еще немного.

2020-11-09 14:47 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +    public CompletableFuture<List<ResponseValue>> collect(final List<CompletableFuture<ResponseValue>> responseValues,
Какое поведение будет, если `responseValues.size() < ack`?

2020-11-09 14:47 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            if (id.isBlank()) {
Логичнее будет в блоке `try` оставить только вызов `execute()`.

2020-11-09 14:47 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        final Context context = new Context(session, isProxy, request, replicasFactor);
Может создать контекст уровнем выше? Тогда в этот метод можно будет передавать 1-2 параметра.

2020-11-09 14:47 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            requestHelper.sendLoggedResponse(context.getSession(),
Мы точно не отправим в сессию больше одного ответа? Обработка ошибок расползлась по всему классу, вижу минмиум два блока `exceptionally` и несколько `try-catch`, из которых что-то отправляется в сессию.

2020-11-09 14:47 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +    void executeMethod(final Context context, final ByteBuffer key, final Action action) {
`private`?

2020-11-09 14:47 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        return CompletableFuture.supplyAsync(() -> {
А на каком потоке будет выполняться этот код?

2020-11-09 18:30 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +    public CompletableFuture<List<ResponseValue>> collect(final List<CompletableFuture<ResponseValue>> responseValues,
В этом случае collect отдаст пустой List, merge прокинет null в executeMethod, где в блоке exceptionally будет оправлено 504.

2020-11-10 09:25 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            requestHelper.sendLoggedResponse(context.getSession(),
Не должны, отправка ответов в блоке обработки IllegalArgumentException не будет произведена, тк условия, при которых можно получить эту ошибку были проверяются и обрабатываются при получении запроса.

2020-11-10 20:21 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +    private CompletableFuture<ResponseValue> getLocalResults(final Action action) {
Теперь получается, что вместо того, чтобы зашедулить поиск в локальном DAO и сделать запросы к другим нодам, мы сначала синхронно будем искать в DAO (хотя могли бы отправить запросы, а пока ждем ответы искать локально). Нужно вернуть асинхронность, но явно указать тред пул, на котором выполняться. В вашем прошлом варианте он не был указан, а значит использовался `ForkJoinPool#commonPool()` вместо нашего.

2020-11-10 20:24 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +    public CompletableFuture<List<ResponseValue>> collect(final List<CompletableFuture<ResponseValue>> responseValues,
Вы уверены? У меня есть ощущение, что если, например, `responseValues.size() == 1`, а `ack = 3` (то есть ждем 3 подтверждений, хотя передаем сюда только 1 фьючу), то `resultsFuture` никогда ни выполнится, ни зафейлится.

2020-11-10 20:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +    public CompletableFuture<List<ResponseValue>> collect(final List<CompletableFuture<ResponseValue>> responseValues,
Это я все к тому, что лучше явно провалидировать входные параметры и бросить исключение в случае чего.

2020-11-11 00:15 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +    public CompletableFuture<List<ResponseValue>> collect(final List<CompletableFuture<ResponseValue>> responseValues,
Вы правы, лучше пробросить исключение, исправила.

2020-11-11 08:12 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +    private CompletableFuture<ResponseValue> getLocalResults(final Action action) {
Поняла, спасибо, исправила.

2020-11-11 18:05 UTC, vaddya commented on tests/stage6/results2.md
> +Среднее время ответов на get запросы возросло примерно в 1.6 раз, на put запросы в 1.2 раза. Stdev стало немного лучше.
То есть при переходе от one-nio клиента к асинхронному, время так сильно выросло? :(

2020-11-11 18:14 UTC, KateMoreva commented on tests/stage6/results2.md
> +Среднее время ответов на get запросы возросло примерно в 1.6 раз, на put запросы в 1.2 раза. Stdev стало немного лучше.
К сожалению, да. Правда, тестирование было до последних изменений, но они не должны радикально улучшить ситуацию.

2020-11-11 18:16 UTC, vaddya commented on tests/stage6/results2.md
> +Среднее время ответов на get запросы возросло примерно в 1.6 раз, на put запросы в 1.2 раза. Stdev стало немного лучше.
Интересно, с чем это связано может быть. Раньше, например, при `2/3` всегда ждали 3 ответов, а теперь 2 самых быстрых. Наверное, в рамках одной машины это просто незаметно.

2020-11-11 18:17 UTC, vaddya approved these changes
Принято.

2020-11-11 18:17 UTC, closed without merging