test_me_one
polis-mail-ru/2020-highload-dht pull request #14
Opened 2020-09-28 09:42 UTC by ScriptoMax

prime request

2020-10-04 10:20 UTC, dormidon commented on src/main/java/ru/mail/polis/service/codearound/RocksRecordIterator.java
> +     * define evaluation of an element (record) at next step of file reading by iterator.
Само слово `define` избыточно в комменте у метода :)
Метод ведь и так определяет какое-то поведение.
Тут лучше `Evaluates next element of ...` (причем принято писать то, что делают методы в третьем лице единственном числе, т.е. метод как "он мой" evaluates, performs, reads и т.д.

2020-10-04 10:21 UTC, dormidon commented on src/main/java/ru/mail/polis/service/codearound/RocksRecordIterator.java
> +            throw new IllegalStateException("End of file content reached. Iterator stopped\n");
В этих ситуациях общепринято бросать `NoSuchElementException`.

2020-10-04 10:22 UTC, dormidon commented on src/main/java/ru/mail/polis/service/codearound/TaskDAO.java
> +                logger.log(Level.SEVERE, "Storage initialization failed");
Можно еще и само исключение вывести в лог, чтобы было понятно, почему именно обломилась инициализация хранилища.

2020-10-04 10:23 UTC, dormidon commented on src/main/java/ru/mail/polis/service/codearound/TaskService.java
> +public class TaskService extends HttpServer implements Service {
Странное название. Что за `Task`? Какая здесь подоплека? :)

2020-10-04 10:24 UTC, dormidon commented on src/main/java/ru/mail/polis/service/codearound/TaskService.java
> +     * determine what request and how to be handled if receiving one.
Тут даже по смыслу комментарий не актуальный.
Надо написать, что-то вроде "возвращает статус сервиса, а-ля его живость и готовность отвечать на запросы".

2020-10-04 10:26 UTC, dormidon commented
Я не могу найти отчета по нагрузочному тестированию и профилированию.
Плюс есть небольшие замечания по коду, которые нужно исправить.

2020-10-04 11:01 UTC, dormidon commented
По поводу отчета:

1. Первый пункт называется `1) curl http://127.0.0.1:8080/v0/status`, хотя по виду там не курлом, а используется `wrk`. При этом стрельба идет не на ресурс `/v0/status`, а на `/`, что видно на первом флеймграфе, ибо там фигурирует метод `TaskService.handleDefault`. 
Второй флеймграф (который с аллокациями) вообще флеймграф Влада Зыбкина (или его кода), что видно в именах пакетах - `zvladn7`, а если смотреть по методам - это это вызов `get`, а не `status`, к которому относится раздел отчета. Разумных объяснений, кроме заимствования флеймграфа, я не нахожу.  
В общем, с этим пунктом какая-то каша, написано одно, делается другое, получается третье, да и то не свое.

2. Пункт про GET
Не очень понятно, была ли наполнена БД до этих стрельб или же она пустая.
Если пустая, то вывод "при установлении наличия в нём целевого ключа сервер затрачивает дополнительное время на формирование ответа, содержащего соответствующее аргументу функции значение." не правильный.
Вывод 
```
359998 requests in 3.00m, 49.09MB read
  Non-2xx or 3xx responses: 359998
```
намекает на то, что на все запросы было 404, т.е. БД была пустой.

Флеймграфы к этому методу отстуствтуют (а они нужны, ибо могут показать, где есть проблемы с производительностью).

3. Пункт про PUT
Нет флеймграфов - результатов профилирования под таким типом нагрузки.
Без этого нельзя сделать вывод, почему именно изменилось время и на что оно стало уходить. 

4. Пункт про DELETE
Нет флеймграфов - результатов профилирования под таким типом нагрузки. 
Без этого нельзя сделать вывод, почему именно изменилось время и на что оно стало уходить. 
Вывод "Столь негативный эффект можно рассматривать как следствие интенсивного уменьшения объёма данных одновременно с динамической оптимизацией структуры хранилища под влиянием серийного исключения записей." - пальцем в небо, нужны доказательства в виде фреймов вызовов и аллокаций.

2020-10-04 11:05 UTC, dormidon requested changes
См. комменты. 
Нужно объяснить, откуда профиль Влада появился, а также пострелять по наполенной БД и получить профили CPU и аллокаций для всех методов.

2020-10-04 15:58 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RocksRecordIterator.java
> +     * define evaluation of an element (record) at next step of file reading by iterator.
требуемые правки внесены

2020-10-04 15:58 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RocksRecordIterator.java
> +            throw new IllegalStateException("End of file content reached. Iterator stopped\n");
требуемые правки внесены

2020-10-04 15:58 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/TaskDAO.java
> +                logger.log(Level.SEVERE, "Storage initialization failed");
требуемые правки внесены

2020-10-04 16:01 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/TaskService.java
> +public class TaskService extends HttpServer implements Service {
Данный идентификатор выбран для обозначения класса, требующего самостоятельной реализации в рамках задачи. Задача - создать класс и определить его члены для последующего контроля. По Вашей рекомендации мною может быть использовано альтернативное название (пожалуйста, сообщите, какое именно)

2020-10-04 16:01 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/TaskService.java
> +     * determine what request and how to be handled if receiving one.
требуемые правки внесены

2020-10-04 16:08 UTC, ScriptoMax commented
> См. комменты.
> Нужно объяснить, откуда профиль Влада появился, а также пострелять по наполенной БД и получить профили CPU и аллокаций для всех методов.

Прошу прощения, налицо некорректное заимствование: признаю, что торопился успеть к дедлайну, а с подключением символов дебаггинга для JVM в контексте профилирования памяти наметились проблемы. Я решил их с помощью данной дискуссии https://github.com/jvm-profiling-tools/async-profiler/issues/193. Текущая редакция readme содержит оригинальные иллюстрации ко всем релевантным процедурам, неподобающих действий в ситуации с отдельным заимствованием я не отрицаю.

2020-10-04 16:09 UTC, ScriptoMax commented
пожалуйста, рассмотрите актуальное содержимое pull request

2020-10-05 09:12 UTC, dormidon commented
Теперь более-менее хорошо. 
Единственное, что смущает ровно секунда максимального времени во всех операциях, что чтения, что удаления, что добавления. По профилям с виду ничего лишнего не происходит (хотя тут Rocks, особо ничего и не должно быть). 
Ставлю в ведомость 8 баллов - минус 2 за изначальные заимствования (изначально за такое вообще отчислять планировалось).

2020-10-05 09:12 UTC, closed without merging