Stage6
polis-mail-ru/2020-highload-dht pull request #141
Opened 2020-11-03 18:51 UTC by dariaGap

2020-11-08 20:48 UTC, incubos requested changes
Есть ряд замечаний и вопросов, особенно по анализу результатов профилирования и рассуждениям о причинах достигнутых успехов.

2020-11-08 20:48 UTC, incubos commented on doc/Stage6.md
> +- время обстрела - 20 секунд
Маловато с учётом необходимости "прогрева".

2020-11-08 20:48 UTC, incubos commented on doc/Stage6.md
> +По результатам нагрузочного тестирования видно, что скорость обработки запросов по сравнению с предыдущим этапом увеличивается (в 1.89 раз для 99.9% запросов и в 1.60 раз для 99.999% запросов), что о
Разве не потому, что мы обращаемся к репликам параллельно, а не последовательно?

2020-11-08 20:48 UTC, incubos commented on doc/Stage6.md
> +При профилировании видны выполнение вычислений асинхронно в пуле потоков (CompletableFuture.AsyncSupply),
Выделение памяти, а не вычисления?

2020-11-08 20:48 UTC, incubos commented on doc/Stage6.md
> +Добавляются блокировки, связанные с завершением CompletableFuture, блокировки переключения между потоками выполнения, а также блокировки, связанные с выбором задач на исполнение в асинхронном клиенте
Можете назвать конкретные методы (CompletableFuture и переключения между потоками выполнения)? Я на верхних полках вижу различные методы `SelectorManager` и `ConnectionPool`.

2020-11-08 20:48 UTC, incubos commented on doc/Stage6.md
> +- время обстрела - 20 секунд
Опять же маловато будет с учётом необходимости "прогрева".

2020-11-08 20:48 UTC, incubos commented on doc/Stage6.md
> +Добавляется отправка запросов к репликам через пул потоков асинхронного сервера, в пуле потоков (executorPool)
Можете подробнее и конкретнее описать, что вы видите? Я например, вижу, что много процессорного времени уходит на работу с сокетами, а также код `HttpClient` (верхние зелёные полки и то, что к ним ведёт снизу), а вот названия пулов потоков, про которые вы пишете, наоборот не вижу.

2020-11-08 20:48 UTC, incubos commented on doc/Stage6.md
> +Добавляются блокировки, связанные с завершением CompletableFuture, блокировки переключения между потоками выполнения,
См. замечания к `PUT`.

2020-11-08 20:48 UTC, incubos commented on src/main/java/ru/mail/polis/service/dariagap/BasicService.java
> +    public void sendResponseFromFuture(final HttpSession session,
Почему этот метод находится именно в текущем классе, а не является `static` где-то в утилитном класс? Разве, мы от чего-то здесь зависим?

2020-11-08 20:48 UTC, incubos commented on src/main/java/ru/mail/polis/service/dariagap/ClusterServiceImpl.java
> +    public synchronized void stop() {
Может, и `basicService` стоит остановить? У него внутри тоже есть executor.

2020-11-10 14:24 UTC, incubos commented
Ждать исправлений или уже всё?

2020-11-10 14:37 UTC, dariaGap commented
> Ждать исправлений или уже всё?

Исправления в процессе.

2020-11-12 11:01 UTC, incubos commented
Принято.

2020-11-12 11:01 UTC, closed without merging