Task 6
polis-mail-ru/2020-highload-dht pull request #142
Opened 2020-11-03 20:11 UTC by nik27090

2020-11-21 18:16 UTC, lamtev requested changes
# Реализация

Нужно переосмыслить то, как пользоваться CompletableFuture

Обычно любая операция с суффиксом Async, если не передать свой ExecutorService, будет выполняться на ForkJoinPool.commonPool, что почти наверняка не является ожидаемым поведением. Так нужно помнить передавать свой экзекютор

Также стоит понимать, что нет смысла в том, чтобы всегда выполнять над результатом предыдущей фючи действия асинхронно, что засабмитит в underlying экзекютор новую задачу. Соответственно появятся накладные расходы как минимум в локах BlockingQueue. Бывают случаи, когда стоит выполнять асинхронно, например, когда это какая-то долгая операция, и при этом не хочется надолго занимать экзекютор. Тогда асинхронное выполнение позволит выполнить на экзекюторе другие засабмиченные в него задачи.

# Профилирование

Отсутствует :(

2020-11-21 18:16 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/RendezvousTopology.java
> +            ).get();
такое решение не годится, нужно посмотреть как было на лекции

2020-11-21 18:16 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +    private final Map<String, HttpClient> nodeToClient;
Нужно убрать, так это больше не должно использоваться

2020-11-24 09:33 UTC, nik27090 commented
Подумаю

2020-11-29 06:59 UTC, lamtev commented
Планируется поправить?

2020-12-04 12:13 UTC, lamtev commented
@nik27090 планируется довести до ума данное решение?

2020-12-08 18:39 UTC, nik27090 commented
Да, спасибо за напоминания!

2020-12-10 00:47 UTC, nik27090 commented on src/main/java/ru/mail/polis/service/nik27090/RendezvousTopology.java
> +            ).get();
фикс

2020-12-10 00:47 UTC, nik27090 commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +    private final Map<String, HttpClient> nodeToClient;
оно не используется, забыл удалить

2020-12-10 20:53 UTC, nik27090 commented
тесты проходят

2020-12-11 21:30 UTC, lamtev approved these changes

2020-12-11 21:31 UTC, lamtev commented
Принято

2020-12-11 21:31 UTC, closed without merging