Homework6
polis-mail-ru/2020-highload-dht pull request #143
Opened 2020-11-03 20:58 UTC by Marashov-Alexander

2020-11-06 06:37 UTC, Marashov-Alexander commented
Извините за задержку публикования [результатов профилирования](https://github.com/polis-mail-ru/2020-highload-dht/blob/e4a1b0393e2f67af1316eecdd71f53bbb81577a8/profiler/homework6/2_3/analysis.md) , возможность снижения баллов понимаю)

2020-11-21 16:53 UTC, lamtev requested changes
# Реализация

Нужно переосмыслить то, как пользоваться CompletableFuture

Обычно любая операция с суффиксом Async, если не передать свой ExecutorService, будет выполняться на ForkJoinPool.commonPool, что почти наверняка не является ожидаемым поведением. Так нужно помнить передавать свой экзекютор

Также стоит понимать, что нет смысла в том, чтобы всегда выполнять над результатом предыдущей фючи действия асинхронно, что засабмитит в underlying экзекютор новую задачу. Соответственно появятся накладные расходы как минимум в локах BlockingQueue. Бывают случаи, когда стоит выполнять асинхронно, например, когда это какая-то долгая операция, и при этом не хочется надолго занимать экзекютор. Тогда асинхронное выполнение позволит выполнить на экзекюторе другие засабмиченные в него задачи.

# Профилирование

Скорее всего результат оказался хуже, чем на прошлом этапе как раз из-за проблем в реализации. Если исправить замечания, то в теории должно стать получше

2020-11-21 16:53 UTC, lamtev commented on src/main/java/ru/mail/polis/service/alexander/marashov/ResponseManager.java
> +                                .thenApplyAsync(voidHttpResponse -> new Response(Response.ACCEPTED, Response.EMPTY));
Помимо того, что тут надо подумать о необходимости асинхронности, стоит понимать так же, что выполняться будет лямбда на ForkJoinPool.commonPool(). Это глобальный пул, который может использоваться много кем

2020-11-21 16:53 UTC, lamtev commented on src/main/java/ru/mail/polis/service/alexander/marashov/analyzers/FutureAnalyzer.java
> +                throw new RuntimeException("Who canceled my future??");
можно IllegalStateException

2020-11-21 19:22 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/ResponseManager.java
> +        this.httpClient = java.net.http.HttpClient.newBuilder()
Добрый вечер! Да, сейчас это лишнее - добавил как обычный импорт, спасибо)
Переделывал этот файл из своего 5 этапа, где был HttpClient из one.nio, забыл убрать

2020-11-21 19:23 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/DaoManager.java
> +        return CompletableFuture.supplyAsync(
Указал свой daoExecutor, спасибо за замечание!

2020-11-21 19:27 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/ResponseManager.java
> +            return daoManager.rowGet(validParams.key).thenApplyAsync(
Так, исправил. И вроде разобрался: thenApplyAsync добавил бы новую задачу уже после получения результата фючи, а thenApply выполнил бы указанное в том же контексте, где выполнялась фюча?

2020-11-21 19:28 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/ResponseManager.java
> +                        .thenApplyAsync(HttpResponse::body, proxyExecutor);
Спасибо за замечания, ситуация для меня вроде проясняется)
Исправил в ещё парочке мест, кроме указанных в Ваших комментариях

2020-11-21 19:29 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/ResponseManager.java
> +                                .thenApplyAsync(voidHttpResponse -> new Response(Response.ACCEPTED, Response.EMPTY));
Ой, да, тут уж совсем не в тему было async, спасибо)

2020-11-21 19:29 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/analyzers/FutureAnalyzer.java
> +                throw new RuntimeException("Who canceled my future??");
Исправил. И в остальных аналогичных местах

2020-11-21 19:35 UTC, Marashov-Alexander commented
> # Реализация
> Нужно переосмыслить то, как пользоваться CompletableFuture
> 
> Обычно любая операция с суффиксом Async, если не передать свой ExecutorService, будет выполняться на ForkJoinPool.commonPool, что почти наверняка не является ожидаемым поведением. Так нужно помнить передавать свой экзекютор
> 
> Также стоит понимать, что нет смысла в том, чтобы всегда выполнять над результатом предыдущей фючи действия асинхронно, что засабмитит в underlying экзекютор новую задачу. Соответственно появятся накладные расходы как минимум в локах BlockingQueue. Бывают случаи, когда стоит выполнять асинхронно, например, когда это какая-то долгая операция, и при этом не хочется надолго занимать экзекютор. Тогда асинхронное выполнение позволит выполнить на экзекюторе другие засабмиченные в него задачи.
> 
> # Профилирование
> Скорее всего результат оказался хуже, чем на прошлом этапе как раз из-за проблем в реализации. Если исправить замечания, то в теории должно стать получше

Спасибо за объяснения, теперь лучше понимаю!
Исправил Ваши замечания, провёл нагрузочное тестирование.
Если вкратце, то так:
* Этап 5, 99.9% запросов при replicas=2/3:
    - PUT - за 4.22ms,
    - GET - за 2.68ms
* Этап 6, предыдущая реализация, 99.9% запросов при replicas=2/3:
    - PUT -- за 8ms.
    - GET -- за 5.57ms.
* Этап 6, исправленная реализация, 99.9% запросов при replicas=2/3:
    - PUT -- за 5.63ms.
    - GET -- за 3.16ms.
Стало значительно лучше :)

Вот полные результаты:
## Для PUT
```bash
./wrk -c 64 -d 4m -t1 -s ../../2020-highload-dht/profiler/scripts/putS2.lua --latency -R2000 http://localhost:8080
Running 4m test @ http://localhost:8080
  1 threads and 64 connections
  Thread calibration: mean lat.: 1.548ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.05ms  502.05us  13.35ms   71.88%
    Req/Sec     2.08k   140.36     3.90k    72.89%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.03ms
 75.000%    1.36ms
 90.000%    1.60ms
 99.000%    2.10ms
 99.900%    5.63ms
 99.990%    8.18ms
 99.999%   11.03ms
100.000%   13.36ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.185     0.000000            1         1.00
       0.470     0.100000        45985         1.11
       0.607     0.200000        92026         1.25
       0.746     0.300000       137810         1.43
       0.879     0.400000       183791         1.67
       1.027     0.500000       229832         2.00
       1.092     0.550000       252858         2.22
       1.152     0.600000       275640         2.50
       1.215     0.650000       298739         2.86
       1.284     0.700000       321753         3.33
       1.356     0.750000       344661         4.00
       1.394     0.775000       356211         4.44
       1.432     0.800000       367747         5.00
       1.470     0.825000       379128         5.71
       1.508     0.850000       390507         6.67
       1.551     0.875000       402095         8.00
       1.574     0.887500       407764         8.89
       1.599     0.900000       413505        10.00
       1.625     0.912500       419295        11.43
       1.653     0.925000       425106        13.33
       1.682     0.937500       430659        16.00
       1.700     0.943750       433655        17.78
       1.718     0.950000       436473        20.00
       1.740     0.956250       439384        22.86
       1.764     0.962500       442168        26.67
       1.797     0.968750       445041        32.00
       1.817     0.971875       446493        35.56
       1.839     0.975000       447899        40.00
       1.867     0.978125       449321        45.71
       1.906     0.981250       450764        53.33
       1.951     0.984375       452203        64.00
       1.980     0.985938       452900        71.11
       2.016     0.987500       453627        80.00
       2.061     0.989062       454337        91.43
       2.133     0.990625       455052       106.67
       2.265     0.992188       455776       128.00
       2.411     0.992969       456132       142.22
       2.635     0.993750       456488       160.00
       2.905     0.994531       456850       182.86
       3.219     0.995313       457207       213.33
       3.563     0.996094       457564       256.00
       3.733     0.996484       457745       284.44
       3.947     0.996875       457923       320.00
       4.207     0.997266       458103       365.71
       4.427     0.997656       458287       426.67
       4.739     0.998047       458461       512.00
       4.883     0.998242       458553       568.89
       5.023     0.998437       458642       640.00
       5.211     0.998633       458730       731.43
       5.435     0.998828       458821       853.33
       5.655     0.999023       458912      1024.00
       5.783     0.999121       458957      1137.78
       5.939     0.999219       459001      1280.00
       6.099     0.999316       459046      1462.86
       6.271     0.999414       459089      1706.67
       6.459     0.999512       459135      2048.00
       6.567     0.999561       459157      2275.56
       6.719     0.999609       459179      2560.00
       6.811     0.999658       459201      2925.71
       6.979     0.999707       459224      3413.33
       7.151     0.999756       459248      4096.00
       7.231     0.999780       459258      4551.11
       7.359     0.999805       459269      5120.00
       7.451     0.999829       459280      5851.43
       7.723     0.999854       459292      6826.67
       7.923     0.999878       459302      8192.00
       8.075     0.999890       459308      9102.22
       8.247     0.999902       459314     10240.00
       8.367     0.999915       459319     11702.86
       8.487     0.999927       459325     13653.33
       8.663     0.999939       459330     16384.00
       8.951     0.999945       459333     18204.44
       9.159     0.999951       459336     20480.00
       9.423     0.999957       459339     23405.71
       9.887     0.999963       459342     27306.67
      10.015     0.999969       459344     32768.00
      10.127     0.999973       459346     36408.89
      10.199     0.999976       459347     40960.00
      10.303     0.999979       459349     46811.43
      10.335     0.999982       459350     54613.33
      10.711     0.999985       459351     65536.00
      11.007     0.999986       459352     72817.78
      11.031     0.999988       459353     81920.00
      11.063     0.999989       459354     93622.86
      11.063     0.999991       459354    109226.67
      11.399     0.999992       459355    131072.00
      11.399     0.999993       459355    145635.56
      11.447     0.999994       459356    163840.00
      11.447     0.999995       459356    187245.71
      11.447     0.999995       459356    218453.33
      12.511     0.999996       459357    262144.00
      12.511     0.999997       459357    291271.11
      12.511     0.999997       459357    327680.00
      12.511     0.999997       459357    374491.43
      12.511     0.999998       459357    436906.67
      13.359     0.999998       459358    524288.00
      13.359     1.000000       459358          inf
#[Mean    =        1.046, StdDeviation   =        0.502]
#[Max     =       13.352, Total count    =       459358]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  479715 requests in 4.00m, 30.65MB read
Requests/sec:   1998.81
Transfer/sec:    130.78KB
```
## Для GET
./wrk -c 64 -d 4m -t1 -s ../../2020-highload-dht/profiler/scripts/getS2.lua --latency -R2000 http://localhost:8080
Running 4m test @ http://localhost:8080
  1 threads and 64 connections
  Thread calibration: mean lat.: 1.110ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.11ms  468.18us  11.62ms   64.56%
    Req/Sec     2.10k   124.61     3.11k    69.59%
  Latenc [...]

2020-11-21 19:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/alexander/marashov/ResponseManager.java
> +            return daoManager.rowGet(validParams.key).thenApplyAsync(
Да 👍🏻

2020-11-21 19:55 UTC, lamtev commented
> Стало значительно лучше :)

Это хорошо!

Но по-прежнему хуже, чем в 5-м этапе. Тут можно более внимательно посмотреть на флейм графы и попытаться найти что-то подозрительное. Либо попробовать сравнить на более высоких нагрузках, потому что судя по задержкам подаваемые 2к - не предел. Возможно, на более высоких нагрузках, картина изменится. 
Если, конечно, интересно)

2020-11-23 11:04 UTC, Marashov-Alexander commented
> > Стало значительно лучше :)
> 
> Это хорошо!
> 
> Но по-прежнему хуже, чем в 5-м этапе. Тут можно более внимательно посмотреть на флейм графы и попытаться найти что-то подозрительное. Либо попробовать сравнить на более высоких нагрузках, потому что судя по задержкам подаваемые 2к - не предел. Возможно, на более высоких нагрузках, картина изменится.
> Если, конечно, интересно)

Добрый день!
Имитировал нагрузку 6000 запросов в секунду - всё равно асинхронный клиент пятого этапа, написанный на ExecutorService, опережает асинхронный клиент шестого этапа с использованием Future.
Очень может быть, что в этом кроется моя ошибка в реализации, но у меня сейчас больше не осталось времени на более глубокое изучение задачи - нужно ещё бонусные фичи реализововать.
Спасибо за ревью, объяснения и полезные комментарии! :)

2020-11-23 12:39 UTC, lamtev commented
Принято

2020-11-23 12:39 UTC, closed without merging