Task7
polis-mail-ru/2020-highload-dht pull request #147
Opened 2020-11-13 11:54 UTC by IvanovAndrey

2020-11-17 09:27 UTC, incubos requested changes
Есть небольшие замечания.

2020-11-17 09:27 UTC, incubos commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +            basicFuctions.trySendResponse(session, CompletableFuture.supplyAsync(() ->
Тут нет смысла в асинхронщине, потому что ответ вычислять не нужно -- можно отправить всё синхронно.

2020-11-17 09:27 UTC, incubos commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +        final ByteBuffer count;
Почему выбрано название `count`? Это же правая граница диапазона.

2020-11-17 09:27 UTC, incubos commented on src/main/java/ru/mail/polis/service/ivanovandrey/ServiceSession.java
> +    public static final byte[] CRLR = "\r\n".getBytes(StandardCharsets.US_ASCII);
`CRLF`, наверное?

2020-11-17 09:27 UTC, incubos commented on src/main/java/ru/mail/polis/service/ivanovandrey/ServiceSession.java
> +    private byte[] toChunk(final Record elem) throws IOException {
Мы здесь **два раза** копируем память: сначала формируем тело `data`, потом аллоцируем и копируем в `chunk` -- можем убрать одно копирование?

2020-11-17 09:27 UTC, incubos commented on src/test/java/ru/mail/polis/dao/AllDeadTest.java
> +import org.junit.jupiter.api.RepeatedTest;
Зачем это?

2020-11-17 09:27 UTC, incubos commented on src/test/java/ru/mail/polis/service/SingleNodeTest.java
> +import org.junit.jupiter.api.RepeatedTest;
Зачем это?

2020-11-17 16:01 UTC, IvanovAndrey commented on src/main/java/ru/mail/polis/service/ivanovandrey/ServiceSession.java
> +    private byte[] toChunk(final Record elem) throws IOException {
Если я правильно понял замечание, что в данном случае вместо 
`byte[] chunk = data + somthing;`
`return chunk;`
стоит писать
`return data + something;`
В этом смысле порефакторил
Но есть ощущение, что я понял не так

2020-11-18 12:04 UTC, incubos commented on src/main/java/ru/mail/polis/service/ivanovandrey/ServiceSession.java
> +    private byte[] toChunk(final Record elem) throws IOException {
Да, я непонятно описал замечание, видимо. Претензия была к массиву `byte[] data`.
Зачем нам аллоцировать его, копировать в него `dataKey` и `dataValue`, а затем копировать массив `data` в `ByteBuffer`? Можно сразу выделить `ByteBuffer` нужного размера и сложить в него все поля (включая `[key]\n[value]`), избавившись от лишней аллокации `data` и копирования байт ключа и значения.
Лишние аллокации и копирования -- основная причина недостаточной производительности нагруженных сервисов.

2020-11-18 12:05 UTC, incubos requested changes
Нужно немного дооптимизировать.

2020-11-18 13:11 UTC, IvanovAndrey commented
Поправил
`continuous-integration/travis-ci/pr` еще думает, но вроде должно быть правильно.
А то, что я сделал в первый раз имеет смысл? или просто повышает когнитивную сложность?

2020-11-19 17:40 UTC, incubos requested changes
Уже почти, но не до конца.

2020-11-19 17:40 UTC, incubos commented on src/main/java/ru/mail/polis/service/ivanovandrey/ServiceSession.java
> +                .put("\n".getBytes(StandardCharsets.US_ASCII))
Давайте сделаем константой. Зачем нам каждый раз аллоцировать этот массив?

2020-11-23 16:05 UTC, incubos commented
> Поправил
> `continuous-integration/travis-ci/pr` еще думает, но вроде должно быть правильно.
> А то, что я сделал в первый раз имеет смысл? или просто повышает когнитивную сложность?

Я потерял контекст :(

2020-11-23 16:05 UTC, incubos commented
Принято.

2020-11-23 16:05 UTC, closed without merging