Stage 7
polis-mail-ru/2020-highload-dht pull request #148
Opened 2020-11-14 11:29 UTC by StasyanOi

2020-11-17 09:43 UTC, incubos requested changes
Есть ряд замечаний и вопросов.

2020-11-17 09:43 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +        closeStream();
Это неправильно сразу закрывать поток, потому что все данные могли не влезть в сокет (`queueHead` стал не `null` и запись прекратилась в `sendStream()`).

2020-11-17 09:43 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +        final byte[] emptyBody = new byte[0];
Тянет на константу. Зачем лишние аллокации?

2020-11-17 09:43 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +        byte[] valueWithoutTimestamp = new byte[value.length - Constants.TIMESTAMP_LENGTH];
Зачем сразу аллоцировать этот массив, если иногда мы отправляем `emptyBody` ниже?

2020-11-17 09:43 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +    private byte[] getRecordData(final Record record) {
Мы здесь **три раза** копируем данные: `valueWithoutTimestamp`, `data` и `chunk` -- надо свести к одному копированию.

2020-11-17 09:43 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +            if (session instanceof StreamingSession) {
Стоит отправить ошибку или хотя бы залоггировать, если это не так -- а не тихо игнорировать проблему.

2020-11-18 08:07 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +        closeStream();
Добавил do while со спец условием

2020-11-18 08:07 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +        final byte[] emptyBody = new byte[0];
Добавил в Constants

2020-11-18 08:07 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +        byte[] valueWithoutTimestamp = new byte[value.length - Constants.TIMESTAMP_LENGTH];
Убрал в if

2020-11-18 08:07 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +    private byte[] getRecordData(final Record record) {
Переделал

2020-11-18 08:07 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +            if (session instanceof StreamingSession) {
Добавил логер

2020-11-18 12:07 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +        closeStream();
А теперь мы будем тут крутиться и жечь циклы процессора, пока всё не запихнём в сокет. Неэффективно.

2020-11-18 12:08 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +            if (session instanceof StreamingSession) {
Ошибку всё равно нужно отправить, иначе клиент будет висеть, пока не истечёт таймаут на получение ответа.

2020-11-18 12:11 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +            valueWithoutTimestamp = Arrays.copyOfRange(value, 0, pureBodyLength);
Здесь осталось лишнее копирование данных -- можно переместить вниз, вызвать `ByteBuffer.put()` с `offset` и `length` и избавиться от `copyOfRange()`.
Лишние аллокации и копирования данных -- основная проблема недостаточной производительности нагруженных систем.

2020-11-18 12:11 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +    private byte[] getRecordData(final Record record) {
Надо дооптимизировать. Написал коммент.

2020-11-18 12:12 UTC, incubos requested changes
Ещё есть неисправленные замечания.

2020-11-21 08:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +        closeStream();
Добавил processWrite

2020-11-21 08:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +    private byte[] getRecordData(final Record record) {
Переделал

2020-11-21 08:30 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/server/CustomServer.java
> +            if (session instanceof StreamingSession) {
переделал на отправку 500ой ошибки

2020-11-21 08:49 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/StreamingSession.java
> +            valueWithoutTimestamp = Arrays.copyOfRange(value, 0, pureBodyLength);
Переделал

2020-11-23 16:07 UTC, incubos commented
Принято.

2020-11-23 16:07 UTC, closed without merging