Task1
polis-mail-ru/2020-highload-dht pull request #15
Opened 2020-09-28 16:34 UTC by IvanovAndrey

First try to pass bots

2020-09-29 08:31 UTC, incubos requested changes
Не хватает результатов нагрузочного тестирования и профилирования под нагрузкой, а также анализа результатов.

2020-09-29 08:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/RecordIterator.java
> +            throw new IllegalStateException("Empty");
По контракту `Iterator` нужно кидать unchecked `NoSuchElementException`.

2020-09-29 08:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/RocksDBImpl.java
> +    } catch (RocksDBException e) {
Не выровнено

2020-09-29 08:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/RocksDBImpl.java
> +    public ByteBuffer get(@NotNull final ByteBuffer key) throws IOException, NoSuchElementException {
А чем default реализация не подошла?

2020-09-29 08:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/RocksDBImpl.java
> +    public static byte[] fromByteBufferToByte(@NotNull final ByteBuffer buffer) {
`fromByteBufferToByteArray()`?

2020-09-29 12:25 UTC, IvanovAndrey commented on src/main/java/ru/mail/polis/dao/RocksDBImpl.java
> +    public ByteBuffer get(@NotNull final ByteBuffer key) throws IOException, NoSuchElementException {
Падали тесты на этом методе, решил переписать, но дело было в неправильном переводе из ByteBuffer в массив byte. Тесты прошли, а реализацию забыл удалить.

2020-09-29 13:14 UTC, incubos requested changes
Нужно освежить зависимость от RocksDB

2020-09-29 13:14 UTC, incubos commented on build.gradle.kts
> +    compile( "org.rocksdb:rocksdbjni:5.15.10")
Подозрительно, что такая старая версия. Давайте свежую возьмём?

2020-09-29 18:07 UTC, IvanovAndrey commented
На счет не подошедшей мне дефолтной реализации метода put в DAO: я его убрал и у меня неожиданно упало несколько тестов. Так-как приближался дэдлайн - я решил вернуть свой, с которым тесты проходят. Если принципиально использовать дефолтный, то я бы, с вашего позволения, разобрался с этим к следующему дэдлайну

2020-09-30 12:13 UTC, incubos commented
Самая свежая версия `rocksdbjni` **6.11.4**: https://search.maven.org/search?q=rocksdbjni

2020-09-30 12:16 UTC, incubos commented
Как интерпретировать `delete_cpu.svg`? Прикладного кода там вообще не видно. Либо не было нагрузки, либо это не то приложение.

2020-09-30 12:17 UTC, incubos reviewed
> Как интерпретировать `delete_cpu.svg`? Прикладного кода там вообще не видно. Либо не было нагрузки, либо это не то приложение.

В `get_cpu2.svg` то же самое.

2020-09-30 12:17 UTC, incubos commented on HighloadLog
> +  Non-2xx or 3xx responses: 79995
Стрелять `GET`ами нужно после стрельбы `PUT`ами, иначе БД пустая и **ни одного `200 ОК`**

2020-09-30 13:05 UTC, incubos requested changes
Есть замечания по нагрузочному тестированию и профилированию, кроме того, нет анализа результатов. Будете исправлять или 5 из 10 баллов за текущий статус?

2020-09-30 16:39 UTC, IvanovAndrey commented
> Есть нагрузочному тестированию и профилированию, кроме того, нет анализа результатов. Будете исправлять или 5 из 10 баллов за текущий статус?

Если исправления можно сдать вместе со следующим заданием (Имеется в виду до 7 октября), то буду

2020-10-01 09:45 UTC, incubos commented
> > Есть нагрузочному тестированию и профилированию, кроме того, нет анализа результатов. Будете исправлять или 5 из 10 баллов за текущий статус?
> 
> Если исправления можно сдать вместе со следующим заданием (Имеется в виду до 7 октября), то буду

Можно сдать **до** сдачи следующего задания. Каждый этап -- отдельный pull request (иначе всё превращается в кашу).

2020-10-06 20:24 UTC, IvanovAndrey commented
У меня возникли некоторые проблемы с Трэвисом, поэтому пришлось откатываться до рабочей версии. Теперь кодклимат бот чет не может проверить, но смею надеяться что там все хорошо, потому что ничего особо не менялось. 

Добавил нормальное профилирование, потому как в прошлый раз профилировал несчастного спокойно работающего демона, а не сервер ( во время cpu).  За это стыдно конечно.

Собрал все результаты в md файл [тут](https://github.com/IvanovAndrey/2020-highload-dht/blob/task1/async/report_task1.md)

2020-10-06 21:30 UTC, incubos requested changes
Результаты выглядят адекватно, но:
- В нагрузке `GET` лежит flamegraph от `cpu` профилирования `PUT`, а не от `GET`
- Не хватает краткой интерпретации результатов -- что вы сами видите в этих таймингах/графиках?
- Наконец, непонятно, кому проставлять баллы в ведомости -- Иванова Андрея на polis.mail.ru найти не могу

2020-10-07 14:10 UTC, IvanovAndrey commented
"В нагрузке GET лежит flamegraph от cpu профилирования PUT, а не от GET" - перепутал Url, поправил
"Не хватает краткой интерпретации результатов -- что вы сами видите в этих таймингах/графиках?" - очевидно в дэдлайн с этим я не уложился, но на будущее - какого рода информацию надо писать? 
"Наконец, непонятно, кому проставлять баллы в ведомости -- Иванова Андрея на polis.mail.ru найти не могу" - [Вот](https://polis.mail.ru/profile/and.ivanov/)  мой лк, я что-то не так сделал на сайте технополиса? Вроде в успеваемости курс отображается

2020-10-09 06:53 UTC, incubos commented
Спасибо, я был невнимателен в ведомости, нашёл вас.
В анализе результатов ожидаются рассуждения о том, на что тратятся ресурсы, а также возможные оптимизации.
Принято.

2020-10-09 06:53 UTC, closed without merging