Hw7
polis-mail-ru/2020-highload-dht pull request #152
Opened 2020-11-15 09:45 UTC by re1nex

2020-11-22 16:32 UTC, vaddya requested changes

2020-11-22 16:32 UTC, vaddya commented on src/main/java/ru/mail/polis/service/re1nex/ChunkCreator.java
> +        System.arraycopy(dataLen, 0, answer, 0, cur);
Лишних аллокаций, конечно, нет, но ошибиться в таком коде слишком просто. Давай заиспользуем `ByteBuffer.wrap` и его `put` методы?

2020-11-22 16:32 UTC, vaddya commented on src/main/java/ru/mail/polis/service/re1nex/RangeStream.java
> +        response.addHeader("Transfer-Encoding: chunked");
`private static final`?

2020-11-22 16:32 UTC, vaddya commented on src/main/java/ru/mail/polis/service/re1nex/FullAsyncTopologyReplicaService.java
> +        executeTask(() -> {
Может сделаем обработку параметров на потоке-селекторе? Внутри задачи оставим только запрос к ДАО и стриминг.

2020-11-22 18:54 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/ChunkCreator.java
> +        System.arraycopy(dataLen, 0, answer, 0, cur);
Хорошо , поменяю ,просто казалось, что это самый быстрый вариант

2020-11-22 18:54 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/RangeStream.java
> +        response.addHeader("Transfer-Encoding: chunked");
Поправлю

2020-11-22 18:55 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/FullAsyncTopologyReplicaService.java
> +        executeTask(() -> {
Хорошо

2020-11-25 21:12 UTC, vaddya approved these changes
Принято.

2020-11-25 21:12 UTC, vaddya commented on src/main/java/ru/mail/polis/service/re1nex/ChunkCreator.java
> +        return ByteBufferUtils.byteBufferToByte(
Можно делать еще меньше аллокаций, выбрав одно из:
- `buffer = ByteBuffer.allocate` + puts + `return buffer.array()`
- `bytes = new byte[len]` + `ByteBuffer.wrap(bytes)` + puts + `retrurn bytes`

2020-11-25 21:12 UTC, closed without merging