Stage7
polis-mail-ru/2020-highload-dht pull request #154
Opened 2020-11-15 18:46 UTC by KateMoreva

2020-11-21 11:52 UTC, vaddya requested changes

2020-11-21 11:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/StreamingSession.java
> +    private byte[] makeChunk(final Record record) {
Как-то многовато аллокаций получается, по идее можно обойтись без `toByteArray` совсем. Попробуйте не делать `ByteBuffer.allocate`, а посмотреть в сторону `ByteBuffer.wrap`. И распологайте, пожалуйста, `put` на новой строке, проще читаться будет.

2020-11-21 11:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/StreamingSession.java
> +    private static final byte[] EOC = "0\r\n\r\n".getBytes(StandardCharsets.UTF_8);
Не `EOF`? Обычно это end of file. Или как-то по другому зашифровали?

2020-11-21 11:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            log.error("Request with incorrect parameters on /v0/entities");
Может залогировать параметры?

2020-11-21 11:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final boolean futuresWereCanceled = CompletableFuture.supplyAsync(() -> {
Нужна ли тут фьюча? Кажется, что `executor.execute` ничем не хуже в данном случае.

2020-11-22 07:38 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/StreamingSession.java
> +    private byte[] makeChunk(final Record record) {
Поняла, исправила.

2020-11-22 07:40 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MyRequestHelper.java
> +        final boolean futuresWereCanceled = CompletableFuture.supplyAsync(() -> {
Фьюча не обязательна, теперь использую просто executor.

2020-11-22 07:48 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            log.error("Request with incorrect parameters on /v0/entities");
Да, залогировала.

2020-11-22 07:50 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/StreamingSession.java
> +    private static final byte[] EOC = "0\r\n\r\n".getBytes(StandardCharsets.UTF_8);
Думала про end of chunk, переименовала.

2020-11-22 14:37 UTC, vaddya approved these changes
Принято.

2020-11-22 14:37 UTC, closed without merging