Stage #7
polis-mail-ru/2020-highload-dht pull request #155
Opened 2020-11-15 21:01 UTC by ScriptoMax

Использована кластерная конфигурация с синхронным HTTP-клиентом на основе one-nio (результат этапа №5)

2020-11-22 16:02 UTC, vaddya requested changes

2020-11-22 21:02 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +    private static final String CRLF = "\r\n";
устранено

2020-11-22 21:05 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +    Iterator<Record> it;
однозначно, собственный глаз расхождений не подметил. Устранено

2020-11-22 21:05 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +        response.addHeader("Transfer-Encoding: chunked");
устранено

2020-11-22 21:12 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +     * @param recordString - String-formatted combination of record ID and value content
согласен - некоторое время экспериментировал со строковыми вариантами хранения, а придя к выводу об их нецелесообразности, внёс изменения видимо везде, кроме "строковых" имен. В действительности же подразумеваются вычисления, связанные с определением размера чанка. Устранено

2020-11-22 21:14 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +            final int recordString = id.length + LF.length() + value.length;
устранено, ответная реплика к предыдущему замечанию охватывает и данное

2020-11-22 21:16 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +        chunkBuf.put(recordBytes);
безусловно, выглядит как по-настоящему чистый код. Повторил, устранил

2020-11-22 21:19 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +            execChunkWrite(id, value, chunkSize, base16RecordString);
Создал метод, содержащий все релевантные контексту части кода. Не уверен, что обошлось без недочётов и на сей раз, но к полуночи всё выглядит так, как будто устранено

2020-11-22 21:26 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +        final String start = req.getParameter("start=");
Да, снова нечего возразить по факту. Воспроизвёл рекомендованные изменения, за исключением приведения ```required``` в параметре ```end``` - при соблюдении этого условия валится тест ```triple``` в ```SingleRangeTest``` (что логично с учётом случая, предполагающего проверку со значением аргумента ```null```)

2020-11-22 21:26 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +                endBuf);
устранено

2020-11-22 21:35 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +        final Iterator<Record> records = dao.range(
кажется осилил добавлением вспомогательного метода и вызовом через лямбду в ```execute```. Возможно, вопросы вызовет логика (либо, напротив, алогичность) решения для перехвата исключения - тут сделал по аналогии с ```runAsyncHandler```, споров из-за реализации которого пока не возникало

2020-11-22 21:37 UTC, ScriptoMax commented
текущие замечания устранены, добавлены отвечающие логике правок фрагменты кода

2020-11-25 21:08 UTC, vaddya requested changes
Минорные замечания остались.

2020-11-25 21:08 UTC, vaddya commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +    private static final byte[] bytesOfCRLF = "\r\n".getBytes(Charset.defaultCharset());
В Java принято называть константы `EXACTLY_LIKE_THIS`.

2020-11-25 21:08 UTC, vaddya commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +        exec.execute(() -> {
Здесь может прилететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа.

2020-11-25 21:08 UTC, vaddya commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +        exec.execute(() -> {
Здесь может прилететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа.

2020-11-25 21:08 UTC, vaddya commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +                                    final String start,
Поехало немного форматирование.

2020-11-26 03:52 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/ChunkStreamingSession.java
> +    private static final byte[] bytesOfCRLF = "\r\n".getBytes(Charset.defaultCharset());
так и есть, исправил

2020-11-26 03:53 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +        exec.execute(() -> {
добавил блок ```catch```

2020-11-26 03:53 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +        exec.execute(() -> {
добавил блок ```catch```

2020-11-26 03:53 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/RepliServiceImpl.java
> +                                    final String start,
исправил

2020-11-26 03:58 UTC, ScriptoMax commented
замечания 2-го ревью устранены, обновления доступны для проверки

2020-11-26 07:54 UTC, vaddya approved these changes
Принято.

2020-11-26 07:54 UTC, closed without merging