Task 7
polis-mail-ru/2020-highload-dht pull request #157
Opened 2020-11-15 22:49 UTC by nik27090

2020-11-18 13:55 UTC, incubos requested changes
Есть предложение соптимизировать работу с памятью.

2020-11-18 13:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/nik27090/ChunkIterator.java
> +        final byte[] data = toByteArray(ByteBuffer.allocate(dataLength).put(key).put(SEP).put(value).position(0));
Это явно лишняя аллокация и копирование данных. Давайте сразу складывать всё в результирующий `ByteBuffer`.
Лишние аллокации и копирование -- бич высоконагруженных систем.

2020-11-18 13:55 UTC, incubos commented on src/test/java/ru/mail/polis/dao/ConcurrentTest.java
> +            final AtomicInteger matches = new AtomicInteger();
Зачем это изменение? Обычно просматривают diff перед коммитом.

2020-11-23 16:08 UTC, incubos requested changes
Ждать исправлений или за часть баллов?

2020-11-24 09:32 UTC, nik27090 commented on src/test/java/ru/mail/polis/dao/ConcurrentTest.java
> +            final AtomicInteger matches = new AtomicInteger();
Случайнно подтянул старый коммит

2020-11-24 09:32 UTC, nik27090 commented
> Ждать исправлений или за часть баллов?

Да, исправления будут

2020-11-24 15:55 UTC, nik27090 commented on src/test/java/ru/mail/polis/dao/ConcurrentTest.java
> +            final AtomicInteger matches = new AtomicInteger();
fixed

2020-11-24 15:55 UTC, nik27090 commented on src/main/java/ru/mail/polis/service/nik27090/ChunkIterator.java
> +        final byte[] data = toByteArray(ByteBuffer.allocate(dataLength).put(key).put(SEP).put(value).position(0));
fixed

2020-11-29 10:59 UTC, incubos commented
Принято.

2020-11-29 10:59 UTC, closed without merging