Stage7
polis-mail-ru/2020-highload-dht pull request #158
Opened 2020-11-16 08:45 UTC by gogun

2020-11-18 14:08 UTC, incubos requested changes
Надо пооптимизировать работу с памятью.

2020-11-18 14:08 UTC, incubos commented on src/main/java/ru/mail/polis/service/gogun/StreamingSession.java
> +        final byte[] data = new byte[key.length + LF.length + value.length];
Нужно избавиться от аллокации лишнего массива и лишнего копирования данных -- это бич высоконагруженных систем. Пишите всё сразу в результирующий `ByteBuffer`.

2020-11-18 14:08 UTC, incubos commented on src/test/java/ru/mail/polis/service/ShardingTest.java
> -import static org.junit.jupiter.api.Assertions.*;
Зачем это изменение?

2020-11-18 14:35 UTC, gogun commented on src/test/java/ru/mail/polis/service/ShardingTest.java
> -import static org.junit.jupiter.api.Assertions.*;
случайность, уже исправленная в 6м этапе)

2020-11-19 17:41 UTC, incubos commented
Принято.

2020-11-19 17:41 UTC, closed without merging