Yandex.Tank
polis-mail-ru/2020-highload-dht pull request #159
Opened 2020-11-16 17:28 UTC by IvanovAndrey

2020-11-16 21:34 UTC, IvanovAndrey commented
Забыл указать на [отчёт](https://github.com/IvanovAndrey/2020-highload-dht/blob/YandexTank/YandexTanl/report.md)

2020-11-17 10:42 UTC, incubos requested changes
Проделана качественная работа, но есть ряд замечаний/вопросов.

2020-11-17 10:42 UTC, incubos commented on YandexTanl/report.md
> +Вот тут уже более понятная мне картина. Сервер тоже справился, но перезапись очевидно более долгая операция. чем просто запись, что и видно на графике.
Почему "перезапись очевидно более долгая операция"? Мы же просто пишем в memtable.

2020-11-17 10:42 UTC, incubos commented on YandexTanl/report.md
> +[Результат пробной стрельбы](https://overload.yandex.net/350578#tab=test_data&tags=&plot_groups=main&machines=&metrics=&slider_start=1605523782&slider_end=1605523850&compress_ratio=1
Тут можно было и на 800 стрелять, ну да ладно.

2020-11-17 10:42 UTC, incubos commented on YandexTanl/report.md
> +Тут у меня есть теория почему так. Вроде как для доступа к конечной записи в ноде нужно проитерироваться от первой и при распределении неравномерном, а как тут сложность операции
Можете раскрыть мысль? Я не совсем понял гипотезу.

2020-11-17 10:42 UTC, incubos commented on YandexTanl/report.md
> +Подводя итог можно сказать что утилита в освоении не сложнее Wrk, особенно с лекцией в виде пример аперед глазами. Но в ней сильно более наглядно видно какие именно запросы приходят, и это большой пл
Хороший отчёт, но не хватает сравнительного анализа перцентилей **разных** типов запросов на **разных** этапах -- см. вкладки Distributions и Tables.

2020-11-17 17:05 UTC, IvanovAndrey commented on YandexTanl/report.md
> +Тут у меня есть теория почему так. Вроде как для доступа к конечной записи в ноде нужно проитерироваться от первой и при распределении неравномерном, а как тут сложность операции
Я имел в виду, что для получения самой старой записи потребуется меньше времени, чем для получения самой новой. Разница по моему мнению в том, что надо проитерироваться  к самой новой, чтобы затем ее вернуть. 
В первом случае с гетами распределение равномерное и получается среднее время ответа. Во втором случае 90 процентов запросов хотят получить новые записи (10 процентов самых новых из всех записей). И из-за этого немного увеличивается среднее время ответа сервера.

2020-11-17 17:07 UTC, IvanovAndrey commented on YandexTanl/report.md
> +Вот тут уже более понятная мне картина. Сервер тоже справился, но перезапись очевидно более долгая операция. чем просто запись, что и видно на графике.
Я имею в виду большое количество пут запросов с уникальными ключами отличается по времени от большого количества пут-запросов-перезаписей. Скорее всего потому, что тратится дополнительное время на удаление устаревших записей.

2020-11-17 17:40 UTC, IvanovAndrey commented on YandexTanl/report.md
> +Подводя итог можно сказать что утилита в освоении не сложнее Wrk, особенно с лекцией в виде пример аперед глазами. Но в ней сильно более наглядно видно какие именно запросы приходят, и это большой пл
Добавил

2020-11-18 13:12 UTC, incubos commented on YandexTanl/report.md
> +Вот тут уже более понятная мне картина. Сервер тоже справился, но перезапись очевидно более долгая операция. чем просто запись, что и видно на графике.
Может, профильнём под нагрузкой?

2020-11-18 13:13 UTC, incubos commented on YandexTanl/report.md
> +Тут у меня есть теория почему так. Вроде как для доступа к конечной записи в ноде нужно проитерироваться от первой и при распределении неравномерном, а как тут сложность операции
Поиск данных по ключу работает не за линейный скан, а как минимум за логарифм.
Вообще, ожидалось, что во втором случае время ответа будет меньше, потому что выше кеш хит, но точно не больше. Может, профильнём под нагрузкой?

2020-11-18 13:15 UTC, incubos requested changes
Пока гипотезы выглядят не очень убедительно. Будете профилировать под нагрузкой и сравнивать профили?

2020-11-18 13:20 UTC, IvanovAndrey commented
> Пока гипотезы выглядят не очень убедительно. Будете профилировать под нагрузкой и сравнивать профили?

Давайте попробую, время еще есть вроде как.

Только, с Вашего позволения, займусь этим когда справлюсь с рандеву хешированием и тестами к нему.
Получается надо сделать те же стрельбы, но около 800 rps и сравнить что вышло?

2020-11-19 17:45 UTC, incubos commented
> > Пока гипотезы выглядят не очень убедительно. Будете профилировать под нагрузкой и сравнивать профили?
> 
> Давайте попробую, время еще есть вроде как.
> 
> Только, с Вашего позволения, займусь этим когда справлюсь с рандеву хешированием и тестами к нему.
> Получается надо сделать те же стрельбы, но около 800 rps и сравнить что вышло?

Давайте на той же нагрузке, что и была, стрельнем снова (на разных типах запросов) и попрофилируем после минутного прогрева (хотя бы cpu и alloc), а затем сравним профили (на разных типах запросов) и попробуем понять, чем они отличаются.

2020-11-19 17:45 UTC, incubos requested changes
Ждём результатов профилирования.

2020-11-20 20:10 UTC, IvanovAndrey commented
В [отче](https://github.com/IvanovAndrey/2020-highload-dht/blob/YandexTank/YandexTanl/report.md)т добавил результаты профилирования, небольшой их анализ. Пересмотрев еще раз все, пришел к новым выводам и изложил их в последнем пункте. Они немного противоречат предыдущим. В какой-то из двух раз я точно занимался натягиванием совы на глобус, надеюсь что в первый, а сейчас теории более близки к истине

2020-11-29 11:03 UTC, incubos commented
Принято.

2020-11-29 11:03 UTC, closed without merging