Stage7
polis-mail-ru/2020-highload-dht pull request #161
Opened 2020-11-17 08:35 UTC by mariarheon

2020-11-25 20:33 UTC, lamtev requested changes

2020-11-25 20:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +            }
Данное решение кардинально отличается от предложенного на лекции. И оно не учитывает, что за 1 раз может все не влезть. И никак не реагирует на события селектора о том, можно ли делать запись в сокет или нельзя. Стоит переделать подобно референсу с лекции: наследоваться от HttpSession и переопределять processWrite().

2020-11-25 20:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +        final var parsedRecord = Record.newFromRawValue(ByteBufferUtils.toArray(value));
Избыточное копирование при конвертации ByteBuffer -> byte[]. Этого можно избежать

2020-11-29 07:23 UTC, lamtev requested changes
Теперь хорошо. Осталось избавиться от лишних копирований/аллокаций

2020-11-29 07:23 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +            final byte[] newLine = new byte[]{'\r', '\n'};
такое в константу надо вынести и переиспользовать, чтобы не генерировать мусор

2020-11-29 07:23 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +            final byte[] keyBytes = ByteBufferUtils.toArray(key);
Тут происходит избыточное копирование при конвертации BB -> byte[]. Лучше в цикле по 1 байту из байтбуффера писать, тогда не будет лишних аллокаций

2020-11-29 07:23 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +            logger.info("Chunked response item: " + new String(res, StandardCharsets.UTF_8));
при логгировании стоит пользоваться плейсхолдерами вместо конкатенации

2020-11-29 07:23 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +        final byte[] res = "0\r\n\r\n".getBytes(StandardCharsets.UTF_8);
тоже вынести в константу стоит

2020-11-29 07:23 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +        logger.info("Closed chunked response item: " + new String(res, StandardCharsets.UTF_8));
аналогично

2020-12-06 13:33 UTC, lamtev approved these changes
Хорошо

2020-12-06 13:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +        logger.info(String.format("Closed chunked response item: %s",
по большому счету ничего не изменилось. речь была о плейсхолдерах в методах логгера: `info("Something: {}", value)`

2020-12-06 13:33 UTC, lamtev commented
Принято

2020-12-06 13:33 UTC, closed without merging

2020-12-06 13:34 UTC, mariarheon commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +        logger.info(String.format("Closed chunked response item: %s",
Поняла, спасибо