Task 7
polis-mail-ru/2020-highload-dht pull request #162
Opened 2020-11-17 12:44 UTC by s3ponia

2020-11-25 20:22 UTC, lamtev requested changes

2020-11-25 20:22 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingRecordValue.java
> +        final var value = Utility.fromByteBuffer(record.getValue());
Лишние копирования. Можно через ByteBuffer.put(ByteBuffer) сразу

2020-11-25 20:22 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingSession.java
> +            final byte[] chunk = new byte[chunkSize];
Можно уменьшить количество аллокаций. Код из StreamingRecordValue.value и этот можно объединить. 1 раз выделить массив нужной длины, завернуть в ByteBuf, заполнить

2020-11-25 20:22 UTC, lamtev commented on src/main/java/ru/mail/polis/util/MapIterator.java
> +public class MapIterator<T, U> implements Iterator<U> {
Особого смысла в MapIterator не видно. Хотя, бесспорно, красиво получилось.
Когда будет произведена оптимизация количества аллокация, то он совсем окажется не нужен

2020-11-26 17:30 UTC, s3ponia commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingSession.java
> +            final byte[] chunk = new byte[chunkSize];
Можно из StreamingRecordValue возвращать еще QueueItem, в котором бы записывались постепенно все нужные поля, но из-за того что нельзя просто так взять и вызвать на ByteBuffer array(), то без аллокаций не выйдет, хотя можно было бы если бы не интерфейс у сокета, который не принимает ByteBuffer или кодстайл) А так неприятно аллоцировать и копировать по несколько килобайт для каждого рекорда. В общем случае это может наверное доходить и до мегабайтов.

2020-11-26 17:53 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingSession.java
> +            final byte[] chunk = new byte[chunkSize];
Предлагалось сделать примерно вот так:
```java
static byte[] convertToChunk(final Record record) {
        final ByteBuffer key = record.getKey();
        final ByteBuffer val = record.getValue();
        final byte[] length = ...
        return ByteBuffer
                .wrap(new byte[result size])
                .put(length)
                .put(CRLF)
                .put(key))
                .put(LF)
                .put(value)
                .put(CRLF)
                .array();
}
```

То есть мы уже сразу знаем сколько байтов будет занимать результат. Выделяем ровно столько байтов. Заворачиваем в BB. Заполняем. Возвращаем

2020-11-26 17:57 UTC, lamtev requested changes

2020-11-26 17:57 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingRecordValue.java
> +        return record.getKey().limit() + 1 /* NEW LINE */ + record.getValue().limit();
проблема в том, что getKey и getValue возвращают новые объекты

2020-11-26 17:58 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingSession.java
> +            final byte[] chunk = new byte[chunkSize];
Примерно так и было сделано, посмотрел. Но остался момент с множественными вызовами getKey и getValue, которые создают новые объекты

2020-11-26 18:02 UTC, s3ponia commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingRecordValue.java
> +        return record.getKey().limit() + 1 /* NEW LINE */ + record.getValue().limit();
Разве? Он же возвращает asReadOnlyBuffer, который не делает никаких новых аллокаций, а шарит буффер с другим только делает его константным и невозможностью его изменить извне.

2020-11-26 18:05 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingRecordValue.java
> +        return record.getKey().limit() + 1 /* NEW LINE */ + record.getValue().limit();
можно посмотреть реализацию. там возвращаются новые объекты

2020-11-26 18:07 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingRecordValue.java
> +        return record.getKey().limit() + 1 /* NEW LINE */ + record.getValue().limit();
Хотя даже в реализацию можно не смотреть: в доке написано: "**Creates a new**, read-only buffer that shares this buffer's conent"

2020-11-26 18:19 UTC, s3ponia commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingRecordValue.java
> +        return record.getKey().limit() + 1 /* NEW LINE */ + record.getValue().limit();
Ну буффер то шарится) Так что там копируются только всякие оффсеты, марки и флаги. Это где-то выходит 29 байт на объект, не знаю насколько это критично, но исправил. Ну и вроде ситуация довольно тривиальная и JIT может это заоптимайзить и просто подставить лимит из буфера, который в рекорде хранится, но я не уверен.

2020-11-26 18:36 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingRecordValue.java
> +        return record.getKey().limit() + 1 /* NEW LINE */ + record.getValue().limit();
Буффер шарится, с этим никто не спорит. Но зачем генерировать лишний мусор, когда можно этого не делать?

2020-11-26 18:49 UTC, lamtev commented on src/main/java/ru/mail/polis/service/s3ponia/StreamingRecordValue.java
> +        return record.getKey().limit() + 1 /* NEW LINE */ + record.getValue().limit();
Особенно странно генерировать мусор в методе `size()`

2020-11-26 18:50 UTC, lamtev approved these changes

2020-11-26 18:50 UTC, lamtev commented
Принято

2020-11-26 18:50 UTC, closed without merging