Stage 7
polis-mail-ru/2020-highload-dht pull request #163
Opened 2020-11-17 13:21 UTC by Igor-Manikhin

2020-11-21 22:33 UTC, lamtev requested changes
В целом хорошо, но выполняются необязательные аллокации. Можно сделать более оптимально

2020-11-21 22:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return ByteConvertor.toArray(chunk);
Избыточная аллокация в toArray. Можно выделить byte[] нужного размера. Его завернуть в ByteBuf, дальше так же складывать в ByteBuf составляющие. И в результате все окажется в результирующем byte[]

2020-11-21 22:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return formChunk(new byte[0]);
new byte[0] можно вынести в константу, чтобы не аллоцировать каждый раз

2020-11-21 22:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +            final byte[] value = ByteConvertor.toArray(record.getValue());
Можно обойтись без данных аллокаций. А сразу в ByteBuf, в который завернут byte[] нужной длины, записывать ключ и значение через put

2020-11-21 22:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return formChunk(ByteConvertor.toArray(data));
Лишние аллокации. Можно оптимизировать

2020-11-22 12:31 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return ByteConvertor.toArray(chunk);
Исправлено.

2020-11-22 12:31 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return formChunk(new byte[0]);
Исправлено.

2020-11-22 12:31 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +            final byte[] value = ByteConvertor.toArray(record.getValue());
Исправлено.

2020-11-22 12:31 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return formChunk(ByteConvertor.toArray(data));
Исправлено.

2020-11-22 12:34 UTC, lamtev requested changes
Можно сделать еще немного получше

2020-11-22 12:34 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return chunk.array();
Стало лучше, но по идее можно всего 1 раз сделать byte[] нужного размера. Обернуть в ByteBuf. И записать в него все, что нужно. Сейчас это делается 2 раза

2020-11-22 13:29 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return chunk.array();
Исправлено. Исправил так как я понял, если я правильно понял вас.

2020-11-22 14:27 UTC, lamtev requested changes
Остались последние косметические моменты

2020-11-22 14:27 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +    private static final ByteBuffer END_CHUNK_DATA = ByteBuffer.wrap(new byte[0]);
вот это лишнее, было правильно и до этого

2020-11-22 14:27 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return formChunk();
можно просто перенести сюда тело метода formChunk, ведь больше нет использований. да и formChunk теперь как раз делает formEndChunk

2020-11-22 14:27 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
>          data.position(0);
это по идее не нужно

2020-11-22 14:27 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
>          chunk.position(0);
это по идее не нужно

2020-11-22 14:49 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
>          chunk.position(0);
речь о position(0), если что

2020-11-22 14:50 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +    private static final ByteBuffer END_CHUNK_DATA = ByteBuffer.wrap(new byte[0]);
Исправлено.

2020-11-22 14:50 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        return formChunk();
Исправлено.

2020-11-22 14:51 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
>          data.position(0);
Разве? Разрыв строки не нужен? Тесты тогда валятся. Не очень ожидаемые результат тогда получается)

2020-11-22 14:52 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
>          chunk.position(0);
Ок, сейчас исправлю.

2020-11-22 14:53 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
>          data.position(0);
комментарий же к строке с data.position(0);

2020-11-22 14:54 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
>          data.position(0);
Или тут тоже речь о position(0) ?

2020-11-22 14:58 UTC, lamtev approved these changes

2020-11-22 14:58 UTC, lamtev commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        chunk.put(END_CHUNK_DATA);
Точно нужно пустой byte[] записывать?)

2020-11-22 14:59 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamSession.java
> +        chunk.put(END_CHUNK_DATA);
Думаю что нет. Сейчас удалим)

2020-11-22 15:00 UTC, lamtev commented
Принято

2020-11-22 15:00 UTC, closed without merging

2020-11-22 15:01 UTC, Igor-Manikhin commented
Thanks.