Stage 7
polis-mail-ru/2020-highload-dht pull request #164
Opened 2020-11-17 16:29 UTC by JavaUnchained

За основу была взята реализация 5 этапа.

2020-11-25 20:09 UTC, lamtev requested changes

2020-11-25 20:09 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/ranges/StreamingSession.java
> +        final var value = BufferConverter.unfoldToBytes(currentRecord.getValue());
Избыточное копирование при конвертации ByteBuf -> byte[]

Есть ByteBuf.put(ByteBuf), которым можно воспользоваться

2020-11-26 15:58 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ranges/StreamingSession.java
> +        final var value = BufferConverter.unfoldToBytes(currentRecord.getValue());
Испрвил

2020-11-26 17:34 UTC, lamtev approved these changes

2020-11-26 17:34 UTC, lamtev commented
Принято

2020-11-26 17:34 UTC, closed without merging

2020-11-26 17:46 UTC, lamtev commented on src/main/java/ru/mail/polis/service/kovalkov/ranges/StreamingSession.java
> +                    .put(currentRecord.getValue())
Проглядел, что результаты getKey и getValue не кэшируются в локальную переменную, а вызываются дважды. поэтому все еще есть лишние аллокации.

решение уже зачтено, но прошу этот момент поправить

2020-11-26 18:03 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ranges/StreamingSession.java
> +                    .put(currentRecord.getValue())
Точно, я тоже не заметил что так написал. Исправил.