Bonus stage | Tank'n'Overload
polis-mail-ru/2020-highload-dht pull request #168
Opened 2020-11-20 17:51 UTC by ScriptoMax

- доп. задание по проведению тестов highload-сервера с использованием Яндекс.Overload и Яндекс.Танк 
- объект тестирования - узел кластера с реализацией клиента <em>one-nio</em> на основе результата этапа №5 
- аналитические комментарии и ссылки на статистику испытаний и приведены в [отчёте](https://github.com/ScriptoMax/2020-highload-dht/blob/extra_stage/resources/report.md)

2020-11-29 14:35 UTC, incubos requested changes
Есть замечания на будущее, не требующие исправления (см. генератор патронов), и просьба дополнить отчёт впечатлениями об инструменте.

2020-11-29 14:35 UTC, incubos commented on resources/report.md
> +Профиль нагрузки на ресурс процессора подтверждает дуализм операций, осуществлённых в ходе тестирования с соответствующим режимом нагрузки (в числе структурных компонент графа представлены вызовы обр
Я бы нагружал меньшей нагрузкой во всех стрельбах, поскольку заметно, что количество workerов почти везде регулярно достигает лимита, т.е. танк периодически не справлялся с обеспечением заданного rps, но предлагаю уже не перестреливать (потому что HTTP/сетевых ошибок не было).
Можете добавить в выводы собственное впечатление от использования инструмента? Что представляло сложность? Что кажется полезным?

2020-11-29 14:35 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/TankAmmoQueries.java
> +            if (ThreadLocalRandom.current().nextInt(10) == 1) {
Имеет смысл вынести долю перезаписываемых ключей в аргумент функции. Здесь 10%, если я правильно всё понял?

2020-11-29 14:35 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/TankAmmoQueries.java
> +            if (position == 0) {
Здесь реализовано кусочное распределение, верно?

- 10% первая половина ключей
- 10% третья четверть
- 80% случайный ключ из последней четверти

Можно было бы использовать `nextGaussian()` и выбирать ключи с помощью нормального распределения со средним в "текущий момент".

2020-11-30 20:38 UTC, ScriptoMax commented on resources/report.md
> +Профиль нагрузки на ресурс процессора подтверждает дуализм операций, осуществлённых в ходе тестирования с соответствующим режимом нагрузки (в числе структурных компонент графа представлены вызовы обр
Спасибо за рекомендацию по выбору нагрузки - понял, что не вписался в ресурс воркеров на узле только во время подведения итогов, хотя и следовал методике расчёта для <em>rps</em> с константным значением. Впрочем, наиболее правдоподобной выглядит ошибка при нахождении уровня разладки в режиме линейного роста числа запросов. <br/>
Субъективное мнение об инструментарии привёл в нижней секции отчёта.

2020-11-30 20:41 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/TankAmmoQueries.java
> +            if (ThreadLocalRandom.current().nextInt(10) == 1) {
Совершенно верно, в соответствии с заданием удельный вес обновляемых записей не превосходит 10%. Внёс изменения, в текущей версии доля этого сегмента определяется во время ввода консольной команды

2020-11-30 20:49 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/TankAmmoQueries.java
> +            if (position == 0) {
Так и есть, в первоначальном варианте реализовано кусочное распределение. Затеял решение с нормальным, но не уверен, что итог и ожидания совпали.

2020-12-02 13:34 UTC, incubos commented
Спасибо за хорошую работу. Принято.

2020-12-02 13:34 UTC, closed without merging