Read repair bonus
polis-mail-ru/2020-highload-dht pull request #169
Opened 2020-11-21 10:25 UTC by re1nex

2020-11-29 14:43 UTC, incubos commented
`tenReaderWriterManyRecords()` падает на [Travis](https://travis-ci.com/github/polis-mail-ru/2020-highload-dht/builds/205110638).

2020-11-29 15:36 UTC, incubos requested changes
Добротная реализация, но не хватает ещё одного теста и есть мелкие замечания по коду.

2020-11-29 15:36 UTC, incubos commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new FullAsyncTopologyReplicaService(port,
Почему `port` не с новой строки? :)

2020-11-29 15:36 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/MergeUtils.java
> +        int numResponses = 0;
Можно убрать эту переменную и использовать `responses.size()`, верно?

2020-11-29 15:36 UTC, incubos commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +    void waitForRepair() throws Exception {
Зачем это? У вас же read repair выполняется при формировании ответа.

2020-11-29 15:36 UTC, incubos commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +}
Не хватает теста с пропущенной **перезаписью** значения и распространением последней версии благодаря механизму read repair.

2020-11-29 16:33 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    Iterator<Record> iterator(@NotNull final ByteBuffer from) throws IOException;
Хорошо , уберу

2020-11-29 16:33 UTC, re1nex commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new FullAsyncTopologyReplicaService(port,
Поправлю

2020-11-29 16:34 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/MergeUtils.java
> +        int numResponses = 0;
Поправлю

2020-11-29 16:35 UTC, re1nex commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +    void waitForRepair() throws Exception {
Да , но просто там ведь асинхронная отправка исправлений на ноды, решил на всякий случай добавить

2020-11-29 16:35 UTC, re1nex commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +}
Хорошо, добавлю

2020-11-29 20:04 UTC, re1nex commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +    void waitForRepair() throws Exception {
хотя я кажется понял, что оно не должно быть асинхронным , т.к. могут возникнуть неправильные восстановления потом

2020-12-02 13:41 UTC, incubos commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +    void waitForRepair() throws Exception {
Асинхронность -- это норм, но если я правильно понял текущее решение, вы не возвращаете ответ, пока не закончится repair, т.е. ждать чего-то смысла вроде как нет.
Почему могут возникнуть неправильные исправления, если вы передаёте оригинальный `timestamp`?

2020-12-02 13:48 UTC, incubos commented
Принято.

2020-12-02 13:48 UTC, closed without merging