Task 1
polis-mail-ru/2020-highload-dht pull request #17
Opened 2020-09-28 22:08 UTC by PolinaShneider

2020-09-29 08:44 UTC, incubos requested changes
Стрельбы проводились некорректными запросами -- см. `Non-2xx or 3xx responses` в выводе `wrk`. Обстреливать нужно скриптом, который генерит `PUT` запросы, а затем скриптом, который генерит `GET` запросы.
В результатах профилирования CPU половину занимает JIT компилятор JVM (процесс не прогрет, профилировать нужно после прогрева), вторую половину -- `LoggerFactory.getLogger()`, что странно.
В результатах выделения памяти всё занимает `Logger`, что тоже странно (либо неудачный момент, либо его выключить).
Кстати, чем профилировали? При какой нагрузке? Сколько времени?
Нужен анализ результатов профилирования.

2020-09-29 08:44 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOImpl.java
> +    public ByteBuffer get(@NotNull final ByteBuffer key) throws IOException {
Чем default реализация не подошла?

2020-09-29 08:44 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOImpl.java
> +        RocksDB.loadLibrary();
Зачем это здесь, если имеется static инициализатор?

2020-09-29 08:44 UTC, incubos commented on src/main/java/ru/mail/polis/service/Service.java
> - * <p>
Зачем удалять JavaDoc?

2020-09-29 08:44 UTC, incubos commented on src/main/java/ru/mail/polis/service/ServiceImpl.java
> +        } catch (NoSuchElementException | IOException ex) {
`IOException` это не `NOT_FOUND`. В случае ошибок, будет возвращаться код `404`, а не `500`, что неправильно.

2020-09-29 12:04 UTC, incubos commented on src/main/java/ru/mail/polis/dao/RecordIterator.java
> +            throw new IllegalStateException("End of file");
Здесь по контракту `Iterator` нужно кидать `NoSuchElementException` -- см. JavaDoc

2020-09-29 13:15 UTC, incubos requested changes
Нужно использовать свежую версию RocksDB

2020-09-29 13:15 UTC, incubos commented on build.gradle.kts
> +    compile("org.rocksdb", "rocksdbjni", "6.2.2")
Почему такая старая версия? Нужно освежить.

2020-09-29 17:08 UTC, PolinaShneider commented on src/main/java/ru/mail/polis/dao/DAOImpl.java
> +    public ByteBuffer get(@NotNull final ByteBuffer key) throws IOException {
![image](https://user-images.githubusercontent.com/15448200/94590308-29374900-028f-11eb-83d8-082cca18f676.png)
Она возвращает `null`, если элемент не найден. А нам требуется выбрасывать исключение `NoSuchElementException`,  поэтому написана дополнительная обертка

2020-09-29 19:33 UTC, PolinaShneider commented
Добавила [результаты](https://github.com/PolinaShneider/2020-highload-dht/blob/task_1/docs/Task1.md) профилирования

2020-09-30 12:04 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOImpl.java
> +    public ByteBuffer get(@NotNull final ByteBuffer key) throws IOException {
Это вы правильно говорите, но я про `default` реализацию интерфейса `DAO`, который вы реализуете.

2020-09-30 12:05 UTC, incubos commented
Последняя версия `rocksdbjni` -- **6.11.4**: https://search.maven.org/search?q=a:rocksdbjni

2020-09-30 12:11 UTC, incubos requested changes
RocksDB всё ещё не самый последний. Есть замечания к стрельбам `GET`ами.
Будете исправлять или 5 из 10 баллов за этот этап?

2020-09-30 12:11 UTC, incubos commented on docs/Task1.md
> +![wrk get](assets/wrk_get.png)
Здесь `-R` задран до небес -- `wrk` не может обеспечить такую нагрузку, нужно выбирать реалистичное значение, например, 20000.
Все 682136 коды ответов **не 200 ОК** -- либо стреляли по пустой БД, либо использовали ID несуществующих ключей.
Интерпретация результатов профилирования по делу.

2020-09-30 14:42 UTC, PolinaShneider commented
Параметры wrk поменяла, результаты профилирования обновила

2020-10-01 09:49 UTC, incubos requested changes
Принято, но не могу найти вас в ведомости на polis.mail.ru -- вы регистрировались под другими именем?

2020-10-01 19:56 UTC, PolinaShneider commented
@incubos мое настоящее ФИ — Шурыгина Наталья. На polis.mail.ru этот гитхаб указывала

2020-10-01 20:34 UTC, closed without merging