Consistent hashing topology test
polis-mail-ru/2020-highload-dht pull request #170
Opened 2020-11-21 16:56 UTC by re1nex

2020-11-30 20:24 UTC, vaddya requested changes
Неплохое тестирование равномерности распределения ключей, но есть несколько пожеланий:

1. Вы проверяете распределение ключей для `primaryFor`, то есть без реплик. Неплохо бы проверить и то, как работает распределение ключей по нескольким нодам через метод `severalNodesForKey`.

2. Если вы помните, то причина, по которой мы используем более сложные и затратные Rendezvous и Consistent hashing, состоит в том, что мы можем относительно безболезненно менять кластер (добавлять и удалять ноды), т.к. при этом у нас не происходит полная миграция ключей, как в случае топологии на основе взятия остатка от деления на число нод. Это тоже нужно проверить.

2020-11-30 20:24 UTC, vaddya commented on src/test/java/ru/mail/polis/service/HashTopologyTest.java
> +    private static final float delta = 0.5f;
`DELTA`?

2020-11-30 20:24 UTC, vaddya commented on src/test/java/ru/mail/polis/service/HashTopologyTest.java
> +        for (final String node : nodes) {
В целом, наверное, хватило бы и тестирования для одной ноды.

2020-11-30 20:24 UTC, vaddya commented on src/test/java/ru/mail/polis/service/HashTopologyTest.java
> +            for (int i = -NUM_ELEM; i < NUM_ELEM; i++) {
Я не очень понял этого усложнения с отзеркаливанием промежутка на `[-NUM_ELEM, 0)`, кажется простого `[0, NUM_ELEM)` вполне бы хватило.

2020-12-01 17:24 UTC, re1nex commented on src/test/java/ru/mail/polis/service/HashTopologyTest.java
> +            for (int i = -NUM_ELEM; i < NUM_ELEM; i++) {
Уберу

2020-12-01 17:25 UTC, re1nex commented on src/test/java/ru/mail/polis/service/HashTopologyTest.java
> +        for (final String node : nodes) {
Хорошо, уберу , просто во всех тестах так делаем

2020-12-01 17:25 UTC, re1nex commented on src/test/java/ru/mail/polis/service/HashTopologyTest.java
> +    private static final float delta = 0.5f;
Поправлю

2020-12-11 11:06 UTC, vaddya commented
Any updates?

2020-12-15 11:42 UTC, vaddya approved these changes
Принято.

2020-12-15 11:42 UTC, closed without merging