Stage 8. Rendezvous test
polis-mail-ru/2020-highload-dht pull request #171
Opened 2020-11-22 16:24 UTC by JavaUnchained

Тест находится [тут](https://github.com/JavaUnchained/2020-highload-dht/blob/Stage-8/src/test/java/ru/mail/polis/RendezvousHashingTest.java). В тесте смотрим что ключи в нодах распределяются в пределах погрешности в 5%. 

Тест прогоняется для кластера из 3, 5, 8, 10, 20, 100 нод. Для каждого из кластеров метод репликации вызывается 1 млн раз.

Реализация рандеву была проверена на этапе 4 для idenitifyByKey, по этому пришлось дописывать логику под replicasFor. 

p.s В прошлом ревью мы разделяли нахождение хешей ( хеши нод - конструктор, хеш ключа в identifyByKey). В результате тестирования выяснилось что данный подход неверен, так как он нарушает лавинный эффект хеш-функций и нарушает равномерность распределения. Поэтому было принято вернутся обратно к подсчёту в одном месте.

2020-11-26 17:58 UTC, JavaUnchained commented
Переписал replicsFor убрав использование TreeMap, и коллекций в целом, сортировок как таковых теперь тоже нет.

2020-11-28 23:32 UTC, JavaUnchained commented
Добавил тест, который проверяет, что при рандеву хешировании не происходит полной миграции ключей.

2020-11-30 21:04 UTC, vaddya requested changes
Вроде кейсы протестированы, но есть ряд пожеланий по реализации.

2020-11-30 21:04 UTC, vaddya commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        return random.ints(size-1, MIN_PORT, MAX_PORT - 1).mapToObj(i -> URL + i).collect(Collectors.toSet());
Лучше разносить такую длинную цепочку вызовов на несколько строк.

2020-11-30 21:04 UTC, vaddya commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +                .filter(i -> i > avg + avg * ERR || i < avg - avg * ERR).collect(Collectors.toList());
Можно `anyMatch` использовать.

2020-12-03 06:20 UTC, JavaUnchained commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +    private static boolean isEquitableDistribution(@NotNull final Multiset<String> resultIdentify,
resultIdentify осталось и забылось от тестирования identifyByKey

2020-12-03 06:30 UTC, JavaUnchained commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +                .filter(i -> i > avg + avg * ERR || i < avg - avg * ERR).collect(Collectors.toList());
Да, это и правда лучше. Заменил на noneMatch

2020-12-03 07:29 UTC, JavaUnchained commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +            sumOfDeference = before.count(node) + after.count(node);
Да что-то я тут не то сделал. Исправил. Тут я хотел получить сумма различий между топологией до и после.

2020-12-03 07:35 UTC, JavaUnchained commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +            countOFReplicas += replicas[i];
Оказалось что да, так и есть. Исправил.

2020-12-03 07:35 UTC, JavaUnchained commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        long countOFReplicas = 0;
Его больше нет

2020-12-03 07:39 UTC, JavaUnchained commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        final int[] replicas = random.ints(COUNT_OF_KEYS, 1, (int) Math.ceil(allNodes.size() * 0.75) + 1).toArray();
Ну можно сделать маленький метод с switch и массивом, элемент массива количество нод,  а значение - кворум. Или же можно добавить в провайдер теста второе значение - кворум. Думаю второй вариант лучше. Вечером доделаю

2020-12-03 08:34 UTC, vaddya commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        final int[] replicas = random.ints(COUNT_OF_KEYS, 1, (int) Math.ceil(allNodes.size() * 0.75) + 1).toArray();
У нас есть число нод, даввайте просто детерминировано найдем кворум (N / 2 + 1) и будем использовать это число.

2020-12-03 21:12 UTC, vaddya requested changes

2020-12-03 21:12 UTC, vaddya commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        assertTrue(compareOwners(ownersBeforeChange, ownersAfterChange, newNode, topologyOld.nodeCount()));
А мы разве проверяем таким способом устойчивость к изменениям?
Например, было:
```
key1 -> node1
key2 -> node2
key3 -> node1
key4 -> node2
```
Стало после добавления `node3`:
```
key1 -> node2
key2 -> node1
key3 -> node3
key4 -> node1
```
У нас переехали все (!) ключи, при этом ключи +- равномерно распределены. Но полная миграция ключей -- это то, чего мы и хотим избежать, когда используем консистент/рандеву хэшинг.

Проще это проверить с `REPLICAS = 1`. Взять старую и новую топологию, и на рандомных ключах проверить, для скольких ключей отличается нода. Это число должно быть примерно `N_keys / N_nodes`.

2020-12-03 22:03 UTC, JavaUnchained commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        assertTrue(compareOwners(ownersBeforeChange, ownersAfterChange, newNode, topologyOld.nodeCount()));
Я кажется въехал в суть, завтра переделаю

2020-12-05 08:12 UTC, JavaUnchained commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        assertTrue(compareOwners(ownersBeforeChange, ownersAfterChange, newNode, topologyOld.nodeCount()));
Теперь clusterChangeResistanceTest считает именно количество миграций.  Так же мы на всякий случай на каждой итерации сравниваем, а не слишком ли много уже у нас миграций и если слишком то уже продолжать не имеет смысла.

2020-12-05 11:44 UTC, vaddya approved these changes
Принято, +5 дополнительных баллов.

2020-12-05 11:44 UTC, vaddya commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +    private static final int REPLICAS = 5;
Unused.

2020-12-05 11:44 UTC, vaddya commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        System.out.println(replicas);
Лучше не печатать лишнего.

2020-12-05 11:44 UTC, vaddya commented on src/test/java/ru/mail/polis/RendezvousHashingTest.java
> +        assertTrue(countOfMigrateKey <= acceptableMigration);
Хороший тон в тестах добавлять поясняющее сообщение:
```java
assertTrue(countOfMigrateKey <= acceptableMigration, "Too many keys migrated after adding a node!");
```

2020-12-05 11:44 UTC, closed without merging