stage-8-ysc!b
polis-mail-ru/2020-highload-dht pull request #172
Opened 2020-11-22 20:07 UTC by StasyanOi

2020-11-29 16:11 UTC, incubos requested changes
Где отчёт? Конфиги? Результаты?
zip-архивы коммитить не стоит: выкладывайте всё отдельными файлами (желательно в markdown) для построчного review.

2020-11-29 16:11 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    void open();
Для чего это? Почему не открывать при создании `DAO`?

2020-11-29 16:21 UTC, StasyanOi commented
Сорян, не ту ветку залил на МР. Сейчас вмерджу то, что у меня в stage 8 ветке

2020-11-29 16:27 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    void open();
При выключении ноды вызывается закрытие dao и rocksdb storage, при включении ноды надо востанавливать доступ к srocksdb storage. Для этого этот метод создан

2020-12-04 10:44 UTC, incubos requested changes
Есть замечания и вопросы. Будете разбираться и исправлять или примем как есть (на оценку **хорошо** хватит)?

2020-12-04 10:44 UTC, incubos commented on reports/stage-8-yscb/summary.md
> +       [READ], Return=NOT_FOUND, 368886
Откуда `NOT_FOUND`?

2020-12-04 10:44 UTC, incubos commented on reports/stage-8-yscb/summary.md
> +       [READ-FAILED], Operations, 368886
Большинство чтений -- `FAILED`. Чем это объяснить?

2020-12-04 10:44 UTC, incubos commented on reports/stage-8-yscb/summary.md
> +       [READ], Return=NOT_FOUND, 528787
Почему половина ответов `NOT_FOUND`? Как это исправить?

2020-12-04 10:44 UTC, incubos commented on reports/stage-8-yscb/summary.md
> +       [READ], Return=NOT_FOUND, 170210
Уже меньше, но всё равно много `NOT_FOUND`. Давайте разберёмся?

2020-12-04 10:44 UTC, incubos commented on reports/stage-8-yscb/summary.md
> +Резульаты для WORKLOAD B:
`B` уже был ведь?

2020-12-04 10:44 UTC, incubos commented on reports/stage-8-yscb/summary.md
> +       [READ], Return=NOT_FOUND, 383876
Снова :(

2020-12-04 10:44 UTC, incubos commented on reports/stage-8-yscb/summary.md
> +Чтение прошло НЕ успешно для 368886 запросов. Это связано с тем, что база изначально пустая.
Давайте наполним?

2020-12-04 10:44 UTC, incubos commented on reports/stage-8-yscb/summary.md
> +
Не хватает сравнительного анализа перцентилей (95% и 99%) для `READ`/`UPDATE` на разных workloads.

2020-12-04 10:49 UTC, StasyanOi commented
@incubos согласен на оценку 'хорошо'

2020-12-04 14:55 UTC, incubos commented
> @incubos согласен на оценку 'хорошо'

ОК, принято с замечаниями.

2020-12-04 14:55 UTC, closed without merging