Expire feature implementation
polis-mail-ru/2020-highload-dht pull request #173
Opened 2020-11-23 16:58 UTC by MrSandman5

2020-11-24 12:29 UTC, MrSandman5 commented
Пока основная проблема - это хранение Instant.
Я пытаюсь хранить его двумя числами (секунды и смещение в наносекундах), но при чтении из LSM он выдаёт некорректные данные.
Либо запись происходит неправильно, либо чтение.

2020-11-28 18:27 UTC, MrSandman5 commented
На данный момент реализовано:
- Добавление параметра *expire* в DAO, чтобы была возможность указывать время жизни записи
- Очистка от устаревших записей происходит совместно с очисткой от могилок
- Рефакторинг исходных DAO-тестов для работы с записями с "вечной жизнью"
- Простые тесты на работы с недолговечными записями (пока 3, но добавлю больше)
- Добавление параметра *expire* в сервис
- Рефакторинг исходных Service-тестов для работы с записями с "вечной жизнью"

2020-11-29 16:13 UTC, incubos requested changes
Ждём готовности к review.

2020-11-30 17:26 UTC, MrSandman5 commented
Добавлено:
- Новые тесты для DAO (на compact и множественные вставки записей);
- Тесты для сервиса (шардирование и работа на одной ноде).

Недоделано:
- У записей не истекает время жизни при работе через сервис;
- Отсутствие тестов для, по крайней мере, двух нод.

2020-12-04 12:56 UTC, incubos requested changes
Есть вопросы и замечания по expire. Будете исправлять или примем как есть (на зачёт теперь хватит)?
Если хотите бонусные баллы за `ConsistentHashingTopology`, нужен набор дополнительных тестов на равномерность распределения ключей для кластеров разного размера при разном факторе репликации, а также тестов на равномерное перераспределение нагрузки при добавлении/удалении нод из кластера.

2020-12-04 12:56 UTC, incubos commented on src/main/java/ru/mail/polis/utils/RequestUtils.java
> +        final boolean expired = request.getHeader(ResponseUtils.EXPIRES) != null;
Это работает за `O(n)` и на следующей строке мы это делаем снова.

2020-12-04 12:56 UTC, incubos commented on src/test/java/ru/mail/polis/TestBase.java
> +        return Instant.ofEpochSecond(randomSeconds);
Зачем так сложно? Можно же:
```java
return Instant.now().plusSeconds(ThreadLocalRandom.current().nextInt(startSeconds, endSeconds));
```

2020-12-04 12:56 UTC, incubos commented on src/test/java/ru/mail/polis/dao/CompactionTest.java
> -
Зачем это изменение?

2020-12-04 12:56 UTC, incubos commented on src/test/java/ru/mail/polis/expire/dao/ExpireRecordsTest.java
> +        final Instant expire = Instant.ofEpochSecond(current.getEpochSecond(), current.getNano());
Зачем пересоздавать `Instant` здесь и ниже?

2020-12-04 12:56 UTC, incubos commented on src/test/java/ru/mail/polis/expire/service/ClusterExpireTestBase.java
> +abstract class ClusterExpireTestBase extends TestBase {
Можно было существующий `ClusterTestBase` расширить новыми методами, чтобы не копировать столько кода.

2020-12-04 21:15 UTC, MrSandman5 commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    Iterator<Record> iterator(@NotNull final ByteBuffer from) throws IOException;
Я не знаю, кто ещё мог делать expire, поэтому не в курсе.
Это изменение было одним из первых, и я уже не помню, зачем это сделал.

2020-12-04 21:30 UTC, MrSandman5 commented on src/main/java/ru/mail/polis/dao/impl/tables/SSTable.java
> +            if (!expire.equals(Instant.MAX)) {
Когда я пытаюсь писать Instant в любой ситуации большая часть тестов падает из-за того, что полученный ByteBuffer больше ожидаемого на (Long.BYTES + Integer.BYTES)
Решить я это не смог, поэтому решил, что при вечный записях запись их времени жизни идти не будет.

2020-12-04 21:31 UTC, MrSandman5 commented on src/main/java/ru/mail/polis/dao/impl/tables/SSTable.java
> +                final ByteBuffer expireSecondsBuffer = ByteBuffer.allocate(Long.BYTES);
Так как в этот метод передаётся только индекс ячейки, я не придумал, как проверять, что получаемые при чтении данные = Instant.MAX.

2020-12-04 21:32 UTC, MrSandman5 commented on src/test/java/ru/mail/polis/dao/CompactionTest.java
> -
Этот тест я не менял.

2020-12-04 21:34 UTC, MrSandman5 commented on src/main/java/ru/mail/polis/dao/impl/models/Value.java
> +                 final long seconds,
я подумал, что содержимое Instant стоит проверять в самом Value, так как на некоторых тестах приходит отрицательный Instant. Или проверку стоит перенести в другое место?

2020-12-04 21:35 UTC, MrSandman5 commented on src/main/java/ru/mail/polis/dao/impl/models/Value.java
> +        this.expire = (seconds > Instant.MAX.getEpochSecond() || nanos > Instant.MAX.getNano())
То есть нет смысла проверять getNano(), если уже есть проверка getEpochSecond()?

2020-12-04 21:39 UTC, MrSandman5 commented
А сколько можно получить максимум за эту таску?
Я бы хотел дотянуть хотя бы до 20 баллов.

2020-12-05 13:54 UTC, incubos commented on src/main/java/ru/mail/polis/utils/RequestUtils.java
> +        final String proxyExpire = request.getHeader(ResponseUtils.EXPIRES) == null
Мы всё равно **2 раза** вызываем `getHeader()`. Может, сохранить значение в переменную и проверить её на `null`?

2020-12-05 13:54 UTC, incubos commented on src/main/java/ru/mail/polis/dao/impl/models/Value.java
> +                 final long seconds,
Давайте разберёмся с "отрицательным Instant"? Возможно, он возникает из-за неправильной десериализации `expire` -- см. обсуждение в `SSTable`.
Здесь постоянная конвертация `Instant` в/из seconds + nanos выглядит лишней.

2020-12-05 13:54 UTC, incubos commented on src/main/java/ru/mail/polis/dao/impl/models/Value.java
> +        this.expire = (seconds > Instant.MAX.getEpochSecond() || nanos > Instant.MAX.getNano())
Предлагаю перейти на `Instant` -- см. коммент выше.

2020-12-05 13:58 UTC, incubos commented on src/main/java/ru/mail/polis/dao/impl/tables/SSTable.java
> +            if (!expire.equals(Instant.MAX)) {
Падения тестов можно и нужно отладить, написав простейший тест, который вставляет ключ, вызывает `flush()` и переоткрывает базу. Сейчас в коде баг и решение не выглядит полноценным.
В случае вечных записей вы не пишете время жизни, но **при чтении** вечных записей время жизни **всегда** вычитывается, т.е. вы просто читаете следующие байты (видимо, следующий ключ/значение) и интерпретируете как время жизни, что неправильно.
Предлагаю всегда писать время жизни и найти баг :)

2020-12-05 13:59 UTC, incubos commented on src/main/java/ru/mail/polis/dao/impl/tables/SSTable.java
> +                final ByteBuffer expireSecondsBuffer = ByteBuffer.allocate(Long.BYTES);
Либо всегда писать время жизни, либо завести **обязательный** флажок из одного байта, который будет говорить, протухает ли запись и идёт ли дальше время жизни или запись вечная и времени жизни дальше нет.

2020-12-05 13:59 UTC, incubos commented on src/main/java/ru/mail/polis/service/mrsandman5/clustering/ConsistentHashingTopology.java
> +            ring.put(hash, vnode);
Не поправлено.

2020-12-05 14:02 UTC, incubos requested changes
> А сколько можно получить максимум за эту таску?
> Я бы хотел дотянуть хотя бы до 20 баллов.

Тут остались баги. Текущее решение можно оценить не больше 8 баллов, если всё поправите, то 15.
Можно получить баллов за качественный фидбек по курсу (в конце).

2020-12-07 12:31 UTC, MrSandman5 commented
Хотел бы ещё кое-что прояснить.
Я ещё раз проверил работу SSTable. При сериализации запись выполняется корректно: timestamp, данные и expire по отдельности. При десериализации, когда необходимо считать размер данных записи, байты expire включаются в этот размер. Как временное решение мне пришлось вычитать эти байты из размера.

2020-12-07 14:07 UTC, incubos requested changes
Есть ряд замечаний. Если требуется 20 баллов, то ждём исправлений.

2020-12-07 14:07 UTC, incubos commented on src/main/java/ru/mail/polis/utils/ByteUtils.java
> +                .putLong(value.getEpochSecond()).rewind().putInt(value.getNano()).rewind();
В результате промежуточного вызова `rewind()` секунды **затираются** наносекундами.

2020-12-07 14:07 UTC, incubos commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +            distr.values().forEach(i -> assertTrue(i != 0));
По построению кода выше это всегда выполняется, разве нет? Здесь хотелось бы убедиться, что нагрузка на ноды распределена более-менее равномерно.

2020-12-07 14:07 UTC, incubos commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +class ConsistentTopologyTest extends ClusterTestBase{
Не хватает тестов, проверяющих равномерность нагрузки, для разного **размера кластера** и разного количества **реплик данных** (`replicasFor()`).

2020-12-09 12:07 UTC, incubos commented
Принято.

2020-12-09 12:07 UTC, closed without merging