Homework8
polis-mail-ru/2020-highload-dht pull request #174
Opened 2020-11-23 21:39 UTC by Marashov-Alexander

# Бонусные фичи
## Expire: возможность указания времени жизни записей
Клиент в заголовках может указать время жизни записи, после истечения которого запись превращается в "Tombstone".
Написаны тесты, доказывающие корректность добавленной возможности, но пока на уровне DAO. Нужно ли создавать тесты уровня Service?
## Регулярный автоматический фоновый compaction
В работу DAO добавлен поток Compactor, который производит операцию сжатия данных на диске по запросу потока Flusher (если файлов накопилось больше указанного значения). Написание тестов в процессе.
## Тесты для rendezvous hashing, демонстрирующие (не) равномерность распределения данных
После написания парочки простых тестов выяснилось, что моя реализация RendezvousTopology распределяет данные не совсем равномерно, что связано с простотой взятой за основу хэш-функции.

2020-11-29 17:21 UTC, incubos requested changes
Реализация достойная, но есть ряд замечаний и вопросов по коду, а также не хватает тестов.

2020-11-29 17:21 UTC, incubos commented on src/main/java/ru/mail/polis/dao/alexander/marashov/DAOImpl.java
> +    public synchronized void compact() {
Нужен ли здесь теперь `synchronized`?

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/dao/ExpiresTest.java
> +    private static final long LIFE_TIME_DELTA = 500L;
В названии временных литералов стоит указывать единицы измерения, иначе с ходу непонятно.

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/dao/ExpiresTest.java
> +    private static final CountDownLatch waiter = new CountDownLatch(1);
Почему не `Thread.sleep()`?

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        for (int i = 1; i < NODES_COUNT; ++i) {
Зачем усложнять, т.е. почему не с `0`? :)

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        for (int i = 1; i < NODES_COUNT; ++i) {
Почему префиксный инкремент? Не очень идиоматично.

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        for (final String str: topology.all()) {
Можно этого не делать, а проверить ниже в `compute()`, что `counter == null` для отсутствующего значения.

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        for (final String str: topology.all()) {
А вообще для таких случаев есть метод `Map.merge()`, подходящий лучше `compute()`.

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        countersMap.values().stream().sorted().forEach(v -> System.out.println(v + " "));
Этот тест не проверяет отклонения между нагрузкой на ноды, а лишь печатает в консоль. Давайте проверим, что расхождения между нодами не больше определённого порога (например, 10%).

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        for (final String str: topology.all()) {
См. замечания выше.

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        countersMap.values().stream().sorted().forEach(v -> System.out.println(v + " "));
Этот тест не проверяет отклонения между нагрузкой на ноды, а лишь печатает в консоль. Давайте проверим, что расхождения между нодами не больше определённого порога (например, 10%).

2020-11-29 17:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +public class RendezvousTopologyTest extends TestBase {
Нужно абстрагировать этот тест и протестировать разные размеры кластеров, например, 2, 3, 5, 10, 100. Конечно, не копированием тестов, а параметризацией.

2020-11-29 17:21 UTC, incubos commented on src/main/java/ru/mail/polis/dao/alexander/marashov/Compactor.java
> +public class Compactor extends Thread {
Отсутствуют тесты, демонстрирующие работу автоматического compaction.

2020-12-01 20:50 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/Compactor.java
> +    private final Function<NavigableMap<Integer, Table>, Function<Integer, Consumer<File>>> tablesCompactedCallback;
Добрый вечер, спасибо за замечания!
Создал интерфейс CompactorCallback - да, так код стал значительно понятнее :)
А файлы всё же решил удалять вне блокировки, так как после атомарной замены SSTable'ов ссылок на скомпакченные таблицы остаться не должно, если правильно понимаю

2020-12-01 20:51 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/TableIterator.java
> +    private final Integer compareKey;
Помню, что менял названия с generation на compareKey. Прошёлся по истории изменений в git - сделал замену на втором этапе, но зачем - не смог вспомнить... Вернул обратно)

2020-12-01 20:54 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/TableIterator.java
> +        final int comp = this.getBufferedCell().getKey().compareTo(o.getBufferedCell().getKey());
В связке с CellIterator и его приоритетной очередью, удаляющей TableIterator, если у него bufferedCell стал null, я не мог получить такой случай. Однако если использовать отдельно, то такая ситуация очень вероятна.
Исправил, спасибо!

2020-12-01 20:55 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/TableIterator.java
> +            return -this.compareKey.compareTo(o.compareKey);
Добавил описание: сравнение идёт сначала по Cell, затем по generation

2020-12-01 20:56 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/CellIterator.java
> +            public boolean add(final TableIterator tableIterator) {
Хорошо, добавил TableIteratorPriorityQueue. А тип переменной в таком случае какой лучше оставлять? PriorityQueue или наследника?

2020-12-01 20:57 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/DAOImpl.java
> +                tables -> maxGen -> dst -> postCompactingMethod(tables, maxGen, dst)
Да, спасибо, исправил)

2020-12-01 20:59 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/TableSnapshot.java
> +        final ConcurrentSkipListMap<Integer, Table> newStorageTables = new ConcurrentSkipListMap<>(storageTables);
Ой. Да. Извините

2020-12-01 21:00 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/TableSnapshot.java
> +        final ConcurrentSkipListMap<Integer, Table> newStorageTables = new ConcurrentSkipListMap<>(storageTables);
Переделал на интерфейс NavigableMap, а в качестве реализации взял TreeMap

2020-12-01 21:00 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/DAOImpl.java
> +    public synchronized void compact() {
Спасибо, теперь не нужен)

2020-12-01 21:00 UTC, Marashov-Alexander commented on src/test/java/ru/mail/polis/dao/ExpiresTest.java
> +    private static final long LIFE_TIME_DELTA = 500L;
Понял. Исправил

2020-12-01 21:05 UTC, Marashov-Alexander commented on src/test/java/ru/mail/polis/dao/ExpiresTest.java
> +    private static final CountDownLatch waiter = new CountDownLatch(1);
Что-то я сразу на wait() стал думать. Да, мы тут не ждём сигнала, изменил на sleep

2020-12-01 21:10 UTC, Marashov-Alexander commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        for (int i = 1; i < NODES_COUNT; ++i) {
Дело в том, что количество нод в кластере должно быть равно nodesCount, а как указать, что на 1 меньше после добавления локальной...
Ну, мне кажется, здесь можно с разных позиций смотреть)

2020-12-01 21:12 UTC, Marashov-Alexander commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        for (int i = 1; i < NODES_COUNT; ++i) {
Плюсовая привычка. В java обычно используют постфиксный? Мне первый раз замечание на этот счёт сделали)

2020-12-01 21:12 UTC, Marashov-Alexander commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        for (final String str: topology.all()) {
Спасибо, так действительно удобнее!

2020-12-01 21:18 UTC, Marashov-Alexander commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        countersMap.values().stream().sorted().forEach(v -> System.out.println(v + " "));
Добавил такую проверку: проверяю отклонение на 10% от среднего между наибольшим и наименьшим.
String::hashCode(), разумеется, не затащил)
Подключил библиотеку "com.github.eprst:murmur", воспользовался murmur3_32. Теперь метод primaryFor обеспечивает нужное распределение, а primariesFor - нет: между количеством нод, равного кворуму от кластера, данные распределены равномерно, а у остатка - значительно меньше

2020-12-01 21:19 UTC, Marashov-Alexander commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +public class RendezvousTopologyTest extends TestBase {
Спасибо, реализовал :)

2020-12-01 21:20 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/dao/alexander/marashov/Compactor.java
> +public class Compactor extends Thread {
Добавил один тест: по структуре напоминает тест overwrites, но явно compact не вызывает

2020-12-01 21:21 UTC, Marashov-Alexander commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        countersMap.values().stream().sorted().forEach(v -> System.out.println(v + " "));
* падают как раз тесты с распределением :)

2020-12-04 13:13 UTC, incubos commented on src/main/java/ru/mail/polis/dao/alexander/marashov/Compactor.java
> +    private final Function<NavigableMap<Integer, Table>, Function<Integer, Consumer<File>>> tablesCompactedCallback;
А если кто-то уже взял слепок `TableSet` и итерируется по файлам в этот момент? :)

2020-12-04 13:14 UTC, incubos commented on src/main/java/ru/mail/polis/dao/alexander/marashov/CellIterator.java
> +            public boolean add(final TableIterator tableIterator) {
Вопрос хороший. Обычно тип должен быть самым общим интерфейсом, но тут неоднозначно.

2020-12-04 13:18 UTC, incubos commented on src/test/java/ru/mail/polis/service/RendezvousTopologyTest.java
> +        countersMap.values().stream().sorted().forEach(v -> System.out.println(v + " "));
Уже есть методы `Hash.murmur3()` из `one-nio`.

2020-12-04 14:30 UTC, incubos commented
Принято с замечаниями.

2020-12-04 14:30 UTC, closed without merging