[WIP] Task 8
polis-mail-ru/2020-highload-dht pull request #175
Opened 2020-11-23 23:09 UTC by PolinaShneider

2020-12-01 14:12 UTC, incubos requested changes
Имеется ряд замечаний и вопросов. Будете исправлять или за часть баллов?

2020-12-01 14:12 UTC, incubos commented on docs/Task8.md
> +1. [Лента с PUT-ами с уникальными ключами](https://overload.yandex.net/355603#tab=test_data&tags=&plot_groups=main&machines=&metrics=&slider_start=1606235517&slider_end=1606235817)
Чем можно объяснить периодические всплески на графике Quantiles и Threads?

2020-12-01 14:12 UTC, incubos commented on docs/Task8.md
> +2. [Лента с PUT-ами с частичной перезаписью ключей (вероятность 10%)](https://overload.yandex.net/355608#tab=test_data&tags=&plot_groups=main&machines=&metrics=&slider_start=1606237187&slider_end=160
Чем можно объяснить всплеск Threads и сетевые ошибки в начале стрельбы на небольшой нагрузке?

2020-12-01 14:12 UTC, incubos commented on docs/Task8.md
> +3. [Лента с GET-ами существующих ключей с равномерным распределением (стреляем по наполненной БД)](https://overload.yandex.net/355618#tab=test_data&tags=&plot_groups=main&machines=&metrics=&slider_st
Чем можно объяснить всплеск Threads и сетевые ошибки в начале стрельбы на небольшой нагрузке?

2020-12-01 14:12 UTC, incubos commented on docs/Task8.md
> +4. [То же самое, но со смещением распределения GET-ов к недавно добавленным ключам (частый случай на практике)](https://overload.yandex.net/355627#tab=test_data&tags=&plot_groups=main&machines=&metri
Почему половина ответов `404`?

2020-12-01 14:12 UTC, incubos commented on docs/Task8.md
> +4. [То же самое, но со смещением распределения GET-ов к недавно добавленным ключам (частый случай на практике)](https://overload.yandex.net/355627#tab=test_data&tags=&plot_groups=main&machines=&metri
Что за провал нагрузки в 20:25:35?

2020-12-01 14:12 UTC, incubos commented on docs/Task8.md
> +5. [Наконец, лента со смешанной нагрузкой с 50% PUT-ы новых ключей и 50% GETы существующих ключей (равномерное распределение)](https://overload.yandex.net/355634#tab=test_data&tags=&plot_groups=main&
Чем можно объяснить периодические всплески Quantiles и Threads?

2020-12-01 14:12 UTC, incubos commented on docs/Task8.md
> +![Результаты с async profiler-а (CPU)](assets/stage_8/profiling/put_not_unique/cpu.svg)
Здесь явно не дали сервису прогреться и начали профилировать слишком рано: четверть CPU съедает JIT-компилятор.

2020-12-01 14:12 UTC, incubos commented on docs/Task8.md
> +На данном этапе было проведено нагрузочное тестирование при помощи Яндекс.Танк. В результате испытаний было выяснено, что сервис «держит» обстрел нагрузкой 2000 запросов в секунду. Для обстрела line
Не хватает сравнительного анализа полученных значений перцентилей (например, 95% и 99%) на разных типах нагрузки, а также объяснения их отличий.

2020-12-01 14:20 UTC, PolinaShneider commented
Буду исправлять

2020-12-01 19:41 UTC, PolinaShneider commented on src/main/java/ru/mail/polis/AmmoGenerator.java
> +            if (i % 10 != 0 || i == 0) {
Если вызвать `random.nextInt(0)`, то получим [`java.lang.IllegalArgumentException: bound must be positive`](https://stackoverflow.com/questions/32101688/illegalargumentexception-bound-must-be-positive). Проверка на ноль здесь для этого. В принципе можно код переписать по-другому

2020-12-04 14:39 UTC, incubos commented
Принято.

2020-12-04 14:39 UTC, closed without merging