Stage8 read repair
polis-mail-ru/2020-highload-dht pull request #176
Opened 2020-11-24 14:11 UTC by mariarheon

2020-12-03 20:51 UTC, vaddya requested changes
Реализация более менее понятна, но есть вопросы.

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +        final var timestamp = new Date().getTime();
Можно сразу взять `System.currentTimeMillis()`.

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                    if (composer.answerIsReady()) {
Я правильно понял, что мы не делаем рид репейр для нод, чьи ответы мы получили уже после нужного количества ответов?

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/ReadRepairer.java
> +        request.addHeader("Connection: Keep-Alive");
Я не очень понял для чего тут так аккуратно заполняются все поля для `Request`, если потом все равно вызывается `RequestConverter.convert`, который их все игнорирует.

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/ChunkedEncoder.java
> +        builder.append("HTTP/1.1 200 OK\r\n");
Лучше чейнить такие вызовы
```java
final var head = new StringBuilder()
    .append(...)
    .toString()
    .getBytes(StandardCharsets.UTF_8);
```

Но в целом, StringBuilder нужно использовать только в циклах, а в ситуациях, как здесь [можно](https://dzone.com/articles/string-concatenation-performacne-improvement-in-ja) использовать обычный плюс, компилятор сам все сделает.

Еще я не очень понял, зачем самостоятельно формировать HTTP-ответы, если можно воспользоваться методом `Response.toBytes`.

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                    final @Param(value = Util.MYSELF_PARAMETER) String myself,
Есть ощущение, что чтобы маркировать запросы от ноды к ноде, лучше использовать HTTP-хедер, например, `X-Proxy: true`.

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +        final String timestampStr = request.getParameter("timestamp");
Таймстемп по идее тоже служебная информация и такое тоже лучше передавать в хедере, а не через квери параметры запроса.

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +        logger.info("\n" + sharding.getMe() + ": Start " + request.getMethodName()
Просто на будущее: если в лог формируется сложная строчка, то лучше это делать внутри ифа:
```java
if (logger.isInfoEnabled()) {
    logger.info("Very " + "expansive " + "concatination");
}
```

В этом случае, если уровень логирования выше, чем инфо, то строки не будут конкатенироваться и плодить мусор.

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                        trySendResponse(session, requiredResponse);
То есть мы будем синхронно делать рид репейр, и пока это не сделаем, клиент не получит ответа? Может можно унести это в бэкграунд?

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/ReadRepairer.java
> +        if (repairInfo == null) {
Такое может быть? Если может, тогда лучше вообще в этом случае не создавать репейрер, потому что зачем.

2020-12-03 20:51 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/ReadRepairer.java
> +                .get();
Очень настораживает. У нас весь из себя асинхронный сервер, а тут блокировка на фьюче, не еще и без таймаута.

2020-12-03 20:51 UTC, vaddya commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +public class ReadRepairTest extends ClusterTestBase {
Я может туплю, но здесь точно проверка репейринга? На ноду пишется, другие стопаются, из живой читаем с `ack = 1`, успех. А репейр где?

В мое понимании, нужно чтобы нода (или ноды) пропустили **запись**, потом сработал ваш репейр, и уже с этих нод мы прочитали актуальное значение.

2020-12-06 13:40 UTC, mariarheon commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                    if (composer.answerIsReady()) {
Это так, согласно https://tinyurl.com/y5v7k95b

2020-12-06 13:58 UTC, mariarheon commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                        trySendResponse(session, requiredResponse);
Согласно https://tinyurl.com/y5v7k95b рид репейр может быть синхронным. Но проблема в том, что я не знаю, как в таком случае написать тест, который проверяет, что рид репейр выполнился. Ориентироваться на таймаут ненадёжно. Как поступить?

2020-12-06 14:16 UTC, mariarheon commented on src/main/java/ru/mail/polis/service/mariarheon/ReadRepairer.java
> +                .get();
Да, верно. Всё упирается в то, каким образом тестить, что асинхронный рид рипейр прошёл. В тесте придется вводить задержку, зависящую от скорости ПК. Как лучше поступить?

2020-12-06 14:30 UTC, mariarheon commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +public class ReadRepairTest extends ClusterTestBase {
Задумка была такая.
Для каждого узла A из 3х узлов выполняется следующее:
Просим узел A разместить на 2 любых узла значение value1.
Просим узел A на одном из 2х узлов (из предыдущего пункта) заменить значение value1 на значение value2.
Итого для этого ключа: на одном из узлов должно быть value1, на другом value2, на третьем - отсутствует запись.
Просим узел A получить значение с 2мя подтверждениями. В этот момент запускается функциональность ReadRepair, которая синхронным блокирующим способом выявляет, что на одном из 2х узлов хранится старое значение value1, поэтому оно подменяется на value2.
Для того, чтобы далее убедиться, что теперь 2 из 3х узлов имеют value2 в качестве значений, а оставшийся не имеет записи вовсе, мы в цикле поочерёдно оставляем включенным каждый из узлов при отключении остальных, чтобы чистым образом проверить, что теперь 2 узла из 3х (а не 1, как было бы без ReadRepair) возвращают value2.
Данный тест не будет работать без функциональности ReadRepair.
Это неверно?

2020-12-06 15:59 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                        trySendResponse(session, requiredResponse);
Согласен, давайте оставим синхронный репейр

2020-12-06 16:01 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/ReadRepairer.java
> +                .get();
А можем параллельно (через фьючи) отправить запросы починки на другие ноды и дожидаться ответов, аналогично нашему решению с шардированием?

2020-12-06 16:05 UTC, vaddya commented on src/test/java/ru/mail/polis/service/ReadRepairTest.java
> +public class ReadRepairTest extends ClusterTestBase {
Теперь понятно, спасибо.
Ну да, учитывая, что мы не знаем точно, на какую ноду осядет ключ, такой перебор всех нод и остается. Окей, годится.

2020-12-06 16:08 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                    if (composer.answerIsReady()) {
Consistency levels Кассандры немного сложно смапить на наши `ack/from`. Вы получается будете репейр делать только среди первых `ack` нод, а можно и среди всех `from`. Но на синхронное решение это ложится плохо. Оставляем.

2020-12-15 11:02 UTC, vaddya approved these changes
Минорные замечания.
Принято.

2020-12-15 11:02 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                    final @Param("request") Request request) {
Аннотация `@Param` нужна для query-параметров.

2020-12-15 11:02 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/ReadRepairer.java
> +                .exceptionally(ex -> {
Есть ощущение, что логировать фейл логирования не стоит.

2020-12-15 11:02 UTC, vaddya commented on src/main/java/ru/mail/polis/service/mariarheon/ReadRepairer.java
> +                resp.get();
Нужно ждать с таймаутом каким-нибудь, учитывая что мы делаем это синхронно с запросом клиента, например 100 мс.

2020-12-15 11:03 UTC, closed without merging