Task8
polis-mail-ru/2020-highload-dht pull request #177
Opened 2020-11-24 15:25 UTC by s3ponia

Casandra like node repair. Необходимо еще написать тесты

2020-12-07 13:21 UTC, incubos requested changes
Интересная реализация и хорошие тесты. Кода много, поэтому хотелось бы увидеть небольшой отчёт в Markdown с высокоуровневым описанием реализованного дизайна.
Также есть несколько вопросов по результатам review.

2020-12-07 13:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/SingleNodeTest.java
> +import org.junit.jupiter.api.RepeatedTest;
Зачем это?

2020-12-07 13:21 UTC, incubos commented on src/test/java/ru/mail/polis/service/SingleRangeTest.java
> +            final var temp = chunkOf(key, value);
Зачем это?

2020-12-09 12:05 UTC, s3ponia commented on src/main/java/ru/mail/polis/util/merkletree/MismatchedRanges.java
> +        return compact(compact(result));
Это осталось еще с прошлых коммитов просто. Исправил

2020-12-09 12:07 UTC, s3ponia commented on src/test/java/ru/mail/polis/dao/PersistenceTest.java
> +                ByteBuffer suffixed = join(key, suffix);
Изменял тест для того чтобы дебажить падение с OOM. Видимо при мерж конфликте осталось. Исправил

2020-12-09 12:11 UTC, s3ponia commented on src/test/java/ru/mail/polis/service/NodeRepairTest.java
> +    void noRepair() {
Проверяется ситуация когда нет никаких пропущенных значений/удалений и repair ничего не делает

2020-12-09 12:11 UTC, incubos requested changes
Не вижу исправлений. Сейчас в ветке `task8` последний коммит:
```
$ git pull
Current branch task8 is up to date.
$ git log -n 1
commit a671284666bcc1b4266bfbda5b97c83882c43e0c (HEAD -> task8, origin/task8)
Merge: 64b02a1 c646d62
Author: Vadim Tsesko <incubos@users.noreply.github.com>
Date:   Mon Dec 7 12:42:00 2020 +0300

    Merge branch 'master' into task8
```
Или куда-то не туда смотрю?

2020-12-09 12:13 UTC, s3ponia commented on src/test/java/ru/mail/polis/service/NodeRepairTest.java
> +    void missedValue() {
Проверяется то, что пропущенное значение при исправлении добавляется

2020-12-09 12:13 UTC, s3ponia commented on src/test/java/ru/mail/polis/service/SingleNodeTest.java
> +import org.junit.jupiter.api.RepeatedTest;
Это я проверял мигающие тесты и забыл убрать

2020-12-09 12:14 UTC, s3ponia commented
@incubos не думал что такой быстрый ответ будет) Я думал исправить и залить вместе с отчетом

2020-12-09 12:16 UTC, s3ponia commented on src/test/java/ru/mail/polis/service/ClusterTestBase.java
> +
Автоформат в ИДЕ.

2020-12-09 12:57 UTC, incubos commented
> @incubos не думал что такой быстрый ответ будет) Я думал исправить и залить вместе с отчетом

ОК, ждём :)

2020-12-11 12:27 UTC, s3ponia commented
> > @incubos не думал что такой быстрый ответ будет) Я думал исправить и залить вместе с отчетом
> 
> ОК, ждём :)

2020-12-14 11:18 UTC, incubos commented
Принято.

2020-12-14 11:18 UTC, closed without merging