Stage 8. Gatling
polis-mail-ru/2020-highload-dht pull request #178
Opened 2020-11-24 16:11 UTC by makaryb

Добрый день!

Отправляю результаты работы по дополнительному этапу по теме: "Нагрузочное тестирование при помощи Gatling".

Скрипты и отчет (тот же, что здесь ниже): https://github.com/makaryb/2020-highload-dht/tree/feature/task8/myGatlingTest

# Нагрузочное тестирование при помощи [Gatling](https://gatling.io/).

Содержание отчета:

1. [Gatling - инструмент нагрузочного тестирования](#gatling---инструмент-нагрузочного-тестирования).
2. [Scala-скрипт для симуляции нагрузки](#scala-скрипты-для-симуляции-нагрузки).
3. [Характеристики системы](#характеристики-системы)
4. [Обстрел _PUT_'ами](#обстрел-putами).
5. [Обстрел _GET_'ами](#обстрел-getами).
6. [Обстрел _PUT_+_GET_](#обстрел-put-+-get).
7. [Выводы по работе](#выводы-по-работе).

## Gatling - инструмент нагрузочного тестирования.

_Gatling_ - [популярный][1] инструмент нагрузочного тестирования. Как с [открытым исходным кодом][2], так и с коммерческими [предложениями][3]. В дальнейшем речь пойдет о версии open-source.

Позволяет симулировать [поведение пользователей][4] - абстракции типа: контекст пользователя.

Предоставляет _красивые_ информативные [отчеты][5] по результатам симуляций нагрузки.

## Scala-скрипты для симуляции нагрузки.

_Gatling_ предоставляет возможность записи действий пользователя с помощью инструмента [Recorder][6] для дальнейшего автоматического формирования Scala-скриптов для симуляции нагрузки. Подходит для тестирования E-Commerce веб-сайтов.

В данном случае напишем Scala-скрипты для обстрела _PUT_ и _GET_ запросами (подобно lua-скриптам, использовавшимся ранее для обстрела с помощью утилиты [_wrk2_][7]):

```scala
interp.load.ivy("io.gatling" % "gatling-core" % "3.3.1")
interp.load.ivy("io.gatling" % "gatling-http" % "3.3.1")

import io.gatling.core.Predef._
import io.gatling.core.structure.ScenarioBuilder
import io.gatling.http.Predef._
import io.gatling.http.protocol.HttpProtocolBuilder

import scala.concurrent.duration._

class MySimulation extends Simulation {

  /********************************************************************/
  
    /*
    Для демонстрации работы основного функционала и отличий Gatling
    определим основные параметры, с которыми можно запустить симуляцию:
    1. USERS - заданное число симулируемых виртуальных пользователей;
    2. RAMP_DURATION - заданная продолжительность временного окна,
          по которому равномерно распределены заданное количество виртуальных пользователей;
    3. DURATION - заданная общая продолжительность обстрела.
     */
     
  private def getProperty(propertyName: String,
                          defaultValue: String) = {
    Option(System.getenv(propertyName))
      .orElse(Option(System.getProperty(propertyName)))
      .getOrElse(defaultValue)
  }

  def userCount: Int =
    getProperty("USERS", "5").toInt
  def rampDuration: Int =
    getProperty("RAMP_DURATION", "10").toInt
  def testDuration: Int =
    getProperty("DURATION", "60").toInt

  before {
    println(s"Running test with ${userCount} users")
    println(s"Ramping users over ${rampDuration} seconds")
    println(s"Total test duration: ${testDuration} seconds")
  }
  
  /********************************************************************/

    /*
    Симуляция запросов по ключу
    */

  val httpConf: HttpProtocolBuilder =
    http.baseUrl("http://localhost:8080")

  val scn: ScenarioBuilder = scenario("putRequests") // "getRequests"
    .forever("key") {
      exec(
        http("PUT")
          .put("/v0/entity?id=${key}")
          .body(StringBody { "${key}" })
      )
//      exec(
//        http("GET")
//          .get("/v0/entity?id=${key}")
//      )
    }

  /********************************************************************/

    /*
    Блок запуска установок симуляции
     */

  setUp(
    scn.inject(
      nothingFor(5 seconds),
      // Проецирует заданное число пользователей,
      // равномерно распределенных по временному окну заданной продолжительности.
      rampUsers(userCount) during (rampDuration second)
    )
  ).protocols(httpConf)
    .maxDuration(testDuration seconds)
}
```

В случае _wrk2_ мы открывали 64 соединения и производили обстрел со стабильной нагрузкой в течение заданного промежутка времени.
В данном же случае мы симулируем заданное количество вирутальных пользователей, каждый из которых пытается открыть свое собственное соединение, и стреляем так быстро, как только возможно.
В данном случае используется [открытая модель симуляции нагрузки][8]: мы определяем скорость прибытия новых виртуальных пользователей, 
а количество одновременных пользователей внутри системы является следствием времени ответа и общей длительности, и мы не контролируем этот параметр.
Закрытая же модель - это когда система работает на полную мощность, и прибывающие пользователи отправляются в очередь, когда мы не контролируем скорость прибытия новых виртуальных пользователей, а только текущее количество активных на данный момент.
В случае закрытой модели возможна проблема "_Coordinated Omission Problem_", которую [рассматривал][9] Gil Tene.
И _Gatling_, и _wrk2_ : генератор запросов - основан на [открытой системе][10], то есть когда продолжает выдавать запросы независимо от скорости отклика, независимо от пропускной способности системы.

## Характеристики системы:

Наименование | Модель
--- | ---
Процессор | Intel Core i7 6700HQ (Skylake) 2.6 ГГц
Количество ядер | 8
Оперативная память | 8 ГБ DDR4 DDR4-2133 МГц
Накопитель | 128 ГБ HDD (5400 об/мин.)
ОС | Ubuntu Budgie 20.04
Версия курсового проекта | Этап 6. Асинхронный клиент

## Обстрел PUT'ами:

Обстрел был произведен со следующими настройками симуляции:

```
Running test with 5 users
Ramping users over 10 seconds
Total test duration: 60 seconds
Simulation boriskin.PutSimulation started...
```

_Gatling_ выводит в консоль каждые 5 сек. следующую информацию:

```
...

================================================================================
2020-11-24 12:49:24                                          40s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=267993 KO=0     )
> PUT                                                      (OK=267993 KO=0     )

---- putRequests ---------------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 5      / done: 0     
================================================================================

...
```

В конечном итоге по завершению обстрела _Gatling_ формирует следующий общий консольный вывод по результатам работы:

```
Simulation boriskin.PutSimulation completed in 60 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                     447977 (OK=447977 KO=0     )
> min response time                                      0 (OK=0      KO=-     )
> max response time                                    893 (OK=893    KO=-     )
> mean response time                                     1 (OK=1      KO=-     )
> std deviation                                          2 (OK=2      KO=-     )
> response time 50th percentile                          1 (OK=1      KO=-     )
> response time 75th percentile                          1 (OK=1      KO=-     )
> response time 95th percentile                          1 (OK=1      KO=-     )
> response time 99th percentile                          2 (OK=2      KO=-     )
> mean requests/sec                                8145.036 (OK=8145.036 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                        447974 (100%)
> 800 ms < t < 1200 ms                                   3 (  0%)
> t > 1200 ms [...]

2020-12-01 16:03 UTC, incubos requested changes
Есть вопросы и замечания: перестреливать нет необходимости, но хотелось бы получить комментарии.

2020-12-01 16:03 UTC, incubos commented on myGatlingTest/README.md
> +В ходе работы были составлены сценарии симуляции обстрела разработанной системы PUT и GET запросами. Было проведено тестирование стрессоустойчивости системы с использованием концепции виртуальных пол
Было бы интересно поисследовать более сложные (и реалистичные) смеси запросов, например, вставлять новые ключи и одновременно запрашивать ключи, вставленные недавно по убывающему распределению. Впрочем, и так проделана хорошая самостоятельная работа.

2020-12-01 16:03 UTC, incubos commented on myGatlingTest/README.md
> +          .body(StringBody { "${key}" })
Было бы реалистичнее использовать тела большего размера.

2020-12-01 20:56 UTC, makaryb commented on myGatlingTest/README.md
> +    .forever("key") {
Как я понимал, в данном случае это простой `counter`: https://gatling.io/docs/current/general/scenario/#forever
Он генерируется не случайно, а, начиная от 0, итерируется в каждый проход петли

![Новый проект (1)](https://user-images.githubusercontent.com/36387962/100777974-7f537480-3417-11eb-8c30-72278ec7548e.png)

2020-12-01 20:56 UTC, makaryb commented on myGatlingTest/README.md
> +Видно, что есть выбросы по времени ответа.
Поставил логгер:

```scala
...
val context: LoggerContext = LoggerFactory.getILoggerFactory.asInstanceOf[LoggerContext]
// Log all HTTP requests
context.getLogger("io.gatling.http").setLevel(Level.valueOf("DEBUG"))
...
```

В самом отчете _Gatling_ видно, что нужно смотреть в районе 22:43:12

![image](https://user-images.githubusercontent.com/36387962/100791498-630d0300-342a-11eb-99d1-cae244f51aca.png)

за один проход 180 сек. насобирал логов на 900 мб)

Вот небольшая выжимка в миллисекунды, когда всплеск:

```
...
host: localhost:8080
content-length: 6, content=null}
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 6, cap: 6/6))
PUT /v0/entity?id=105007 HTTP/1.1
accept: */*
host: localhost:8080
content-length: 6, content=null}
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.885 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=104276: scenario=putRequests, userId=2
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 6, cap: 6/6))
PUT /v0/entity?id=104276 HTTP/1.1
accept: */*
host: localhost:8080
content-length: 6, content=null}
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.885 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=97548: scenario=putRequests, userId=5
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 5, cap: 5/5))
PUT /v0/entity?id=97548 HTTP/1.1
accept: */*
host: localhost:8080
content-length: 5, content=null}
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.885 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=98399: scenario=putRequests, userId=4
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 5, cap: 5/5))
PUT /v0/entity?id=98399 HTTP/1.1
accept: */*
host: localhost:8080
content-length: 5, content=null}
22:43:12.885 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=100679: scenario=putRequests, userId=3
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 6, cap: 6/6))
PUT /v0/entity?id=100679 HTTP/1.1
accept: */*
host: localhost:8080
content-length: 6, content=null}
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.885 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=105008: scenario=putRequests, userId=1
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 6, cap: 6/6))
PUT /v0/entity?id=105008 HTTP/1.1
accept: */*
host: localhost:8080
content-length: 6, content=null}
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.885 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=104277: scenario=putRequests, userId=2
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 6, cap: 6/6))
PUT /v0/entity?id=104277 HTTP/1.1
accept: */*
host: localhost:8080
content-length: 6, content=null}
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.885 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.885 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=97549: scenario=putRequests, userId=5
22:43:12.886 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.886 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:43:12.886 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.886 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:43:12.886 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 5, cap: 5/5))
PUT /v0/entity?id=97549 HTTP/1.1
accept: */*
host: localhost:8080
content-length: 5, content=null}
22:43:12.886 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=98400: scenario=putRequests, userId=4
22:43:12.886 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 5, cap: 5/5))
PUT /v0/entity?id=98400 HTTP/1.1
accept: */*
...
```

а вот в норме:

```
...
host: localhost:8080
content-length: 5, content=null}
22:42:35.523 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:42:35.523 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:42:35.524 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:42:35.524 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:42:35.524 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
Connection: Keep-Alive'
22:42:35.524 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
22:42:35.524 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=45452: scenario=putRequests, userId=4
22:42:35.524 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=47561: scenario=putRequests, userId=3
22:42 [...]

2020-12-01 20:56 UTC, makaryb commented on myGatlingTest/README.md
> +В случае 15k виртуальных пользователей сервер не справился с нагрузкой:
На 15 тыс с логгером у меня совсем зависает убунта - не могу повторить. В тот раз тоже зависла, но дошла до конца в бэкраунде и после ребута получилось открыть сохраненный отчет.

В документации написано, что каждый виртуальный пользователь открывает свое соединение

`... virtual users behave as independent browsers ...`

`... the default behavior is that every user has his own connection pool ...`

source: https://gatling.io/docs/current/http/http_protocol/#connection-sharing

[тут написано](https://stackoverflow.com/a/34990430), что переиспользует

2020-12-01 20:56 UTC, makaryb commented on myGatlingTest/README.md
> +Как и у PUT:
Вижу в логах, что довольно часть встречается следующее:

```
...
Connection: Keep-Alive'
23:46:32.968 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 4, cap: 4/4, unwrapped: PooledUnsafeDirectByteBuf(ridx: 66, widx: 66, cap: 80)), decoderResult: success)'
23:46:32.968 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=2175: scenario=putRequests, userId=63
23:46:32.968 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=GET uri=http://localhost:8080/v0/entity?id=2145: scenario=putRequests, userId=66
23:46:32.968 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=GET uri=http://localhost:8080/v0/entity?id=2130: scenario=putRequests, userId=70
23:46:32.968 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Content-Length: 4
Connection: Keep-Alive'
23:46:32.968 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 201 Created
Content-Length: 0
...
```

то есть проскакивает два GET и один PUT.

Чаще всего, однако один GET, один PUT:

```
...
Connection: Keep-Alive'
23:46:32.948 [DEBUG] i.g.h.c.i.HttpAppHandler - Read msg='EmptyLastHttpContent'
23:46:32.948 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=PUT uri=http://localhost:8080/v0/entity?id=2626: scenario=putRequests, userId=8
23:46:32.948 [DEBUG] i.g.h.e.t.HttpTxExecutor - Sending request=GET uri=http://localhost:8080/v0/entity?id=2335: scenario=putRequests, userId=45
23:46:32.948 [DEBUG] i.g.h.c.i.HttpAppHandler - Write request WritableRequest{request=DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(ridx: 0, widx: 4, cap: 4/4))
...
```

Просмотрел довольно много - такого, чтобы два PUT на один GET - не увидел.

Возможно, что распределение, обнаруженное на данной гистограмме, как раз описывает эту закономерность. Не берусь утверждать точно

2020-12-04 14:43 UTC, incubos commented on myGatlingTest/README.md
> +В случае 15k виртуальных пользователей сервер не справился с нагрузкой:
Жесть...

2020-12-04 14:45 UTC, incubos commented
Принято.

2020-12-04 14:45 UTC, closed without merging