First task
polis-mail-ru/2020-highload-dht pull request #18
Opened 2020-09-29 10:19 UTC by ViaSacra

Vladislav Ivlev

2020-09-29 16:33 UTC, ViaSacra commented
Результаты нагрузочного тестирования лежат в `src/main/resources/result-testing`

2020-09-30 19:42 UTC, vaddya requested changes
Реализация ОК, есть пару замечаний. Огромные вопросы по профилированию. Есть ли какое-то разумное объяснение, как на залитых флейм-графах оказался не ваш контроллер, а решение из #9 ?

2020-09-30 19:42 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ServiceController.java
> +    private Response getResponse(final ByteBuffer key, final Request request) {
Можно здесь и ниже навешать `@NotNull` на параметры

2020-09-30 19:42 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ServiceController.java
> +            final ByteBuffer duplicate = dao.get(key).duplicate();
Стоит ли делать `duplicate()`, если после этого сразу перекопируешь в массив байт? Да и в целом, если для это необходимо для корректной работы хранилища, это надо делать на стороне DAO, а не на стороне клиента.

2020-09-30 19:42 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ServiceImpl.java
> +
Лишняя строка.

2020-09-30 19:42 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ServiceController.java
> +     * @return
Лучше не оставлять пустыми поля в JavaDoc.

2020-10-01 11:41 UTC, ViaSacra commented
Я брал результаты тестов у Макария для наглядного примера и случайно запушил его вместо своих, не обратив внимания. Добавил свои, дискуссии закрыл

2020-10-01 16:51 UTC, vaddya commented
Реализация ОК.

"Нужно вкоммитить результаты нагрузочного тестирования через wrk2 (put и get, параметры запуска и гистограммы времён ответа сервиса), результаты профилирования cpu и alloc под нагрузкой (файлы svg), а также **их краткий анализ в виде текстового файла Markdown**."

Не надо профилировать по 10 минут (`-d10m`), хватит 30 секунд на разогрев и 30 на замер.

2020-10-06 08:27 UTC, ViaSacra commented
@vaddya, добавил. Простите, что так долго, на выходных не было доступа к интернету

2020-10-06 10:14 UTC, vaddya commented
Частично принято из-за заимствований и неполного анализа. Сейчас их исправлять уже времени нет, старайтесь в следующий раз оперативнее реагировать на замечания и пожелания.

- Используйте `wrk2` вместо `wrk`, чтобы явно задавать частоту запросов и получать более честные результаты.
- Флейм графы по `alloc` нужны как для `put`, так и для `get` запросов. Именно эти запросы нам интересны, а не `/status`. Учтите, что во втором этапе нужно анализировать еще и по `lock`.
- В отчете отражайте возможные оптимизации и узкие места **вашего хранилища**. То, что `Все 100% cpu занимает SelectorThread` нам ничего не говорит и не помогает оптимизировать решение.
- Собирайте, пожалуйста, все результаты `wrk2`(и выводы поним) в один Markdown-файлик, будет удобнее.
- Ну и никогда не коммитьте больше чужие результаты.

2020-10-06 10:14 UTC, closed without merging