Work in porocess Stage8
polis-mail-ru/2020-highload-dht pull request #180
Opened 2020-11-24 20:23 UTC by KateMoreva

Пока пытаюсь понять, как лучше реализовать стриминг с нод.
Выложена часть реализации.

2020-12-08 18:12 UTC, vaddya requested changes
Неплохая реализация кластерного range-метод, но не хочется ли написать тесты? А то код `StreamingHttpClient` весьма нетривиальный, а проверить особо никак.

И вопросы по заимствованиям в тестах к ConsisnetHashing.

2020-12-08 18:12 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/RangeRequestHelper.java
> +    private void workOnTheNode(final Context context,
С точки зрения дизайна -- лучше просто вернуть итератор, а не модифцировать коллекцию внутри метода.

2020-12-08 18:12 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/RangeRequestHelper.java
> +                    final Iterator<Record> recordIterator = Iterators.transform(iterator, (bytes) -> {
Хотелось бы попробвать создавать итераторы с разных параллельно, а не друг за другом. Но реализация все сложнее и сложнее. Если не получится, оставляйте это как есть.

2020-12-09 23:06 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/RangeRequestHelper.java
> +                runProxied(start, end, streamSession, context);
Спасибо, исправила.

2020-12-09 23:06 UTC, KateMoreva commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +public class ConsistentTopologyTest extends ClusterTestBase {
Не копировала Вашу реализацию тестов, но буду тогда создавать новые.

2020-12-09 23:06 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/RangeRequestHelper.java
> +                    workProxied(context, nodes, iterators);
Исправила.

2020-12-09 23:07 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/RangeRequestHelper.java
> +                    final Iterator<Record> recordIterator = Iterators.transform(iterator, (bytes) -> {
Пока оставлю как есть, к сожалению, сейчас нет времени на улучшение реализации

2020-12-10 09:13 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/StreamingHttpClient.java
> +                    if (pos + 128 >= buf.length) {
Все константы взяты из реализации one.nio.http.HttpClient

2020-12-10 09:14 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/StreamingHttpClient.java
> +            isAvailable = false;
Исправила

2020-12-10 09:14 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/RangeRequestHelper.java
> +    private void workOnTheNode(final Context context,
Поправила дизайн, теперь возвращается итератор.

2020-12-10 15:29 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/StreamingHttpClient.java
> +                throws IOException, InterruptedException, PoolException, HttpException;
Выделила общий StreamingException

2020-12-10 15:31 UTC, KateMoreva commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +import java.nio.ByteBuffer;
Исправила.

2020-12-10 15:31 UTC, KateMoreva commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +public class ConsistentTopologyTest extends ClusterTestBase {
Добавила новый тест

2020-12-10 15:32 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/ConsistentTopology.java
> +            while (nodesRing.containsKey(hashFunction)) {
Думаю, что лучше все же обрабатывать событие при котором будет два одинаковых хэша.

2020-12-10 18:12 UTC, vaddya requested changes
Хорошие тесты для кластерного range-метода, остался последний штрих в `ConsistentTopologyTest`.

2020-12-10 18:12 UTC, vaddya commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +         double mistakesCount = 0;
1. Почему счетчик `double`?
2. Ваши кластера одинаковые. Нужно менять не число VNODE, а размер кластера. То есть во второй конструктор `ConsistentTopology` нужно передать на одну ноду больше в `set`.

2020-12-10 18:26 UTC, KateMoreva commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +         double mistakesCount = 0;
Ой, спасибо, что указали на ошибки, поправила.

2020-12-10 18:38 UTC, vaddya commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +         double mistakesCount = 0;
Они опять одинаковые. Добавить экстра ноду надо между конструкторами. При этом хорошо бы в конструкторе `ConsistentTopology` сделать защитное копирование `nodes`.

2020-12-10 19:41 UTC, KateMoreva commented on src/test/java/ru/mail/polis/service/ConsistentTopologyTest.java
> +         double mistakesCount = 0;
Ошиблась строчкой, в конструкторе добавила проверку на пустоту nodes.

2020-12-10 20:31 UTC, vaddya approved these changes
Принято.

2020-12-10 20:31 UTC, closed without merging