Stage 8
polis-mail-ru/2020-highload-dht pull request #181
Opened 2020-11-24 22:34 UTC by Igor-Manikhin

2020-11-24 22:37 UTC, Igor-Manikhin commented
На текущий момент времени частично сделан сервер на Netty, в котором реализована обработка запросов как с одной ноды, так и с нескольких. Репликация пока дорабатывается, поскольку не все тесты проходят.

2020-11-29 17:24 UTC, incubos requested changes
Ожидаем готовности фичи.

2020-12-04 14:52 UTC, incubos requested changes
Ждём готовности.

2020-12-07 16:53 UTC, incubos requested changes
Есть ряд критичных замечаний, требующих исправлений.
Готовы стрельнуть через `wrk2` и попрофилировать?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/NettyAsyncServiceImpl.java
> +        Runtime.getRuntime().addShutdownHook(new Thread(this::stop));
Зачем это?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +        for (final String node : nodes.getNodes()) {
При использовании `java.net.http.HttpClient` не нужен пул клиентов к разным нодам (пул соединений уже есть внутри `HttpClient`).

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +        context = ctx;
В текущей реализации один объект `NettyRequests` обслуживает все соединения (каналы), но работа с его полями сейчас не является потокозащищённой (здесь мы сохраняем `context`, например). Верно?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +        } else if (uri.contains(ENTITIES_PATH)) {
`startsWith()`?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +        } else if (uri.contains(ENTITY_PATH)) {
`startsWith()`?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/utils/ServiceUtils.java
> +        ctx.writeAndFlush(response).addListener(ChannelFutureListener.CLOSE);
Почему мы **всегда** закрываем соединение и игнорируем keep-alive?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/StreamNettySession.java
> +        while (iterator.hasNext()) {
Такая реализация является блокирующей (мы просто запихиваем все данные в канал, возможно, блокируясь) и отсутствует back pressure, верно?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/Replicas.java
> +        final Replicas replicaFactor = isForwarded || replicas == null ? quorum(clusterSize) : parser(replicas.get(0));
Почему мы используем `quorum()` в случае `isForwarded`?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/utils/ServiceUtils.java
> +                ctx.writeAndFlush(r).addListener(ChannelFutureListener.CLOSE);
Т.е. keep-alive у нас не работает?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +            replicaHelper.multiGet(context, replicaFactor, request);
И внутри снова парсим запрос?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +            replicaHelper.multiPut(context, replicaFactor, request);
И внутри снова парсим запрос?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +            replicaHelper.multiDelete(context, replicaFactor, request);
И внутри снова парсим запрос?

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/ReplicasNettyRequests.java
> +    private Set<String> replicaClusters;
Объект текущего класса существует в одном экземпляре и дёргается из разных потоков, верно? При этом его поля ничем не защищены.

2020-12-07 16:53 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/Replicas.java
> +    public static Replicas parser(final String replicas) {
`parse()`?

2020-12-07 18:22 UTC, Igor-Manikhin commented
Замечания будут исправлены сегодня же.

2020-12-07 18:22 UTC, Igor-Manikhin commented on .github/workflows/gradle.yml
> -name: Java CI with Gradle
Случайно удалил.

2020-12-07 18:23 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/NettyAsyncServiceImpl.java
> +        Runtime.getRuntime().addShutdownHook(new Thread(this::stop));
Уберу.

2020-12-07 18:23 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +        for (final String node : nodes.getNodes()) {
Переделаю.

2020-12-07 18:26 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +        context = ctx;
Да, здесь и в других методах для реплик сохраняется контекст и выполняется проверка на проксирование.  Переделаю так, чтобы это данные вещи использовались внутри методов, а не на глобальном уровне.

2020-12-07 18:26 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +        } else if (uri.contains(ENTITIES_PATH)) {
Исправлю.

2020-12-07 18:26 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +        } else if (uri.contains(ENTITY_PATH)) {
Исправлю.

2020-12-07 18:26 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/utils/ServiceUtils.java
> +        ctx.writeAndFlush(response).addListener(ChannelFutureListener.CLOSE);
Переделаю.

2020-12-07 18:27 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/StreamNettySession.java
> +        while (iterator.hasNext()) {
Мы их запихиваем и тут же отсылаем и флушим сразу.

2020-12-07 18:27 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/Replicas.java
> +        final Replicas replicaFactor = isForwarded || replicas == null ? quorum(clusterSize) : parser(replicas.get(0));
Исправлю.

2020-12-07 18:27 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/utils/ServiceUtils.java
> +                ctx.writeAndFlush(r).addListener(ChannelFutureListener.CLOSE);
Переделаю.

2020-12-07 18:27 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +            replicaHelper.multiPut(context, replicaFactor, request);
Переделаю.

2020-12-07 18:27 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/NettyRequests.java
> +            replicaHelper.multiDelete(context, replicaFactor, request);
Переделаю.

2020-12-07 18:28 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/Replicas.java
> +    public static Replicas parser(final String replicas) {
Переделаю.

2020-12-07 18:29 UTC, Igor-Manikhin commented on src/main/java/ru/mail/polis/service/manikhin/ReplicasNettyRequests.java
> +    private Set<String> replicaClusters;
Да, он только в одном экземпляре создаётся. Сделать его создание непосредственно в методах обработки соответствующих запросов?

2020-12-09 12:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/StreamNettySession.java
> +        while (iterator.hasNext()) {
Но если клиент тормозит и не успевает принимать, очередной flush заблокируется ведь.

2020-12-09 12:32 UTC, incubos commented on src/main/java/ru/mail/polis/service/manikhin/ReplicasNettyRequests.java
> +    private Set<String> replicaClusters;
Есть разные подходы к обеспечению потокозащищённости.

2020-12-09 12:54 UTC, incubos commented
Принято с замечаниями.

2020-12-09 13:03 UTC, incubos requested changes
Стриминг остался блокирующим. На максимум баллов нужны стрельбы и профилирование, потому что мы полностью поменяли "движок" и хорошо бы найти в нём узкие места.

2020-12-11 01:45 UTC, Igor-Manikhin commented
Добавлен отчёт, который доступен по следующей [ссылке](https://github.com/Igor-Manikhin/2020-highload-dht/blob/Stage_8/reports/report_8.md). Обновлена реализация стриминга на Netty. Добавлена проверка доступности записи в канал как в момент записи данных в него, так и непосредственно и в переопределённом обработчике, отслеживающем его активность. Данное решение мне пришло на ум, другого придумать не смог.

2020-12-17 13:09 UTC, incubos commented
Принято с замечаниями.

2020-12-17 13:09 UTC, closed without merging