Topology tests
polis-mail-ru/2020-highload-dht pull request #182
Opened 2020-11-29 19:15 UTC by gogun

2020-12-08 21:06 UTC, vaddya requested changes
Неплохие тесты, но нужен еще один тест.

Если вы помните, то причина, по которой мы используем более сложные и затратные Rendezvous и Consistent hashing, состоит в том, что мы можем относительно безболезненно менять кластер (добавлять и удалять ноды), т.к. при этом у нас не происходит полная миграция ключей, как в случае топологии на основе взятия остатка от деления на число нод. Это тоже нужно проверить.

2020-12-08 21:06 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +            final int avg = distr
Проще, наверное, посчитать ожидаемое +- дельта. Ожидаемое у нас это число ключей поделить на число нод. Ну и дельта 10-20%, например.

2020-12-08 21:06 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +    void multipleNodesTest() {
Кажется, что `distributionTest` в целом покрывает эту проверку.

2020-12-09 11:37 UTC, vaddya requested changes

2020-12-09 11:37 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +        return 15;
Хватит 3/5.

2020-12-09 11:37 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +                float maximumDeviation = eachNodeNum * 0.4f;
Если кластер уменьшить, то здесь и с `0.2f` проходит.

2020-12-09 11:37 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +                    ConsistentHashing.add(nodeToAdd, topology.getCircle(), VNODES);
Во внутренности лезть не хочется совсем, наружу статический метод открывать, который меняет кольцо.. Давайте просто создадим два объекта топологии (один с `N` нодами, а во вторую топологию изначально дадим `N + 1` ноду)? 

Нужно проверить не то, что на новую ноду переехало `N_keys / N_nodes` ключей (в общем то это выполняется и для топлогии на основе взятия остатка от деления на число нод), а то, что остальные ключи не мигрировали. Для этого проще пройти по ключам с `RF = 1` и посчитать все несовпадения primary ноды в старой и новой топологии. Именно это число говорит о том, как кластер переживает добавление/удаление ноды.

2020-12-09 11:37 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/ConsistentHashing.java
> +        return circle;
Кольцо это внтуреннее представление для ConsistentHashing, которое не стоит отдавать наружу. В худшем случае нужно защитное копирование, а лучше вообще не делать это частью API.

2020-12-09 18:33 UTC, gogun commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +                    ConsistentHashing.add(nodeToAdd, topology.getCircle(), VNODES);
Что подразумевается под "все несовпадения primary ноды"? Разница между кол-вом ключей на primary ноде с N и N + 1 ключами?

2020-12-09 18:46 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +                    ConsistentHashing.add(nodeToAdd, topology.getCircle(), VNODES);
Возьмем `RF = 1`. Например, было:
```
key1 -> node1
key2 -> node2
key3 -> node1
key4 -> node2
```
Стало после добавления `node3`:
```
key1 -> node1
key2 -> node2
key3 -> node3
key4 -> node2
```
У нас переехал только один ключ, `key3`. Количество таких переездов и нужно посчитать.

2020-12-09 19:00 UTC, gogun commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +                    ConsistentHashing.add(nodeToAdd, topology.getCircle(), VNODES);
все, понял, спасибо

2020-12-09 22:01 UTC, gogun commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +                float maximumDeviation = eachNodeNum * 0.4f;
у меня иногда проходит, иногда нет, поэтому побольше поставил

2020-12-10 09:10 UTC, vaddya requested changes

2020-12-10 09:10 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +        Assertions.assertTrue(migrationCounter < KEYS / 2);
Почему 2? `N_keys / N_nodes + delta` же.

2020-12-10 09:10 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +        for (int i = 0; i < KEYS; i++) {
А нельзя за один цикл это сделаться , а не за 3? У нас есть два объекта топологии, генерим ключ, смотрим ноду в старой, смотрим в новой, обновляем счетчик...

2020-12-10 09:10 UTC, vaddya commented on src/test/java/ru/mail/polis/service/TopologyTests.java
> +        return 9;
Нет смысла для тестов делать кластер больше 3 или 5. Чаще всего, то, что справедливо для 3 нод, справделиво и для большего числа нод.

2020-12-11 08:19 UTC, vaddya approved these changes
Принято.

2020-12-11 08:19 UTC, closed without merging