Stage 8
polis-mail-ru/2020-highload-dht pull request #185
Opened 2020-12-14 22:00 UTC by Basta123

Реализация рандеву хеширования лежит по пути /src/main/java/ru/mail/polis/service/basta123/RendezvousTopology.java

Реализация равномерного распределения данных для рандеву хеширования лежит по пути /src/test/java/ru/mail/polis/RendezvousHashTest.java

2020-12-17 13:25 UTC, Basta123 commented
> Реализация рандеву хеширования лежит по пути /src/main/java/ru/mail/polis/service/basta123/RendezvousTopology.java
> 
> Реализация теста, проверяющего равномерность распределения данных лежит по пути /src/test/java/ru/mail/polis/RendezvousHashTest.java

2020-12-17 18:22 UTC, incubos requested changes
Есть ряд замечаний как по производительности, так и по тестированию.

2020-12-17 18:22 UTC, incubos commented on src/main/java/ru/mail/polis/service/basta123/RendezvousTopology.java
> +    public List<String> getNodesForKey(@NotNull final ByteBuffer id, final int numOfReplicas) {
Эту реализацию тоже трудно назвать эффективной: мы держим все хеши в памяти, их сортируем, а потом извлекаем **каждую** из `numOfReplicas` за `O(nodes.size())`. В качестве значительно более быстрой реализации можно завести класс-кортеж `NodeHash` (содержащий `String node`, `int hash`, `Comparable` by `hash`) и хранить `numOfReplicas` элементов в структуре Heap (в Java это PriorityQueue). Надеюсь, понятно описал?

2020-12-17 18:22 UTC, incubos commented on src/main/java/ru/mail/polis/service/basta123/RendezvousTopology.java
> +    public List<String> getNodesForKey(@NotNull final ByteBuffer id, final int numOfReplicas) {
Почему такое внимание уделяется эффективности? Это действительно горячий код: обработка всех запросов проходит через `Topology` -- поэтому реализация должна быть максимально производительной.

2020-12-17 18:22 UTC, incubos commented on src/test/java/ru/mail/polis/RendezvousHashTest.java
> +                    (String) randomNodes.toArray()[0]);
`randomNodes.iterator().next()` меньше выделит памяти.

2020-12-17 18:22 UTC, incubos commented on src/test/java/ru/mail/polis/RendezvousHashTest.java
> +                    if (numberOfEachNode.get(node) == null) {
Есть метод `getOrDefault()`.

2020-12-17 18:22 UTC, incubos commented on src/test/java/ru/mail/polis/RendezvousHashTest.java
> +public class RendezvousHashTest {
Суть rendezvous hashing в minimal disruption при **изменении количества нод** в кластере -- как минимум, не хватает тестов, проверяющих, что при добавлении ноды в кластер "переедет" лишь необходимая часть ключей, а большинство останется на тех же репликах.

2020-12-21 10:55 UTC, incubos commented
Принято с замечаниями.

2020-12-21 10:55 UTC, closed without merging