Task1
polis-mail-ru/2020-highload-dht pull request #19
Opened 2020-09-29 12:43 UTC by mariarheon

2020-09-30 11:42 UTC, lamtev requested changes
Попрошу сразу дополнить PR отчетом с анализом результатов нагрузочного тестирования и профилирования. [
<img width="849" alt="Screenshot 2020-09-30 at 14 40 39" src="https://user-images.githubusercontent.com/10428179/94680831-11150780-032b-11eb-8c13-97b206f0ce75.png">
](https://github.com/polis-mail-ru/2020-highload-dht#develop)

2020-10-03 23:10 UTC, lamtev requested changes
По коду оставил несколько некритичных замечаний, и задал вопрос. В целом все ОК

Посмотрел результаты `wrk` и `async-profiler`, там тоже все ок. Методика профилирования под нагрузкой скорее всего была правильной. 

Просьба в Markdown отчете:
1. выводы `wrk` вынести в блоки кода, чтобы в отрендеренном виде все выглядело красиво
2. Добавить в отчет полученные флейм-графы для наглядности
3. Кратко проанализировать результаты: как сервер справляется с нагрузкой, на что в каких сценариях тратится CPU/ALLOC

2020-10-05 12:04 UTC, mariarheon commented on build.gradle.kts
> +    compile("org.rocksdb:rocksdbjni:6.7.3")
Я пробовала использовать версию 6.11.4, заменила компаратор на кастомный. Однако, 1 раз из примерно 15-ти не проходит тест Compactiontest - multiple. 
Нативный метод put() библиотеки RocksDB создаёт ByteBuffer, для которого далее вызывает метод array(), в котором оказывается, что данный буфер не имеет под собой массива. 
При этом, судя по отладке, методу put() передаются корректные массивы байт. 
Пока понять почему ошибка именно в этом тесте появляется не могу.

2020-10-05 12:54 UTC, lamtev requested changes
Профилирование - ОК
По коду есть недочеты

2020-10-05 12:54 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ServiceImpl.java
> +    final Logger logger = LoggerFactory.getLogger(ServiceImpl.class);
`private static`

2020-10-05 12:54 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ServiceImpl.java
> +            logger.error("Error in ServiceImpl.get() method: key is empty");
В данной ситуации клиент прислал плохой запрос - это не ошибка с точки зрения работы сервера. `info`/`warn` подойдет

2020-10-05 12:54 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ServiceImpl.java
> +            logger.error("Error in ServiceImpl.get() method; internal error: " + ex.getMessage());
1. На первой лекции обсуждали, что лучше пользоваться плейсхолдерами, а не конкатенацией
2. Иногда `message` не очень информативен, и без стэктрейса исключения будет довольно трудно найти место, где оно было выброшено
Поэтому лучше так: 
```java
logger.error("Error in ServiceImpl.get() method; internal error: ", ex);
```
(метод `error` позволяет не добавлять плейсхолдер `{}` явно для исключений)

2020-10-05 12:54 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ServiceImpl.java
> +            logger.error("Error in ServiceImpl.put() method: key is empty");
аналогично

2020-10-05 12:54 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ServiceImpl.java
> +            logger.error("Error in ServiceImpl.put() method; internal error: " + ex.getMessage());
аналогично

2020-10-05 12:54 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ServiceImpl.java
> +            logger.error("Error in ServiceImpl.delete() method; internal error: " + ex.getMessage());
аналогично

2020-10-05 12:54 UTC, lamtev commented on src/main/java/ru/mail/polis/service/mariarheon/ServiceImpl.java
> +            logger.error("Error in ServiceImpl.delete() method: key is empty");
аналогично

2020-10-05 12:54 UTC, lamtev commented on build.gradle.kts
> +    compile("org.rocksdb:rocksdbjni:6.7.3")
На более свежих версиях поменялся компаратор: теперь в нем сравниваются ключи, представленные в unsigned byte. То есть для использования свежих версий нужно самостоятельно правильно реализовать конвертацию unsigned <-> signed. Не буду требовать это сделать)

2020-10-05 13:12 UTC, lamtev commented
Принято

2020-10-05 13:12 UTC, closed without merging