Stage1
polis-mail-ru/2020-highload-dht pull request #2
Opened 2020-09-26 09:14 UTC by bmendli

2020-09-28 10:27 UTC, vaddya commented
Не вижу результатов профилирования, будут?

2020-09-28 14:57 UTC, bmendli commented
-t1 -c1 -d30s --latency http://127.0.0.1:8080/v0.status

```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    29.65us   94.61us   7.51ms   99.58%
    Req/Sec    35.69k     4.76k   39.70k    90.03%
  Latency Distribution
     50%   23.00us
     75%   25.00us
     90%   31.00us
     99%   77.00us
  1068776 requests in 30.10s, 72.37MB read
  Non-2xx or 3xx responses: 1068776
Requests/sec:  35506.64
Transfer/sec:      2.40MB
```


![image](https://user-images.githubusercontent.com/45788828/94448814-07b55f00-01b4-11eb-8f44-9b53ed1a2135.png)

2020-09-28 15:41 UTC, bmendli commented
-t1 -c1 -d30s -s ./wrk/put.lua --latency http://127.0.0.1:8080

```
 Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    27.15us   32.22us   2.63ms   98.51%
    Req/Sec    31.79k     3.07k   34.67k    91.03%
  Latency Distribution
     50%   24.00us
     75%   25.00us
     90%   31.00us
     99%   67.00us
  952032 requests in 30.10s, 64.46MB read
  Non-2xx or 3xx responses: 952032
Requests/sec:  31629.36
Transfer/sec:      2.14MB
```

![image](https://user-images.githubusercontent.com/45788828/94453848-d63f9200-01b9-11eb-9ecb-b340dc291fe5.png)

2020-09-28 15:45 UTC, bmendli commented
-t1 -c1 -d30s -s ./wrk/get.lua --latency http://127.0.0.1:8080

```
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    26.05us   23.31us   2.83ms   98.29%
    Req/Sec    32.40k     2.43k   34.89k    90.70%
  Latency Distribution
     50%   24.00us
     75%   25.00us
     90%   29.00us
     99%   60.00us
  970347 requests in 30.10s, 65.70MB read
  Non-2xx or 3xx responses: 970347
Requests/sec:  32238.29
Transfer/sec:      2.18MB
```

![image](https://user-images.githubusercontent.com/45788828/94454578-b5c40780-01ba-11eb-8011-2152110797f1.png)

2020-09-29 09:19 UTC, bmendli commented
-t1 -c1 -d30s -s ./wrk/get.lua --latency http://127.0.0.1:8080
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    27.19us   39.05us   4.11ms   99.30%
    Req/Sec    31.52k     2.11k   34.53k    75.42%
  Latency Distribution
     50%   24.00us
     75%   26.00us
     90%   31.00us
     99%   59.00us
  943905 requests in 30.10s, 63.91MB read
  Non-2xx or 3xx responses: 943905
Requests/sec:  31359.57
Transfer/sec:      2.12MB
```

cpu
![image](https://user-images.githubusercontent.com/45788828/94539505-f9b41c80-024d-11eb-92a0-01af75408631.png)

2020-09-29 09:24 UTC, bmendli commented
-t1 -c1 -d30s --latency http://127.0.0.1:8080/v0/status
```
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    31.50us  198.17us  13.17ms   99.75%
    Req/Sec    36.90k     4.34k   39.69k    93.69%
  Latency Distribution
     50%   23.00us
     75%   24.00us
     90%   28.00us
     99%   72.00us
  1104967 requests in 30.10s, 65.33MB read
Requests/sec:  36709.80
Transfer/sec:      2.17MB
```

cpu
![image](https://user-images.githubusercontent.com/45788828/94539984-9b3b6e00-024e-11eb-8c64-866a4206f24d.png)

2020-09-30 15:58 UTC, vaddya commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +                    ? Response.ok(getBytesFromByteBuffer(dao.get(ByteBuffer.wrap(id.getBytes(Charsets.UTF_8)))))
Чисто визуально предложил бы разнести кучу вызовов в переменные и на разные строки, пять закрывающих скобок в конце строки заставляют грустить

2020-09-30 15:58 UTC, vaddya commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +            e.printStackTrace();
Вызывать `e.printStackTrace()` это плохая практика, предлагаю воспользоваться одной из либ для логирования

2020-09-30 15:58 UTC, vaddya commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +                ? new Response(Response.BAD_REQUEST, Response.EMPTY)
Может лучше бы было в самих методах get/put/delete проверять, что `!id.isBlank()`? Кажется, что большой выгоды от `handleParam` нет, но логика при этом разъезжается на несколько методов. Но дело вкуса

2020-09-30 16:07 UTC, vaddya commented
`Non-2xx or 3xx responses: 970347` означает, что что-то идет не так. Нужно разбираться в причинах. Стрелять нужно сначала `PUT`ами, а затем `GET`ами по наполненной БД. Проводить профилирование нужно не только по `latency`, но и по `cpu` и `alloc`. Кроме того, помимо самих файлов нужен еще их анализ: на что тратится основное время/память. И будет лучше вкоммитить результаты, а не комментариями оставлять в ПР.

Если нет желания доводить профилирование до конца, можно согласиться на 5 из 10 баллов.

2020-09-30 16:31 UTC, vaddya requested changes
`Non-2xx or 3xx responses: 970347` означает, что что-то идет не так. Нужно разбираться в причинах. Стрелять нужно сначала `PUT`ами, а затем `GET`ами по наполненной БД. Проводить профилирование нужно не только по `latency`, но и по `cpu` и `alloc`. Кроме того, помимо самих файлов нужен еще их анализ: на что тратится основное время/память. И будет лучше вкоммитить результаты, а не комментариями оставлять в ПР.

Если есть желание, можно доделать профилирование до конца для максимального балла.

2020-09-30 18:03 UTC, bmendli commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +                ? new Response(Response.BAD_REQUEST, Response.EMPTY)
fixed

2020-09-30 18:03 UTC, bmendli commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +            e.printStackTrace();
fixed

2020-09-30 18:04 UTC, bmendli commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +                    ? Response.ok(getBytesFromByteBuffer(dao.get(ByteBuffer.wrap(id.getBytes(Charsets.UTF_8)))))
fixed

2020-09-30 18:06 UTC, bmendli commented
Профилирование переделаю, анализ сделаю, постараюсь сделать в ближайшее время

2020-10-02 19:44 UTC, bmendli commented
@vaddya Добавил к файлам проекта, прошу извинения за задержку.

2020-10-03 09:01 UTC, vaddya requested changes
Отчет неплохой, но есть недочеты:

- `wekGet.txt: 99.900% 1.84m` -- это хорошо, конечно, что мы укладываемся в 2 минуты, но я бы не стал использовать БД с таким latencty :) Очевидно, сервис не успевает обслуживать так много `GET` запросов (LSM Read Amplification), давайте снижать интенсивность запросов, пока не дойдем до сотен миллисекунд.
- `cpuPut.svg` -- треть флейм графа занимает C2 компиляция, это значит, что замеры производились до того, как JVM полностью прогрелась. Это влияет и на флейм граф, и на распределение latency. Еще видны JMX треды, отключайтесь во время замеров, чтобы результаты были более честными. Предлагаю перепрофилировать CPU PUT, предварительно прогрев JVM и дав отработать C2.
- Можно не тратить 5 минут на замеры, 30-60 секунд обычно хватает, чтобы оценить "горячие места".
- "Большую часть времени GET запроса составляет обработка запроса, и особенно действия связанные с файловой системой, **так же вывод стек трейса, если ключа в нашем dao не было**." -- Можно бросать свое исключение, которое [не будет собирать стектрейс](https://stackoverflow.com/a/25324497) (что-то вроде `NoSuchElementLiteException`). Но не уверен, что это часть первого этапа, давайте оставим на потом.

2020-10-04 18:07 UTC, bmendli commented
* Переделал профилирование и прогнал с врк 30 сек, профилирование особо улучшить не получилось(
* Своё исключение будет во 2 дз

2020-10-04 18:26 UTC, vaddya requested changes
Давайте все же как-то добьем ситуацию с `GET` запросами. Минутные latency это никуда не годится. Попробуйте уменьшать нагрузку, пока время не станет приемлемым (хотя бы секунды). Может быть проблема, что перед `GET` запросами стреляете **слишком** большим количеством `PUT` запросов? И DAO честно начинает искать по всем-всем флашнутым файлам и умирает от нагрузки?

Понимаю, что хочется ко второму этапу переходить, но там вам зададут точно такие же вопросы про `99.000% 1.77m`, лучше сейчас это решить.

2020-10-04 20:15 UTC, bmendli commented
@vaddya, извините, может я не совсем понял, а где сейчас хоть один результат с минутным временем? Я стрелял по 30 сек, и в ```GET``` запросах такие результаты:
```
Thread calibration: mean lat.: 0.884ms, rate sampling interval: 10ms
Thread Stats Avg Stdev Max +/- Stdev
Latency 0.87ms 441.29us 7.62ms 63.13%
Req/Sec 2.08k 132.12 2.60k 71.98%
Latency Distribution (HdrHistogram - Recorded Latency)
50.000% 0.87ms
75.000% 1.18ms
90.000% 1.50ms
99.000% 1.69ms
99.900% 1.77ms
99.990% 5.81ms
99.999% 7.62ms
100.000% 7.62ms
```

2020-10-04 20:20 UTC, bmendli commented
@vaddya, Вы скорее всего смотрели предыдущий коммит.

2020-10-04 20:30 UTC, vaddya approved these changes
Да, видимо не спулился, прошу прощения. Все ок.

Принято.

2020-10-04 20:30 UTC, closed without merging

2020-10-04 20:31 UTC, bmendli commented
@vaddya, ничего страшного, главное разобрались)
Спасибо!)