homework #1
polis-mail-ru/2020-highload-dht pull request #21
Opened 2020-09-29 15:38 UTC by Nekobitlz

2020-10-04 11:09 UTC, dormidon commented on build.gradle.kts
> +    implementation("com.github.Nekobitlz:2020-db-lsm:1.0")
👍

2020-10-04 11:10 UTC, dormidon commented on src/main/java/ru/mail/polis/service/ServiceImpl.java
> +            logger.debug("Failed to get data {}", request.getBody(), e);
Тут это, конечно, `error`, а не debug.

2020-10-04 11:10 UTC, dormidon commented on src/main/java/ru/mail/polis/service/ServiceImpl.java
> +            logger.error("Failed to find value by key {}", id);
Мне кажется, это не нужно логгировать как ошибку - ведь стандартная ситуация - пришли за ключом, а его нет.

2020-10-04 11:12 UTC, dormidon requested changes
Всё хорошо, но не могу найти отчета о нагрузочном тестировании и результатов профилирования под нагрузкой - это ведь основная часть этого задания.

2020-10-04 13:57 UTC, Nekobitlz commented
> Всё хорошо, но не могу найти отчета о нагрузочном тестировании и результатов профилирования под нагрузкой - это ведь основная часть этого задания.

Хорошо, сделаю

2020-10-09 09:06 UTC, dormidon commented
Доработок не поступило, без профиля в ведомость идет 5 баллов.

2020-10-09 09:06 UTC, closed without merging