hw1
polis-mail-ru/2020-highload-dht pull request #22
Opened 2020-09-29 15:45 UTC by gogun

2020-09-30 11:55 UTC, incubos requested changes
Нет профилирования аллокации памяти, под нагрузкой. На профиле CPU справа много красных вызовов JVM, возможно, это сборщик мусора -- нужно понять, откуда столько мусора.
Не хватает анализа результатов -- что вы видите на профилях и как интерпретируете полученные числа. Например, из профиля CPU очевидно, что много времени уходит на логгирование -- надо бы его временно выключить через `logback.xml`.
Стрельбы `GET` по одному ключу (да и его, видимо, нет) -- нужно стрелять после наполнения БД стрельбой из `PUT`ов.
Ждать результатов или 5 баллов из 10?

2020-09-30 11:55 UTC, incubos commented on profiling_and_loading/wrk_entity_get_test
> +  Non-2xx or 3xx responses: 2521573
Здесь же одни ошибки -- вы по пустой БД стреляли?

2020-09-30 11:55 UTC, incubos commented on profiling_and_loading/wrk_entity_get_test
> +  Non-2xx or 3xx responses: 2521573
`GET`ами нужно стрелять после `PUT`.

2020-09-30 11:55 UTC, incubos commented on profiling_and_loading/wrk_entity_put
> +  439801 requests in 20.01s, 28.10MB read
Вы успели попрофилировать за 20 с?

2020-09-30 11:55 UTC, incubos commented on profiling_and_loading/wrk_entity_get_test
> +Running 2m test @ http://127.0.0.1:8080/v0/entity?id=1
Всё время запрашивали одну и ту же сущность? Это выглядит несколько искусственно.

2020-09-30 12:12 UTC, gogun commented
> Нет профилирования аллокации памяти, под нагрузкой. На профиле CPU справа много красных вызовов JVM, возможно, это сборщик мусора -- нужно понять, откуда столько мусора.
> Не хватает анализа результатов -- что вы видите на профилях и как интерпретируете полученные числа. Например, из профиля CPU очевидно, что много времени уходит на логгирование -- надо бы его временно выключить через `logback.xml`.
> Стрельбы `GET` по одному ключу (да и его, видимо, нет) -- нужно стрелять после наполнения БД стрельбой из `PUT`ов.
> Ждать результатов или 5 баллов из 10?

Хорошо, попробую исправить

2020-10-01 20:48 UTC, gogun commented on profiling_and_loading/wrk_entity_get_test
> +Running 2m test @ http://127.0.0.1:8080/v0/entity?id=1
Согласен, исправил.

2020-10-01 20:50 UTC, gogun commented on profiling_and_loading/wrk_entity_put
> +  439801 requests in 20.01s, 28.10MB read
да, у `async-profiler` -d 10, поэтому укладывался, но в исправленной версии сделал все нагрузочные тесты по 100s

2020-10-01 20:51 UTC, gogun commented on profiling_and_loading/wrk_entity_get_test
> +  Non-2xx or 3xx responses: 2521573
поправил, теперь `GET` корректный.

2020-10-01 22:23 UTC, gogun commented
UPD:
Добавил скрипт для `GET`  запросов, теперь стрельба идет по наполненной БД и по разным ключам. Добавил скриншоты из visualvm с heap'ом во время нагрузки для каждого вида запросов. alloc async-profiler'а выплевывал пустой flamegraph, починить не получилось. Выключил логгирование. По поводу красных вызовов jvm, добавил опции VM, повышающие точность профилирования, вызовы стали занимать меньше процессора.

2020-10-03 14:19 UTC, incubos commented
Принято.

2020-10-03 14:19 UTC, closed without merging