Stage 1
polis-mail-ru/2020-highload-dht pull request #23
Opened 2020-09-29 16:13 UTC by JavaUnchained

2020-09-29 17:44 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +            log.error("Method get. IO exception. ", e);
fix

2020-09-29 17:45 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        } catch (NoSuchElementException e){
fix

2020-09-30 20:40 UTC, vaddya requested changes
Есть небольшие замечания по реализации. Не вижу результатов профилирования, будут?

2020-09-30 20:40 UTC, vaddya commented on build.gradle.kts
> +    compile("org.rocksdb", "rocksdbjni", "6.2.2")
Предлагаю убрать лишние комментарии и поднять версию, 6.11.x уже пару месяцев как доступна

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +    public static class RecordIterator implements Iterator<Record>, AutoCloseable {
Может в отдельный класс его, посвободнее будет?

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +    protected static final Logger log = LoggerFactory.getLogger(DAOImpl.class);
Статические поля должны быть выше пропертей

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            final var record = Record.of(bufferKey, bufferValue);
Я бы не стал смешивать явно указываемые типы и `var`, может заменим тут на `Record`?

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +    private static byte[] converBytes(@NotNull final ByteBuffer key) {
`convert`?

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            options.setMaxBackgroundFlushes(2);
Сеттеры этого класса возвращают сам инстанс, можно красивенько
```java
final var options = new Options()
        .setCreateIfMissing(true)
        .setCompressionType(CompressionType.NO_COMPRESSION);
...
```

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            wOptions.setDisableWAL(true);
Это точно хорошая идея с точки зрения надежности?

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/utils/BufferConverter.java
> +    public static byte[] unfoldToBytes(@NotNull final ByteBuffer key) {
А они с одноименным статическим методом из `DAOImpl` как-нибудь связаны? Может единообразно перетащить все утильные методы сюда?

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        response.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Удобнее не самому заполнять этот заголовок, а передать в конструктор `Response` второй аргумент `Response.EMPTY`. В этом случае не придется самому указывать длину.

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +            throw new RuntimeException(e);
Плохая практика -- просто пробрасывать исключение дальше. Предлагаю
1. Логировать непредвиденные исключения, это очень пригодится на следующих этапах.
2. В случае исключения явно формировать `Response` со статусом 500

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        if (id.isEmpty()) {
Будет спокойнее, если еще проверим на `null`

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +    @SuppressWarnings("UnsynchronizedOverridesSynchronized")
Может просто оставим метод `synchronized`?

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        session.sendResponse(new Response(Response.BAD_REQUEST, new byte[0]));
`Response.EMPTY`

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        final byte[] bytes = BufferConverter.unfoldToBytes(value);
Предлагаю спрятать все манипуляции с байтами на уровень `DAO`. Пусть сервис только принимает запросы и тупо отвечает тем, что получил от `DAO`.

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +    public ServiceImpl(final HttpServerConfig config, final DAO dao, final Object... routers) throws IOException {
Не очень понял, зачем нужны `routers`.

2020-09-30 20:40 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            log.error("Remove error: ",e);
Пробел пропал

2020-09-30 20:45 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/utils/BufferConverter.java
> +        final byte[] bytes = new byte[key.limit()];
Тут, кстати, надо не `limit()`, а `remaining()`

2020-09-30 20:48 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        final AcceptorConfig acceptorConfig = new AcceptorConfig();
Советую спрятать настрйку конфига и создание сервиса в статический метод внутрь `ServiceImpl`, и здесь только вызвать этот метод.

2020-09-30 20:49 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/utils/BufferConverter.java
> +        key.clear();
Если что-то деструктивное делаешь с `ByteBuffer`, лучше сделать `duplicate()` перед этим.

2020-10-02 11:55 UTC, JavaUnchained commented
> Есть небольшие замечания по реализации. Не вижу результатов профилирования, будут?
Не видел уведомлений что проверялось ревью. Профилирование добавлю замечания исправлю ( сегодня вечером этим займусь)

2020-10-02 17:10 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/utils/BufferConverter.java
> +        key.clear();
исправил

2020-10-02 17:10 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/utils/BufferConverter.java
> +        final byte[] bytes = new byte[key.limit()];
исправил

2020-10-02 17:16 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +    private static byte[] converBytes(@NotNull final ByteBuffer key) {
Поправил очепятку)

2020-10-02 17:17 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            final var record = Record.of(bufferKey, bufferValue);
поправил

2020-10-02 17:18 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +    protected static final Logger log = LoggerFactory.getLogger(DAOImpl.class);
Поправил

2020-10-02 17:29 UTC, JavaUnchained commented on build.gradle.kts
> +    compile("org.rocksdb", "rocksdbjni", "6.2.2")
Сделал

2020-10-02 17:34 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        final AcceptorConfig acceptorConfig = new AcceptorConfig();
поправил

2020-10-02 17:34 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            log.error("Remove error: ",e);
поправил

2020-10-02 17:35 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +    public ServiceImpl(final HttpServerConfig config, final DAO dao, final Object... routers) throws IOException {
поправил

2020-10-02 17:36 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +    @SuppressWarnings("UnsynchronizedOverridesSynchronized")
исправил

2020-10-02 17:37 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        if (id.isEmpty()) {
поправил

2020-10-02 17:39 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            wOptions.setDisableWAL(true);
поправил

2020-10-02 17:40 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            options.setMaxBackgroundFlushes(2);
поправил

2020-10-02 17:42 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +    public static class RecordIterator implements Iterator<Record>, AutoCloseable {
поправил

2020-10-02 17:46 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/utils/BufferConverter.java
> +    public static byte[] unfoldToBytes(@NotNull final ByteBuffer key) {
Готово, вынес их в тот же класс.

2020-10-02 17:48 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +            throw new RuntimeException(e);
Добавил

2020-10-02 17:55 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        session.sendResponse(new Response(Response.BAD_REQUEST, new byte[0]));
исправил

2020-10-02 17:59 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        response.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
поправил

2020-10-02 18:10 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            wOptions.setDisableWAL(true);
Не правда

2020-10-02 18:11 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kovalkov/RecordIterator.java
> +}
Хорошая практика -- оставлять [пустую строку в конце файла](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

2020-10-02 18:14 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        final byte[] bytes = BufferConverter.unfoldToBytes(value);
Немного неестественно выглядит, я бы занес эту и строку ниже в блок `try`. Тогда и объявление переменной `value` не придется разделять с инициализацией.

2020-10-02 19:45 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/RecordIterator.java
> +}
сделано

2020-10-02 19:47 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        final byte[] bytes = BufferConverter.unfoldToBytes(value);
сделал

2020-10-02 19:59 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        if (id.isEmpty() || id == null) {
может тогда удалить id == null ?

2020-10-02 20:00 UTC, JavaUnchained commented
Добавил в папку proffiling 
![image](https://user-images.githubusercontent.com/45318753/94964846-14fb8200-0503-11eb-97bd-7b87d8e1d05d.png)

2020-10-02 20:53 UTC, JavaUnchained commented on src/main/java/ru/mail/polis/dao/kovalkov/DAOImpl.java
> +            wOptions.setDisableWAL(true);
Теперь точно поправил

2020-10-03 09:28 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kovalkov/ServiceImpl.java
> +        return Response.ok(bytes);
Почему бы это тоже не оставить в `try` блоке? И занести внутрь объявление переменных `value` и `bytes`. Сейчас последовательность действий разбивается аж на три блока -- объявления, блок `try` и `return`, будет лучше, если они будут рядом

2020-10-03 09:36 UTC, vaddya requested changes
Реализация ОК, по профилированию вопросы. Цитирую @incubos из чата курса: "Нужно вкоммитить результаты нагрузочного тестирования через `wrk2` (`put` и `get`, параметры запуска и гистограммы времён ответа сервиса), результаты профилирования `cpu` и `alloc` под нагрузкой (файлы `svg`), а также их краткий анализ в виде текстового файла `Markdown`." Из этого сразу следуют вопросы: Почему флейм граф один? Какой HTTP метод сервиса дергался? Где на графе ваш код? Где отчеты `wrk2` и анализ результатов?

2020-10-03 16:53 UTC, JavaUnchained commented
> Реализация ОК, по профилированию вопросы. Цитирую @incubos из чата курса: "Нужно вкоммитить результаты нагрузочного тестирования через `wrk2` (`put` и `get`, параметры запуска и гистограммы времён ответа сервиса), результаты профилирования `cpu` и `alloc` под нагрузкой (файлы `svg`), а также их краткий анализ в виде текстового файла `Markdown`."
> 
> Из этого сразу следуют вопросы: Почему флейм граф один? Какой HTTP метод сервиса дергался? Где на графе ваш код? Где отчеты `wrk2` и анализ результатов?

Добавил графики для put и get для alloc и cpu, выложил луа скрипты и написал мини записку results.md

2020-10-03 17:03 UTC, vaddya approved these changes
Принято

2020-10-03 17:03 UTC, closed without merging