Stage 1. HTTP + storage
polis-mail-ru/2020-highload-dht pull request #24
Opened 2020-09-29 16:27 UTC by shakirov-aa

2020-09-29 21:17 UTC, shakirov-aa commented
### **Отчёт про профилированию под нагрузкой cpu и alloc**

**PUT запросы**
```
wrk -t1 -c1 -d10m -s put.lua --latency http://127.0.0.1:8080
Running 10m test @ http://127.0.0.1:8080
  1 threads and 1 connections
^C  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    38.88us  357.94us  13.82ms   99.47%
    Req/Sec    45.19k     7.13k   49.98k    92.32%
  Latency Distribution
     50%   16.00us
     75%   16.00us
     90%   19.00us
     99%   55.00us
  2590662 requests in 1.31m, 165.53MB read
  Socket errors: connect 0, read 0, write 0, timeout 8
Requests/sec:  32947.01
Transfer/sec:      2.11MB
```
Большой stdev, вероятно, получился из-за того, что в какой-то момент у нас происходит очистка мусора + запись на диск, а при этом приложение у нас однопоточное.

**cpu_put**
Действительно, запись на диск довольно затратна - занимает 40%
![Screenshot from 2020-09-30 00-02-59](https://user-images.githubusercontent.com/47986788/94615385-53e5c980-02b0-11eb-820c-a3062505d32c.png)

**alloc_put**
![Screenshot from 2020-09-30 00-03-50](https://user-images.githubusercontent.com/47986788/94615450-724bc500-02b0-11eb-9be7-eeb71f9dc17d.png)

**GET запросы**
```
wrk -t1 -c1 -d10m -s get.lua --latency http://127.0.0.1:8080
Running 10m test @ http://127.0.0.1:8080
  1 threads and 1 connections
^C  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   499.61us   96.89us  15.06ms   93.13%
    Req/Sec     1.98k   112.05     2.34k    81.70%
  Latency Distribution
     50%  477.00us
     75%  511.00us
     90%  564.00us
     99%  771.00us
  566227 requests in 6.91m, 39.84MB read
  Socket errors: connect 0, read 1, write 7091437, timeout 0
Requests/sec:   1365.71
Transfer/sec:     98.41KB
```
Тут stdev хотя и меньше, но всё равно высокий.

**cpu_get**
96% занимает поиск.
![Screenshot from 2020-09-30 00-06-45](https://user-images.githubusercontent.com/47986788/94615707-e0908780-02b0-11eb-89b2-b65cf1bc32b8.png)

**alloc_get**

![Screenshot from 2020-09-30 00-07-54](https://user-images.githubusercontent.com/47986788/94615795-0322a080-02b1-11eb-8d4d-de358c825e49.png)

2020-10-03 22:43 UTC, lamtev requested changes
Отчет по профилированию мне понравился 👍🏻
После небольших правок по коду и ответа на вопросы PR будет принят

2020-10-03 22:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +import com.google.common.base.Charsets;
Почему не `java.nio.charset.StandardCharsets` ?

2020-10-03 22:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(MyHttpServer.class);
Обычно `log` называют

2020-10-03 22:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +        if (port <= 0 || port >= 65536) {
Данная проверка избыточна здесь, т.к. уже проводится уровнем выше в `ServiceFactory`

2020-10-03 22:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +        config.selectors = 4;
Почему 4?

2020-10-03 22:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +        if (id == null || id.isEmpty()) {
Проверку на `null` можно заменить добавлением в `@Param` параметра `required = true` для `id`

2020-10-03 22:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +                    final ByteBuffer duplicate = value.duplicate();
`duplicate` здесь необходим или "на всякий случай" ?)

2020-10-03 22:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +            return new Response(Response.INTERNAL_ERROR, Response.EMPTY);
Раз есть логгер, то стоит эту ситуацию залоггировать

2020-10-04 08:47 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +                    final ByteBuffer duplicate = value.duplicate();
> `duplicate` здесь необходим или "на всякий случай" ?)

Необходим, так как если не делать duplicate, по ошибке может произойти перезапись в БД ("не наш" ByteBuffer). Однако если аккуратно за этим следить, ничего не произойдёт :)
Однако duplicate дорогостоящая операция... Учитывая это, стоит ли её убрать?

2020-10-04 08:48 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +import com.google.common.base.Charsets;
> Почему не `java.nio.charset.StandardCharsets` ?

Ошибка импорта, исправил

2020-10-04 08:48 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(MyHttpServer.class);
> Обычно `log` называют

Исправил

2020-10-04 08:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +        if (port <= 0 || port >= 65536) {
> Данная проверка избыточна здесь, т.к. уже проводится уровнем выше в `ServiceFactory`

Исправил

2020-10-04 08:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +        if (id == null || id.isEmpty()) {
> Проверку на `null` можно заменить добавлением в `@Param` параметра `required = true` для `id`

Исправил

2020-10-04 08:49 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +            return new Response(Response.INTERNAL_ERROR, Response.EMPTY);
> Раз есть логгер, то стоит эту ситуацию залоггировать

Добавил логирование

2020-10-04 08:58 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +        config.selectors = 4;
> Почему 4?

Насколько я понимаю, selectors отвечает за количество используемых ядер. Хотел, чтобы БД использовала 4 ядра. Уточнил этот момент, оказывается one-nio сама оптимизирует это дело (привожу кусок кода из one-nio).
```
        int processors = Runtime.getRuntime().availableProcessors();
        SelectorThread[] selectors = new SelectorThread[config.selectors != 0 ? config.selectors : processors];
        for (int i = 0; i < selectors.length; i++) {
            selectors[i] = new SelectorThread(i, config.affinity ? i % processors : -1);
            selectors[i].setPriority(config.threadPriority);
        }
        this.selectors = selectors;
```

Поэтому решил удалить
`config.selectors = 4;`

2020-10-04 12:18 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +                    final ByteBuffer duplicate = value.duplicate();
Javadoc говорит, что `duplicate` создает новый буфер, который разделяет контент с исходным. То есть это не deep-copy. Но значения `position`, `limit`, `mark`, `capacity`, ссылка на байтики продублируются. Т.е. дорогостоящей операцией я бы это не назвал. O(1) и по памяти, и по времени

> по ошибке может произойти перезапись в БД
Можно поподробнее, пожалуйста? Вроде бы из базы возвращаются `asReadOnlyBuffer()`, в них нельзя писать. А даже если бы и было можно, то `duplicate()` от этого бы не спас, т.к. контент разделяемый, и изменения в дубликате затронули бы исходный.

2020-10-04 12:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +                    final ByteBuffer duplicate = value.duplicate();
Понял, спасибо!

2020-10-04 12:20 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +                    final ByteBuffer duplicate = value.duplicate();
В таком случае думаю логичным оставить duplicate

2020-10-04 12:20 UTC, lamtev commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +            log.error("Key(id) = {} not found: {}", id, e);
не ошибка, а нормальная ситуация

2020-10-04 12:24 UTC, shakirov-aa commented on src/main/java/ru/mail/polis/service/shakirov/MyHttpServer.java
> +            log.error("Key(id) = {} not found: {}", id, e);
> не ошибка, а нормальная ситуация

Исправил уровень логгирования на info

2020-10-04 12:37 UTC, lamtev reviewed
Обратил внимание сейчас на то, что из аутпута `wrk` из latency distribution были убраны результаты для большего числа девяток. Там были какие-то проблемы?) Обстрел `PUT` выполняется с довольно большой нагрузкой 40+к r/s. Вероятно, задержки могли быть сильно бОльшими, чем на 2 девятках

2020-10-04 12:43 UTC, shakirov-aa commented
> Обратил внимание сейчас на то, что из аутпута `wrk` из latency distribution были убраны результаты для большего числа девяток. Там были какие-то проблемы?) Обстрел `PUT` выполняется с довольно большой нагрузкой 40+к r/s. Вероятно, задержки могли быть сильно бОльшими, чем на 2 девятках

Не понимаю "из latency distribution были убраны результаты для большего числа девяток". Ничего намеренно не убирал. Обстрел делал на wrk, а не на wrk2 (возможно, это вас смутило).

2020-10-04 13:09 UTC, lamtev commented
> Не понимаю "из latency distribution были убраны результаты для большего числа девяток". Ничего намеренно не убирал. Обстрел делал на wrk, а не на wrk2 (возможно, это вас смутило).

Конечно, надо было воспользоваться `wrk2`, об этом говорилось на лекции. `wrk2` позволяет задать rate подаваемой нагрузки, а также предоставляет более точные данные по задержкам. В будущем прошу использовать именно `wrk2`

2020-10-04 13:09 UTC, lamtev approved these changes

2020-10-04 13:09 UTC, lamtev commented
Принятно

2020-10-04 13:09 UTC, closed without merging

2020-10-04 13:10 UTC, shakirov-aa commented
> > Не понимаю "из latency distribution были убраны результаты для большего числа девяток". Ничего намеренно не убирал. Обстрел делал на wrk, а не на wrk2 (возможно, это вас смутило).
> 
> Конечно, надо было воспользоваться `wrk2`, об этом говорилось на лекции. `wrk2` позволяет задать rate подаваемой нагрузки, а также предоставляет более точные данные по задержкам. В будущем прошу использовать именно `wrk2`

Понял, учту, спасибо