First stage
polis-mail-ru/2020-highload-dht pull request #28
Opened 2020-09-29 22:25 UTC by KirKungurov

2020-09-30 21:04 UTC, vaddya requested changes
Реализация ОК. Результатов профилирования не вижу, будут?

2020-10-05 13:45 UTC, KirKungurov commented on src/main/java/ru/mail/polis/service/kirkungurov/HttpService.java
> +            if (id.length() == 0) {
А у нас разве может вернуться null? Если будет пустая строка, например, v0/entity?id=&foo=acr, то id будет равен ""

Ну и плюс идея возвращает id != null как код, который всегда true

2020-10-05 13:45 UTC, KirKungurov commented on src/main/java/ru/mail/polis/service/kirkungurov/HttpService.java
> +        } catch (NoSuchElementException exc) {
fix

2020-10-07 06:37 UTC, vaddya commented
Результатов профилирования за 2 недели не появилось, поэтому принято частично.

2020-10-07 06:37 UTC, closed without merging