Stage2
polis-mail-ru/2020-highload-dht pull request #29
Opened 2020-10-03 22:41 UTC by bmendli

2020-10-05 19:33 UTC, bmendli commented
Результаты профилирования будут попозже

2020-10-09 19:38 UTC, vaddya requested changes
Профилирование хорошо, несколько предложений по реализации

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/DAOImpl.java
> +        this.executorService.execute(() -> {
Может лучше вынести это всю логику в метод? И запустить потом `this.executorService.execute(this::flush);`

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/DAOImpl.java
> +    private final Logger logger = LoggerFactory.getLogger(DAOImpl.class);
Тут и в других классах -- по канону лучше
`private static final Logger log = LoggerFactory.getLogger(DAOImpl.class)`

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/DAOImpl.java
> +    private final ReadWriteLock readWriteLock;
Может просто `lock`?

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            logger.error("error put flush table {} int blocking queue", flushTable, e);
Сообщение было сгенерировано нейросетью? :) 
У `FlushTable` нет нормального метода `toString()`

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +    private final BlockingQueue<FlushTable> blockingQueue;
Мне кажется, что не лучшее название, не объясняет, зачем нужна. Может `flushQueue` или что-то такое?

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/NoSuchElementExceptionLightWeight.java
> +public class NoSuchElementExceptionLightWeight extends NoSuchElementException {
Дело стиля и вкуса, но
1) Можно без `Weight`, и так длинное название
2) `Exception` должно быть последним -- более менее все экспешены в Java имеют такой суффикс
Итого, я бы предложил заменить на `NoSuchElementLightException`

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +            logger.error("Does not exist record by id = {}", id, e);
В целом, я бы не сказал, что это ошибка для хранилища. Нет и нет. Но для дебага можно и оставить

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +        config.selectors = 4;
Подбирали как-то эту константу? Может тут от `Runtime.getRuntime().availableProcessors()` отталкиваться?

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            tempSize.set(currentMemTable.size());
Это точно безопасно? Несколько читателей в параллель могут начать считать размер и перетерать значения друг друга. И все из-за состояния. Поле `tempSize` точно нужно? С виду это локальная перменная, причем можно не атомик даже, тут все последоватльно.

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            throw new IllegalStateException();
Не стоит кидать исключения без сообщений.

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +    private final AtomicBoolean stop;
`stopped` или `isStopped`, кажется, более подходящие названия

2020-10-09 19:38 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            waitingFlushTables.descendingMap().values().forEach(table -> {
А нам важно получить итераторы именно в порядке убывания?

2020-10-09 21:03 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +    private volatile MemTable currentMemTable;
А зачем переменная `volatile`?

2020-10-10 10:04 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            logger.error("error put flush table {} int blocking queue", flushTable, e);
Невнимательно копипастнул текст)

2020-10-10 10:10 UTC, bmendli commented on src/main/java/ru/mail/polis/service/bmendli/MyService.java
> +        config.selectors = 4;
В начале так и делал, но подумал, что может быть много селекторов, не совсем наверное это нужно в наших заданиях, но хорошо, переделаю

2020-10-10 10:13 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            tempSize.set(currentMemTable.size());
то что переменная локальная может быть - да. Значение бы не перетералось, здесь лок стоит

2020-10-10 10:50 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            tempSize.set(currentMemTable.size());
Разве два читателя не могут зайти в эту секцию?

2020-10-10 11:08 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            tempSize.set(currentMemTable.size());
так если здесь лок стоит, то одновременно не могут же, и tempSize нужна была только в пределах лока. Поэтому когда один поток выходит из лока ему уже всё равно что в этом tempSize и его можно спокойно перезаписать

2020-10-10 11:09 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            tempSize.set(currentMemTable.size());
Вы видимо не до конца осознали концепцию `ReadWriteLock`. Несколько читателей **могут** находиться в критической секции, а здесь вы берете именно рид лок.

2020-10-10 11:13 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +    private volatile MemTable currentMemTable;
Вообще, чтобы работать всегда с актуальной MemTable и не кэшировались таблицы у потоков, иначе может быть такое, что какой-то поток попытается положить в него данные, а на самом деле эта MemTable уже давно на флаш отдана

2020-10-10 11:18 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +    private volatile MemTable currentMemTable;
Все правильно говорите про `volatile`. Но на самом деле, чтение `currentMemTable` тоже нужно прикрывать локом, иначе пока мы флашим таблицу, в нее могут успеть вставить больше данных, чем было во время начала флаша, и сериалиация сломается. Тесты, которые бы отлавливали такую ситуацию написать сложно, но такая ситуация возможна.

Итого, по хорошему нужно прикрыть обращения к `currentMemTable` рид локом и убрать `volatile` за ненадобностью.

2020-10-10 11:19 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +            tempSize.set(currentMemTable.size());
Всё, осознал свою проблему. Был не прав что только 1 поток может зайти в секцию

2020-10-10 11:29 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +    private volatile MemTable currentMemTable;
Понятно, спасибо большое, пошёл править)

2020-10-10 12:01 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +        lock.writeLock().lock();
Ой, level of concurrency ушел в ноль. При такой реализации, мы будем делать все операции буквально последоватльно.

В `upsert`/`remove` хватит рид лока, нам нужно только исключить ситуацию, когда `enqueueToFlush` под райт локом меняют `currentMemTable`, а мы еще пытаемся запихнуть в нее еще записей, потому что не захватили лок (в реализации с `volatile`). Для этого достаточно захватывать рид лок в этих методах.

2020-10-10 12:15 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +        lock.writeLock().lock();
Можете, пожалуйста, после этого еще раз попрофилировать `lock` для гет запросов? Убедимся, что ничего не сломали

2020-10-10 13:14 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +        lock.writeLock().lock();
Хорошо

2020-10-10 15:11 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +        lock.writeLock().lock();
На использование `readLock()` то перейдем в `upsert`/`remove`?

2020-10-10 19:12 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +        lock.writeLock().lock();
моя невнимательность меня подвела, сори(

2020-10-10 19:28 UTC, bmendli commented on src/main/java/ru/mail/polis/dao/bmendli/MemTablePool.java
> +        lock.writeLock().lock();
профилирование чуть позже сделаю

2020-10-11 12:10 UTC, vaddya approved these changes
Принято.

2020-10-11 12:10 UTC, closed without merging