stage 1
polis-mail-ru/2020-highload-dht pull request #3
Opened 2020-09-26 20:55 UTC by StasyanOi

2020-09-27 09:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    /**
fixed

2020-09-27 09:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +     * @param idParam
fixed

2020-09-27 09:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/IteratorImpl.java
> +    public IteratorImpl(ByteBuffer key, RocksIterator rocksIterator) {
fixed

2020-09-27 09:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/IteratorImpl.java
> +        byte[] key = rocksIterator.key();
fixed

2020-09-27 09:52 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +import one.nio.http.Param;
fixed

2020-09-27 09:52 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +import one.nio.http.Param;
fixed

2020-09-27 09:52 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    private Iterator<Record> getIterator(final @NotNull ByteBuffer from){
fixed

2020-09-27 09:52 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +            System.err.println("compact");
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +            System.out.println("compact");
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/status")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/abracadabra")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @NotNull
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/status")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/abracadabra")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @NotNull
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    public DAOImpl(final File data) {
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/status")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/abracadabra")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @NotNull
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    public DAOImpl(final File data) {
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/status")
fixed

2020-09-27 09:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/abracadabra")
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @NotNull
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            badReqResponse.addHeader(HttpHeaders.CONTENT_LENGTH + ": 0");
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    public DAOImpl(final File data) {
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/status")
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/abracadabra")
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @NotNull
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/ServiceImpl.java
> +    public ServiceImpl(CustomServer customServer) {
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    @Path("/v0/entity")
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/IteratorImpl.java
> +        byte[] value = rocksIterator.value();
fixed

2020-09-27 09:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/IteratorImpl.java
> +    public IteratorImpl(ByteBuffer key, RocksIterator rocksIterator) {
fixed

2020-10-04 12:18 UTC, gopito requested changes
Не нашел скриптов для wrk, которыми пуляли. 
Зачем в команде для put 
./wrk2/wrk -t1 -c1 -d15s -R2000 -s ./wrk2/scripts/put.lua --u_latency http://localhost:8080/v0/entity?id=100 > wrkLogsPut.txt &

нужен id=100  ?

Хотелось бы выводов в отчете.

2020-10-04 12:34 UTC, gopito requested changes

2020-10-04 12:34 UTC, gopito commented on logs_pics/put.lua
> +wrk.method = "PUT"
Идет запись по одному ключу, как можно исправить?

2020-10-04 12:41 UTC, StasyanOi commented on logs_pics/put.lua
> +wrk.method = "PUT"
$RANDOM подставить в скрипт вместо 100

2020-10-04 13:15 UTC, StasyanOi commented on logs_pics/put.lua
> +wrk.method = "PUT"
Либо в луа файле можно сделать ключ и там его инкрементить

2020-10-04 13:49 UTC, StasyanOi commented on logs_pics/put.lua
> +wrk.method = "PUT"
@gopito,  допилил луа файл. Теперь там инкрементится ключ. Так же подправил wrk скрипт в соответствии с новым луа файлом.

2020-10-04 19:23 UTC, gopito approved these changes

2020-10-06 07:19 UTC, closed without merging

2020-10-12 23:21 UTC, gopito reviewed
Поставил 9 за 1 этап