Part1.
polis-mail-ru/2020-highload-dht pull request #30
Opened 2020-10-04 19:39 UTC by Valaubr

Сдаю сейчас т.к. просил отсрочку у Вадима Цесько (@incubos )

2020-10-05 09:49 UTC, incubos requested changes
Нет результатов нагрузочного тестирования (`PUT`, а затем `GET` по наполненной БД) с помощью `wrk2`, результатов профилирования `cpu` и `alloc` под обоими типами нагрузки, а также вашей собственной интерпретации результатов. Будете доделывать (дедлайн в полночь со вт на ср) или 5 баллов?

2020-10-05 09:49 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> -            throw new IllegalStateException("The heap is too big. Consider setting Xmx.");
Зачем это изменение?

2020-10-05 09:49 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> -            throw new IllegalArgumentException("Path doesn't exist: " + data);
Зачем это изменение?

2020-10-05 09:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/valaubr/HttpService.java
> +    /**
К private полям JavaDoc обычно не пишут. Да и нужен ли тут комментарий? `DAO` везде `DAO`.

2020-10-05 09:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/valaubr/HttpService.java
> +     * slf4j logger.
Какую пользу несёт этот комментарий?

2020-10-05 14:09 UTC, Valaubr commented on src/main/java/ru/mail/polis/service/valaubr/HttpService.java
> +     * slf4j logger.
Я подключил checkstyle у себя в идее просто, кодстайл от Sun Microsystem не проходили :)

2020-10-06 21:36 UTC, incubos commented
К сожалению, не успели. Принято за 5 баллов.

2020-10-06 21:36 UTC, closed without merging