Stage2
polis-mail-ru/2020-highload-dht pull request #32
Opened 2020-10-05 13:12 UTC by KateMoreva

2020-10-06 11:23 UTC, KateMoreva commented
Анализ результатов тестирования будет добавлен чуть позже.

2020-10-06 20:10 UTC, KateMoreva commented
### PUT запросы 

-t10 -c20 -d30s -R2000 -s ./wrk/put.lua --latency http://localhost:8080

CPU
<img src = "https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/4cc12d11a93b7ddcd197d967c1684ce153c5e445/tests/threadSave/cpuPut.svg"> 

Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.06ms  445.81us  11.40ms   66.94%
    Req/Sec   213.28     34.60   444.00     88.85%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.07ms
 75.000%    1.33ms
 90.000%    1.64ms
 99.000%    2.00ms
 99.900%    2.17ms
 99.990%   10.51ms
 99.999%   11.41ms
100.000%   11.41ms
  60010 requests in 30.00s, 3.83MB read
Requests/sec:   2000.23
Transfer/sec:    130.87KB

Для каждого из селекторов (0-7)
Обработка http запроса не более 13.25%
Запись в сокет не более 6.37%
Чтение из сокета не более 2.21%
DAO upsert занимает менее 1.1%

Alloc
<img src = "https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/4cc12d11a93b7ddcd197d967c1684ce153c5e445/tests/threadSave/allocPut.svg"> 

  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.08ms  428.02us   4.24ms   63.26%
    Req/Sec   213.86     36.56   333.00     87.36%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.11ms
 75.000%    1.36ms
 90.000%    1.65ms
 99.000%    1.95ms
 99.900%    2.12ms
 99.990%    2.88ms
 99.999%    4.25ms
100.000%    4.25ms
  60010 requests in 30.00s, 3.83MB read
Requests/sec:   2000.21
Transfer/sec:    130.87KB

Для каждого из селекторов (0-7)
Http буфер занимает не более 24.89%
Обработчик не более 13.92%
Отправка Response не более 2.95%
DAO.upsert не более 3.38%

Flush теперь асинхронный, поэтому нет резкого возрастания времени обработки запросов, как это было в предыдущем случае.

2020-10-06 20:12 UTC, KateMoreva commented
Lock для Put запросов  

 -t10 -c20 -d1s -R2000 -s ./wrk/put.lua --latency http://localhost:8080

<img src = "https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/4cc12d11a93b7ddcd197d967c1684ce153c5e445/tests/threadSave/lockPut2000_1s_20c_10t.svg">

Running 1s test @ http://localhost:8080
  10 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.40ms    6.26ms  48.86ms   95.49%
    Req/Sec       -nan      -nan   0.00      0.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.17ms
 75.000%    1.41ms
 90.000%    1.76ms
 99.000%   39.87ms
 99.900%   47.97ms
 99.990%   48.90ms
 99.999%   48.90ms
100.000%   48.90ms
  2007 requests in 999.55ms, 131.32KB read
Requests/sec:   2007.89
Transfer/sec:    131.38KB

Блокировки работают только при записи объектов.
Причем блокировки потоки не держат долго. Под блокировкой проходит только минимальная необходимая работа.
(Увидеть блокировки удалось увидеть на непрогретой машине за минимальное возможное время - 1 секунду)

2020-10-06 20:17 UTC, KateMoreva commented
### GET запросы

-t10 -c20 -d30s -R2000 -s ./wrk/get.lua --latency http://localhost:8080

**CPU**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/4cc12d11a93b7ddcd197d967c1684ce153c5e445/tests/threadSave/cpuGet.svg">
Running 30s test @ http://localhost:8080
  10 threads and 20 connections
  rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.11ms  428.67us  10.35ms   65.74%
    Req/Sec   212.13     30.20   400.00     91.61%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.14ms
 75.000%    1.38ms
 90.000%    1.65ms
 99.000%    1.99ms
 99.900%    2.22ms
 99.990%    6.35ms
 99.999%   10.36ms
100.000%   10.36ms
  60010 requests in 30.00s, 4.05MB read
Requests/sec:   2000.23
Transfer/sec:    138.33KB

Для каждого из селекторов (0-7)
Обработка http запроса не более 13.38%
Запись в сокет не более 6.37%
Чтение из сокета не более 1.78%
DAO get не более 2.29%

**Alloc**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/4cc12d11a93b7ddcd197d967c1684ce153c5e445/tests/threadSave/allocGet.svg">

Running 30s test @ http://localhost:8080
  10 threads and 20 connections
  rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.15ms  526.81us  14.02ms   65.53%
    Req/Sec   212.30     31.78   500.00     90.83%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.19ms
 75.000%    1.51ms
 90.000%    1.76ms
 99.000%    2.01ms
 99.900%    3.46ms
 99.990%   12.83ms
 99.999%   14.03ms
100.000%   14.03ms
  60010 requests in 30.00s, 4.05MB read
Requests/sec:   2000.23
Transfer/sec:    138.33KB

Для каждого из селекторов (0-7)
Http буфер не более 19.02%
Обработчик не более 15.43%
Response не более 1.06% 
DAO get не более 12.10%

2020-10-09 21:42 UTC, vaddya requested changes
Отписал небольшие пожелания по реализации.

По профилированию:
- Профилируйте подольше, пожалуйста, а то многие интересные места имеют всего 4-5 samples на флейм графе.
- Флейм граф локов как-то странно выглядит. Ни одного нашего лока. Наверное, слишком мало профилировали, что даже флашиться ничего не стало. Попробуете подольше?

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/TablesPool.java
> +    private final ReadWriteLock readWriteLock = new ReentrantReadWriteLock();
Давайте назовем просто `lock` для краткости?

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/MyDAO.java
> +        this.executorService = Executors.newFixedThreadPool(2);
Какие-то магические двойки, может в константы?

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/MyDAO.java
> +            log.error(e.getMessage());
Лучше не терять стектрейс при логировании
`log.error("DAO opening error", e)`

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/MyDAO.java
> +        this.executorService.execute(() -> {
Давайте вынесем логику в метод и вызовем `this.executorService.execute(this::flusher)`?

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/TablesPool.java
> +    public long sizeInBytes() {
Если из разных потоков начать вызывать этот метод, он консистетно будет работать?

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/TablesPool.java
> +            for (final Table table : writingFlushTables.descendingMap().values()) {
Нам важен порядок итераторов? Они же схлопнутся все при мерже?

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +    private static final Logger log = LoggerFactory.getLogger(MySimpleHttpServer.class);
Статические переменные должны быть выше полей.

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/MyDAO.java
> +    private final Logger log = LoggerFactory.getLogger(MyDAO.class);
`static`?

2020-10-09 21:42 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/MyDAO.java
> +    private int generation;
У нас получается тут `generation` и в `TablesPool`, может здесь это не нужно?

2020-10-09 23:17 UTC, KateMoreva commented on src/main/java/ru/mail/polis/dao/kate/moreva/TablesPool.java
> +    public long sizeInBytes() {
Нет, не будет, поняла ошибку.

2020-10-09 23:26 UTC, KateMoreva commented on src/main/java/ru/mail/polis/dao/kate/moreva/TablesPool.java
> +    private volatile MemTable current;
Предполагалось, что для метода upsert нужно прочитать одно значение, поэтому можно было не использовать блокировку, а использовать volatile.  
Так мы избежим ситуации, когда несколько потоков работают с своими копиями.
Но потом необходимость в очереди таблиц, метод putIntoFlushQueue был написан с использованием блокировок, поэтому volatile использовать не нужно.

2020-10-10 13:35 UTC, KateMoreva commented
@vaddya, спасибо, что указали на ошибки в реализации, исправила все замечания.
Профилирование провела еще раз, увеличив время в 2 раза.

2020-10-10 13:50 UTC, KateMoreva commented
### Результаты новых тестов.
### PUT запросы 

-t10 -c20 -d60s -R2000 -s ./wrk/put.lua --latency http://localhost:8080

**CPU**

<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/a3d173483c4d86f9068315a1d79040bc8c8fd346/tests/threadSave/cpuPutLong.svg">

Running 1m test @ http://localhost:8080
  10 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.11ms  472.42us   7.86ms   66.75%
    Req/Sec   211.69     26.03   400.00     92.29%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.20ms
 75.000%    1.41ms
 90.000%    1.62ms
 99.000%    1.98ms
 99.900%    4.57ms
 99.990%    6.15ms
 99.999%    7.26ms
100.000%    7.87ms
  120008 requests in 1.00m, 7.67MB read
Requests/sec:   2000.10
Transfer/sec:    130.87KB

**Alloc**

<img src = "https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/a3d173483c4d86f9068315a1d79040bc8c8fd346/tests/threadSave/allocPutLong.svg">

Running 1m test @ http://localhost:8080
  10 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.11ms  475.48us   9.41ms   67.46%
    Req/Sec   212.14     30.06   444.00     89.84%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.16ms
 75.000%    1.39ms
 90.000%    1.65ms
 99.000%    2.02ms
 99.900%    4.76ms
 99.990%    7.46ms
 99.999%    9.30ms
100.000%    9.41ms
  120010 requests in 1.00m, 7.67MB read
Requests/sec:   2000.11
Transfer/sec:    130.87KB


### Lock для Put запросов

-t10 -c20 -d10s -R20000 -s ./wrk/put.lua --latency http://localhost:8080

<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/a3d173483c4d86f9068315a1d79040bc8c8fd346/tests/threadSave/lockPutLOng.svg">

Running 10s test @ http://localhost:8080
  10 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.25ms    1.49ms  42.98ms   97.71%
    Req/Sec       -nan      -nan   0.00      0.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.06ms
 75.000%    1.45ms
 90.000%    1.70ms
 99.000%    6.79ms
 99.900%   23.53ms
 99.990%   34.59ms
 99.999%   41.41ms
100.000%   43.01ms
  199931 requests in 10.00s, 12.77MB read
Requests/sec:  19993.11
Transfer/sec:      1.28MB

### GET запросы

-t10 -c20 -d60s -R2000 -s ./wrk/get.lua --latency http://localhost:8080

**CPU**

<img src ="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/a3d173483c4d86f9068315a1d79040bc8c8fd346/tests/threadSave/cpuGetLong.svg">

Running 1m test @ http://localhost:8080
  10 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.13ms  499.42us  14.28ms   68.81%
    Req/Sec   211.47     26.08   500.00     92.47%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.22ms
 75.000%    1.43ms
 90.000%    1.64ms
 99.000%    1.99ms
 99.900%    4.97ms
 99.990%    9.75ms
 99.999%   14.17ms
100.000%   14.29ms
 120004 requests in 1.00m, 8.15MB read
Requests/sec:   2000.10
Transfer/sec:    139.15KB

**Alloc**

<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/a3d173483c4d86f9068315a1d79040bc8c8fd346/tests/threadSave/allocGetLong.svg">

Running 1m test @ http://localhost:8080
  10 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.13ms  479.94us  19.26ms   68.61%
    Req/Sec   211.57     29.27   500.00     90.60%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.20ms
 75.000%    1.43ms
 90.000%    1.65ms
 99.000%    2.00ms
 99.900%    4.74ms
 99.990%    8.11ms
 99.999%   14.49ms
100.000%   19.28ms
  120004 requests in 1.00m, 8.00MB read
  Non-2xx or 3xx responses: 59985
Requests/sec:   2000.04
Transfer/sec:    136.54KB

2020-10-10 16:27 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/kate/moreva/TablesPool.java
> +    private volatile MemTable current;
Все правильно говорите

2020-10-10 16:32 UTC, vaddya commented
Все еще не покидает ощущение, что флейм графы `lock*.svg` больше похожи на флейм графы аллокаций. Или я не прав? Какие ключи используете для их получения?

2020-10-10 16:54 UTC, KateMoreva commented
> Все еще не покидает ощущение, что флейм графы `lock*.svg` больше похожи на флейм графы аллокаций. Или я не прав? Какие ключи используете для их получения?

Очень похож, но я использовала: 
-e lock -f lockPutL.svg -t 20315

2020-10-10 17:17 UTC, KateMoreva commented
> Все еще не покидает ощущение, что флейм графы `lock*.svg` больше похожи на флейм графы аллокаций. Или я не прав? Какие ключи используете для их получения?

Удалось получить другие результаты повысив количество заявок и уменьшив время.
Lock для PUT запроса  
-t10 -c20 -d5s -R5000 -s ./wrk/put.lua --latency http://localhost:8080
<img srs="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/49a88491e297a3616c7604eb537bb9452bc0fffa/tests/threadSave/lockPut5000_5s_20c_10t.svg">
Running 5s test @ http://localhost:8080
  10 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.12ms    1.15ms  21.34ms   98.33%
    Req/Sec       -nan      -nan   0.00      0.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.01ms
 75.000%    1.33ms
 90.000%    1.59ms
 99.000%    5.32ms
 99.900%   16.93ms
 99.990%   20.74ms
 99.999%   21.36ms
100.000%   21.36ms
  24972 requests in 5.00s, 1.60MB read
Requests/sec:   4993.16
Transfer/sec:    326.70KB

2020-10-10 18:24 UTC, vaddya approved these changes
Принято.

2020-10-10 18:24 UTC, closed without merging

2020-10-10 18:59 UTC, vaddya commented
Но вообще, конечно, 5 секунд профлиривать точно не надо. Минимум 30, лучше 60. Что за `Object` и `int[]` на ваших флейм графах для лока мне все равно не очень понятно. 

Чтобы поймать локи в вашем решении пришлось уменьшить `flushThreshold`, тогда происходит конкуренция за разделяемый ресурс (наконец-то!) и можно увидеть локи. Учтите это на следующих этапах, пожалуйста. 

<img width="1200" alt="Screen Shot 2020-10-10 at 21 55 27" src="https://user-images.githubusercontent.com/15687094/95662948-91b1e000-0b43-11eb-8ba2-708378418425.png">

2020-10-11 08:51 UTC, KateMoreva commented
> Но вообще, конечно, 5 секунд профлиривать точно не надо, что-то я просмотрел. Минимум 30, лучше 60. Что за `Object` и `int[]` на ваших флейм графах для лока мне все равно не очень понятно. Синхронизация на этих объектах, может? Не знаю.
> 
> Чтобы поймать локи в вашем решении пришлось уменьшить `flushThreshold`, тогда происходит конкуренция за разделяемый ресурс (наконец-то!) и можно увидеть локи. Учтите это на следующих этапах, пожалуйста.
> 
> <img alt="Screen Shot 2020-10-10 at 21 55 27" width="1200" src="https://user-images.githubusercontent.com/15687094/95662948-91b1e000-0b43-11eb-8ba2-708378418425.png">

Спасибо, обязательно учту. К сожалению, профилировать даже 30 секунд не получалось, граф выходил пустой.