Round #2
polis-mail-ru/2020-highload-dht pull request #39
Opened 2020-10-06 08:50 UTC by ScriptoMax

Отчёт по данному этапу содержится в readme.

2020-10-09 09:55 UTC, dormidon commented
> Ввиду того, что RocksDB обеспечивает потокобезопасность по умолчанию, код проекта не содержит специальных методов для управления совместным доступом. По этой причине профилирование lock/monitor лишено релевантных объектов и соответствующие графы (как в данном испытании, так и в последующих) оказываются пустыми.

Я не уверен, но мне кажется, что хоть какие-то блокировки и захваты мониторов должны происходить хоть где-то. 
Быть может, нет поддержки ивента на целевой системе, отвечающей за блокировки?
А что в списке поддерживаемых событий сэмплирования (`profiler.sh list <PID>`)

2020-10-09 12:23 UTC, dormidon commented
Не очень понятно, за счет чего получилось ускорение GET-ов в расширенной конфигурации RocksDB. Здесь нужен профиль (возможно, разложенный по потокам - опция `-t` в `async-profiler`). 
А то получается, что что-то накрутили, `put` лучше не стал, а `get` стал. Хотя казалось бы, включали паралльную запись в мемтейбл (ускорение пута?), а компакшен выключили (замедление гета?). 
В общем, нужно сравнивать профили с накрученным конфигом БД и без него.

2020-10-09 12:23 UTC, dormidon requested changes
См. комменты.

2020-10-10 06:47 UTC, ScriptoMax commented
> > Ввиду того, что RocksDB обеспечивает потокобезопасность по умолчанию, код проекта не содержит специальных методов для управления совместным доступом. По этой причине профилирование lock/monitor лишено релевантных объектов и соответствующие графы (как в данном испытании, так и в последующих) оказываются пустыми.
> 
> Я не уверен, но мне кажется, что хоть какие-то блокировки и захваты мониторов должны происходить хоть где-то.
> Быть может, нет поддержки ивента на целевой системе, отвечающей за блокировки?
> А что в списке поддерживаемых событий сэмплирования (`profiler.sh list <PID>`)

Ситуация с этим профилем оказалась достаточно странной. Я пытался получить граф для текущей итерации и следующей (асинхронный сервер), и если в первом случае не хватает даже 20 запусков профилировщика (всё также пусто), то для сервера, поддерживающего асинхронную обработку, аналогичный граф формируется с первого раза

![basic_put_lock](https://user-images.githubusercontent.com/55311053/95647885-c25e2f00-0adb-11eb-8cf0-91ab666c4cde.jpg)

Т.е. событие однозначно поддерживается
![Screenshot from 2020-10-10 10-33-26](https://user-images.githubusercontent.com/55311053/95647902-efaadd00-0adb-11eb-9f48-2b58be2de828.png)

Из-за таких двояких результатов у меня возникло предположение, что профилировщик не имеет доступа к данным о вызовах методов БД (но при этом, согласен, потоки регулируются без всякого волшебства, поэтому инфу наверняка можно извлечь). Описания аналогичных проблем на гите и вне его так и не нашёл да ещё и сокурсники с RocksDB говорят, что и у них вместо графов только заголовок. То ли что-то у меня не настроено, то ли кейс на полпотока

2020-10-10 07:12 UTC, ScriptoMax commented
> Не очень понятно, за счет чего получилось ускорение GET-ов в расширенной конфигурации RocksDB. Здесь нужен профиль (возможно, разложенный по потокам - опция `-t` в `async-profiler`).
> А то получается, что что-то накрутили, `put` лучше не стал, а `get` стал. Хотя казалось бы, включали паралльную запись в мемтейбл (ускорение пута?), а компакшен выключили (замедление гета?).
> В общем, нужно сравнивать профили с накрученным конфигом БД и без него.

Дополнил отчёт требуемыми иллюстрациями. Проблема в том, что по ним всё ещё не улавливается релевантных факторов. Видимо, нужен профиль <em>monitor/lock</em>, с которым пока сплошной детектив. По крайней мере, ЦПУ и ОП изначально не могли внести достаточно ясности, и, на мой взгляд, пока всё выглядит так же туманно, как и поначалу: существенных различий в панорамах с потоками я не наблюдаю. Хотел бы отметить, что дополнительные графы были получены мною утром в субботу (10.10), и по результатам этих тестов добавление в расширенной конф-и происходит ещё быстрее (195 мс в худшем случае против почти 400 в первой версии отчёта (без графов для расширения)). Проявились различия и в откликах на GET-запросы - 30 мс в субботу против 66 изначально. По сути ускорение операций достигается в обоих тестах (что радует), но вариации для верхних квантилей вызывают некоторое смущение. Как упоминалось и до сих пор упоминается в отчёте, у меня существуют сомнения в адекватности 2-ядерного ЦП разработке highload. Не исключаю, что в наблюдаемых колебаниях проявляется причудливость поведения системы, где одна фоновая задача сразу сворачивает весь параллелизм. Это лишь субъективное представление о проблеме, ПК с более  соразмерными 4 ядрами под рукой сейчас в любом случае не отыщется.

2020-10-10 07:14 UTC, ScriptoMax commented
пожалуйста, рассмотрите фид к комментариям

2020-10-12 05:46 UTC, dormidon approved these changes

2020-10-12 05:47 UTC, closed without merging