Task2
polis-mail-ru/2020-highload-dht pull request #42
Opened 2020-10-06 15:04 UTC by IvanovAndrey

2020-10-06 15:04 UTC, IvanovAndrey commented
Нагрузочного тестирования пока нет, в процессе

2020-10-06 20:26 UTC, IvanovAndrey commented
Графы на профилировании получаются странной формы. Буду разбираться в чем дело, пока не хочу выкладывать результаты профилирования (чтобы не казаться еще более не умным).

2020-10-09 07:03 UTC, incubos requested changes
- Стрелять и профилировать нужно нагрузкой в **несколько соединений** -- мы же тестируем многопоточную реализацию
- Нет анализа результатов

2020-10-09 07:03 UTC, incubos commented on HighloadLog
> +  Non-2xx or 3xx responses: 79995
`GET` по пустой БД?

2020-10-09 07:03 UTC, incubos commented on HighloadLog
> +andrey@andrey-Mint:~/wrk2-master$ ./wrk -t1 -c1 -d40s -R2000 -s get.lua --latency http://127.0.0.1:8080
Стрельба в 1 соединение? Это отчёт от этапа 1?

2020-10-09 07:03 UTC, incubos commented on HighloadLog
> +andrey@andrey-Mint:~/wrk2-master$ ./wrk -t1 -c1 -d40s -R2000 -s put.lua --latency http://127.0.0.1:8080
1 соединение?

2020-10-09 07:03 UTC, incubos commented on HighloadLog
> +andrey@andrey-Mint:~/wrk2-master$ ./wrk -t1 -c1 -d40s -R2000 -s delete.lua --latency http://127.0.0.1:8080
1 соединение?

2020-10-09 07:03 UTC, incubos commented on src/main/java/ru/mail/polis/Server.java
> -/*
Зачем это изменение?

2020-10-09 07:03 UTC, incubos commented on src/test/java/ru/mail/polis/dao/AllDeadTest.java
> +    @RepeatedTest(20)
Зачем это?

2020-10-12 09:20 UTC, incubos commented
> * Стрелять и профилировать нужно нагрузкой в **несколько соединений** -- мы же тестируем многопоточную реализацию
> * Нет анализа результатов

Ждать исправлений или часть баллов?

2020-10-12 11:04 UTC, IvanovAndrey commented on src/main/java/ru/mail/polis/Server.java
> -/*
Это ошибочная интерпретация ошибки от codeclimat. Это было еще в первом таске, потом перекочевало в мастер по средствам merge, затем оказалось в этой ветке.

2020-10-12 11:05 UTC, IvanovAndrey commented on src/test/java/ru/mail/polis/dao/AllDeadTest.java
> +    @RepeatedTest(20)
У меня возникла проблема с падением всех тестов, начиная с этого у Трэвиса, при том что на локальной машине было все ок. Я говорил об этом на занятии. Это была попытка выяснить в чем дело, которую я забыл вернуть обратно. Поправил.

2020-10-12 11:07 UTC, IvanovAndrey commented
Прошу прощения, результаты профилирования, которые Вы видели и комментировали - это неправильные результаты еще с первого этапа. Мне следовало их удалить, чтобы не тратить ваше время. Сейчас я загрузил актуальные результаты [сюда](https://github.com/IvanovAndrey/2020-highload-dht/blob/task2/async/report_task2.md)

2020-10-12 15:58 UTC, IvanovAndrey commented
Сейчас делаю профилирование для третьего этапа и замечаю, что у меня для второго этапа результаты получились не в миллисекундах, а в секундах. Не справляется моя машина с 32 тысячами, буду переделывать

2020-10-13 15:10 UTC, incubos commented
Принято.

2020-10-13 15:10 UTC, closed without merging