Stage2
polis-mail-ru/2020-highload-dht pull request #45
Opened 2020-10-06 15:34 UTC by mariarheon

2020-10-16 01:46 UTC, lamtev requested changes
В профилях в целом все ОК. Попрошу в отчет добавить:
1. Выполняемые команды профилировщика и wrk
2. Более подробное описание того, на что тратится время и память при CPU и ALLOC
3. Собственные мысли по результатам профилирования

2020-10-16 01:46 UTC, lamtev commented on src/main/java/ru/mail/polis/dao/mariarheon/ByteBufferUtils.java
> +            res[i] = (byte)(Byte.toUnsignedInt(res[i]) - Byte.MIN_VALUE);
Вообще, конечно, есть более простой (в том числе и по вычислительной сложности, хотя тут явно нет bottleneck) способ: поксорить с `Byte.MIN_VALUE`. В обратную сторону тоже

2020-10-16 01:46 UTC, lamtev commented on src/main/java/ru/mail/polis/dao/mariarheon/ByteBufferUtils.java
> +    public static byte[] toArraySpecial(@NotNull final ByteBuffer buffer) {
Почему Special?

2020-10-16 01:46 UTC, lamtev commented on build.gradle.kts
> +    //compile("org.rocksdb:rocksdbjni:5.15.10")
незачем оставлять закомментированный код

2020-10-17 16:54 UTC, lamtev commented
Можно смотреть или еще будет что-то?

2020-10-17 17:06 UTC, mariarheon commented
> Можно смотреть или еще будет что-то?

Пока не добавила "собственные мысли", в выходные они тяжело формулируются. Без них можно сдать?

2020-10-17 17:31 UTC, lamtev commented
Помимо "собственных мыслей" так же не были добавлены выполняемые команды профилировщика (`./profiler.sh -e cpu -d 30 -t -f res.svg 1234`), из которых хотя бы можно было узнать длительность 🙂
Попрошу в следующих этапах данные замечания учесть

2020-10-17 17:32 UTC, lamtev commented
Принято

2020-10-17 17:32 UTC, closed without merging