hw2
polis-mail-ru/2020-highload-dht pull request #46
Opened 2020-10-06 16:15 UTC by zvladn7

нагрузочное тестирование в процессе

2020-10-06 20:46 UTC, zvladn7 commented
[Анализ нагрузочного тестирования](https://github.com/zvladn7/2020-highload-dht/blob/stage2/report/hw2.md)

2020-10-13 18:44 UTC, lamtev commented
> @lamtev добрый вечер, когда можно ожидать review?

Добрый вечер. Приношу извинения за то, что ревью пока не готово. Постараюсь завтра-послезавтра проревьюить в полном объеме. На один момент укажу уже сейчас

2020-10-13 18:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/BasicService.java
> +    private final Map<String, byte[]> cache = new LinkedHashMap<>();
Намекал в прошлый раз, что данный кэш не работает. Кейс, в котором данный кэш будет работать, крайне маловероятен, и при текущем генераторе запросов в `get.lua` данный кейс не воспроизводится. Для того чтобы стабильно был cache-hit надо чтобы после первых `CACHE_SIZE` запросов поступали запросы с id, которые лежат в кэше, т.е.  те первые 15 id. Согласно `get.lua` id в запросах идут по порядку, дублирования id вообще нет, не говоря уже об окнах с id, которые есть в кэше, то есть cache-miss происходит регулярно

Ожидал, что данный момент будет переосмыслен

Стратегия вытеснения крайне плоха, такому кэшу трудно найти применение.

Если есть желание прикрутить нормальный кэш, который в теории должен сильно ускорить выполнение GET  запросов, то рекомендую посмотреть на [guava](https://github.com/google/guava/wiki/CachesExplained) или [cache2k](https://github.com/cache2k/cache2k). Они довольно гибки в настройке, поддерживают ttl и потоко-безопасны из коробки

Если желания нет, то стоит просто убрать текущую реализацию

2020-10-14 14:30 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/BasicService.java
> +    private final Map<String, byte[]> cache = new LinkedHashMap<>();
Хорошо. На данном этапе уберу кэш, так как сейчас большая загрузка по учебе, и чисто по времени не успеваю разобраться. Но постараюсь в 3 этапе это исправить, потому что там сейчас такая же проблема имеется. Вообще уже смотрел в сторону guava, и хотел переписать на нее. Так что думаю, что выберу ее для реализации.

2020-10-16 01:12 UTC, lamtev requested changes
# Review отчета по профилированию под нагрузкой

1. Просьба добавлять в отчет саму команду `async-profiler`
2. ~~Лучше воспользоваться ключиком `-t`, чтобы на флейм графах видеть стектрейсы по потокам, а не в общем.~~
3. Хоть и фигурирует слово "Анализ", анализа, к сожалению, нет. Это просто интерпретация результатов. Было бы интересно еще увидеть каки-нибудь размышления по полученным результатам.
4. Там где приведены проценты по CPU и ALLOC сумма получается больше 100. 
    Например:
    ```
     - Обработка запроса: 74.41%
     - Запись в сокет: 33.92%
     - Чтение из сокета: 13.35%
     - Вставка в ConcurrentSkipListMap - Memory Table в DAO занимает - 9.87%
     - Flush в 4 потока занимает - 7.42%%
    ```
    Очевидно, что тут все показатели относятся к обработке запроса (они находятся в рамках одного столбика на флейм-графе).
Для наглядности лучше оформлять так, чтобы было видно что является частью чего. По этому же примеру: сказано, что 74.41% занимает обработка запроса, но не говорится, куда уходят оставшиеся ~26%. Epoll/select/kqueue, jit, ... ?
5. Так же стоит добавить на какой ОС и на каком железе проводились замеры (судя по Epoll - Linux)
6. Вовсе необязательно делать разные обстрелы для профилирования CPU/ALLOC/LOCK. Достаточно прогреть сервис и последовательно подключиться профилировщиком для снятия профилей CPU/ALLOC/LOCK

# Review реализации

* Оставил комментарии и вопросы. Прошу разобраться и ответить
* Одна из фишек one-nio в использовании неблокирующих сокетов и системного вызова epoll, что позволяет довольно небольшим числом потоков (Selector Threads) обрабатывать большое число запросов. На потоках селектора крайне нежелательно выполнять блокирующий код, т.е. по-хорошему нужно обработку запросов вынести на другие потоки. **UPD**: это же как раз 3-й этап. Здесь не нужно

2020-10-16 13:37 UTC, zvladn7 commented
@lamtev а как быть с тестами, которые обновились для 4 этапа? Получается, что они в любом случае не пройдут.

2020-10-16 13:48 UTC, lamtev commented
> @lamtev а как быть с тестами, которые обновились для 4 этапа? Получается, что они в любом случае не пройдут.
Буду локально прогонять тесты на этой ветке

2020-10-16 13:50 UTC, lamtev commented
> 2. Лучше воспользоваться ключиком `-t`, чтобы на флейм графах видеть стектрейсы по потокам, а не в общем.

Наверное, это спорное утверждение. Когда потоков немного - то кажется довольно удобным видеть расклад по каждому. Когда потоков много - то уже становится тяжело анализировать

2020-10-16 15:36 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/LsmDAOImpl.java
> +    private static ByteBuffer EMPTY_BUFFER = ByteBuffer.allocate(0);
Поправил

2020-10-16 15:36 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/LsmDAOImpl.java
> +    Map<ByteBuffer, Long> lockTable = new HashMap<>();
тоже поправил

2020-10-16 15:37 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/LsmDAOImpl.java
> +            files.filter(file -> !file.toFile().isDirectory() && file.toString().endsWith(SSTABLE_FILE_POSTFIX))
Да, код действительно с прошлого семестра. Но тут, действительно, лучше использовать `Files.isRegularFile(file)`, чтобы не мешать старый и новый api.

2020-10-16 15:38 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/LsmDAOImpl.java
> +                            e.printStackTrace();
действительно, случайно осталось, убрал)

2020-10-16 15:40 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/LsmDAOImpl.java
> +        readLock.lock();
Проблема действительно была. Поэтому создал еще один метод в `TableSet`, где создаю копии для `memToFlush` и 'SSTables', чтобы можно было безопасно получать размер для списка итераторов и добавлять итераторы туда соответственно.

2020-10-16 15:44 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/LsmDAOImpl.java
> +    public synchronized void compact() throws IOException {
Здесь он нужен для того, чтобы одновременно мог выполняться только один `compaction`. Вадим сказал, что реализация нескольких одновременно - это доп задание. Однако также в последующих этапах хочу добавить возможность этого, поскольку - это поможет повысить пропускную способность.

2020-10-16 15:45 UTC, zvladn7 commented
@lamtev все поправил
[Обновленный анализ нагрузочного тестирования](https://github.com/zvladn7/2020-highload-dht/blob/stage2/report/hw2_updated.md)

2020-10-17 17:37 UTC, lamtev requested changes
Отчет по профилированию был дополнен, стало лучше - ОК

В реализации - откатить последнее изменение с дополнительным копированием (либо если уверен, что оно необходимо, то объяснение и кейс) и изменением ссылки под рид локом. И тогда реализация будет принята

Рекомендации по коду:
1. Сейчас из `TableSet` является по сути data классом для `memTable` и `ssTables`, и доступ к ним осуществляется извне напрямую к филду. Обращений очень много, они размазаны по большому количеству кода. Из-за этого довольно трудно читать. Трудно отслеживать логику. Вполне логично было часть логики из `LsmDAOImpl` перенести в `TableSet`.
2. В `LsmDAOImpl` `readLock` торчит наружу для использования в `TransactionalDAOImpl`. Лучше лок сделать приватным и сделать метод, который будет под локом безопасно читать snapshot. Этот метод можно будет и внутри `LsmDAOImpl` вызывать и из `TransactionalDAOImpl`, получится переиспользование вместо дублирования.

2020-10-17 17:38 UTC, lamtev commented on src/main/java/ru/mail/polis/dao/zvladn7/LsmDAOImpl.java
> +        readLock.lock();
Я еще раз подумал обо всем вот этом, и пришел к тому, что проблемы на самом деле не было.

При upsert и remove производится работа с thread-safe структурами данных. Операций, модифицирующих memTable, memToFlush, ssTables нет.

Дополнительное копирование, добавленное в последних коммитах, кажется избыточным

2020-10-17 17:57 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/MemoryTable.java
> -    private final SortedMap<ByteBuffer, Value> map = new ConcurrentSkipListMap<>();
на самом деле ничем, это просто было изменено в процессе рассуждений, когда хотел сделать второй конструктор. Однако потом оказалось, что он вовсе не нужен, поэтому оставил только 1 из них

2020-10-17 17:57 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/LsmDAOImpl.java
> +            this.tableSet = this.tableSet.startIterating();
да, действительно, не учел, буду внимательнее

2020-10-17 17:57 UTC, zvladn7 commented
Да, вы правы. Действительно, сейчас подумал еще раз и понял, что дополнительное копирование совершенно не нужно. Меня почему-то заклинило, что здесь была проблема с получением размеров, почему-то в голове сидело, что если мы проинициализровали ArrayList c каким-то начальным capacity, то он больше не изменяется. Но это, естественно, не так, в чем я убедился, зайдя в `javadoc`. С каким-то другим языком видимо спутал. Однако на самом деле проблема небольшая была в методе `compact`. Иногда удалял файл, который был только что флашнут, и получалось, что я его терял. Это было сложно отловить, так как проблема проявлялась очень редко.

2020-10-17 17:59 UTC, zvladn7 commented
Рекомендации по коду попробуй устранить в 3 этапе. Там вроде вы тоже у ревьювер.

2020-10-17 17:59 UTC, zvladn7 commented
@lamtev поправил. Спасибо за ревью!

2020-10-17 19:09 UTC, lamtev commented
Все тесты 2-го этапа успешно выполняются

Принято

2020-10-17 19:09 UTC, closed without merging