Homework 1
polis-mail-ru/2020-highload-dht pull request #5
Opened 2020-09-27 09:41 UTC by Marashov-Alexander

2020-09-28 10:35 UTC, incubos requested changes
Не хватает результатов нагрузочного тестирования через `wrk`, результатов профилирования под нагрузкой и их краткого анализа.

2020-09-28 10:36 UTC, incubos requested changes
Реализация ОК. Но не хватает результатов нагрузочного тестирования через `wrk`, результатов профилирования `cpu` и `alloc` под нагрузкой и их краткого анализа.

2020-09-29 19:07 UTC, Marashov-Alexander commented
> Реализация ОК. Но не хватает результатов нагрузочного тестирования через `wrk`, результатов профилирования `cpu` и `alloc` под нагрузкой и их краткого анализа.

Спасибо, сегодня добавлю!

2020-09-29 20:39 UTC, Marashov-Alexander commented
# Результаты нагрузочного тестирования
## Оценка эффективности PUT запросов
### Скрипт на lua
cnt = 0
request = function ()
    path = "/vo/entity&id=key" .. cnt
    wrk.method = "PUT"
    wrk.body = "value" .. cnt
    cnt = cnt + 1
    return wrk.format(nil, path)
end
### Запуск wrk2
`./wrk -t1 -c1 -d 1m -R 2000 -s put.lua --latency http://localhost:8080`
### Запуск профайлера
`sudo ./profiler.sh -e cpu -d 10 -f ./cpuPutTst.svg 19752`
`sudo ./profiler.sh -e alloc -d 10 -f ./allocPut.svg 19752`
### Результаты работы wrk2
Running 1m test @ http://localhost:8080
  1 threads and 1 connections
  Thread calibration: mean lat.: 0.867ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.87ms  432.82us   3.77ms   62.45%
    Req/Sec     2.05k   134.28     2.56k    39.63%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.87ms
 75.000%    1.17ms
 90.000%    1.49ms
 99.000%    1.69ms
 99.900%    1.76ms
 99.990%    1.92ms
 99.999%    3.33ms
100.000%    3.77ms
----------------------------------------------------------
  120000 requests in 1.00m, 8.13MB read
  Non-2xx or 3xx responses: 120000
Requests/sec:   1999.98
Transfer/sec:    138.67KB
## Оценка эффективности GET запросов
### Скрипт на lua
```
cnt = 0
request = function ()
    path = "/vo/entity&1d=key" .. cnt
    wrk.method = "GET"
    cnt = cnt + 1
    return wrk.format(nil, path)
end
```
### Запуск wrk2
`./wrk -t1 -c1 -d 1m -R 2000 -s ./get.lua --latency http://localhost:8080`
### Запуск профайлера
`sudo ./profiler.sh -e cpu -d 10 -f ./cpuGetTst.svg 19752`
`sudo ./profiler.sh -e alloc -d 10 -f ./allocGet.svg 19752`
### Результаты работы wrk2
Running 1m test @ http://localhost:8080
  1 threads and 1 connections
  Thread calibration: mean lat.: 0.867ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.87ms  432.82us   3.77ms   62.45%
    Req/Sec     2.05k   134.28     2.56k    39.63%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.87ms
 75.000%    1.17ms
 90.000%    1.49ms
 99.000%    1.69ms
 99.900%    1.76ms
 99.990%    1.92ms
 99.999%    3.33ms
100.000%    3.77ms
----------------------------------------------------------
  120000 requests in 1.00m, 8.13MB read
  Non-2xx or 3xx responses: 120000
Requests/sec:   1999.98
Transfer/sec:    138.67KB
## Полученные Flame Graphs:
[flame_graphs.zip](https://github.com/polis-mail-ru/2020-highload-dht/files/5301715/flame_graphs.zip)

2020-09-29 20:50 UTC, Marashov-Alexander commented
> Реализация ОК. Но не хватает результатов нагрузочного тестирования через `wrk`, результатов профилирования `cpu` и `alloc` под нагрузкой и их краткого анализа.

Результаты добавил, но не до конца их осознал. Кроме того, столкнулся с ошибкой отсутствия "AllocTracer symbols", из-за чего -e alloc профилирование было недоступно. Пришлось разворачивать свой сервер на другой машине

2020-09-30 13:16 UTC, incubos requested changes
Как объяснить это в выводе `wrk`: `Non-2xx or 3xx responses: 120000`? Стрелять нужно сначала `PUT`ами, а затем `GET`ами по наполненной БД.
Вкомитьте, пожалуйста, файлы SVG (профилирование) и консольный вывод `wrk` отдельными файлами, чтобы не нужно было выкачивать и распаковывать архив.
Наконец, не хватает анализа результатов (с alloc не получилось, в следующих этапах попробуем) -- но на что уходит время CPU?
Будете доделывать или остановимся на 5 баллах из 10?

2020-09-30 17:04 UTC, Marashov-Alexander commented
> Как объяснить это в выводе `wrk`: `Non-2xx or 3xx responses: 120000`? Стрелять нужно сначала `PUT`ами, а затем `GET`ами по наполненной БД.
> Вкомитьте, пожалуйста, файлы SVG (профилирование) и консольный вывод `wrk` отдельными файлами, чтобы не нужно было выкачивать и распаковывать архив.
> Наконец, не хватает анализа результатов (ОК, с alloc не получилось) -- но на что уходит время CPU?
> Будете доделывать из остановимся на 5 баллах из 10?

Спасибо за комментарий, попробую разобраться, исправить и предоставить результаты в требуемом формате

2020-10-03 09:18 UTC, Marashov-Alexander commented
> Как объяснить это в выводе `wrk`: `Non-2xx or 3xx responses: 120000`? Стрелять нужно сначала `PUT`ами, а затем `GET`ами по наполненной БД.
> Вкомитьте, пожалуйста, файлы SVG (профилирование) и консольный вывод `wrk` отдельными файлами, чтобы не нужно было выкачивать и распаковывать архив.
> Наконец, не хватает анализа результатов (с alloc не получилось, в следующих этапах попробуем) -- но на что уходит время CPU?
> Будете доделывать или остановимся на 5 баллах из 10?

Добрый день! 
Такое количество ошибочных кодов получалось из-за опечаток в скрипте профилирования, поправил.
Загрузил файлы в папку profiler/homework1, в ней же есть файл testsReview, который содержит моё представление о происходящем в системе по результатам профилирования

2020-10-03 14:04 UTC, incubos commented
Принято.

2020-10-03 14:04 UTC, closed without merging