Stage 2
polis-mail-ru/2020-highload-dht pull request #51
Opened 2020-10-06 19:36 UTC by makaryb

Добрый день!

Отправляю решение по заданиям ко второму этапу.

Результаты профилирования к данному этапу и .md-файл находятся на стадии оформления и будут добавлены в ближайшее время.

2020-10-07 14:20 UTC, makaryb commented
Добрый день!

**Результаты профилирования** под _нагрузкой_.

## 1. Для PUT:

### 1.1 Нагрузочное тестирование потокобезопасного сервера с утилитой _wrk2_ в несколько соединений и мониторинг утилитой _visualVM_.

```
wrk2 -t4 -c100 -d3m -R* -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/put.lua --latency http://127.0.0.1:8080
```

Сравнение полученных результатов для разного rate:

**R 30k-50k-100k-150k-200k**:

![output-put-all](https://user-images.githubusercontent.com/36387962/95331802-2b169300-08b3-11eb-961d-8646ba22bae3.png)

**R 30k-50k-100k-150k**:

![output-put-many](https://user-images.githubusercontent.com/36387962/95331938-61541280-08b3-11eb-99bb-08df15b6366a.png)

Можно видеть, что адекватное время ответа при 100 соединениях при стабильной нагрузке R150k.

Мониторинг работы сервера:

Слева _wrk2_ c `... -t1 -c16 ...`, справа с `... -t4 -c100 ...`

![put-put_monitor](https://user-images.githubusercontent.com/36387962/95332670-6b2a4580-08b4-11eb-9914-f1faddf9c57d.png)

Треды при работе **PUT**:

![put_threads](https://user-images.githubusercontent.com/36387962/95332693-75e4da80-08b4-11eb-99ec-520eeffe78c3.png)

### 1.2 Профилирование под нагрузкой с async-profiler.

#### 1.2.1. Прифилирование CPU:

![cpu-put-150000](https://user-images.githubusercontent.com/36387962/95333479-82b5fe00-08b5-11eb-8118-31e551f8e8c3.png)

Видно, что наибольшее количество времени занимает передача данных по сети. Обработка запроса - _82.47%_.; запись в сокет - _9.78%_; чтение из сокета - _9.00%_; ConcurrentSkipListMap вставка занимает - _21.41%_; многопоточная запись данных на диск - _12.26%_.

#### 1.2.2. Прифилирование Allocation:

![alloc-put-150000](https://user-images.githubusercontent.com/36387962/95335168-b85be680-08b7-11eb-80db-a73057706fe1.png)

Большую часть времени занимает httpBuffer - _99.17%_; большую часть времени занимает парсинг запроса - _54.33%_; операция upsert занимает - _36.36%_; NewDAO.upsert - _17.55%_; запрос - _6.32%_ ответ - _7.34%_; запись - _6.78%_.

 #### 1.2.3. Прифилирование Lock:

![lock-put-150000](https://user-images.githubusercontent.com/36387962/95336552-79c72b80-08b9-11eb-9629-53f2b2348f2b.png)

С помощью данной опции профилирования можно видеть как на сервере происходят блокировки. На данном профиле ReentrantReadWriteLock.ReadLock занимает большую часть времни - _95.35%_; WriteLock занимает - _4.65%_; 


### 2. Для GET:

### 2.1 Нагрузочное тестирование потокобезопасного сервера с утилитой _wrk2_ в несколько соединений и мониторинг утилитой _visualVM_.

```
wrk2 -t4 -c100 -d3m -R* -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/get.lua --latency http://127.0.0.1:8080
```

Сравнение полученных результатов для разного rate:

**R 60-100-150-1k-10k**:

![output-get-all](https://user-images.githubusercontent.com/36387962/95332179-babc4180-08b3-11eb-98a1-bea503093134.png)

**R 60-100-150**:

![output-get-many](https://user-images.githubusercontent.com/36387962/95332207-c3147c80-08b3-11eb-9c3a-e98838d4a6e7.png)

**R 60-100-150**:

![output-get-two](https://user-images.githubusercontent.com/36387962/95332235-cc054e00-08b3-11eb-8324-0e038fd0a906.png)

Можно видеть, что адекватное время ответа при 100 соединениях при стабильной нагрузке R100.

Мониторинг работы сервера:

Слева _wrk2_  **PUT** c `... -t1 -c16 ...`, затем `... -t4 -c100 ...` - справа _wrk2_  *GET** c `... -t4 -c100 ...`

![put-put-get_monitor](https://user-images.githubusercontent.com/36387962/95332888-afb5e100-08b4-11eb-8632-0ba3627020b9.png)

Треды при работе **GET**:

![get_threads_3](https://user-images.githubusercontent.com/36387962/95332942-c2301a80-08b4-11eb-8cb9-6ae378a3a2e8.png)

![get-threads_2](https://user-images.githubusercontent.com/36387962/95332933-bf352a00-08b4-11eb-8c76-652dcaf8fc78.png)

![get-threads](https://user-images.githubusercontent.com/36387962/95332918-b9d7df80-08b4-11eb-82b1-e80cf9cf2d82.png)

### 2.2 Профилирование под нагрузкой с async-profiler.

#### 2.2.1. Прифилирование CPU:

![cpu-get-100](https://user-images.githubusercontent.com/36387962/95337641-b9dade00-08ba-11eb-8f8a-9def830d7e6e.png)

На данном профиле можно видеть, что get и iterator занимают большую часть времени - _99.62%_; на бинарный поиск места, с которого считывать, затрачивается - _89.92%_; на чтение тратится - _58.26%_ ; операция merge для iterator'ов занимает - _9.12%_.

#### 2.2.2. Прифилирование Allocation:

![alloc-get-100](https://user-images.githubusercontent.com/36387962/95338750-ed6a3800-08bb-11eb-93f2-aae69ad4564d.png)

Большую часть времени занимает httpBuffer - _99.98%_; операция get занимает - _99.82%_; на бинарный поиск и ключ тратится - _87.27%_; на смещение до ключа - _27.88%_; операция merge для iterator'ов занимает - _11.36%_.

 #### 2.2.3. Прифилирование Lock:

Для того, чтобы увидеть время, которое тратится при блокировке на чтение, постреляем одновременно запросами **PUT** и **GET** (перед этим заполним хранилище некоторым объемом данных):

```
wrk2 -t4 -c100 -d3m -R100000 -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/put.lua --latency http://127.0.0.1:8080

wrk2 -t4 -c100 -d3m -R100 -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/get.lua --latency http://127.0.0.1:8080
```

```
sudo ./profiler.sh -d 10 -f /tmp/lock-put-100k-get-100.svg -e lock 9787
```

Получим следующим профиль:

![lock-put-100k-get-100](https://user-images.githubusercontent.com/36387962/95342791-78e5c800-08c0-11eb-93a1-517a7af17e91.png)

Можно видеть, что блокировка ReadLock заняла - _56.79%_; на запись WriteLock: _4.94%_.

2020-10-11 20:22 UTC, dormidon commented
Как-то подозрительно долго стал работать `get`. 
Даже в однопоточном сервере все было сильно лучше, не так ли? 100 запросов в секунду - это совсем небольшая нагрузка, чтобы под ней такие процентили были.

2020-10-11 20:29 UTC, dormidon commented on src/main/java/ru/mail/polis/dao/boriskin/NewDAO.java
> +    private TableSet memTable;
Название, конечно, сбивает толку.
Это ведь уже совсем не `memTable`.

2020-10-12 05:51 UTC, dormidon requested changes
Нужно разобраться с медленным GET-ом.

2020-10-12 11:35 UTC, makaryb commented
Добрый день!

Снова пострелял по той же реализации: получил совсем другие временные результаты:

**GET для 1k-2k-3k**:

![output-get-all](https://user-images.githubusercontent.com/36387962/95741849-b0c18680-0c97-11eb-95c5-4105925cc0fd.png)

**GET для 1k-2k**:

![output-get-many](https://user-images.githubusercontent.com/36387962/95741901-cafb6480-0c97-11eb-99e4-1000db2f2eae.png)

Держит стабильную нагрузку в 2000 rate.

```
wrk2 -t4 -c100 -d1m -R2000 -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/get.lua --latency http://127.0.0.1:8080
```

**latency**:

```
Running 1m test @ http://127.0.0.1:8080
  4 threads and 100 connections
  Thread calibration: mean lat.: 11.120ms, rate sampling interval: 28ms
  Thread calibration: mean lat.: 11.416ms, rate sampling interval: 23ms
  Thread calibration: mean lat.: 8.887ms, rate sampling interval: 21ms
  Thread calibration: mean lat.: 8.967ms, rate sampling interval: 23ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.87ms    3.89ms 110.78ms   92.38%
    Req/Sec   510.71     61.18     0.86k    74.13%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    5.03ms
 75.000%    6.88ms
 90.000%    9.10ms
 99.000%   17.02ms
 99.900%   55.20ms
 99.990%   82.30ms
 99.999%  104.45ms
100.000%  110.85ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       1.909     0.000000            1         1.00
       3.145     0.100000         9979         1.11
       3.613     0.200000        19952         1.25
       4.025     0.300000        29956         1.43
       4.459     0.400000        39913         1.67
       5.035     0.500000        49927         2.00
       5.383     0.550000        54905         2.22
       5.747     0.600000        59878         2.50
       6.115     0.650000        64876         2.86
       6.479     0.700000        69829         3.33
       6.875     0.750000        74809         4.00
       7.091     0.775000        77338         4.44
       7.343     0.800000        79832         5.00
       7.659     0.825000        82286         5.71
       8.043     0.850000        84801         6.67
       8.519     0.875000        87275         8.00
       8.799     0.887500        88534         8.89
       9.103     0.900000        89768        10.00
       9.423     0.912500        91017        11.43
       9.815     0.925000        92283        13.33
      10.311     0.937500        93522        16.00
      10.615     0.943750        94132        17.78
      10.959     0.950000        94764        20.00
      11.399     0.956250        95383        22.86
      11.903     0.962500        96009        26.67
      12.463     0.968750        96629        32.00
      12.815     0.971875        96942        35.56
      13.183     0.975000        97248        40.00
      13.647     0.978125        97564        45.71
      14.295     0.981250        97874        53.33
      15.071     0.984375        98185        64.00
      15.511     0.985938        98340        71.11
      16.023     0.987500        98496        80.00
      16.591     0.989062        98652        91.43
      17.311     0.990625        98807       106.67
      18.735     0.992188        98961       128.00
      20.383     0.992969        99041       142.22
      22.719     0.993750        99118       160.00
      25.375     0.994531        99195       182.86
      28.047     0.995313        99273       213.33
      31.087     0.996094        99352       256.00
      32.799     0.996484        99390       284.44
      34.271     0.996875        99429       320.00
      36.511     0.997266        99468       365.71
      38.943     0.997656        99507       426.67
      41.791     0.998047        99546       512.00
      43.743     0.998242        99565       568.89
      46.495     0.998437        99585       640.00
      49.247     0.998633        99604       731.43
      52.671     0.998828        99624       853.33
      55.583     0.999023        99643      1024.00
      57.247     0.999121        99653      1137.78
      58.847     0.999219        99663      1280.00
      60.351     0.999316        99672      1462.86
      62.591     0.999414        99682      1706.67
      65.343     0.999512        99692      2048.00
      66.239     0.999561        99697      2275.56
      68.031     0.999609        99702      2560.00
      68.735     0.999658        99706      2925.71
      70.847     0.999707        99711      3413.33
      72.575     0.999756        99716      4096.00
      73.279     0.999780        99719      4551.11
      73.855     0.999805        99721      5120.00
      75.199     0.999829        99723      5851.43
      76.607     0.999854        99726      6826.67
      78.975     0.999878        99728      8192.00
      82.303     0.999890        99730      9102.22
      85.119     0.999902        99731     10240.00
      87.295     0.999915        99732     11702.86
      88.063     0.999927        99733     13653.33
      89.535     0.999939        99734     16384.00
      90.879     0.999945        99735     18204.44
      91.199     0.999951        99736     20480.00
      91.199     0.999957        99736     23405.71
      97.727     0.999963        99737     27306.67
      97.727     0.999969        99737     32768.00
     102.911     0.999973        99738     36408.89
     102.911     0.999976        99738     40960.00
     102.911     0.999979        99738     46811.43
     104.447     0.999982        99739     54613.33
     104.447     0.999985        99739     65536.00
     104.447     0.999986        99739     72817.78
     104.447     0.999988        99739     81920.00
     104.447     0.999989        99739     93622.86
     110.847     0.999991        99740    109226.67
     110.847     1.000000        99740          inf
#[Mean    =        5.869, StdDeviation   =        3.892]
#[Max     =      110.784, Total count    =        99740]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  119919 requests in 1.00m, 8.27MB read
Requests/sec:   1998.58
Transfer/sec:    141.10KB
```

2020-10-12 11:53 UTC, dormidon commented
Хм.. Очень загадочно.
А сейчас GET был не пустой базе случаем?

2020-10-12 12:33 UTC, makaryb commented
> Хм.. Очень загадочно.
> А сейчас GET был не пустой базе случаем?

Нет, предварительно пострелял также минуту PUT'ами со стабильной нагрузкой R100k.

При проведении испытаний было только одно отличие:

Раньше всегда запускал сервер в терминале

```
./gradlew run
```

А сейчас запустил в Идее со следующей конфигурацией:

![Selection_012](https://user-images.githubusercontent.com/36387962/95745093-254af400-0c9d-11eb-97f4-35e6f0ee3773.png)

Посмотрел `gradlew`, там следующее:

![Selection_011](https://user-images.githubusercontent.com/36387962/95745153-3bf14b00-0c9d-11eb-96a4-8876edc2bd6f.png)

Провел экспериментальное сравнение:

C PUT'ами все одинаково и так, и так.

С GET'ами сперва нестабильно (при указании wrk2 стрелять R1500), однако затем все в порядке:

первую минуту 1300 с запредельным временем ответа и затем уже все время также заданные 1500:

![output-get-all](https://user-images.githubusercontent.com/36387962/95746680-dce10580-0c9f-11eb-989f-e55503cdd663.png)

Однако со стабильной R100, как было раньше - не столкнулся.

Не знаю, могло ли быть связано с этим в прошлый раз, но сейчас стабильно GET до 2k rate обеспечивает нагрузку на данной реализации.

2020-10-12 12:37 UTC, dormidon commented
🔥

2020-10-12 12:38 UTC, dormidon approved these changes

2020-10-12 12:38 UTC, closed without merging