hw1
polis-mail-ru/2020-highload-dht pull request #6
Opened 2020-09-27 09:49 UTC by zvladn7

Отчет по профилированию находится в папке `profile`

2020-10-02 22:55 UTC, lamtev requested changes
Замечания по профилированию сервиса под нагрузкой:
1. В репозитории отсутствуют флейм-графы в формате `.svg`, поэтому нет возможности ознакомиться с результатами более детально
2. В репозитории отсутствуют файлы с выводом `wrk`
3. Формат отчета выбран не самый reviewer-friendly. Лучше бы это был Markdown
4. Хоть в проекте и выставлен уровень логгирования `INFO`, профилирование сервиса, вероятно, проводилось до данной настройки, о чем свидетельствуют флейм-графы (очень много в стектрейсах логгирования относительно всего остального)
5. Вместо `wrk2` использовалась `wrk`. Нужно воспользоваться `wrk2` и добавить в отчет полученные перцентили
6. Есть подозрение, что сначала проводился обстрел GET по пустому DAO, что категорически неправильно
7. Хоть в репозитории есть `get.lua`, судя по отчету, данный генератор не использовался, а все GET были с ключом *key*. Возможно это не так. В отчете стоит этот момент более четко отразить.
8. Отлично что была реализована оптимизация с кэшом, но судя по 5% приросту производительности, как-то это не работает) Возможно из-за неправильной методики, о чем было упомянуто выше. Возможно из-за маленького размера кэша (10 записей). Возможно сценарий обстрела был неправильным, например, чтение осуществлялось с помощью `get.lua` по последовательности ключей, без дубликатов.
9. 10 минут обстреливать вовсе необязательно. Вполне достаточно и десятков секунд

Вся суть данной части первого этапа  в том, чтобы
1) Заполнить хранилище данными, посмотрев с помощью `wrk2` latency distribution, и посмотрев с помощью профилировщика какой код сколько времени выполняется. Сделать выводы, предложить оптимизации
2) Обстрелять GET запросами уже наполненное данными хранилище, проанализировать результаты, предложить оптимизации
3) Реализовать оптимизации и сравнить результаты с тем, что было до них

Необходимо исправить замечания по коду. За это можно будет получить 5 баллов. Для большего нужно разобраться с профилированием

2020-10-02 22:55 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/BasicService.java
> +    private final Map<String, byte[]> cache = new LinkedHashMap<>();
Стоит помнить, что данное решение не thread-safe. В первом этапе допустимо

2020-10-03 12:59 UTC, zvladn7 commented
@lamtev все поправил. Вот [обновленные результаты нагрузочного тестирования, профилирования и их анализ](https://github.com/zvladn7/2020-highload-dht/blob/master/report/hw1.md)

2020-10-03 13:44 UTC, lamtev requested changes

2020-10-03 13:44 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/BasicService.java
> +                updateCache(id, request.getBody());
Так тоже неправильно, потому что метод `updateCache` будет вытеснять записи:
Пусть у нас размер кэша 5, и в нем находятся следующие ключи `[0, 1, 2, 3, 4]`.
Посмотрим как сейчас все работает:
1. На сервер приходит `PUT` запрос с ключем `3`
2. Пара ключ-значение вставляются в dao
3. Т.к. кэш уже содержит ключ `3`, мы попадаем в эту ветку
4. Удаляем первый ключ, получаем `[1, 2, 3, 4]`
5. Обновляем значение по ключу `3`, ключи в кэше остаются прежними
6. При последующих аналогичных поступающих запросах можно дропнуть почти весть кэш :(

То есть получается, что на `upsert` мы непонятно зачем выбрасываем значения из кэша

Как нужно делать:
Если такой ключ уже есть в кэше, то просто меняем значение по нему:
```java
if (cache.containsKey(k) {
    cache.put(k, v);
}
```

В java 8+ есть метод `Map.computeIfPresent`, который можно использовать в этой ситуации:
```java
cache.computeIfPresent(k, __ -> v);
```

2020-10-03 15:31 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/BasicService.java
> +                updateCache(id, request.getBody());
@lamtev Действительно, не заметил этот момент, спасибо за ревью! Использовал `putIfAbsent`

2020-10-03 15:40 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/BasicService.java
> +                updateCache(id, request.getBody());
`putIfAbsent` вставляет значение по ключу, если для этого ключа еще нет записи. У нас же цель другая - как раз обновить существующее значение на новое

2020-10-03 16:20 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/BasicService.java
> +                updateCache(id, request.getBody());
Прошу прощения, к концу недели уже тяжело соображаю) Искал `computeIfPresent` и почему-то принял `Absent` за `Present`. Еще раз спасибо! Поправил, и обновил соответственно результаты нагрузочного тестирования. В следующий раз буду более внимательным)

2020-10-03 20:08 UTC, lamtev approved these changes
Принятно

Но есть один момент:
Судя по latency, сервер такую нагрузку совершенно не вывозит. Правильно было бы попробовать пострелять с разной нагрузкой, чтобы выявить, с чем сервер может с правиться, а с чем нет. Профилировать лучше под нагрузкой, которую сервер может выдержать. Можно не переделывать. Прошу просто это учесть, в следующих этапах пригодится

2020-10-03 20:09 UTC, closed without merging