Stage 3
polis-mail-ru/2020-highload-dht pull request #62
Opened 2020-10-11 14:48 UTC by StasyanOi

2020-10-12 09:50 UTC, incubos requested changes
Текущая реализация неасинхронная. Более того, она медленнее предыдущей, потому что работу в `get()`  мы **удвоили**. Кроме того, хотя работа с `DAO` и (почти) вынесена в отдельный пул потоков, мы **блокируем** потоки-обработчики HTTP запросов в ожидании результатов.

2020-10-12 09:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        httpServerConfig.selectors = 3;
Почему именно 3?

2020-10-12 09:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        httpServerConfig.maxWorkers = 10;
Это для чего?

2020-10-12 09:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            response = dao.get(id);
Это же совершенно неправильно. Вы запускаете `dao.get()` в отдельном потоке через `submit()`, затем дожидаетесь завершения асинхронной операции, выкидываете результат, а затем снова вызываете `dao.get()` в текущем потоке. Здесь нет никакой асинхронности и целевую операцию мы выполняем **2 раза**.
Это же видно и на flamegraph CPU профилирования.
Необходимо, чтобы ответ отправлялся клиенту из потока, который выполнил `dao.get()`.

2020-10-12 09:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        awaitUntilReady(future);
См. замечание к `get()` выше -- всё применимо и здесь.

2020-10-12 09:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private void awaitUntilReady(final Future<?> future) {
Этот метод не нужен. Наш сервер должен быть асинхронным, а тут мы просто сжигаем процессорные циклы.

2020-10-12 09:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        future.get();
См. замечание к `get()` выше -- всё применимо и здесь.

2020-10-12 09:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public Response abracadabra() {
Это зачем?

2020-10-12 14:03 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public Response abracadabra() {
![Снимок экрана от 2020-10-12 16-26-03](https://user-images.githubusercontent.com/36096614/95755233-d3aa6580-0cac-11eb-838c-5af30eb0fd1d.png)
Тест такой просто есть

2020-10-12 14:03 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        future.get();
Пофиксил

2020-10-12 14:04 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        httpServerConfig.selectors = 3;
Это просто для себя я дебажил для интереса, в комит попало. Уже убрал

2020-10-12 14:05 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        httpServerConfig.maxWorkers = 10;
Для интереса проставлял опции для конфига и дебажил. В комит попало случайно. Тоже уже убрал

2020-10-12 14:05 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            response = dao.get(id);
Исправил

2020-10-12 14:05 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        awaitUntilReady(future);
Убрал функцию, там больше нету ожидания

2020-10-12 14:05 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private void awaitUntilReady(final Future<?> future) {
Убрал функцию.

2020-10-14 09:59 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public Response abracadabra() {
Смысл этого теста в том, что на все запросы, которые сервер не понимает, нужно возвращать HTTP код `400`, поэтому правильнее переопределить метод `HttpServer.handleDefault()`.

2020-10-14 10:31 UTC, incubos requested changes
Имеется ряд замечаний, требующих исправления. Особенно большие вопросы вызывает использование `synchronized`.

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    public synchronized ByteBuffer get(final @NotNull ByteBuffer key) throws NoSuchElementException {
Почему здесь `synchronized`?

2020-10-14 10:31 UTC, incubos commented on reports/stage1/get.lua
> +    wrk.headers["Content-Type"] = "text/plain"
Зачем это?

2020-10-14 10:31 UTC, incubos commented on reports/stage1/put.lua
> +    wrk.headers["Content-Type"] = "text/plain"
Зачем это?

2020-10-14 10:31 UTC, incubos commented on reports/stage1/summary.md
> +rm wrkLogsPut.txt
См. замечание к скриптам выше.

2020-10-14 10:31 UTC, incubos commented on reports/stage3/async/runLoadTestGet.txt
> +rm wrkLogsGet.txt
Идея написать скрипт хорошая, но:

- `wrk2` тратит часть времени на калибровку
- JVM нужно "прогревать"
- Наконец, 5+5+5=15, но запуск профилирования требует времени, и нагрузка уходит раньше, чем закончится профилирование `lock`

Т.е. стрелять нужно гораздо дольше и начинать профилировать нужно после определённой паузы.

2020-10-14 10:31 UTC, incubos commented on reports/stage3/async/runLoadTestPut.txt
> +rm wrkLogsPut.txt
См. замечание к `runLoadTestGet.txt`.

2020-10-14 10:31 UTC, incubos commented on reports/stage3/async/wrkLogsGet.txt
> +Requests/sec:   1866.48
2000 выжать не смогли -- почему?

2020-10-14 10:31 UTC, incubos commented on reports/stage3/get.lua
> +    wrk.headers["Content-Type"] = "text/plain"
Зачем это?

2020-10-14 10:31 UTC, incubos commented on reports/stage3/put.lua
> +    wrk.headers["Content-Type"] = "text/plain"
Зачем это?

2020-10-14 10:31 UTC, incubos commented on reports/stage3/summary.md
> +rm wrkLogsPut.txt
См. замечания к скриптам выше.

2020-10-14 10:31 UTC, incubos commented on reports/stage3/summary.md
> +![alt text](sync/flamePutCpu.svg "put cpu")
Например, тут видно, как "молотит" JIT, потому что идёт прогрев.

2020-10-14 10:31 UTC, incubos commented on reports/stage3/summary.md
> +![alt text](async/flamePutCpu.svg "put cpu")
И тут "молотит" JIT.

2020-10-14 10:31 UTC, incubos commented on reports/stage3/summary.md
> +что реализация get требует блокирования всей операции.  Таким образом образуется
Почему требует? Давайте уберём бутылочное горлышко? У нас же RocksDB под капотом.

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAO.java
> -    default ByteBuffer get(@NotNull ByteBuffer key) throws IOException, NoSuchElementException {
Зачем это изменение?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAO.java
> -    void upsert(
Зачем это изменение?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAO.java
> -    default void compact() throws IOException {
Зачем это изменение?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Зачем это?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            ByteBuffer body;
Почему не внести в `try`?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                throw new RuntimeException(e);
Не хватает логгирования и возврата HTTP кода `500`.

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Зачем это?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                throw new RuntimeException(e);
Не хватает логгирования и возврата HTTP кода `500`.

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Зачем это?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Зачем это?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                throw new RuntimeException(e);
Не хватает логгирования и возврата HTTP кода `500`.

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Зачем это?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Зачем это?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        response.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Зачем это?

2020-10-14 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public synchronized void stop() {
Ещё нужно корректно остановить `executorService`.

2020-10-14 11:00 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +    public synchronized ByteBuffer get(final @NotNull ByteBuffer key) throws NoSuchElementException {
Сейчас реализация get использует рокс дб итератор, который требудет внешней синхронизации при вызове не конст методов. Добавил реализацию через метод get у starage instance
![Снимок экрана от 2020-10-14 13-59-13](https://user-images.githubusercontent.com/36096614/95980281-99b09f00-0e25-11eb-97cf-064cb25c39be.png)

2020-10-14 11:06 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        response.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
![Снимок экрана от 2020-10-14 14-05-27](https://user-images.githubusercontent.com/36096614/95980813-5f93cd00-0e26-11eb-9e0c-b6a8631e19fd.png)
Получаю вот такие ошибки иначе.

2020-10-14 11:07 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
![Снимок экрана от 2020-10-14 14-05-27](https://user-images.githubusercontent.com/36096614/95980884-7c300500-0e26-11eb-9ac3-3b7f7dcafb31.png)
Ошибка иначе

2020-10-14 11:08 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public synchronized void stop() {
пофиксил

2020-10-14 11:08 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
![Снимок экрана от 2020-10-14 14-05-27](https://user-images.githubusercontent.com/36096614/95981043-c31dfa80-0e26-11eb-96c6-95e925207474.png)

2020-10-14 11:09 UTC, StasyanOi commented on reports/stage3/summary.md
> +что реализация get требует блокирования всей операции.  Таким образом образуется
Да, переделал get без итератора

2020-10-14 11:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/DAO.java
> -    default ByteBuffer get(@NotNull ByteBuffer key) throws IOException, NoSuchElementException {
Сейчас уже оно не релевантно. Откатил обратно.

2020-10-14 11:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/DAO.java
> -    void upsert(
Сейчас уже оно не релевантно. Откатил обратно.

2020-10-14 11:13 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/DAO.java
> -    default void compact() throws IOException {
Сейчас уже оно не релевантно. Откатил обратно.

2020-10-14 11:14 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
![Снимок экрана от 2020-10-14 14-05-27](https://user-images.githubusercontent.com/36096614/95981565-830b4780-0e27-11eb-941f-8f9126ef62fb.png)

2020-10-14 11:14 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
![Снимок экрана от 2020-10-14 14-05-27](https://user-images.githubusercontent.com/36096614/95981578-8999bf00-0e27-11eb-8ba6-2fb489bae786.png)

2020-10-14 11:14 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
![Снимок экрана от 2020-10-14 14-05-27](https://user-images.githubusercontent.com/36096614/95981592-8dc5dc80-0e27-11eb-8153-4814dc6e256f.png)

2020-10-14 11:14 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
![Снимок экрана от 2020-10-14 14-05-27](https://user-images.githubusercontent.com/36096614/95981611-94545400-0e27-11eb-9458-563c67c048fd.png)

2020-10-14 11:15 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public synchronized void stop() {
Пофиксил

2020-10-14 12:33 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            ByteBuffer body;
добавил

2020-10-14 13:14 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                throw new RuntimeException(e);
добавил

2020-10-14 13:14 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                throw new RuntimeException(e);
добавил

2020-10-14 13:14 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                throw new RuntimeException(e);
добавил

2020-10-14 13:30 UTC, StasyanOi commented on reports/stage1/put.lua
> +    wrk.headers["Content-Type"] = "text/plain"
Нужно указывать тип body в put запросе же по идее.

2020-10-14 13:30 UTC, StasyanOi commented on reports/stage1/get.lua
> +    wrk.headers["Content-Type"] = "text/plain"
Помарка, убрал лишний хэдер для гета.

2020-10-14 17:54 UTC, StasyanOi commented on reports/stage3/async/runLoadTestGet.txt
> +rm wrkLogsGet.txt
переделал скрипт

2020-10-14 17:56 UTC, StasyanOi commented on reports/stage1/summary.md
> +rm wrkLogsPut.txt
Это удаление файлов для автоматизации процесса проверки.

2020-10-14 17:57 UTC, StasyanOi commented on reports/stage3/summary.md
> +rm wrkLogsPut.txt
Это просто удаление старых логов

2020-10-14 17:58 UTC, StasyanOi commented on reports/stage3/summary.md
> +![alt text](sync/flamePutCpu.svg "put cpu")
Добавил новые фото

2020-10-14 17:58 UTC, StasyanOi commented on reports/stage3/summary.md
> +![alt text](async/flamePutCpu.svg "put cpu")
Переделал и добавил новые фото

2020-10-16 05:51 UTC, StasyanOi commented
@incubos, переделал профилирование под нагрузку побольше - около 6000 запросов в секунду. Новый sharding тест в мастере появился - тесты падают.

2020-10-16 10:50 UTC, incubos requested changes
Стрельбы и профилирование выглядят ОК. Есть небольшие замечания по коду.

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +            storageInstance.put(CustomServer.toBytes(key), CustomServer.toBytes(value));
Это замечание, скорее, по дизайну -- `DAO` не должен пользоваться методами `Service`. В архитектуре он находится ниже. Предлагаю вынести `toBytes()`/`fromBytes()` в отдельный утилитный класс и использовать его отовсюду.

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +            body = storageInstance.get(CustomServer.toBytes(key));
Утилитный класс?

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +        return CustomServer.fromBytes(body);
Утилитный класс?

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +            storageInstance.delete(CustomServer.toBytes(key));
Утилитный класс?

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                             final Object... routers) throws IOException {
Зачем тут `routers`? Разве вы их используете?

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public static byte[] toBytes(final ByteBuffer buffer) {
Вынесем в утилитный класс?

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public static ByteBuffer fromBytes(final byte[] bytes) {
Утилитный класс?

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        Response responseHttp;
Стоит добавить `final`, чтобы компилятор контролировал, что значение проициниализировано во всех ветках.

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        Response responseHttp;
Стоит добавить `final`, чтобы компилятор контролировал, что значение проициниализировано во всех ветках.

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        Response responseHttp;
Стоит добавить `final`, чтобы компилятор контролировал, что значение проициниализировано во всех ветках.

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/IteratorImpl.java
> +        this.rocksIterator.seek(CustomServer.toBytes(key));
Утилитный класс? Давайте везде уже :)

2020-10-16 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +     private final Logger logger = LoggerFactory.getLogger(CustomServer.class);
Почему не `static`?

2020-10-16 10:50 UTC, incubos commented on reports/stage3/summary.md
> +rm wrkLogsPut.txt
Замечание было в целом к скриптам. Пофикшено.

2020-10-16 15:38 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +            storageInstance.put(CustomServer.toBytes(key), CustomServer.toBytes(value));
Добавил Mapper

2020-10-16 15:38 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +            body = storageInstance.get(CustomServer.toBytes(key));
Добавил Mapper

2020-10-16 15:38 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +        return CustomServer.fromBytes(body);
Добавил Mapper

2020-10-16 15:38 UTC, StasyanOi commented on src/main/java/ru/mail/polis/dao/stasyanoi/DAOImpl.java
> +            storageInstance.delete(CustomServer.toBytes(key));
Добавил Mapper

2020-10-16 15:39 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +                             final Object... routers) throws IOException {
Нет, не использую уже, убрал

2020-10-16 15:39 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public static byte[] toBytes(final ByteBuffer buffer) {
Добавил Mapper

2020-10-16 15:39 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public static ByteBuffer fromBytes(final byte[] bytes) {
Добавил Mapper

2020-10-16 15:41 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        Response responseHttp;
Здесь добавил

2020-10-16 15:42 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        Response responseHttp;
Добавил

2020-10-16 15:42 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        Response responseHttp;
Здесь проблема возникает с этим 
![Снимок экрана от 2020-10-16 18-41-22](https://user-images.githubusercontent.com/36096614/96279445-569a2b80-0fdf-11eb-9283-13e686664825.png)

2020-10-16 15:43 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/IteratorImpl.java
> +        this.rocksIterator.seek(CustomServer.toBytes(key));
Создал Mapper класс

2020-10-16 15:44 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +     private final Logger logger = LoggerFactory.getLogger(CustomServer.class);
Раньше ошибка выскакивала, но сейчас нормально. Добавил

2020-10-16 15:57 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        Response responseHttp;
Переделал, теперь final есть

2020-10-16 16:14 UTC, StasyanOi commented
@incubos ,  добавил изменения. Были проблемы с final в getInternal, но сейчас все нормально уже

2020-10-18 14:14 UTC, incubos commented
Принято.

2020-10-18 14:14 UTC, closed without merging