Stage 3
polis-mail-ru/2020-highload-dht pull request #64
Opened 2020-10-11 20:18 UTC by re1nex

2020-10-11 21:04 UTC, re1nex commented
профилирование в процессе , открыл пр , чтобы повоевать с codeclimate и travis

2020-10-12 21:53 UTC, re1nex commented
# PUT
## wrk
Реализация без ExecutorService

  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.13ms   34.23ms 839.17ms   99.52%
    Req/Sec   526.26    297.10    39.44k    99.45%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.01ms
 75.000%    1.32ms
 90.000%    1.59ms
 99.000%    2.12ms
 99.900%  672.26ms
 99.990%  823.81ms
 99.999%  838.14ms
100.000%  839.68ms

#[Mean    =        3.128, StdDeviation   =       34.229]
#[Max     =      839.168, Total count    =       339837]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  359953 requests in 3.00m, 23.00MB read
Requests/sec:   1999.73
Transfer/sec:    130.84KB

Реализация c ExecutorService

  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.29ms  520.70us  27.34ms   69.24%
    Req/Sec   525.15    389.84     1.89k    75.60%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.26ms
 75.000%    1.61ms
 90.000%    1.92ms
 99.000%    2.49ms
 99.900%    2.90ms
 99.990%   10.75ms
 99.999%   25.14ms
100.000%   27.36ms

#[Mean    =        1.286, StdDeviation   =        0.521]
#[Max     =       27.344, Total count    =       339838]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  359475 requests in 3.00m, 22.97MB read
Requests/sec:   1996.99
Transfer/sec:    130.66KB

В целом ситуация похожа , возможно стоило взять нагрузку побольше , но даже тут заметно, что 1% запросов уже начинают занимать порядком больше (>500 мс) по сравнению с реализацией с ExecutorService .

## CPU
Реализация без ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95792143-88637780-0ceb-11eb-983f-8af1e1c310a2.png)

Реализация c ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95792169-92857600-0ceb-11eb-9f19-4602ce332e9c.png)

В то время пока в реализации без  ExecutorService тратятся ресурсы процессора на ожидание , пока dao выполнит действия , в реализации c ExecutorService селекторы продолжают заниматься своими обязанностями , но достаточно много уходит на управление ExecutorService  (ArrayBlockingQueue и тд) , в результате на именно сам Dao.upsertуходит только 13 %

## ALLOC
Реализация без ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95792359-06278300-0cec-11eb-870e-cc8c0b2cd226.png)

Реализация c ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95792376-10498180-0cec-11eb-8603-44f27a761fc5.png)

Картина почти такая же, ресурсы  в реализации с ExecutorService
 делятся пополам , только на сам upsert тратиться только 10 %

## LOCK 
Реализация без ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95792764-c44b0c80-0cec-11eb-8efe-c54b59e36ea1.png)

Реализация c ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95792776-cc0ab100-0cec-11eb-9bfa-098ae53d2f3f.png)

Воркеры из ArrayBlockingQueue работают под локами , селекторы занимаются своей работой

# PUT
## wrk
Реализация без ExecutorService
 Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.49ms    2.40ms 138.75ms   99.61%
    Req/Sec   527.36    108.62     1.60k    61.21%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.37ms
 75.000%    1.72ms
 90.000%    2.05ms
 99.000%    2.74ms
 99.900%   34.94ms
 99.990%  109.18ms
 99.999%  134.53ms
100.000%  138.88ms
#[Mean    =        1.488, StdDeviation   =        2.399]
#[Max     =      138.752, Total count    =       339838]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  359952 requests in 3.00m, 24.98MB read
Requests/sec:   1999.72
Transfer/sec:    142.10KB

Реализация c ExecutorService
 Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.20ms  487.42us  17.17ms   66.71%
    Req/Sec   526.40    389.90     1.78k    75.89%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.16ms
 75.000%    1.50ms
 90.000%    1.86ms
 99.000%    2.37ms
 99.900%    2.71ms
 99.990%    7.53ms
 99.999%   16.22ms
100.000%   17.18ms
#[Mean    =        1.199, StdDeviation   =        0.487]
#[Max     =       17.168, Total count    =       339841]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  359484 requests in 3.00m, 24.95MB read
Requests/sec:   1997.02
Transfer/sec:    141.91KB

Ситуация аналогичная с put

## CPU
Реализация без ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95791673-877e1600-0cea-11eb-9dc0-d30bca139b83.png)

Реализация c ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95791701-95339b80-0cea-11eb-8327-230c452fc188.png)

В то время пока в реализации без  ExecutorService тратятся ресурсы процессора на ожидание , пока dao выполнит действия , в реализации c ExecutorService селекторы продолжают заниматься своими обязанностями , но достаточно много уходит на управление ExecutorService  (ArrayBlockingQueue и тд) , в результате на именно сам Dao.get уходит только 14 %

## ALLOC
Реализация без ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95793204-c366aa80-0ced-11eb-9563-6ee86602f429.png)

Реализация c ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95793225-ca8db880-0ced-11eb-8e8f-f4c903fdd842.png)

Большая часть ресурсов уходит на работу воркеров , скорее всего связано с тем , что нам нужно проитерироваться по всему , что достаточно затратно , на сам get из Dao уходит 50%

## LOCK 
Реализация без ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95793436-41c34c80-0cee-11eb-85ac-3c2f36e3e2cd.png)

Реализация c ExecutorService
![image](https://user-images.githubusercontent.com/48808317/95793447-46880080-0cee-11eb-8332-125f526f19d5.png)

Тоже самое ,что и с put

2020-10-17 22:19 UTC, lamtev requested changes
Замечания по профилированию:
1. На флейм графах профилирования синхронной реализации видно, что много времени и памяти жрет `Logger.error`. Зачем-то каждый запрос логгируется с уровнем `ERROR`. Ладно, это был 2-й этап. В асинхронной реализации таких проблем нет
2. Не закоммичены .svg флейм графов, поэтому не могу более детально посмотреть. Полученные .svg надо коммитить.
3. Раздел с `GET` ошибочно назван опять `PUT`, но по графам понятно о чем речь
4. По локам хотелось бы видеть в отчете сколько процентов на readLock, сколько на writeLock
5. Нужно добавлять в отчет выполненные команды wrk и profiler.sh. Так будет понятно, во сколько потоков/соединений выполнялся обстрел. В течение какого времени выполнялось профилирование
6. Нужно в отчет добавлять полный вывод wrk

Нужно добавить .svg и полные выводы wrk. Тогда смогу с большей уверенностью сказать, что есть проблемы, либо же все ок.

На всякий случай скажу как было нужно делать:
Сначала для PUT (наполняем базу), а затем для GET (по наполненной базе)
1. 4 потока 64 соединения
2. выбираем адекватную нагрузку, которую потянет сервис
3. начинаем обстрел с этой стабильной нагрузкой, пусть хотя бы секунд 30 jvm процесс будет прогреваться
4. затем подключаемся профилировщиком и последовательно снимаем CPU/ALLOC/LOCK (можно было снимать и в рамках отдельных обстрелов, но тогда нужно не забывать каждый раз прогревать jvm)

2020-10-17 22:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new MyService(port, dao);
Не AsyncService почему-то

2020-10-17 22:35 UTC, lamtev commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +                        final int queueSize) throws IOException {
workersCount и queueSize задаются разными значениями, и поэтому хотелось бы увидеть какими именно. сейчас в фабрике возвращается сервис из прошлых этапов

2020-10-17 22:39 UTC, lamtev commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +                workersCount, queueSize,
Это так было задумано, что corePoolSize= workersCount, а maximumPoolSize= queueSize ?

2020-10-17 23:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +    private static final Logger logger = LoggerFactory.getLogger(AsyncService.class);
статические поля и тем более константы обычно размещают в начале класса

2020-10-17 23:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +        executor = new ThreadPoolExecutor(
this

2020-10-18 09:59 UTC, re1nex commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new MyService(port, dao);
ой , замеры делал , забыл обратно поставить

2020-10-18 10:04 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +                workersCount, queueSize,
опечатался похоже , но queueSize  > workersCount поэтому вроде нестрашно

2020-10-18 10:06 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/MyService.java
> +        logger.error("PUT element {}.", id);
ой, забыл тут исправить  , сейчас поправлю , видимо замеры тоже придется переделать

2020-10-18 18:30 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new AsyncService(port, dao, Runtime.getRuntime().availableProcessors(), 16);
Не маленький размер очереди?

2020-10-18 18:30 UTC, lamtev commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +        executor.execute(() -> {
Я непонятно спросил? Ответа не поступило, но и правки были внесены не те, которые ожидались. Имелось введу, что мгновенная отправка OK - это очень быстро, поэтому есть ли смысл это операцию выполнять на executor?

2020-10-18 18:35 UTC, lamtev commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +                workersCount, queueSize,
ну как сказать. если `corePoolSize == maximumPoolSize `, то у нас фиксированное число потоков. если `corePoolSize < maximumPoolSize `, тогда пулл может расширяться/уменьшаться. и в этом кейсе логично было бы `keepAliveTime` делать не 0

2020-10-18 18:35 UTC, re1nex commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new AsyncService(port, dao, Runtime.getRuntime().availableProcessors(), 16);
да вроде нет или лучше взять как число соединений ?

2020-10-18 18:36 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +        executor.execute(() -> {
не увидел вначале , сейчас уберу

2020-10-18 18:37 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncService.java
> +        executor.execute(() -> {
уберу

2020-10-18 18:38 UTC, lamtev commented
Остались лишние изменения. Прошу просмотреть дифф всего ПР и убрать все лишнее

2020-10-18 18:57 UTC, lamtev commented on src/main/java/ru/mail/polis/Files.java
> -/*
не исправлено

2020-10-18 21:04 UTC, lamtev reviewed
Оставил еще 1 коммент по коду

По отчету замечания планируется исправить или нет?

2020-10-18 21:17 UTC, lamtev commented
~~Ладно. В дальнейшем прошу учесть оставленные по профилированию замечания~~

~~Принято~~

Хотел принять, но увидел, что не выполняется часть тестов 3 этапа. Нужно починить

2020-10-20 09:51 UTC, lamtev commented
Напомню, что сегодня вечером дедлайн по правкам 3-го этапа. Часть SingleNodeTest так и не была поправлена

2020-10-20 10:07 UTC, lamtev commented
Тесты 3-го этапа проходят. Принято

2020-10-20 10:07 UTC, closed without merging