Homework3
polis-mail-ru/2020-highload-dht pull request #65
Opened 2020-10-11 21:19 UTC by Marashov-Alexander

2020-10-14 10:42 UTC, incubos requested changes
Имеются замечания, требующие исправлений.

2020-10-14 10:42 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +                        trySendError(httpSession, new Response(Response.INTERNAL_ERROR, Response.EMPTY));
В случае ошибки мы ведь отправим **два ответа**.

2020-10-14 10:42 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +                        trySendError(httpSession, new Response(Response.INTERNAL_ERROR, Response.EMPTY));
В случае ошибки мы ведь отправим **два ответа**.

2020-10-14 15:55 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +                        trySendError(httpSession, new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Спасибо, поправил. Заодно и имя метода поменял на более логичное

2020-10-16 11:10 UTC, incubos requested changes
Нагрузочное тестирование и профилирование ОК, но есть ряд замечаний по коду.

2020-10-16 11:10 UTC, incubos commented on profiler/homework3/results.txt
> +../../IdeaProjects/wrk2/wrk2/wrk -t10 -c64 -d 4m -R 10000 -s ../../IdeaProjects/wrk2/wrk2/putS.lua --latency http://localhost:8080
Вкомитьте, пожалуйста, скрипт `putS.lua`.

2020-10-16 11:10 UTC, incubos commented on profiler/homework3/results.txt
> +../../IdeaProjects/wrk2/wrk2/wrk -t10 -c64 -d 4m -R 10000 -s ../../IdeaProjects/wrk2/wrk2/getS.lua --latency http://localhost:8080
Вкомитьте, пожалуйста, скрипт `getS.lua`.

2020-10-17 07:34 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +    private final Logger log = LoggerFactory.getLogger(ServiceImpl.class);
Добрый день!
Прогуглил этот вопрос: при использовании нашего кода  в качестве библиотеки в контейнере, где настроено использование общих классов для "независимых" приложений возникнут проблемы с конфигурацией этого общего логгера относительно каждого приложения.
Однако против static нашего случая я ничего не нашёл, сейчас исправлю)

2020-10-17 07:45 UTC, Marashov-Alexander commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +                        log.debug(String.format("Get entity method: key = '%s' not found", id));
Спасибо за объяснения, замечания исправил в последнем коммите.
Что касается форматирования: меня смущало,  что в методе логгера с аргументами строки отсутствует Throwable. И если я правильно спустился через Идею к имплементации логгера, то такие методы действительно передают null в качестве Throwable. Значит нужно самостоятельно добавить placeholder в конце форматной строки для исключения?

2020-10-17 07:47 UTC, Marashov-Alexander commented on profiler/homework3/results.txt
> +../../IdeaProjects/wrk2/wrk2/wrk -t10 -c64 -d 4m -R 10000 -s ../../IdeaProjects/wrk2/wrk2/getS.lua --latency http://localhost:8080
Добавил скрипты в папку profiler/scripts/, спасибо)

2020-10-18 14:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +    private final Logger log = LoggerFactory.getLogger(ServiceImpl.class);
В целом, про `static` вы верно написали, но применительно к `getLogger(ServiceImpl.class)` -- не удастся независимо его сконфигурировать, потому что имя у всех экземпляров будет одно и то же.

2020-10-18 14:17 UTC, incubos commented on src/main/java/ru/mail/polis/service/alexander/marashov/ServiceImpl.java
> +                        log.debug(String.format("Get entity method: key = '%s' not found", id));
Нет, самостоятельно placeholder добавлять для `Throwable` не нужно. Если поизучать код `logback` (или `slf4j-api`) можно понять, что это соглашение -- всегда передавать исключение последним аргументом и библиотеки логгирования не требуют placeholder для этого случая.

2020-10-18 14:23 UTC, incubos commented
Принято.

2020-10-18 14:23 UTC, closed without merging