Stage3
polis-mail-ru/2020-highload-dht pull request #67
Opened 2020-10-11 21:50 UTC by KateMoreva

2020-10-11 23:30 UTC, KateMoreva commented
Результаты тестирования будут добавлены в ближайшее время.

2020-10-12 19:20 UTC, KateMoreva commented
### PUT запросы

-t64 -c64 -d60s -R2000 -s ./wrk/put.lua --latency http://localhost:8080

**CPU**
<img src="">

Running 1m test @ http://localhost:8080
  64 threads and 64 connections
**Alloc**
<img src="">

2020-10-12 19:28 UTC, KateMoreva commented
GET запросы

-t64 -c64 -d60s -R2000 -s ./wrk/get.lua --latency http://localhost:8080

**CPU**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/6b5718512b576abeea803f68b83fd79d09836581/tests/stage3/cpuGet2000_c64_t64_60s.svg">

Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.07ms  372.06us   8.04ms   67.87%
    Req/Sec    32.82     48.41   111.00     68.43%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.08ms
 75.000%    1.33ms
 90.000%    1.54ms
 99.000%    1.78ms
 99.900%    3.15ms
 99.990%    5.95ms
 99.999%    7.51ms
100.000%    8.04ms
  120056 requests in 1.00m, 8.06MB read
Requests/sec:   2001.41
Transfer/sec:    137.61KB

**Alooc**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/6b5718512b576abeea803f68b83fd79d09836581/tests/stage3/allocGet2000_c64_t64_60s.svg">

Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.07ms  366.46us  10.02ms   67.89%
    Req/Sec    32.82     48.41   111.00     68.44%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.07ms
 75.000%    1.32ms
 90.000%    1.53ms
 99.000%    1.77ms
 99.900%    2.87ms
 99.990%    6.24ms
 99.999%    9.21ms
100.000%   10.03ms
  120053 requests in 1.00m, 8.06MB read
Requests/sec:   2002.07
Transfer/sec:    137.66KB

**Lock**
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/6b5718512b576abeea803f68b83fd79d09836581/tests/stage3/lockGet2000_c64_t64_60s.svg">

Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.08ms  451.07us  14.98ms   78.15%
    Req/Sec    32.82     48.40   111.00     68.44%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.07ms
 75.000%    1.33ms
 90.000%    1.53ms
 99.000%    1.81ms
 99.900%    6.21ms
 99.990%   10.97ms
 99.999%   14.85ms
100.000%   14.98ms
  120028 requests in 1.00m, 8.06MB read
Requests/sec:   2002.28
Transfer/sec:    137.67KB

2020-10-15 16:33 UTC, vaddya requested changes
В реализации есть ошибка, помочь найти может `SingleNodeTest.respectFileFolder` (у меня локально этот тест вовсе упал).

Насчет профилирования: `-R2000` это точно нагрузка, близкая к максимальной? Не пробовали больше, 5к, 10к, 20к?

2020-10-15 16:33 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        executorService.execute(() -> {
Хм, а стоит ли это выносить в экзекьютор? Кажется, что больше ресурсов будет потрачено на передачу этой задачи между потоками, чем на то, чтобы сразу ответить 400 кодом.

2020-10-15 16:33 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +                session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
Мы не забыли тут выйти из метода?

2020-10-15 16:33 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            log.error("GET method failed on /v0/entity for id {}, error{}", key, e);
Можно не добавлять отдельный плейсхолдер для ошибок:
`log.error("GET method failed on /v0/entity for id {}", key, e);`
`key`, кстати, `ByteBuffer`, поэтому вряд ли выведет что-то адеватное в своем строковом значении...

2020-10-15 16:33 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +    private static final int QUEUE_SIZE = 32;
Какая-то маленькая очередь..

2020-10-15 16:33 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        this.executorService = new ThreadPoolExecutor(numberOfWorkers,
Есть какие-нибудь соображения, почему, например не `Executors.newFixedThreadPool`?

2020-10-15 16:33 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +    private static HttpServerConfig getConfigPort(final int port, final int numberOfWorkers) {
Не очень удачное название, давайте просто `getConfig`?

2020-10-15 22:25 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        executorService.execute(() -> {
Спасибо, действительно не стоит.

2020-10-15 22:47 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +    private static final int QUEUE_SIZE = 32;
Какое значение тогда лучше поставить? Пока определила 256.

2020-10-15 22:50 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +                session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
Забыла, спасибо.

2020-10-15 23:18 UTC, KateMoreva commented
> В реализации есть ошибка, помочь найти может `SingleNodeTest.respectFileFolder` (у меня локально этот тест вовсе упал).
> 
> Насчет профилирования: `-R2000` это точно нагрузка, близкая к максимальной? Не пробовали больше, 5к, 10к, 20к?

На первой стадии ставила R 20000, в этой реализации пока не пробовала, но думала провести.

2020-10-16 09:51 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        this.executorService = new ThreadPoolExecutor(numberOfWorkers,
Если бы мы использовали Executors.newFixedThreadPool, то очередь из запросов была бы не ограничена по размеру, а реализует она FIFO, значит, что возможна ситуация, когда старый запрос уже не нуждается в обработке.

2020-10-16 09:55 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        this.executorService = new ThreadPoolExecutor(numberOfWorkers,
Поэтому очередь следует ограничить.

2020-10-16 09:57 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        this.executorService = new ThreadPoolExecutor(numberOfWorkers,
Все так

2020-10-16 09:57 UTC, KateMoreva commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            log.error("GET method failed on /v0/entity for id {}, error{}", key, e);
Да, пожалуй, лучше тогда либо убрать key,  либо использовать key.get()

2020-10-16 13:31 UTC, KateMoreva commented
### PUT запросы

-t64 -c64 -d60s -R80000 -s ./wrk/put.lua --latency http://localhost:8080

**CPU**

<img src ="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/23e574d498c9af70206291be19c76e9c2b029fdc/tests/stage3/cpuPut80000_c64_t64_60s.svg">
Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.92ms  372.72us  13.58ms   69.42%
    Req/Sec     1.29k    73.17     3.00k    74.66%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.91ms
 75.000%    1.18ms
 90.000%    1.34ms
 99.000%    1.58ms
 99.900%    3.94ms
 99.990%    6.86ms
 99.999%   10.74ms
100.000%   13.58ms
  4797791 requests in 1.00m, 306.56MB read
Requests/sec:  80056.95
Transfer/sec:      5.12MB

**Alloc**

<img src ="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/23e574d498c9af70206291be19c76e9c2b029fdc/tests/stage3/allocPut80000_c64_t64_60s.svg">
Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.92ms  396.51us  16.23ms   73.86%
    Req/Sec     1.29k    75.65     3.44k    73.19%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.91ms
 75.000%    1.18ms
 90.000%    1.34ms
 99.000%    1.62ms
 99.900%    4.47ms
 99.990%    8.57ms
 99.999%   13.15ms
100.000%   16.24ms
  4798181 requests in 1.00m, 306.59MB read
Requests/sec:  80080.22
Transfer/sec:      5.12MB

**Lock**
<img src ="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/23e574d498c9af70206291be19c76e9c2b029fdc/tests/stage3/lockPut80000_c64_t64_60s.svg">
Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.95ms  439.84us  16.85ms   80.04%
    Req/Sec     1.30k    85.91     3.56k    72.21%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.93ms
 75.000%    1.20ms
 90.000%    1.37ms
 99.000%    2.25ms
 99.900%    5.13ms
 99.990%    8.68ms
 99.999%   13.30ms
100.000%   16.86ms
  4798182 requests in 1.00m, 306.59MB read
Requests/sec:  80082.65
Transfer/sec:      5.12MB

### GET запросы

-t64 -c64 -d60s -R80000 -s ./wrk/get.lua --latency http://localhost:8080

CPU
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/23e574d498c9af70206291be19c76e9c2b029fdc/tests/stage3/cpuGet80000_c64_t64_60s.svg">
Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.93ms  392.97us  13.97ms   72.73%
    Req/Sec     1.30k    76.44     3.00k    76.13%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.92ms
 75.000%    1.19ms
 90.000%    1.36ms
 99.000%    1.66ms
 99.900%    4.63ms
 99.990%    7.38ms
 99.999%   10.12ms
100.000%   13.98ms
  4797266 requests in 1.00m, 332.69MB read
Requests/sec:  80031.82
Transfer/sec:      5.55MB

Alloc
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/23e574d498c9af70206291be19c76e9c2b029fdc/tests/stage3/allocGet80000_c64_t64_60s.svg">
Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.92ms  370.33us  16.80ms   68.92%
    Req/Sec     1.30k    74.25     3.44k    75.44%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.92ms
 75.000%    1.18ms
 90.000%    1.35ms
 99.000%    1.56ms
 99.900%    3.92ms
 99.990%    7.39ms
 99.999%   11.61ms
100.000%   16.82ms
  4798249 requests in 1.00m, 332.76MB read
Requests/sec:  80061.78
Transfer/sec:      5.55MB

Lock
<img src="https://raw.githubusercontent.com/polis-mail-ru/2020-highload-dht/23e574d498c9af70206291be19c76e9c2b029fdc/tests/stage3/lockGet80000_c64_t64_60s.svg">
Running 1m test @ http://localhost:8080
  64 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.94ms  401.06us  15.59ms   73.98%
    Req/Sec     1.30k    77.82     3.00k    75.72%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.92ms
 75.000%    1.19ms
 90.000%    1.36ms
 99.000%    1.68ms
 99.900%    4.84ms
 99.990%    7.95ms
 99.999%   10.34ms
100.000%   15.60ms
  4798783 requests in 1.00m, 332.79MB read
Requests/sec:  80041.85
Transfer/sec:      5.55MB

2020-10-16 13:54 UTC, KateMoreva commented
Travis почему-то перестал запускаться

2020-10-16 15:01 UTC, KateMoreva commented
> В реализации есть ошибка, помочь найти может `SingleNodeTest.respectFileFolder` (у меня локально этот тест вовсе упал).
> 
> Насчет профилирования: `-R2000` это точно нагрузка, близкая к максимальной? Не пробовали больше, 5к, 10к, 20к?

Вы не могли бы прислать прислать стек трейс ошибки, пожалуйста?

2020-10-16 15:02 UTC, vaddya commented
А вы ее пофиксили уже, она заключалась в том, что при отсутствии ключа не выходили из метода :)

2020-10-16 15:03 UTC, KateMoreva commented
> А вы ее пофиксили уже, она заключалась в том, что при отсутствии ключа не выходили из метода :)

:) А еще одну все искала

2020-10-16 16:10 UTC, vaddya requested changes
Чуть-чуть комментариев по реализации.

По поводу профилирования -- а что у вас за железо? 80k RPS -- это очень много на самом деле (особенно для самописного хранилища). Но сами графики и отчеты wrk выглядят хорошо.

2020-10-16 16:10 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +            try {
Форматирование чуть-чуть поехало

2020-10-16 16:10 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +                session.sendResponse(new Response(Response.OK, Response.EMPTY));
Стоит ли такое простое действие выносить в экзекьютор? Скорее всего, быстрее будет сразу отправить пустой ответ

2020-10-16 16:10 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +                log.error(SERVER_ERROR, session, e);
`return` забыли

2020-10-16 16:10 UTC, vaddya commented on src/main/java/ru/mail/polis/service/kate/moreva/MySimpleHttpServer.java
> +        executorService.execute(() -> {
На самом деле здесь может прилететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа. Это же касается соседних методов

2020-10-16 16:16 UTC, KateMoreva commented
> Чуть-чуть комментариев по реализации.
> 
> По поводу профилирования -- а что у вас за железо? 80k RPS -- это очень много на самом деле (особенно для самописного хранилища). Но сами графики и отчеты wrk выглядят хорошо.

Железо Dell G3 с Intel Core i5-8300H 4 ядра 8 потоков, оперативка на 8Гб.

2020-10-16 17:29 UTC, KateMoreva commented
> Чуть-чуть комментариев по реализации. Трейвис не запускается, потому что есть конфликты с мастером из-за 4-го этапа, не обращайте внимание.
> 
> По поводу профилирования -- а что у вас за железо? 80k RPS -- это очень много на самом деле (особенно для самописного хранилища). Но сами графики и отчеты wrk выглядят хорошо.

Спасибо за комментарии, исправила все замечания.

2020-10-16 21:36 UTC, vaddya approved these changes
Принято.

2020-10-16 21:36 UTC, closed without merging