hw3
polis-mail-ru/2020-highload-dht pull request #68
Opened 2020-10-11 22:40 UTC by zvladn7

Нагрузочное тестирование и профилирование в процессе

2020-10-12 17:34 UTC, zvladn7 commented
[Анализ нагрузочного тестирования](https://github.com/zvladn7/2020-highload-dht/blob/master/report/hw3.md)

2020-10-17 18:31 UTC, lamtev requested changes
Нужно выпилить нерабочий кэш, после этого еще раз посмотрю (из-за кэша много лишний ветвлений)

2020-10-17 18:31 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        log.error("Unsupported mapping request.\n Cannot understand it: {} {}",
С точки зрения сервиса - это не ошибка

2020-10-17 18:31 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        log.error("Empty key was provided in DELETE method!");
1. Не ошибка, а штатная ситуация
2. В сообщении речь про `DELETE`, но метод вызвается и из `GET`/`PUT`

2020-10-17 18:31 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        log.error("Cannot complete request");
В итоге само `RejectedExecutionException` не логируется, и мы не узнаем подробностей. Лучше вынести на уровень выше, где отлавливается исключение

2020-10-18 11:20 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        log.error("Cannot complete request");
Залогировал, изначально хотел вынести на уровень выше, но проблема в том, что `codeclimate` не пропускает вложенные try в одном методе

2020-10-18 11:20 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +    private final Map<String, byte[]> cache = new LinkedHashMap<>();
изменил на `cache` из `guava`

2020-10-18 11:20 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        processRequest(() -> session.sendResponse(Response.ok("Status: OK")), session);
действительно, как то я об этом не подумал, спасибо

2020-10-18 11:21 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        log.error("Unsupported mapping request.\n Cannot understand it: {} {}",
изменил на `info`

2020-10-18 11:22 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +        log.error("Empty key was provided in DELETE method!");
изменил на info и добавил как параметр `methodName`

2020-10-18 11:23 UTC, zvladn7 commented
@lamtev поправил, сейчас обновлю отчёт, чтобы он соответствовал изменениям

2020-10-18 15:36 UTC, zvladn7 commented
@lamtev [Обновленный анализ нагрузочного тестирования](https://github.com/zvladn7/2020-highload-dht/blob/master/report/hw3_updated.md)

2020-10-18 17:22 UTC, lamtev requested changes
Отлично, что кэш заработал! (Нашел на флейм-графах `com/google/common/cache/LocalCache$LocalManualCache.getIfPresent`)

Профилирование принято с замечаниями:

1. Не закоммичен `get_cache.lua` и вообще не описана методика обстрела. На флейм графе не видно `com/google/common/cache/LocalCache$LocalManualCache.put`, а значит обстрел проводился вообще без кэш промахов. не по одному ли айдишнику? =)
2. Можно было стрелять с айдишниками counter % CACHE_SIZE. Тогда сначала у нас заполнится кэш, а на следующих попытках мы бы уже начали читать из него. Можно поиграться с параметрами, добиваясь различных соотношений cache hit/miss, и сравнивать результаты

2020-10-18 17:22 UTC, lamtev commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +            cache.asMap().remove(id);
`cache.invalidate` можно

2020-10-19 08:24 UTC, zvladn7 commented on LICENSE
> +          stating that You changed the ssTables; and
изменял, видимо, имя переменной в проекте и случайно задел, вернул обратно

2020-10-19 08:25 UTC, zvladn7 commented on LICENSE
> +      source, and configuration ssTables.
аналогично

2020-10-19 08:25 UTC, zvladn7 commented on checkstyle.xml
> +    <!-- Excludes all 'module-info.java' ssTables              -->
тоже

2020-10-19 08:26 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +            .concurrencyLevel(CONCURRENT_LEVEL)
перенес в конструктор, и устанавливаю размер кэша и число потоков через параметры

2020-10-19 08:26 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +            .initialCapacity(CACHE_SIZE)
перенес в конструктор

2020-10-19 08:27 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/AsyncService.java
> +            cache.asMap().remove(id);
изменил, не нашел, что так можно изначально, спасибо)

2020-10-19 08:30 UTC, zvladn7 commented
@lamtev добавил к реквесту и изменил скрипт `get_cache.lua`. Теперь на `flame graph'ах` есть как кэш попадания, так и кэш промахи. Немного поправил отчёт по профилированию и исправил недочёты.

2020-10-19 10:26 UTC, lamtev commented
Принято

2020-10-19 10:26 UTC, closed without merging