Stage #3
polis-mail-ru/2020-highload-dht pull request #70
Opened 2020-10-12 12:43 UTC by ScriptoMax

Обзор аналитического задания содержится в readme

2020-10-16 11:55 UTC, incubos requested changes
Нагрузочное тестирование и профилирование ОК, но есть ряд замечаний по коду, требующих исправления.

2020-10-16 11:55 UTC, incubos commented on README.md
> -# 2020-highload-dht
Вы же посылаете PR в upstream -- здесь не должно быть лишних изменений. Отчёт лучше положить в отдельный файл `report.md`.

2020-10-16 11:55 UTC, incubos commented on README.md
> +./profiler.sh -d 60 -e cpu -t -f /path/to/output/folder/flame_output_cpu.svg <server_process_pid>
Профилировать лучше без `-t` -- это лишь затрудняет анализ.

2020-10-16 11:55 UTC, incubos commented on README.md
> +./profiler.sh -d 60 -e alloc -t -f /path/to/output/folder/flame_output_alloc.svg <server_process_pid>
Профилировать лучше без `-t` -- это лишь затрудняет анализ.

2020-10-16 11:55 UTC, incubos commented on README.md
> +./profiler.sh -d 60 -e lock -t -f /path/to/output/folder/flame_output_lock.svg <server_pid>
Профилировать лучше без `-t` -- это лишь затрудняет анализ.

2020-10-16 11:55 UTC, incubos commented on README.md
> +![put_cpu_ext](https://user-images.githubusercontent.com/55311053/95623828-9791bd80-0a7e-11eb-984b-fd61321ec7f1.jpg)
На будущее (здесь и ниже) -- вставлять можно прямо SVG-файлы, они отлично отображаются в браузере.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +    Logger logger = LoggerFactory.getLogger(TaskService.class);
Должно быть `AsyncService.class`, наверное?

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +    Logger logger = LoggerFactory.getLogger(TaskService.class);
Почему не `private final static`?

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +    public AsyncService(final int port, @NotNull final DAO dao,
Обычно либо все аргументы в одну строку, либо каждый -- на отдельной.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                session.sendResponse(Response.ok("Server is running...\n"));
Метод очень легковесный и нет большого смысла выносить его в отдельный `executor`. Это я идею показывал на live coding demo :)

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            session.sendError(Response.BAD_REQUEST,"Identifier is required as parameter. Error handling request\n");
Не хватает `return`, иначе мы будем продолжать обработку запроса со всеми интересными последствиями.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                upsert(buf, req, session);
В текущем дизайне было чуть логичнее передавать не `Request`, а его тело.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            } catch (NoSuchElementException exc) {
Разве это возможно?

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            } catch (NoSuchElementException exc) {
Мы же перехватываем это внутри `getAsync()`.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                logger.error(IO_ERROR_LOG, exc);
Стоит вернуть клиенту HTTP ошибку, иначе запрос "провиснет".

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                logger.error(IO_ERROR_LOG, exc);
Стоит вернуть клиенту HTTP ошибку.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        exec.execute(() -> {
Здесь может прилететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        exec.execute(() -> {
Здесь может прилететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        exec.execute(() -> {
Здесь может прилететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        exec.execute(() -> {
Здесь может прилететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                logger.error(IO_ERROR_LOG, exc);
Вернуть HTTP ошибку клиенту?

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            session.sendResponse(new Response(Response.NOT_FOUND, Response.EMPTY));
Не хватает `return`? В случае ошибки мы ещё и `AssertionError` получим на `buf`.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            logger.error(NOT_FOUND_ERROR_LOG);
В нашем сервисе это не является ошибкой, может быть, `info()`.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Не хватает `return`? В случае ошибки мы отправим **два ответа**.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        } catch (NoSuchElementException exc) {
Это возможно в LSM хранилище?

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Не хватает `return`? В случае ошибки мы отправим **два ответа**.

2020-10-16 11:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            logger.error("Failed executor termination\n");
Зачем `\n`?

2020-10-16 18:19 UTC, ScriptoMax commented on README.md
> -# 2020-highload-dht
Замечание устранено - создана [копия оригинального док-та](https://github.com/ScriptoMax/2020-highload-dht/blob/test_me_3/resources/report.md) в каталоге <em>resources</em> (в дальнейшем оригиналы будут размещаться только в указанном каталоге)

2020-10-16 18:19 UTC, ScriptoMax commented on README.md
> +./profiler.sh -d 60 -e cpu -t -f /path/to/output/folder/flame_output_cpu.svg <server_process_pid>
удалил параметр из текста, поменял стерео на моно

2020-10-16 18:19 UTC, ScriptoMax commented on README.md
> +./profiler.sh -d 60 -e alloc -t -f /path/to/output/folder/flame_output_alloc.svg <server_process_pid>
удалил параметр из текста, поменял стерео на моно

2020-10-16 18:20 UTC, ScriptoMax commented on README.md
> +./profiler.sh -d 60 -e lock -t -f /path/to/output/folder/flame_output_lock.svg <server_pid>
удалил параметр из текста, поменял стерео на моно

2020-10-16 18:31 UTC, ScriptoMax commented on README.md
> +![put_cpu_ext](https://user-images.githubusercontent.com/55311053/95623828-9791bd80-0a7e-11eb-984b-fd61321ec7f1.jpg)
до сегодняшнего дня пользовался дешёвым и сердитым способом добавления иллюстраций в ридми - через форму вопроса в произвольных репозиториях в своём аккаунте. svg к такому способу был полностью равнодушен, т.е. при вставке в форму для генерации ссылки такие изображения немедленно блокировались. Поэтому решил воспользоваться безотказным <em>jpg</em>. С текущего момента в отчёт будут помещаться изображения из svg-файлов в каталоге <em>resources/flamegraphs</em> (актуальные профили асинхронного сервера добавлены в вёрстку через ссылку на тот же каталог).

2020-10-16 18:32 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +    Logger logger = LoggerFactory.getLogger(TaskService.class);
замечание устранено

2020-10-16 18:32 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +    Logger logger = LoggerFactory.getLogger(TaskService.class);
замечание устранено

2020-10-16 18:32 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +    public AsyncService(final int port, @NotNull final DAO dao,
замечание устранено

2020-10-16 18:32 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                session.sendResponse(Response.ok("Server is running...\n"));
замечание устранено

2020-10-16 18:32 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            session.sendError(Response.BAD_REQUEST,"Identifier is required as parameter. Error handling request\n");
замечание устранено

2020-10-16 18:32 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                upsert(buf, req, session);
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            } catch (NoSuchElementException exc) {
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            } catch (NoSuchElementException exc) {
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                logger.error(IO_ERROR_LOG, exc);
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                logger.error(IO_ERROR_LOG, exc);
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        exec.execute(() -> {
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        exec.execute(() -> {
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        exec.execute(() -> {
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        exec.execute(() -> {
замечание устранено

2020-10-16 18:33 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                logger.error(IO_ERROR_LOG, exc);
замечание устранено

2020-10-16 18:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            session.sendResponse(new Response(Response.NOT_FOUND, Response.EMPTY));
замечание устранено

2020-10-16 18:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            logger.error(NOT_FOUND_ERROR_LOG);
замечание устранено

2020-10-16 18:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
замечание устранено

2020-10-16 18:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +        } catch (NoSuchElementException exc) {
замечание устранено

2020-10-16 18:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
замечание устранено

2020-10-16 18:34 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            logger.error("Failed executor termination\n");
замечание устранено

2020-10-16 18:41 UTC, ScriptoMax commented
Пожалуйста, рассмотрите правки по результатам предыдущего ревью

2020-10-18 14:26 UTC, incubos commented on README.md
> +![put_cpu_ext](https://user-images.githubusercontent.com/55311053/95623828-9791bd80-0a7e-11eb-984b-fd61321ec7f1.jpg)
Какая красота теперь! :)

2020-10-18 14:29 UTC, incubos commented
Принято.

2020-10-18 14:29 UTC, closed without merging