Task3
polis-mail-ru/2020-highload-dht pull request #71
Opened 2020-10-12 14:02 UTC by IvanovAndrey

2020-10-24 08:45 UTC, lamtev requested changes
Сразу ревью по коду, чтобы можно было поскорее исправить

Профилирование будет проверено чуть позже

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +    private static final Logger log = LoggerFactory.getLogger(ServiceImpl.class);
1. Название другого класса
2. Статические поля размещают до инстанс полей

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +        httpServerConfig.queueTime = 10;
Для чего были заданы эти параметры?

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +            val = dao.get(key);
1 раз присваивается, чего бы не сделать сразу при объявлении?

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +            }
Очень странное форматирование, сбивающее с толку. catch из одного try имеют разные отступы, но при этом catch от разных try имеют одинаковые отступы

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +                    session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Если я не запутался (ввиду сбивающих с толку отступов), то сюда можно попасть при выбросе `IOException ` из строки 92 `session.sendResponse(Response.ok(Converter.fromByteBufferToByteArray(val)));`. Если случился `IOException` при отправке ответа, то не нужно выполнять еще одну отправку ответа. 

Сюда нужно попадать только в случае `IOException` в `dao.get`

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +        final int countOfWorkers = Runtime.getRuntime().availableProcessors();
`countOfWorkers` и размер очереди `ArrayBlockingQueue` хорошо бы задавать извне, передавая в конструктор, чтобы пользователи данного класса могли задавать эти параметры, например, в соответствии с имеющимся железом.

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +                        .setNameFormat("async_worker-%d")
так же можно задать `setUncaughtExceptionHandler`, хотя бы логгирующий все необработанные на потоках исключения, как было показано на лекции

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +        service.execute(() -> {
`service` был создан с помощью конструктора `ThreadPoolExecutor`, который в качестве `RejectedExecutionHandler` использует `AbortPolicy`, а это значит, что когда очередь (`ArrayBlockingQueue(1024)`) закончится, то будет выброшено `RejectedExecutionException`. 

То есть при добавлении задач в `service` нужно отлавливать такие исключения и отвечать клиентам `503 Service Unavailable`

Аналогично в остальных методах

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +    }
То же самое:
1. Форматирование
2. `RejectedExecutionException`
3. Отправлять ответ `Response.INTERNAL_ERROR` только при `IOException` в `dao`

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +        });
То же самое:
1. Форматирование
2. `RejectedExecutionException`
3. Отправлять ответ `Response.INTERNAL_ERROR` только при `IOException` в `dao`

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +        });
"Мгновенная" отправка `OK` - легковесная операция. Выносить ее на `service` не требуется

2020-10-24 08:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +    private final ExecutorService service;
В контексте серверного приложения, `service` - это скорее какой-то web сервис либо же `@Service` в терминах Spring. Лучше переименовать, например, в `executor`, если не нравится более длинный вариант `executorService `

2020-10-24 08:45 UTC, lamtev commented on src/test/java/ru/mail/polis/dao/AllDeadTest.java
> +import org.junit.jupiter.api.RepeatedTest;
Лучше не вносить лишних изменений

2020-10-24 08:45 UTC, lamtev commented on src/test/java/ru/mail/polis/service/SingleNodeTest.java
> +import org.junit.jupiter.api.RepeatedTest;
Лучше не вносить лишних изменений

2020-10-24 15:51 UTC, lamtev commented
По профилированию в целом все ОК. В данном этапе уже не буду просить ничего исправлять, потому что уже 4-й пора закрывать)

Замечания/Рекомендации:
1. Лучше указывать в отчете выполненную команду `async-profiler`: `./profile.sh -e cpu -d ...`
2. Все-таки лучше не использовать ключ `-t`, чтобы на флейм графах видеть общую картину: проще анализировать, - полученные проценты не по потокам, а в целом, меньше столбиков ...
3. > В случае с запросом put асинхронный вариант показывает более плохие цифры и по средней и по максимальной задержке.

Странно. Могу предположить что дело в "слабом" железе. Всего 2 аппаратных потока

2020-10-25 15:37 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +    private final ExecutorService service;
Еще хорошо бы переопределить метод суперкласса `stop`, где сказать этому `ExecutorService` "остановись!" и подождать несколько секунд, чтобы дать ему возможность доделать уже запланированные задачи

2020-10-26 00:04 UTC, lamtev commented
Еще по профилированию заметил довольно странные флейм-графы для lock. Как будто они невалидные и не отражают реальной картины

2020-10-31 14:14 UTC, lamtev commented
Исправления будут?

2020-11-01 23:04 UTC, IvanovAndrey commented
Прошу прощения за сильную задерку. Сегодня же ночью попытаюсь сделать по четвертому.

2020-11-02 11:37 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +        } catch (RejectedExecutionException e) {
RejectedExecutionException выбрасывается методом executor.execute. Соответственно сюда никогда не попадем

2020-11-02 11:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +                    session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Этот момент до сих пор не поправлен: IOException от dao и от session обрабатываются все так же одинаково с отправкой ответа клиенту. если исключение выбросилось из session, то еще раз отправлять ответ не нужно

2020-11-02 11:44 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ivanovandrey/AsyncServiceImpl.java
> +        httpServerConfig.queueTime = 10;
Вопрос остался без ответа. Ладно. Как минимум параметр maxWorkers в данной реализации не используется, т.к. не используются воркеры one-nio

2020-11-02 11:45 UTC, lamtev commented
Часть недочетов осталась без исправлений

2020-11-04 16:25 UTC, lamtev commented
На данный момент:
1) Некорректно обрабатывается RejectedExecutionException
2) При IOException в session.sendResponse ответ клиенту может быть отправлен дважды

Можно засчитать решение с потерей баллов. Либо нужно поскорее поправить. Уже 6-й этап на ревью

2020-11-05 21:11 UTC, lamtev commented
Принято с замечаниями

2020-11-05 21:11 UTC, closed without merging