Stage 3
polis-mail-ru/2020-highload-dht pull request #73
Opened 2020-10-12 18:03 UTC by makaryb

Добрый день!

Отправляю решение к этапу 3.

## 1. Нагрузочное тестирование  с помощью wrk2 с большим количеством соединений (не меньше 64) **PUT** и **GET** запросами.

### 1.1 Для **PUT**:

```
wrk2 -t64 -c64 -d1m -R* -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/put.lua --latency http://127.0.0.1:8080
```

**Для 10k-15k-20k-50k-100k-120k**:

![output-put-all](https://user-images.githubusercontent.com/36387962/95763356-98f9fa80-0cb7-11eb-8869-446e22944e06.png)

**Для 10k-15k-20k-50k-100k**:

![output-put-until120](https://user-images.githubusercontent.com/36387962/95763386-a0b99f00-0cb7-11eb-9d4f-02d2f6b90744.png)

Можно видеть, что поддерживает с адекватным времени ответа стабильную нагрузку в 100k rate.

### 1.2 Для **GET**:

```
wrk2 -t64 -c64 -d1m -R* -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/get.lua --latency http://127.0.0.1:8080
```

**Для 1k-2k-3k-4k-6k-8k-8.5k-9k-10k-12k-15k-20k**:

![output-get-all](https://user-images.githubusercontent.com/36387962/95761146-921db880-0cb4-11eb-8eb8-83329312b126.png)

**Для 1k-2k-3k-4k-6k-8k-8.5k-9k-10k-12k-15k**:

![output-get-until20](https://user-images.githubusercontent.com/36387962/95761169-9a75f380-0cb4-11eb-8698-709be72642a1.png)

**Для 1k-2k-3k-4k-6k-8k-8.5k-9k-10k-12k**:

![output-get-until15](https://user-images.githubusercontent.com/36387962/95761224-acf02d00-0cb4-11eb-9bda-2c3912b2e57b.png)

Можно видеть, что поддерживает с адекватным времени ответа стабильную нагрузку в 12k rate.

```
Running 1m test @ http://127.0.0.1:8080
  64 threads and 64 connections
  Thread calibration: mean lat.: 27.015ms, rate sampling interval: 312ms
  Thread calibration: mean lat.: 26.067ms, rate sampling interval: 291ms
  Thread calibration: mean lat.: 27.822ms, rate sampling interval: 340ms
  Thread calibration: mean lat.: 24.940ms, rate sampling interval: 248ms
  Thread calibration: mean lat.: 28.353ms, rate sampling interval: 321ms
  Thread calibration: mean lat.: 26.434ms, rate sampling interval: 290ms
  Thread calibration: mean lat.: 25.836ms, rate sampling interval: 288ms
  Thread calibration: mean lat.: 30.641ms, rate sampling interval: 333ms
  Thread calibration: mean lat.: 28.145ms, rate sampling interval: 310ms
  Thread calibration: mean lat.: 25.457ms, rate sampling interval: 269ms
  Thread calibration: mean lat.: 25.077ms, rate sampling interval: 246ms
  Thread calibration: mean lat.: 26.147ms, rate sampling interval: 260ms
  Thread calibration: mean lat.: 25.290ms, rate sampling interval: 273ms
  Thread calibration: mean lat.: 27.933ms, rate sampling interval: 325ms
  Thread calibration: mean lat.: 28.280ms, rate sampling interval: 345ms
  Thread calibration: mean lat.: 26.492ms, rate sampling interval: 278ms
  Thread calibration: mean lat.: 26.175ms, rate sampling interval: 285ms
  Thread calibration: mean lat.: 25.638ms, rate sampling interval: 251ms
  Thread calibration: mean lat.: 28.451ms, rate sampling interval: 315ms
  Thread calibration: mean lat.: 26.564ms, rate sampling interval: 288ms
  Thread calibration: mean lat.: 28.805ms, rate sampling interval: 359ms
  Thread calibration: mean lat.: 24.896ms, rate sampling interval: 251ms
  Thread calibration: mean lat.: 26.406ms, rate sampling interval: 279ms
  Thread calibration: mean lat.: 24.907ms, rate sampling interval: 225ms
  Thread calibration: mean lat.: 25.009ms, rate sampling interval: 232ms
  Thread calibration: mean lat.: 27.181ms, rate sampling interval: 294ms
  Thread calibration: mean lat.: 26.892ms, rate sampling interval: 301ms
  Thread calibration: mean lat.: 27.168ms, rate sampling interval: 286ms
  Thread calibration: mean lat.: 25.508ms, rate sampling interval: 254ms
  Thread calibration: mean lat.: 27.915ms, rate sampling interval: 331ms
  Thread calibration: mean lat.: 26.259ms, rate sampling interval: 271ms
  Thread calibration: mean lat.: 26.200ms, rate sampling interval: 264ms
  Thread calibration: mean lat.: 26.637ms, rate sampling interval: 321ms
  Thread calibration: mean lat.: 26.131ms, rate sampling interval: 272ms
  Thread calibration: mean lat.: 27.583ms, rate sampling interval: 306ms
  Thread calibration: mean lat.: 24.501ms, rate sampling interval: 229ms
  Thread calibration: mean lat.: 26.692ms, rate sampling interval: 319ms
  Thread calibration: mean lat.: 25.957ms, rate sampling interval: 286ms
  Thread calibration: mean lat.: 27.710ms, rate sampling interval: 349ms
  Thread calibration: mean lat.: 26.261ms, rate sampling interval: 284ms
  Thread calibration: mean lat.: 27.152ms, rate sampling interval: 287ms
  Thread calibration: mean lat.: 25.275ms, rate sampling interval: 274ms
  Thread calibration: mean lat.: 23.630ms, rate sampling interval: 243ms
  Thread calibration: mean lat.: 26.917ms, rate sampling interval: 293ms
  Thread calibration: mean lat.: 28.432ms, rate sampling interval: 302ms
  Thread calibration: mean lat.: 26.581ms, rate sampling interval: 280ms
  Thread calibration: mean lat.: 26.783ms, rate sampling interval: 320ms
  Thread calibration: mean lat.: 27.274ms, rate sampling interval: 297ms
  Thread calibration: mean lat.: 26.332ms, rate sampling interval: 283ms
  Thread calibration: mean lat.: 26.220ms, rate sampling interval: 248ms
  Thread calibration: mean lat.: 28.054ms, rate sampling interval: 310ms
  Thread calibration: mean lat.: 25.386ms, rate sampling interval: 250ms
  Thread calibration: mean lat.: 29.999ms, rate sampling interval: 323ms
  Thread calibration: mean lat.: 27.613ms, rate sampling interval: 315ms
  Thread calibration: mean lat.: 26.368ms, rate sampling interval: 275ms
  Thread calibration: mean lat.: 26.324ms, rate sampling interval: 297ms
  Thread calibration: mean lat.: 23.839ms, rate sampling interval: 247ms
  Thread calibration: mean lat.: 29.134ms, rate sampling interval: 321ms
  Thread calibration: mean lat.: 26.010ms, rate sampling interval: 269ms
  Thread calibration: mean lat.: 25.863ms, rate sampling interval: 263ms
  Thread calibration: mean lat.: 28.751ms, rate sampling interval: 311ms
  Thread calibration: mean lat.: 24.748ms, rate sampling interval: 236ms
  Thread calibration: mean lat.: 29.013ms, rate sampling interval: 311ms
  Thread calibration: mean lat.: 28.740ms, rate sampling interval: 307ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.92ms  445.73us  15.91ms   82.37%
    Req/Sec   187.37      1.59   194.00     88.01%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.90ms
 75.000%    1.15ms
 90.000%    1.30ms
 99.000%    2.39ms
 99.900%    5.14ms
 99.990%    9.25ms
 99.999%   12.96ms
100.000%   15.92ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.233     0.000000            1         1.00
       0.448     0.100000        60056         1.11
       0.564     0.200000       120359         1.25
       0.680     0.300000       180236         1.43
       0.792     0.400000       240269         1.67
       0.901     0.500000       300402         2.00
       0.953     0.550000       330340         2.22
       1.004     0.600000       360066         2.50
       1.054     0.650000       390506         2.86
       1.102     0.700000       420144         3.33
       1.150     0.750000       450035         4.00
       1.174     0.775000       464979         4.44
       1.199     0.800000       480437         5.00
       1.223     0.825000       495440         5.71
       1.247     0.850000       509996         6.67
       1.272     0.875000       524985         8.00
       1.285     0.887500       532596         8.89
       1.298     0.900000       539940        10.00
       1.313     0.912500       547454        11.43
       1.331     0.925000       555146        13.33
       1.352     0.937500       562571        16.00
       1.365     0.943750       566367        17.78
       1.379     0.950000       569999        20.00
       1.399     0.956250       573757        22.86
       1.431     0.962500       577463        26.67
       [...]

2020-10-25 15:50 UTC, lamtev requested changes
## Реализация

В целом все ОК. Оставил несколько замечаний

## Профилирование

Все супер, красивые графики задержки! Принято. В будущем лучше профилировать без ключика `-t`, чтобы видеть картину в общем, а не по потокам: потоков очень много, и как-то труднее получается анализировать

2020-10-25 15:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/NewService.java
> +        executorService.execute(() -> {
Нужно ловить `RejectedExecutionException` и отвечать 503

2020-10-25 15:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/NewService.java
> +            httpSession.sendResponse(resp(Response.INTERNAL_ERROR));
В этот `catch` можно попасть как при `dao.get` (что ОК), так и при `httpSession.sendResponse` (что уже не ОК, т.к. будет попытка отправить ответ 2-й раз). `IOException` от dao и от httpSession нужно хэндлить по-разному

2020-10-25 15:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/NewService.java
> +        executorService.execute(() -> {
`/status`, как и `handleDefault` нет смысла уводить на `executor`

2020-10-26 16:34 UTC, lamtev approved these changes
Ок. Теперь осталось пофиксить 3 однотипных замечания от code limate

2020-10-26 16:34 UTC, lamtev commented on src/main/java/ru/mail/polis/service/boriskin/NewService.java
> +        logger.error("Ошибка при выполнении операции ", rejectedExecutionException);
Тут больше подошло бы что-то: превышен допустимый размер очереди задач

2020-10-27 08:59 UTC, makaryb commented
> Ок. Теперь осталось пофиксить 3 однотипных замечания от code limate

Да, извините, поправил

2020-10-27 09:53 UTC, lamtev commented
Принято

2020-10-27 09:53 UTC, closed without merging