Stage3
polis-mail-ru/2020-highload-dht pull request #76
Opened 2020-10-13 08:19 UTC by mariarheon

2020-10-16 12:16 UTC, incubos requested changes
Отсутствуют результаты нагрузочного тестирования и профилирования (до deadline), поэтому не больше 5 баллов после исправления замечаний по коду, нагрузочного тестирования, профилирования и анализа результатов.

2020-10-16 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        config.queueTime = 10;
Для чего это?

2020-10-16 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        config.maxWorkers = Runtime.getRuntime().availableProcessors();
Зачем это? Разве вы используете встроенный work pool из `one-nio`?

2020-10-16 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +        service.execute(() -> {
Может кинуть `RejectedExecutionException`.

2020-10-16 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +        service.execute(() -> {
Может кинуть `RejectedExecutionException`.

2020-10-16 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +        service.execute(() -> {
Может кинуть `RejectedExecutionException`.

2020-10-16 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                } catch (NoSuchElementException ex) {
Тут что-то не так с выравниваем строк.

2020-10-16 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                } catch (NoSuchElementException ex) {
Разве такая ошибка может быть?

2020-10-16 12:16 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                session.sendResponse(new ZeroResponse(Response.OK));
Есть ли смысл выносить такой легковесный метод на `executor`?

2020-10-18 14:49 UTC, incubos requested changes
Осталась пара небольших замечаний и появилось несколько вопросов.

2020-10-18 14:49 UTC, incubos commented on highload-analysis.md
> +./profiler.sh -e cpu -d 15 -t -f cpu-put.svg 240038
Давайте в следующих этапах профилировать без опции `-t` (без разбивки по потокам)? Мы уже убедились, что запросы обрабатываются в отдельном пуле потоков, поэтому не будем усложнять анализ результатов кучей столбиков.

2020-10-18 14:49 UTC, incubos commented on highload-analysis.md
> +wrk2 -t4 -c64 -d3m -R10000 -s wrk/put.lua --latency http://127.0.0.1:8080
А выше написано "15000 запросов в секунду".

2020-10-18 14:49 UTC, incubos commented on highload-analysis.md
> +
Почему ваш отчёт так похож на [отчёт соратника](https://github.com/MrSandman5/2020-highload-dht/blob/297a5c5df32ee46b6726c2774ec6a68c67bb6784/highload-analysis.md)?

2020-10-18 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/dao/mariarheon/ByteBufferUtils.java
> +            res[i] ^= Byte.MIN_VALUE;
Почему решили переделать так? Как к этому пришли?

2020-10-18 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +            logger.error("Error in ServiceImpl.get() method; internal error: ", ex);
Логгирование -- это хорошо, но нужно также отправить HTTP ошибку клиенту, иначе он так и будет ждать ответа, в то время как его запрос никто обрабатывать не будет.

2020-10-18 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +            logger.error("Error in ServiceImpl.put() method; internal error: ", ex);
Логгирование -- это хорошо, но нужно также отправить HTTP ошибку клиенту, иначе он так и будет ждать ответа, в то время как его запрос никто обрабатывать не будет.

2020-10-18 14:49 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +            logger.error("Error in ServiceImpl.delete() method; internal error: ", ex);
Логгирование -- это хорошо, но нужно также отправить HTTP ошибку клиенту, иначе он так и будет ждать ответа, в то время как его запрос никто обрабатывать не будет.

2020-10-18 15:12 UTC, mariarheon commented on src/main/java/ru/mail/polis/dao/mariarheon/ByteBufferUtils.java
> +            res[i] ^= Byte.MIN_VALUE;
На втором этапе при проверки посоветовали ксорить, в связи с тем, что это более простой метод по вычислительной сложности. И действительно, упустила это в ходе первой реализации.

2020-10-18 15:14 UTC, mariarheon commented on highload-analysis.md
> +
Вдохновлялась шаблоном, у Семена лаконично представлены результаты. Постараюсь в следующий раз формулировать анализ в другом формате.

2020-10-18 15:15 UTC, mariarheon commented on highload-analysis.md
> +wrk2 -t4 -c64 -d3m -R10000 -s wrk/put.lua --latency http://127.0.0.1:8080
Ошибка копипаста, исправлю.

2020-10-20 09:41 UTC, incubos commented
Принято.

2020-10-20 09:41 UTC, closed without merging