Stage2 + Stage3
polis-mail-ru/2020-highload-dht pull request #77
Opened 2020-10-13 13:32 UTC by gogun

@incubos, удалось избавить от `OutOfMemory`, в отчете написал как.
[отчет по второму этапу](profile_and_loading_stage2/report.md)
[отчет по третьему этапу](profile_and_loading_stage3/report.md)

2020-10-16 01:56 UTC, lamtev commented
> P.S. я не знаю почему он не хочет отображать заголовки в md

нужен пробел между решёткой # и заголовком

2020-10-16 12:14 UTC, gogun commented
кажется это была плохая идея что-то пушить, добавились новые тесты, они не прошли, но пробелы поставил)

2020-10-17 22:40 UTC, lamtev commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                queueSize,
Это так было задумано, что `corePoolSize= numWorkers `, а `maximumPoolSize=queueSize` ?

2020-10-17 23:02 UTC, lamtev requested changes
Профилирование:
1. На первом флейм-графе JIT занимает 13%, что говорит о том, что процесс не был прогрет.
2. Лучше добавлять команду профилировщика - будет сразу по отчету понятно, какие опции, какая длительность

2020-10-18 16:21 UTC, gogun commented
> Профилирование:
> 
>     1. На первом флейм-графе JIT занимает 13%, что говорит о том, что процесс не был прогрет.
> 
>     2. Лучше добавлять команду профилировщика - будет сразу по отчету понятно, какие опции, какая длительность

Поправил замечания, профилирование не переделывал, переделать или в будущем прикреплять в отчет команду профилировщика?

2020-10-18 18:23 UTC, lamtev commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +        executorService = new ThreadPoolExecutor(numWorkers,
Это, оказывается было. Спутал с другим ПР, возможно

2020-10-18 18:50 UTC, lamtev requested changes

2020-10-18 18:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            log.error("Can't understand request {}", request, e);
А точно не можем понять запрос? Вроде бы не можем отправить

2020-10-18 18:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
не исправлено

2020-10-18 18:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            } catch (RejectedExecutionException e) {
Исключение выбрасывается при добавлении в executor задачи. В этом месте оно не случается

2020-10-18 18:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
и нужно логгировать само исключение.` log.error("My clear error description", e)`. прошу посмотреть по всему ПР

2020-10-18 18:52 UTC, lamtev commented
> профилирование не переделывал, переделать или в будущем прикреплять в отчет команду профилировщика?

пускай в будущем)

2020-10-18 19:13 UTC, gogun commented
Теперь точно все исправил

2020-10-18 19:15 UTC, lamtev commented
> Теперь точно все исправил

Но теперь 3 замечания от Code Climate

2020-10-18 19:58 UTC, lamtev approved these changes

2020-10-18 20:47 UTC, lamtev commented
Принято

2020-10-18 20:47 UTC, closed without merging