Stage 3
polis-mail-ru/2020-highload-dht pull request #79
Opened 2020-10-13 16:41 UTC by Basta123

2020-10-15 17:04 UTC, vaddya requested changes
Профилирование еще не смотрел, вернемся к нему после замечаний

2020-10-15 17:04 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/Utils.java
> +        final byte[] bytes = new byte[buffer.limit()];
Здесь нужно использовать `buffer.remaining()`

2020-10-15 17:04 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/Utils.java
> +        httpServerConfig.acceptors = new AcceptorConfig[1];
`= new AcceptorConfig[]{acceptorConfig}`

2020-10-15 17:04 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +        execService = new ThreadPoolExecutor(numWorkers,
Может заиспользуем один из статичечских методов класса `Executors`?

2020-10-15 17:04 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/DAO.java
> +    ByteBuffer get(@NotNull ByteBuffer key) throws IOException, NoSuchElementException;
Давайте не будем менять интерфейсы, которые являются частью задания. Нужно откатить это изменение

2020-10-18 19:07 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +    String cantSendResponse = "can't send response";
вроде все замечания исправил, но здесь не совсем понял, имеется в виду зачем final и static вместе? если да, то я помню, что на одном из стримов нам говорили, что это нужно по какой-то причине( по какой именно - не помню), возможно я путаю. Если речь шла об этом, то могу убрать, но я просмотрел у других ребят, у них вроде также.

2020-10-19 13:46 UTC, vaddya requested changes

2020-10-19 13:46 UTC, vaddya commented on .gitignore
> -
Добавьте сюда папку `.idea`

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/basta123/DAORocksDB.java
> +        if (recordIter != null) {
Зачем?

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/basta123/DAORocksDB.java
> +            rocksDBInstance.closeE();
С прошлого ревью:
Давайте перед этим еще rocksDBInstance.syncWal(); сделаем

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/basta123/MyComparator.java
> +public class MyComparator extends Comparator {
Почему бы не назвать класс `SingedBytesComparator`?

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/basta123/MyRecordIter.java
> +public class MyRecordIter implements Iterator<Record> {
Что означают эти `My` в каждом втором классе? :)
Называйте осмысленно -- `RocksDBIterator`, `RocksRecordsIterator` или что-то в таком духе

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +    String cantSendResponse = "can't send response";
Я предлагаю додавить все три ключевых слова к переменной `cantSendResponse` -- это же строковая константа в чистом виде. И заодно привести ее имя к `UPPER_CASE_CONSTANT_NAME`

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +    public Response statusCheckMethod(final HttpSession httpSession) {
Зачем вам сессия в этом хендлере?

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +                    if (id == null || id.isEmpty()) {
Форматирование поехало

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +        execService.execute(() -> {
Здесь может вылететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа, поэтому надо его отловить и вернуть 500. Это же касается соседних методов

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +                        throw new RuntimeException("Error getting value :", e);
Есть ли смысл прокидывать исключение дальше? Мы уже вернули 500, залогировали, исключение обработано

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +                responseCreated.addHeader(HttpHeaders.CONTENT_TYPE + ": " + "text/plain");
Зачем это?

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +            final byte[] keyBytes = id.getBytes(UTF_8);
Опять нет `return`

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +                } catch (IOException ioException) {
Принято называть просто `e`

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +        session.sendResponse(new Response(Response.BAD_REQUEST, new byte[0]));
`Response.EMPTY`?

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +            e.printStackTrace();
Не надо так делать, когда у вас логгер

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +        responseOk.addHeader(HttpHeaders.CONTENT_TYPE + ": " + "text/plain");
Зачем это?

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +    @Path("/abracadabra")
Надо убрать

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +    public Response putValueByKey(final @Param("id") String id, final Request request) throws IOException {
В хендлере может вылететь куча разных исключений, и ни одно из них не ловится

2020-10-19 13:46 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +        if ("".equals(id)) {
`id` может быть `null`

2020-10-19 13:46 UTC, vaddya commented on src/test/java/ru/mail/polis/service/StartStopTest.java
> +    private static String endpoint;
Зачем это?

2020-10-19 15:08 UTC, Basta123 commented on src/main/java/ru/mail/polis/dao/basta123/DAORocksDB.java
> +    private MyRecordIter recordIter;
да, забыл убрать

2020-10-19 15:11 UTC, Basta123 commented on src/main/java/ru/mail/polis/dao/basta123/MyComparator.java
> +public class MyComparator extends Comparator {
называл SingedBytesComparator, но дальше (я даже не знаю из-за чего) закоммитилась не то, что нужно было, исправлю.

2020-10-19 15:17 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +            e.printStackTrace();
класс MyHttpServerImpl не стоит смотреть, т.к. он уже не используется. В начале я хотел просто модифицировать его и сделать асинхронным, но затем решил его оставить а для асинхронного сервера создал новый (вернее дублировал старый и модифицировал его)

2020-10-19 15:20 UTC, Basta123 commented on src/test/java/ru/mail/polis/service/StartStopTest.java
> +    private static String endpoint;
это из этапа 4, я сделал мердж из мастера в свою ветку, иначе трэвис зависал и не давал ответа, т.к. код в мастере был изменен к четвертому этапу (мне так посоветовали сделать).

2020-10-19 15:21 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +            e.printStackTrace();
Ну удалите его тогда, не знаю

2020-10-19 15:33 UTC, Basta123 commented on src/main/java/ru/mail/polis/dao/basta123/MyRecordIter.java
> +public class MyRecordIter implements Iterator<Record> {
плохая привычка) избавлюсь от неё.

2020-10-19 16:04 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +                    if (id == null || id.isEmpty()) {
извиняюсь за глупый вопрос, но автоформатирование в idea происходит с помощью горячих клавиш ctrl+alt+L ? если да, то я использую их, но в данном участке кода ничего не форматируется.

2020-10-19 16:05 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +                    if (id == null || id.isEmpty()) {
Уменьшайте руками тогда отступы до 4 (сейчас тут отступ 8)

2020-10-19 16:29 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +                responseCreated.addHeader(HttpHeaders.CONTENT_TYPE + ": " + "text/plain");
убирал это) но я даже не помню, что пошло не так и почему это осталось

2020-10-19 16:36 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +            e.printStackTrace();
ок, понял

2020-10-19 17:27 UTC, Basta123 commented on src/main/java/ru/mail/polis/dao/basta123/DAORocksDB.java
> +            rocksDBInstance.closeE();
когда ставлю rocksDBInstance.syncWal перед rocksDBInstance.closeE(), то тесты не проходят, а именно respectFileFolder фейлится. Я смотрел у ребят, которые используют rocksDB, у них вроде как не используется syncWal.

2020-10-19 17:36 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/basta123/DAORocksDB.java
> +            rocksDBInstance.closeE();
Должно работать, но ладно

2020-10-19 17:36 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/MyHttpServerImpl.java
> +    public Response putValueByKey(final @Param("id") String id, final Request request) throws IOException {
ок, этот сервер удалил

2020-10-19 17:37 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/MyAsyncHttpServerImpl.java
> +                responseCreated.addHeader(HttpHeaders.CONTENT_TYPE + ": " + "text/plain");
Осталось или скопировалось? :)

2020-10-19 19:35 UTC, vaddya requested changes
Профилирование ОК, остались небольшие замечания по реализации

2020-10-19 19:35 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +    private static final int QUEUE_SIZE = 1024;
Все статические поля должны быть выше нестатических -- их лучше не смешивать друг с другом

2020-10-19 19:35 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                put(id, request, httpSession);
Нет ощущения, что три метода отличаются только методом, который они здесь вызывают? Такое надо рефакторить, на лайв кодинге показывали неплохой пример -- интерфейс `Action`. В вашем случае `get`, `put` и `delete` как раз будут экшенами, а этот код не будет дублироваться. Пересмотрите этот момент, пожалуйста

2020-10-19 19:35 UTC, vaddya commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +        super.start();
В чем идея такого переопределения метода? Если это просто удалить -- ничего не поменяется

2020-10-19 19:43 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +        super.start();
да, верно, по сути в переопределенном методе просто вызываем метод родителя, но так вроде было на стримах (хотя могу путать), исправлю.

2020-10-19 19:44 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                put(id, request, httpSession);
ок, заменю функциональным интерфейсом

2020-10-19 21:25 UTC, Basta123 commented on src/main/java/ru/mail/polis/service/basta123/AsyncHttpServerImpl.java
> +                put(id, request, httpSession);
использовал метод makeAct как обертку для методы act интерфейса Action, т.к. codeclimate жаловался на вложенные траи и просил их вынести в отдельный метод.

2020-10-19 21:26 UTC, vaddya approved these changes
Принято.

2020-10-19 21:26 UTC, closed without merging