Task 3
polis-mail-ru/2020-highload-dht pull request #80
Opened 2020-10-13 18:48 UTC by nik27090

2020-10-13 20:36 UTC, nik27090 commented
Профилирование в процессе

2020-10-17 23:07 UTC, lamtev commented
Профилирования нет - смотрю реализацию. Можно получить до 5 баллов 😢

2020-10-17 23:32 UTC, lamtev requested changes

2020-10-17 23:32 UTC, lamtev commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new ServiceImpl(port, dao, Runtime.getRuntime().availableProcessors(), 16);
не маленький размер очереди?

2020-10-17 23:32 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +                workers, queueCapacity,
Намеренно было сделано `corePoolSize= workers `, а `maximumPoolSize= queueCapacity ` ?

2020-10-17 23:32 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +        executorService.execute(() -> {
Имеет смысл такой такую простую обработку уводить в executorService?

2020-10-17 23:32 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +                log.error("FATAL ERROR STATUS. Can't send response.");
не залоггировано исключение. прошу посмотреть во всем ПР и залоггировать

2020-10-17 23:32 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +            } catch (IOException e) {
в данный catch попадет как исключение dao, так и исключение session.sendResponse. лучше бы разделить, т.к. можно не делать retry отправки BAD_REQUEST, когда при его первичной отправке выбросилось исключение. В других методах аналогично

2020-10-17 23:32 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +        executorService.execute(() -> {
Ты выбрал `ThreadPoolExecutor.AbortPolicy()` в качестве `RejectedExecutionHandler`, а значит когда очередь будет достигать максимально допустимого размера, будет выбрасываться исключение `RejectedExecutionException`. Здесь и в других методах его необходимо отлавливать и отвечать клиенту Service Unavailable

2020-10-17 23:32 UTC, lamtev commented on src/test/java/ru/mail/polis/dao/ConcurrentTest.java
> -            final AtomicInteger matches = new AtomicInteger();
ненужное изменение

2020-10-18 12:04 UTC, nik27090 commented
> Профилирования нет - смотрю реализацию. Можно получить до 5 баллов

Досадное нововведение, я как раз рассчитывал сделать профилирование после дедлайна

2020-10-18 16:58 UTC, nik27090 commented
@lamtev случайно запушил сюда четвертую таску :( Исправление замечаний можно посмотреть в коммите `fix task_3`

2020-10-18 18:13 UTC, lamtev requested changes
Хоть это и было не очень удобно, посмотрел изменения в отдельном коммите.
Вместе с исправлением замечаний, из этой ветки нужно также удалить лишние коммиты

2020-10-18 18:13 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +                new ThreadPoolExecutor.DiscardOldestPolicy()
Не очень понятно зачем это было сделано

2020-10-18 18:13 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +        } catch (RejectedExecutionException e) {
С учетом того, что была выполнена замена AbortPolicy  на DiscardOldestPolicy, RejectedExecutionException больше никем не выбрасывается и в этот catch мы не попадем. И клиент не получит ответ

2020-10-18 18:13 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +                workers, queueCapacity,
?

2020-10-18 18:15 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +                workers, queueCapacity,
?

2020-10-18 18:17 UTC, nik27090 commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +        } catch (RejectedExecutionException e) {
упс, это я тестировал остальные обработчики и забыл вернуть AbortPolicy. 
catch оставлю, верну  AbortPolicy.

2020-10-19 10:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +                workers, queueCapacity,
вопрос актуален

2020-10-19 10:37 UTC, lamtev requested changes

2020-10-19 10:37 UTC, lamtev commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +                workers, queueCapacity,
> Намеренно было сделано corePoolSize= workers , а maximumPoolSize= queueCapacity ?

Осталось разобраться с этим

2020-10-20 11:19 UTC, nik27090 commented
Да, намеренно, но я с keepAliveTime провалился)
для наших кейсов минуты, наверное, более чем достаточно.

2020-10-20 11:31 UTC, lamtev commented
Принято

2020-10-20 11:31 UTC, closed without merging