Hw 3
polis-mail-ru/2020-highload-dht pull request #81
Opened 2020-10-13 19:20 UTC by kuzo-liza

2020-10-16 13:37 UTC, incubos requested changes
Отсутствуют результаты нагрузочного тестирования и профилирования (до deadline), поэтому не больше 5 баллов после исправления замечаний по коду, нагрузочного тестирования, профилирования и анализа результатов.

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +                session.sendResponse(Response.ok("OK"));
Есть ли смысл выносить этот легковесный метод в `executor`?

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +        executor.execute(() -> {
Может кинуть `RejectedExecutionException`.

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +        executor.execute(() -> {
Может кинуть `RejectedExecutionException`.

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +        executor.execute(() -> {
Может кинуть `RejectedExecutionException`.

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +        executor.execute(() -> {
Может кинуть `RejectedExecutionException`.

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +                session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
Зачем выносить такой простой метод в `executor`?

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +    public synchronized void stop() {
Зачем здесь `synchronized`?

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +        executor.execute(() -> {
Зачем здесь `executor.execute()`? `response()` и так уже работает в контексте одного из потоков `executor`.

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +            log.error("Can't send response", e);
Здесь нужно отправить HTTP ошибку клиенту.

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +            log.error("Can't upsert element", e);
Т.е. в случае ошибки `DAO` мы отправим `Response.CREATED`? Это неправильно.

2020-10-16 13:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +            log.error("Can't remove element", e);
Т.е. в случае ошибки `DAO` мы отправим `Response.ACCEPTED`? Это неправильно.

2020-10-18 14:51 UTC, incubos commented
Ждать исправления замечаний? Deadline для исправления (и нескольких итераций ревью) -- deadline следующего этапа.

2020-10-18 15:10 UTC, kuzo-liza commented
> Ждать исправления замечаний? Deadline для исправления (и нескольких итераций ревью) -- deadline следующего этапа.

Да, уже в процессе

2020-10-18 20:06 UTC, kuzo-liza commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +        executor.execute(() -> {
Действительно излишне, исправила

2020-10-18 20:10 UTC, kuzo-liza commented on src/main/java/ru/mail/polis/service/kuzoliza/MyService.java
> +    public synchronized void stop() {
Мы переопределяем метод сервера, который synchronized

2020-10-20 09:45 UTC, incubos commented
Принято, но за половину баллов.

2020-10-20 09:45 UTC, closed without merging