Feature 3
polis-mail-ru/2020-highload-dht pull request #82
Opened 2020-10-13 19:38 UTC by ViaSacra

Vladislav Ivlev

2020-10-14 11:14 UTC, ViaSacra commented
@vaddya, в чем может быть проблема? CI вчера прошел, сегодня засквешил комиты и падает тест на `emptyKey`, ожидая Bad Request, а получает Not Found, хотя контроллер кидает Bad Request. Локально тест проходит

2020-10-14 11:21 UTC, vaddya commented
> @vaddya, в чем может быть проблема? CI вчера прошел, сегодня засквешил комиты и падает тест на `emptyKey`, ожидая Bad Request, а получает Not Found, хотя контроллер кидает Bad Request. Локально тест проходит

Ищите ошибку в реализации, она есть

2020-10-14 11:24 UTC, ViaSacra commented
![image](https://user-images.githubusercontent.com/37287436/95982563-e77ad680-0e28-11eb-8ef3-5adf20a9e378.png)
Вот скрин вчерашнего пайплайна, который прошел

2020-10-14 11:25 UTC, vaddya commented
> ![image](https://user-images.githubusercontent.com/37287436/95982563-e77ad680-0e28-11eb-8ef3-5adf20a9e378.png)
> Вот скрин вчерашнего пайплайна, который прошел

И это не отменяет того, что в реализации есть проблемы

2020-10-15 17:56 UTC, vaddya requested changes
Не похоже на третий этап, а время второго уже давно прошло

2020-10-15 22:16 UTC, ViaSacra commented
@vaddya, я когда мержил 2-ю таску в 3-ю, мердж почему-то потер реализацию контроллера и сервис. Зеленым пометил коммит с третьей реалзицией, красным мердж, который потер. Сделал черипик, сейчас все должно работать
![image](https://user-images.githubusercontent.com/37287436/96191644-2d30bf80-0f4d-11eb-88df-4b82a1dfbe5c.png)

2020-10-15 22:18 UTC, ViaSacra commented
Там проблема на этапе компиляции с тестом, который не на нашей стороне, а в CI в зашит видимо, из за этого сборка падает, хотя до этого проходило все.
![image](https://user-images.githubusercontent.com/37287436/96191750-679a5c80-0f4d-11eb-8515-05b10154dc73.png)

2020-10-15 22:53 UTC, ViaSacra commented
@vaddya, я долго не понимал, почему пайплайн начал падать, хотя он работал с тем же коммитом пару дней назад) Почему то в CI контейнер попал тест из 4-го задания, и сборка падала. Я там поправил main класс и интерфейс сервиса. Теперь все прошло

2020-10-16 09:55 UTC, vaddya requested changes
Сами флейм графы выглядят хорошо, но:
"Не забудьте нагрузить, отпрофилировать и **проанализировать результаты** профилирования под нагрузкой."

Хотелось бы увидеть хоть какие-то выводы по ним.

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/Time.java
> +public final class Time {
А этот класс гарантирует хоть какое-то thread safety?

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/TableSet.java
> +     * Конструктор TableSet.
Это [конструктор](https://i.redd.it/iuy9fxt300811.png), понятно.

Тут можно ведь пояснить, что один конструктор для DAO, а второй внутренний для перехода между состояними? Второй, кстати, можно сделать приватным

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/TableSet.java
> +     * @param generation - generation
Начали описывать параметры -- описывайте все

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/impl/DAOImpl.java
> +    final NavigableMap<Integer, Table> ssTables = new ConcurrentSkipListMap<>();
`private`?

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/impl/DAOImpl.java
> +        final File[] list = file.listFiles((dir1, name) -> name.endsWith(SUFFIX));
Нам нужна тут `dir`? Может примем только `file` и вызовем `getName()`?

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/impl/DAOImpl.java
> +        lock.writeLock().lock();
Нужен ли здесь райт лок?

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/TableSet.java
> +    public int generation;
Не знаю, публичные нефинальные поля я бы назвал плохой практикой

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/impl/DAOImpl.java
> +                lock.writeLock().lock();
Нам точно нужен райт лок на все время флаша? Не слишком ли это сильное ограничение, учитывая скорость работы диска?

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/impl/DAOImpl.java
> +                Runtime.getRuntime().halt(-1);
Ой, это мы при какой-либо ошибке флаша сразу все потушим? Так точно не стоит делать

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/impl/DAOImpl.java
> +            final Iterator<Cell> merged = Iterators.mergeSorted(iters, Comparator.naturalOrder());
Вообще, под локом можно собрать итераторы и отпустить

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ServiceController.java
> +        if (Objects.isNull(id) || id.isEmpty()) {
Если параметр `required`, то он не будет `null`

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ServiceController.java
> +        } catch (NoSuchElementException | IOException ex) {
`IOException` это точно 404?

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ThreadController.java
> +    private static final Logger logger = LoggerFactory.getLogger(ThreadController.class);
Статические поля должны быть выше пропертей. И в джаве принято называть `log` для краткости.

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ThreadController.java
> +        executor.execute(() -> {
Такие запросы точно надо выносить на экзекьютор? Не быстрее сразу записать ответ в сессию?

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ThreadController.java
> +            } catch (IOException e) {
Надо бы залогировать ошибку, в других методах тоже

2020-10-16 09:55 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ivlev/ThreadController.java
> +        executor.execute(() -> {
Такое тоже не имеет смысла переносить на экзекьютор отправку пустого ответа

2020-10-20 11:45 UTC, ViaSacra commented on src/main/java/ru/mail/polis/service/ivlev/ThreadController.java
> +    private static final Logger logger = LoggerFactory.getLogger(ThreadController.class);
Да, справлю. Но есть Lombok и если сделать delombok, то он там называет нижней пропертей)

2020-10-20 15:01 UTC, vaddya commented
А замечания то не все пофикшены

2020-10-20 21:13 UTC, ViaSacra commented on src/main/java/ru/mail/polis/Time.java
> +public final class Time {
Да, вы правы. Это видимо вообще легаси код из предыдущего семестра. Нигде не используется

2020-10-21 20:37 UTC, vaddya requested changes
Половину замечаний так и прогинорировали. 

Третий этап частично принят.

2020-10-21 20:37 UTC, closed without merging