Stage2 + Stage 3
polis-mail-ru/2020-highload-dht pull request #83
Opened 2020-10-13 20:47 UTC by Valaubr

Результаты профилирования закинул в архив "решение на скорую руку", т.к. не добавлялось через git add *.

2020-10-14 00:35 UTC, Valaubr commented
### **Stage 3 - PUT**
`wrk -t4 -c100 -d10m -R6000 -s wrkAndProfile/scripts/put.lua --latency http://127.0.0.1:8080`

CPU
https://drive.google.com/file/d/13Fgg0H1kJwH_gbDArFGrLcIHxktjpGgx/view?usp=sharing

Селекторы (0 - 4):
3/4 - менее 8%
1/4 - разжирел аж до 13.28%
Ловят Requestы и отдают Responsы, операцию вставки выполняют другие 4 потока
Потоки:
Максимально 11.72%
DAO upsert макисмально занимает 2.03%

Alloc
https://drive.google.com/file/d/1BZEILXOoY5WUXtX38SX73oKzyv4tKo-o/view?usp=sharing

Максимально - селектор 1 занимает 11.24% 
Максимальный объем у пула потоков - p1-t1: 13.08%
Но у остальных потоков < 10%

Lock
https://drive.google.com/file/d/17tE6LsbjbrjaLo4ODkQn5UTKHojJy2pg/view?usp=sharing

Блокировка только вставке, не более 3.82%

Все выше указанные Flame Graph`ы были получены с одного "подхода" на 10 минут, само профилирование проходило по 3 минуты каждое

Running 10m test @ http://127.0.0.1:8080
  4 threads and 100 connections
  Thread calibration: mean lat.: 1.167ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.230ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.300ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.148ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.24ms    2.86ms 102.78ms   95.77%
    Req/Sec   259.39    230.72     3.89k    54.28%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%  797.00us
 75.000%    1.08ms
 90.000%    1.22ms
 99.000%   13.21ms
 99.900%   37.34ms
 99.990%   77.31ms
 99.999%   96.45ms
100.000%  102.85ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.120     0.000000            1         1.00
       0.354     0.100000        57735         1.11
       0.461     0.200000       114882         1.25
       0.547     0.300000       172540         1.43
       0.684     0.400000       229481         1.67
       0.797     0.500000       287029         2.00
       0.837     0.550000       315718         2.22
       0.879     0.600000       344262         2.50
       0.928     0.650000       372751         2.86
       1.009     0.700000       401456         3.33
       1.078     0.750000       430185         4.00
       1.097     0.775000       444802         4.44
       1.121     0.800000       459006         5.00
       1.140     0.825000       473050         5.71
       1.156     0.850000       488039         6.67
       1.178     0.875000       502208         8.00
       1.193     0.887500       509121         8.89
       1.216     0.900000       516173        10.00
       1.253     0.912500       523219        11.43
       1.354     0.925000       530374        13.33
       1.849     0.937500       537543        16.00
       2.381     0.943750       541126        17.78
       3.051     0.950000       544712        20.00
       3.871     0.956250       548300        22.86
       4.955     0.962500       551884        26.67
       6.243     0.968750       555470        32.00
       6.999     0.971875       557253        35.56
       7.855     0.975000       559048        40.00
       8.871     0.978125       560850        45.71
       9.919     0.981250       562639        53.33
      10.975     0.984375       564423        64.00
      11.479     0.985938       565316        71.11
      12.191     0.987500       566216        80.00
      12.775     0.989062       567113        91.43
      13.615     0.990625       568003       106.67
      14.703     0.992188       568902       128.00
      15.471     0.992969       569349       142.22
      16.351     0.993750       569795       160.00
      17.295     0.994531       570248       182.86
      18.351     0.995313       570691       213.33
      19.743     0.996094       571139       256.00
      20.479     0.996484       571363       284.44
      21.567     0.996875       571586       320.00
      23.023     0.997266       571810       365.71
      24.655     0.997656       572034       426.67
      26.895     0.998047       572258       512.00
      28.319     0.998242       572372       568.89
      30.207     0.998437       572482       640.00
      32.079     0.998633       572594       731.43
      35.039     0.998828       572706       853.33
      38.239     0.999023       572818      1024.00
      40.319     0.999121       572875      1137.78
      42.271     0.999219       572930      1280.00
      44.543     0.999316       572986      1462.86
      47.423     0.999414       573042      1706.67
      51.007     0.999512       573098      2048.00
      52.511     0.999561       573126      2275.56
      54.463     0.999609       573154      2560.00
      56.927     0.999658       573182      2925.71
      61.023     0.999707       573210      3413.33
      62.975     0.999756       573238      4096.00
      64.479     0.999780       573252      4551.11
      65.855     0.999805       573266      5120.00
      68.159     0.999829       573280      5851.43
      70.975     0.999854       573294      6826.67
      72.575     0.999878       573308      8192.00
      74.943     0.999890       573315      9102.22
      77.567     0.999902       573322     10240.00
      78.271     0.999915       573330     11702.86
      79.743     0.999927       573336     13653.33
      82.687     0.999939       573343     16384.00
      84.095     0.999945       573346     18204.44
      85.951     0.999951       573350     20480.00
      87.423     0.999957       573353     23405.71
      89.151     0.999963       573357     27306.67
      90.751     0.999969       573360     32768.00
      91.775     0.999973       573362     36408.89
      93.119     0.999976       573364     40960.00
      93.567     0.999979       573365     46811.43
      93.759     0.999982       573368     54613.33
      95.295     0.999985       573369     65536.00
      95.679     0.999986       573370     72817.78
      96.447     0.999988       573371     81920.00
      96.447     0.999989       573371     93622.86
      97.663     0.999991       573372    109226.67
      97.855     0.999992       573373    131072.00
      99.839     0.999993       573374    145635.56
      99.839     0.999994       573374    163840.00
      99.839     0.999995       573374    187245.71
     100.415     0.999995       573375    218453.33
     100.415     0.999996       573375    262144.00
     100.479     0.999997       573376    291271.11
     100.479     0.999997       573376    327680.00
     100.479     0.999997       573376    374491.43
     100.479     0.999998       573376    436906.67
     100.479     0.999998       573376    524288.00
     102.847     0.999998       573377    582542.22
     102.847     1.000000       573377          inf
[Mean    =        1.244, StdDeviation   =        2.859]
[Max     =      102.784, Total count    =       573377]
[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  590169 requests in 10.00m, 37.71MB read
  Socket errors: connect 0, read 0, write 0, timeout 24942
Requests/sec:    983.59
Transfer/sec:     64.36KB

### **Stage 3 - GET**
`wrk -t4 -c100 -d10m -R6000 -s wrkAndProfile/scripts/get.lua --latency http://127.0.0.1:8080`

CPU
https://drive.google.com/file/d/10O0orfOPG6zszVtsmzlNFgcj0d_k7Kxu/view?usp=sharing
Как видно, селекторы почти не трудятся, за то в поте лица работают другие потоки.
Alloc
https://drive.google.com/file/d/1lYIcywQypo1mu50Dz-paa3enDqLfQFQi/view?usp=sharing

Lock
https://drive.google.com/file/d/1E_1alLOfyG6_hkZAZxbrjYk4xknuLfEM/view?usp=sharing

wrk -t16 -c100 -d10m -R4000 -s /home/valaubr/GitDirs/2020-highload-dht/src/test/wrkAndProfile/scripts/get.lua --latency http://127.0.0.1:8080
Running 10m test @ http://127.0.0.1:8080
  16 threads and 100 connections
  Thread calibration: mean lat.: 3124.694ms, rate sampling interval: 9625ms
  Thread calibration: mean lat.: 3118.685ms, rate sampling interval: 9609ms [...]

2020-10-21 12:16 UTC, incubos commented
> Результаты профилирования закинул в архив "решение на скорую руку", т.к. не добавлялось через git add *.

Нужно поправить `.gitignore` и закоммитить все артефакты по-нормальному.

2020-10-21 12:37 UTC, incubos requested changes
- На стрельбах stage3 сервис **перегружен** (не выдерживает `-R` и сыплет таймаутами) -- учтите в следующем этапе
- CPU профилирование начинается слишком рано -- на FlameGraph отсвечивает JIT компилятор -- также учтите в следующем этапе
- Есть замечания по коду -- их нужно исправить в следующем этапе
- Артефакты в будущем нужно всё-таки коммитить в репозиторий, ссылок на внешние сервисы быть не должно (см. `.gitignore`)
- Наконец, необходимо прояснить вопрос с потенциальным заимствованием из прошлого года

2020-10-21 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> +            throw new IllegalStateException("--Xmx overhead value.");
Зачем это изменение?

2020-10-21 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> +            throw new IllegalArgumentException("Path not exist: " + data);
А это?

2020-10-21 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/dao/valaubr/TablesPool.java
> +public class TablesPool implements Table {
Объясните, пожалуйста, почему это так сильно похоже на решения прошлого года с точностью до названий классов и полей.

2020-10-21 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/valaubr/HttpService.java
> +        executor.execute(() -> {
Может кинуть `RejectedExecutionException` из-за ограниченной очереди -- надо бы отловить и вернуть клиенту вразумительную HTTP ошибку (здесь и в других методах ниже).

2020-10-21 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/valaubr/HttpService.java
> +                    session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Ошибка может прилететь из вызова `sendResponse()` выше и мы попытаемся отправить второй ответ.

2020-10-21 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/valaubr/HttpService.java
> +                    session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Аналогично в методах ниже.

2020-10-21 12:37 UTC, incubos commented on src/main/java/ru/mail/polis/service/valaubr/HttpService.java
> +        executor.execute(() -> {
Метод простой -- нет смысла запускать обработку на `executor`.

2020-10-21 12:37 UTC, incubos commented on src/test/java/ru/mail/polis/dao/ConcurrentTest.java
> -        concurrentReadWrite(1, 1_000,  data);
Зачем изменения в этом файле?

2020-10-21 12:37 UTC, incubos commented on wrkAndProfile/scripts/delete.lua
> +    wrk.method = "DELETE"
Разве есть нагрузочное тестирование `DELETE`-запросами? Тогда зачем и откуда это здесь?

2020-10-21 12:37 UTC, incubos commented on wrkAndProfile/stage3/wrk_get_results
> +Requests/sec:    805.77
Заданная нагрузка в 5К rps не обеспечивается.

2020-10-21 12:37 UTC, incubos commented on wrkAndProfile/stage3/wrk_put_results
> +Requests/sec:    805.73
Заданная нагрузка в 5K rps не обеспечивается.

2020-10-22 20:39 UTC, Valaubr commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> +            throw new IllegalStateException("--Xmx overhead value.");
По срокам не успевал и нервничал, обычно когда я нервничаю для того что бы успокоиться я пару минут выделяю на бессмысленные действия, так получилось, извините :(

2020-10-22 20:39 UTC, Valaubr commented on src/main/java/ru/mail/polis/dao/valaubr/TablesPool.java
> +public class TablesPool implements Table {
Понятия не имею, не стану отрицать что подсматривал как решали другие, но т.к. я делал уже после того как все сдали, прошлогодние решения не смотрел :) Понимаю что это вообще то очень не красиво, но я все же старался писать сам.

2020-10-22 20:39 UTC, Valaubr commented on src/test/java/ru/mail/polis/dao/ConcurrentTest.java
> -        concurrentReadWrite(1, 1_000,  data);
Помните я писал что по более 5 минут тесты проходят (но проходят), пока вы мне не посоветовали проверить на других машинах я в тестах копался пытаясь понять что не так.

2020-10-22 20:39 UTC, Valaubr commented on wrkAndProfile/scripts/delete.lua
> +    wrk.method = "DELETE"
Вообще я это написал потому что думал что будут встречаться задачи где должны быть мёртвые данные.

2020-10-25 11:28 UTC, incubos commented on src/test/java/ru/mail/polis/dao/ConcurrentTest.java
> -        concurrentReadWrite(1, 1_000,  data);
Откатите?

2020-10-25 11:28 UTC, incubos commented on wrkAndProfile/stage3/wrk_get_results
> +Requests/sec:    805.77
Т.е. нужно стрелять на меньшей нагрузке.

2020-10-25 11:29 UTC, incubos commented on wrkAndProfile/stage3/wrk_put_results
> +Requests/sec:    805.73
Нужно стрелять на меньшей нагрузке.

2020-10-25 11:33 UTC, incubos commented
Принято с замечаниями.

2020-10-25 11:33 UTC, closed without merging