stage 4
polis-mail-ru/2020-highload-dht pull request #85
Opened 2020-10-14 16:53 UTC by stakenschneider

2020-10-22 17:52 UTC, vaddya requested changes
Небольшие замечания по реализации.

По профилированию:
- Давайте дальше профилировать без разделения на потоки (`-t`) в `async-profiler`, а то сложно анализировать суммарный вклад разных участков кода.
- Можете сравнить результаты профлирования с прошлым этапом? Стало ли быстрее/медленнее? Выросло/упало число запросов, с которым справляется сервер?

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +        this.executor = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors(),
Мое упущение с прошлого этапа. Давайте здесь заменим на `ThreadPoolExecutor` по причинам, которые были озвучены в лекциях. Такой экзекьютор, как сейчас, не имеет ограничение на очередь, и, рано или поздно, упадает с OOM при большой нагрузке. В конструктор `ThreadPoolExecutor` же мы можем явно передать размер очереди. Нужно только не забыть, что такой экзекьютор уже может бросить `RejectedExecutionException` и такое исключение надо отлавливать при вызове `execute`.

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +        config.maxWorkers = Runtime.getRuntime().availableProcessors();
Если мы используем свой экзектютор, воркеры на стороне `one-nio` нам не нужны, в конфиге нужно только задать число селекторов

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +        config.queueTime = 10;
Этот параметр как-то подбирался?

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +                clusterClients.put(it, new HttpClient(new ConnectionString(it + "?timeout=100")));
Лучше избегать литералов в коде, давайте вынесем значение таймаута в константу?

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +                session.sendResponse(action.act());
```java
Response response = action.act();
session.sendResponse(response);
```
И первая, и вторая строка может бросить `IOException`. Но исключение из первой строки мы хотим поймать и вернуть клиенту 500, это явно ошибка на стороне DAO. Но исключение из второй строчки скорее нужно только залогировать, потому что нам явно не удается отправить ответ (сокет закрыт?) и нет смысла отправлять ещё один. Предлагаю разделить эти два сценария обоработки ошибок.

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +            throw new IOException("fail", e);
`"Failed to forward request to "  + node`

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +    private Response forwardRequestTo(@NotNull final String cluster,
Сюда передается не кластер, а адрес одной ноды, имя `node` больше подойдет

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +                throw new UncheckedIOException(e);
Почему `UncheckedIOException`? Предлагаю не бросать ничего, ведь исключение тут может означать только то, что мы не смогли запихнуть ответ в сокет. Главное залоггировали

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +            session.sendError(Response.INTERNAL_ERROR, e.getMessage());
В эту ветку, получается, тоже попадаем только если не можем запихнуть ответ в сокет, давайте ограничимся логгированием

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +                       final HttpSession session) throws IOException {
Пусть везде тогда будет `@NotNull`

2020-10-22 17:52 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +            return new Response(Response.NOT_FOUND, Response.EMPTY);
Точно ли при `IOException` мы должны возвращать 404? Больше на 500 похоже

2020-10-22 21:22 UTC, stakenschneider commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +        this.executor = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors(),
> * Давайте дальше профилировать без разделения на потоки (`-t`) в `async-profiler`, а то сложно анализировать суммарный вклад разных участков кода.

Я без разделения на потоки профилировала 👀

2020-10-22 21:26 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +        this.executor = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors(),
> Я без разделения на потоки профилировала 👀

Если на те флейм графы смотрю (в папке stage_4), то с разделением. Вот [пример](https://raw.githubusercontent.com/ScriptoMax/2020-highload-dht/347683050e0043bd045ebc59a9ee2cfe00a46414/resources/flamegraphs/put_alloc_multi.svg), как выглядит без разделения.

2020-10-27 15:17 UTC, vaddya approved these changes
Профилирование ОК. Минорные замечания, поправьте к пятому этапу, пожалуйста.

Принято.

2020-10-27 15:17 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +                                      final Request request) {
`@NotNull`?

2020-10-27 15:17 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +        return null;
Такая реализация приведет к `session.sendReponse(null)`, а это прямой путь к NPE. Кажется хорошей идеей в случае ошибки при форварде возвращать `Reponse` с 500 ошбикой, а не `null`.

2020-10-27 15:17 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +                final String timeout = "?timeout=100";
Такое нужно выносить в коснтанты -- в Java это `private static final String TIMEOUT = "?timeout=100"`. А еще лучше константой сделать числовое значение и в `ConnectionString` передавать `it + "?timeout=" + TIMEOUT`.

2020-10-27 15:17 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +                new ArrayBlockingQueue<>(1024),
Лучше вынести в коснтанты с понятным именем `QUEUE_SIZE`.

2020-10-27 15:17 UTC, vaddya commented on src/main/java/ru/mail/polis/service/stakenschneider/AsyncServiceImpl.java
> +            log.error("task cannot be accepted for execution", e);
А клиенту ничего не сказали, нужно ему вернуть ответ.

2020-10-27 15:18 UTC, closed without merging