Hw4
polis-mail-ru/2020-highload-dht pull request #87
Opened 2020-10-18 12:03 UTC by re1nex

открыл пока, чтобы проверить тесты и поправить замечания codeclimate , профилирование в процессе

2020-10-20 11:52 UTC, incubos requested changes
- Не исправлены замечания от CodeClimate
- Есть замечания по коду
- Пока отсутствуют результаты нагрузочного тестирования, профилирования и их анализ
- Пересоздайте, пожалуйста, pull request без лишних изменений в тестах и утилитных классах, которые вы на самом деле не трогали

2020-10-20 11:52 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAO.java
> -/*
Откуда множество таких изменений, которые не меняют файлы (здесь и в других файлах)?

2020-10-20 11:52 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +        executeTask(() -> {
Такой легковесный метод нет смысла запускать в отдельном потоке.

2020-10-20 11:52 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +        executeTask(() -> {
Зачем это запускать в отдельном потоке? Проще сразу вернуть `BAD_REQUEST`.

2020-10-20 11:52 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +    private ByteBuffer getByteBufferKey(@Param(value = "id", required = true) String id) {
Зачем здесь аннотация `@Param`?

2020-10-20 17:39 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +    private ByteBuffer getByteBufferKey(@Param(value = "id", required = true) String id) {
сгенерил так , убрал

2020-10-20 19:53 UTC, re1nex commented
# PUT
## wrk

Реализация без шардирования 

./wrk  -c64 -d3m -R2000 -s put.lua --latency http://127.0.0.1:8080
Running 3m test @ http://127.0.0.1:8080
  2 threads and 64 connections
  Thread calibration: mean lat.: 1.123ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.130ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.15ms  612.25us  81.86ms   79.01%
    Req/Sec     1.05k    89.73     3.80k    82.72%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.13ms
 75.000%    1.48ms
 90.000%    1.79ms
 99.000%    2.20ms
 99.900%    2.47ms
 99.990%   22.16ms
 99.999%   55.65ms
100.000%   81.92ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.104     0.000000            1         1.00
       0.542     0.100000        34100         1.11
       0.683     0.200000        68068         1.25
       0.850     0.300000       101976         1.43
       0.997     0.400000       135894         1.67
       1.126     0.500000       169953         2.00
       1.188     0.550000       187041         2.22
       1.251     0.600000       203895         2.50
       1.321     0.650000       220991         2.86
       1.399     0.700000       237931         3.33
       1.477     0.750000       254818         4.00
       1.519     0.775000       263369         4.44
       1.563     0.800000       271890         5.00
       1.613     0.825000       280393         5.71
       1.670     0.850000       288832         6.67
       1.733     0.875000       297297         8.00
       1.764     0.887500       301521         8.89
       1.795     0.900000       305718        10.00
       1.828     0.912500       310052        11.43
       1.859     0.925000       314267        13.33
       1.891     0.937500       318464        16.00
       1.908     0.943750       320601        17.78
       1.925     0.950000       322702        20.00
       1.944     0.956250       324850        22.86
       1.966     0.962500       327017        26.67
       1.991     0.968750       329064        32.00
       2.007     0.971875       330132        35.56
       2.026     0.975000       331207        40.00
       2.049     0.978125       332269        45.71
       2.081     0.981250       333323        53.33
       2.119     0.984375       334372        64.00
       2.143     0.985938       334909        71.11
       2.167     0.987500       335440        80.00
       2.189     0.989062       335985        91.43
       2.215     0.990625       336529       106.67
       2.239     0.992188       337029       128.00
       2.255     0.992969       337308       142.22
       2.273     0.993750       337582       160.00
       2.293     0.994531       337858       182.86
       2.313     0.995313       338092       213.33
       2.339     0.996094       338381       256.00
       2.351     0.996484       338506       284.44
       2.363     0.996875       338619       320.00
       2.381     0.997266       338753       365.71
       2.399     0.997656       338896       426.67
       2.415     0.998047       339019       512.00
       2.425     0.998242       339090       568.89
       2.437     0.998437       339161       640.00
       2.447     0.998633       339226       731.43
       2.457     0.998828       339287       853.33
       2.471     0.999023       339359      1024.00
       2.477     0.999121       339387      1137.78
       2.485     0.999219       339414      1280.00
       2.501     0.999316       339452      1462.86
       2.515     0.999414       339483      1706.67
       2.543     0.999512       339513      2048.00
       2.701     0.999561       339529      2275.56
       3.569     0.999609       339546      2560.00
       4.703     0.999658       339562      2925.71
       7.855     0.999707       339579      3413.33
      10.759     0.999756       339596      4096.00
      12.471     0.999780       339604      4551.11
      14.503     0.999805       339612      5120.00
      16.495     0.999829       339620      5851.43
      18.527     0.999854       339629      6826.67
      20.063     0.999878       339637      8192.00
      21.807     0.999890       339641      9102.22
      22.191     0.999902       339645     10240.00
      23.503     0.999915       339649     11702.86
      25.839     0.999927       339654     13653.33
      27.039     0.999939       339658     16384.00
      28.431     0.999945       339660     18204.44
      29.167     0.999951       339662     20480.00
      29.695     0.999957       339664     23405.71
      30.991     0.999963       339666     27306.67
      31.711     0.999969       339668     32768.00
      32.015     0.999973       339669     36408.89
      32.671     0.999976       339670     40960.00
      33.119     0.999979       339671     46811.43
      33.919     0.999982       339672     54613.33
      50.111     0.999985       339673     65536.00
      55.007     0.999986       339674     72817.78
      55.007     0.999988       339674     81920.00
      55.647     0.999989       339675     93622.86
      55.647     0.999991       339675    109226.67
      61.183     0.999992       339676    131072.00
      61.183     0.999993       339676    145635.56
      61.183     0.999994       339676    163840.00
      65.599     0.999995       339677    187245.71
      65.599     0.999995       339677    218453.33
      65.599     0.999996       339677    262144.00
      65.599     0.999997       339677    291271.11
      65.599     0.999997       339677    327680.00
      81.919     0.999997       339678    374491.43
      81.919     1.000000       339678          inf
[Mean    =        1.151, StdDeviation   =        0.612]
[Max     =       81.856, Total count    =       339678]
[Buckets =           27, SubBuckets     =         2048]
  359874 requests in 3.00m, 22.99MB read
Requests/sec:   1999.30
Transfer/sec:    130.81KB

Реализация c шардированием

./wrk  -c64 -d3m -R2000 -s put.lua --latency http://127.0.0.1:8080
Running 3m test @ http://127.0.0.1:8080
  2 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.64ms  815.03us  43.39ms   67.75%
    Req/Sec     1.06k     1.08k    3.56k    84.58%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.58ms
 75.000%    2.21ms
 90.000%    2.67ms
 99.000%    3.29ms
 99.900%    3.87ms
 99.990%   24.01ms
 99.999%   25.69ms
100.000%   43.42ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.043     0.000000            1         1.00
       0.643     0.100000        34035         1.11
       0.939     0.200000        67980         1.25
       1.143     0.300000       101949         1.43
       1.346     0.400000       135871         1.67
       1.577     0.500000       169862         2.00
       1.705     0.550000       186826         2.22
       1.827     0.600000       203806         2.50
       1.939     0.650000       220798         2.86
       2.065     0.700000       237860         3.33
       2.211     0.750000       254919         4.00
       2.285     0.775000       263395         4.44
       2.357     0.800000       271904         5.00
       2.427     0.825000       280289         5.71
       2.501     0.850000       288723         6.67
       2.583     0.875000       297319         8.00
       2.625     0.887500       301460         8.89
       2.673     0.900000       305817        10.00
       2.723     0.912500       309990        11.43
       2.779     0.925000       314303        13.33
       2.839     0.937500       318516        16.00
       2.873     0.943750       320625        17.78
       2.909     0.950000       322740        20.00
       2.947     0.956250       324876        22.86
       2.989     0.962500       327010        26.67
       3.035     0.968750       329081        32.00
       3.061     0.971875       330140        35.56
 [...]

2020-10-21 12:39 UTC, incubos commented
> # PUT
> ... 
> Почти тоже самое , что и с put

Отчёт следует вкоммитить отдельный файлом `report.md` для возможности точечного комментирования.

2020-10-21 12:55 UTC, incubos requested changes
- Есть ряд замечаний по коду
- Отчёт должен быть в отдельном `.md`-файле
- В PR не должно быть изменений оригинальных классов и **особенно тестов** -- подмёрджите `master`, чтобы очистить diff от них

2020-10-21 12:55 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        final int numOfNodes = nodes.size();
Почему так?

2020-10-21 12:55 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        if (!map.containsKey(hash)) {
Зачем этот `if`? Почему бы просто не выполнять его тело?

2020-10-21 12:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +                            sendErrorResponse(session, Response.INTERNAL_ERROR);
Если ошибка прилетела из `sendResponse()` выше, мы отправим второй ответ?

2020-10-21 12:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +            return new byte[0];
Можно вынести в константу. Зачем нам лишние аллокации?

2020-10-21 12:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +            sendErrorResponse(session, Response.INTERNAL_ERROR);
Если ошибка прилетела из `sendResponse()` выше, то попытаемся отправить второй ответ -- это неправильно.

2020-10-21 12:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +                            sendErrorResponse(session, Response.INTERNAL_ERROR);
Возможна отправка второго ответа в случае ошибки.

2020-10-21 12:55 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +                            sendErrorResponse(session, Response.INTERNAL_ERROR);
Возможна отправка второго ответа в случае ошибки.

2020-10-21 13:01 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +                            sendErrorResponse(session, Response.INTERNAL_ERROR);
sendResponse() не бросает исключение ведь , он его сам обработает или о какой ошибке речь ?

2020-10-21 13:04 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +            return new byte[0];
вынесу

2020-10-21 13:14 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        final int numOfNodes = nodes.size();
показалось неплохой идеей , но наверное лучше заменю на определенную константу

2020-10-21 13:23 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        if (!map.containsKey(hash)) {
чуть меньше операций выходит , но наверное смысла в такой оптимизации немного

2020-10-22 09:42 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        final int numOfNodes = nodes.size();
Да, лучше зафиксировать количество токенов на ноду. Квадратичный размер кольца от количества узлов в кластере это не очень масштабируемо.

2020-10-22 09:44 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +                            sendErrorResponse(session, Response.INTERNAL_ERROR);
Прошу прощения, проглядел, что это не `session.sendResponse()`.

2020-10-22 10:29 UTC, incubos requested changes
- Есть замечания по анализу результатов
- В SVG файлах с результатам профилирования я не нашёл `HttpClient` -- видимо, вы стреляли по `Server`, а не по многонодовому `Cluster`, поэтому новый код (кроме топологии) не был задействован. Нужно разбираться и перестреливать.

2020-10-22 10:29 UTC, incubos commented on profile_info/report.md
> +Сильных различий не увидел
Опять же они есть -- см. например, 50% и 90% процентиль.

2020-10-22 10:29 UTC, incubos commented on profile_info/report.md
> +Здесь получилась ситуация немного обратная , на асинхронные запросы в старой версии уходит на 4 % больше , но это скорее всего из-за того, что данные все на одной ноде , и  их искать там дольше . В о
Возможно, вы не совсем верно понимаете, что изображено на FlameGraph: "искать там дольше" (или я вас неправильно понимаю). Здесь сагрегированы сэмплы потоков на CPU, а не абсолютное процессорное время. Т.е. происходит перераспределение потребления CPU между разными участками кода.

2020-10-22 13:20 UTC, re1nex commented
> - В SVG файлах с результатам профилирования я не нашёл `HttpClient` -- видимо, вы стреляли по `Server`, а не по многонодовому `Cluster`, поэтому новый код (кроме топологии) не был задействован. Нужно разбираться и перестреливать.

Ой, извините , для сравнения вначале тестировал предыдущий этап , service переключил , а это забыл , хорошо перестреляю и поправлю отчёт

2020-10-22 20:19 UTC, re1nex commented on profile_info/report.md
> +Здесь получилась ситуация немного обратная , на асинхронные запросы в старой версии уходит на 4 % больше , но это скорее всего из-за того, что данные все на одной ноде , и  их искать там дольше . В о
я просто подумал раз количество сэмплов в которых фигурировал этот вызов выше , то значит и выполнялись некоторые вызовы дольше,

2020-10-22 20:19 UTC, re1nex commented on profile_info/report.md
> +Сильных различий не увидел
хорошо , более тщательно изучу , спасибо

2020-10-22 20:20 UTC, re1nex commented on profile_info/report.md
> +![image](https://user-images.githubusercontent.com/48808317/96634315-fed32b80-1322-11eb-8a5a-37fd7c2f597f.png)
поправлю

2020-10-24 19:28 UTC, re1nex commented
Послушал совет Влада и перепроверил хеш , действительно записи шли подряд , наверное в следующем этапе поменяю стандартный хеш на что-то более рандомное , сейчас перестреляю и поправлю отчёт

2020-10-25 12:09 UTC, incubos requested changes
Нужны пояснения к алгоритму выбора реплик `ConsistentHashingTopology`.

2020-10-25 12:09 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                for (int j = 0; j < i; j++) {
Честно говоря, я не понял, что здесь происходит. Например, почему здесь **три** вложенных цикла?

2020-10-25 12:09 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                    newHash += node.hashCode();
А если `node.hashCode() == 0`?

2020-10-25 12:09 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                    newHash += node.hashCode();
Зачем мы всё время это вычисляем, если результат не меняется?

2020-10-25 12:09 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                map.put(newHash, node);
А если коллизия?

2020-10-25 12:53 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                for (int j = 0; j < i; j++) {
до этого проблема была, что реплики шли подряд друг за другом (т.к. node+i не сильно менял хешкод) из-за этого пользы от них никакой не было ,попытался добавить таким способо некоторый рандом

2020-10-25 12:54 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                    newHash += node.hashCode();
да,  про переполнение я забыл

2020-10-25 12:55 UTC, re1nex commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                map.put(newHash, node);
Да , наверное с переполнением возможен , хорошо, поменяю тогда лучше сразу на нормальную хеш функцию

2020-10-26 14:13 UTC, incubos commented
> Послушал совет Влада и перепроверил хеш , действительно записи шли подряд , наверное в следующем этапе поменяю стандартный хеш на что-то более рандомное , сейчас перестреляю и поправлю отчёт

Текущий этап с такой реализацией распределения данных по нодам принять нельзя (и отложить доделки на потом). Дальше мы его будем развивать.

2020-10-26 14:15 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                for (int j = 0; j < i; j++) {
Если уж вы решили реализовывать consistent hashing, давайте делать всё корректно без подхаков? ;)

2020-10-26 14:19 UTC, incubos requested changes
Нужно сделать потоко-безопасно.

2020-10-26 14:19 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        MessageDigest instance;
Этот объект не является потокобезопасным, а мы дёргаем методы `ConsistentHashingTopology` из разных потоков.

2020-10-26 14:19 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        MessageDigest instance;
Нужно поправить (например, создавать `MessageDigest` каждый раз новый), а в остальном выглядит годно.

2020-10-27 09:31 UTC, incubos requested changes
Есть ряд критичных замечаний по коду и отчёту.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
>              instance.reset();
Можно не вызывать `reset()` -- мы ведь каждый раз получаем новый экземпляр `MessageDigest`.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/ByteBufferUtils.java
> +public class ByteBufferUtils {
Здесь все методы должны быть `static`.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/ApiUtils.java
> +public class ApiUtils {
Здесь все методы должны быть `static`.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +        this.apiUtils = new ApiUtils();
Эти два класса выше содержат только `static` методы -- нет смысла создавать экземпляры классов.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +            apiUtils.sendErrorResponse(session, Response.INTERNAL_ERROR, logger);
Мы можем сюда попасть из-за `IOException` в `apiUtils.sendResponse()` выше и попытаемся отправить второй HTTP ответ -- это некорректно.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +                            apiUtils.sendErrorResponse(session, Response.INTERNAL_ERROR, logger);
Мы можем сюда попасть из-за `IOException` в `apiUtils.sendResponse()` выше и попытаемся отправить второй HTTP ответ -- это некорректно.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +                            apiUtils.sendErrorResponse(session, Response.INTERNAL_ERROR, logger);
Мы можем сюда попасть из-за `IOException` в `apiUtils.sendResponse()` выше и попытаемся отправить второй HTTP ответ -- это некорректно.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/re1nex/ApiUtils.java
> +            sendErrorResponse(session, Response.INTERNAL_ERROR, logger);
Мы можем сюда попасть из-за `IOException` в `session.sendResponse()` выше и попытаемся отправить второй HTTP ответ -- это некорректно.

2020-10-27 09:31 UTC, incubos commented on profile_info/report.md
> + 99.900%    1.14s
Выглядит совсем тревожно.

2020-10-27 09:31 UTC, incubos commented on profile_info/report.md
> +Меньше запросов в секунду обработала реализация с шардированием ,  50 % запросов обработано в 1,5 раза медленнее , около 0,1 % запросов на порядок медленнее, заняло уже секунды, что было ожидаемо, т.
Вы же сами задаёте rate запросов через `-R`. `wrk2` пытается его обеспечить. Если более-менее обеспечивает, то смотрим и анализируем распределение latency.

2020-10-27 09:31 UTC, incubos commented on profile_info/report.md
> +Воркеры из ArrayBlockingQueue работают под локами , селекторы занимаются своей работой. В реализации с шардированием добавились новые локи , относящиеяся к проксированию.
Это выглядит как copy-paste из отчёта товарища. Воркеры не "работаю под локами" -- они берут задачи из очереди под локом. Какой "своей работой" занимаются селекторы? Здесь они кладут в очередь задачи на обработку запросов через `executeTask()`.
"В реализации с шардированием добавились новые локи , относящиеяся к проксированию." -- что за локи добавились?
Давайте впредь использовать чёткие и технические формулировки?

2020-10-27 09:31 UTC, incubos commented on profile_info/report.md
> +50 % в 1,5 раза медленнее , среднее в 2 раза хуже.
Среднее на практике мало используют, потому что это "среднее по больнице". Давайте обратим взор на перцентили? 99%, 99.9%.

2020-10-27 09:31 UTC, incubos commented on profile_info/report.md
> +![image](https://github.com/re1nex/2020-highload-dht/blob/hw4/profile_info/with%20sharding/get/cpu.svg)
Профиль похож на `alloc`, а не на `cpu`, потому что всё заканчивается (полки сверху) аллокациями массивов. Перепроверьте, пожалуйста.

2020-10-27 09:31 UTC, incubos commented on profile_info/report.md
> +![image](https://github.com/re1nex/2020-highload-dht/blob/hw4/profile_info/with%20sharding/get/cpu.svg)
И совпадает с `ALLOC` ниже.

2020-10-27 09:31 UTC, incubos commented on profile_info/report.md
> +аналогично put
К put есть вопросы выше.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                map.put(hash, node);
Коллизии нельзя оставлять без проверки. Давайте хотя бы кинем исключение в случае коллизии, потому что это чревато перекосом нагрузки на нодах.

2020-10-27 09:31 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +        long calculateHash(final byte[] key) throws NoSuchAlgorithmException {
По сути, этот метод должен быть `static` и внешний класс `MD5Hash` уже не нужен.

2020-10-27 10:29 UTC, re1nex commented on src/main/java/ru/mail/polis/service/re1nex/AsyncTopologyService.java
> +            apiUtils.sendErrorResponse(session, Response.INTERNAL_ERROR, logger);
там внутри есть catch и сюда мы из-за него попадем

2020-10-28 09:43 UTC, incubos commented
Ждать исправлений или удовлетворимся частью баллов?

2020-10-28 10:02 UTC, incubos commented on src/main/java/ru/mail/polis/dao/re1nex/ConsistentHashingTopology.java
> +                for (int j = 0; j < i; j++) {
В `one-nio` уже есть `Hash.murmur3(String s)` -- вы можете применять его к `node + i`.

2020-10-28 10:05 UTC, incubos commented
Принято за 8 баллов.

2020-10-28 10:05 UTC, closed without merging