Stage 4
polis-mail-ru/2020-highload-dht pull request #88
Opened 2020-10-18 12:10 UTC by StasyanOi

2020-10-24 09:32 UTC, StasyanOi commented
Тесты для пятой стадии валят билд :(

2020-10-25 22:42 UTC, lamtev requested changes
## Реализация

Оставил несколько замечаний и вопросов. Замечания, оставленные для `GET`, просьба поправить и для остальных методов

## Профилирование под нагрузкой

Наверное, единственное замечание -- это использование `wrk2` с ключом `--u_latency` вместо `--latency`. На лекциях говорили, чем отличается `wrk2` от `wrk`, и почему его нужно использовать. Также можно почитать README в репозитории [данной утилиты](https://github.com/giltene/wrk2)

2020-10-25 22:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        if (idParam == null || idParam.isEmpty()) {
Можно воспользоваться параметром аннотации `@Param` `required=true`, тогда one-nio сам ответит 400

2020-10-25 22:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private Response getResponseIfIdNotNull(final ByteBuffer id) throws IOException {
Несмотря на название ***IfIdNotNull** проверки на `null` нет. Она в общем-то здесь и не нужна, потому что осуществляется  на более высоком уровне

2020-10-25 22:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            //if not found then 404
Без данного комментария и так все понятно

2020-10-25 22:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            final ByteBuffer body = dao.get(id);
`IOException` от `Dao` не отлавливается здесь и пробрасывается на более высокий уровень, где одинаково обрабатывается вместе с `IOException` от `HttpSession`. И получается, что когда `IOException` выбросился при попытке ответить клиенту, то `session.sendResponse(500)` будет вызван повторно, когда нужно было уже просто залоггировать ошибку

2020-10-25 22:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            executorService.shutdown();
можно добавить `awaitTermination(timeout)`

2020-10-25 22:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Чего бы не воспользоваться конструктором `Response(code, body)`, который самостоятельно проставит данный заголовок

2020-10-25 22:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final int hash = Math.abs(Arrays.hashCode(idArray));
`Math.abs` может вернуть отрицательное число =)

2020-10-25 22:42 UTC, lamtev commented on reports/stage4/wrkLogsPut1.txt
> +  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
> measured without taking _delayed starts_ into account

фишка `wrk2` в том, что он умеет корректировать задержки с учетом _delayed starts_. Не тот ключ при запуске использовался

2020-10-30 09:52 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Map<Integer, String> nodeMapping;
Мне нужна сортировка

2020-10-30 09:52 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final Map<Integer, String> nodeMappingTemp = new TreeMap<>();
Мне нужна сортировка

2020-10-30 09:52 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private int nodeNum;
Да

2020-10-30 10:24 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final Map<Integer, String> nodeMappingTemp = new TreeMap<>();
Для чего? Просто реально сейчас TreeMap не используется по нзначению. Можно спокойно  заменить на любую другую реализацию Map, и поведение не изменится

2020-10-30 10:28 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Map<Integer, String> nodeMapping;
Для чего?

2020-10-30 10:42 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private Response getResponseIfIdNotNull(final ByteBuffer id) throws IOException {
Просто название метода для понимания того, где его использовать

2020-10-30 10:44 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final int hash = Math.abs(Arrays.hashCode(idArray));
Пофиксил

2020-10-30 10:49 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            final ByteBuffer body = dao.get(id);
Так он и залогируется

2020-10-30 10:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Map<Integer, String> nodeMapping;
Нужна сортировка

2020-10-30 10:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final Map<Integer, String> nodeMappingTemp = new TreeMap<>();
Нужна сортировка

2020-10-30 10:53 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());
Пофиксил

2020-10-30 10:54 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
Просто подставлять пустую строку - вызывает ощущение костыля

2020-10-30 10:55 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final int hash = Math.abs(Arrays.hashCode(idArray));
Пофиксил

2020-10-30 10:56 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Map<Integer, String> nodeMapping;
Для того, чтобы все ноды были в одном порядке

2020-10-30 10:57 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final Map<Integer, String> nodeMappingTemp = new TreeMap<>();
Она мне потом нужна была чтоб нормально раутинг устроить в 5-м этапе

2020-10-30 11:05 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            //if not found then 404
убрал

2020-10-30 11:06 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            httpClient.close();
Я пытаюсь делать чистые функции, чтоб не надо было думать о синхронизации каждый раз.

2020-10-30 11:34 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            executorService.shutdown();
Зафиксил

2020-10-30 11:34 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final HttpClient httpClient = new HttpClient(connectionString);
Завел

2020-10-30 11:34 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            httpClient.close();
пофиксил

2020-10-30 11:35 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        if (idParam == null || idParam.isEmpty()) {
Переделал

2020-10-30 11:45 UTC, StasyanOi commented on reports/stage4/wrkLogsPut1.txt
> +  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
переделал

2020-10-31 14:29 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/Util.java
> +        responseHttp.addHeader(HttpHeaders.CONTENT_LENGTH + ": " + 0);
не пустую строку, а пустой массив байтов. Более того, уже даже есть `Response.EMPTY` для этого. никакого костыля нет. нормальное решение без лишних действий и кода. В общем, ладно, не самый критичный момент в данном решении

2020-10-31 14:32 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            final ByteBuffer body = dao.get(id);
Да, залоггируется, и с этим проблем нет. Проблема вот в чем:

> И получается, что когда IOException выбросился при попытке ответить клиенту, то session.sendResponse(500) будет вызван повторно

2020-10-31 14:34 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        if (idParam == null || idParam.isEmpty()) {
не должно быть такого. ну ладно

2020-10-31 14:41 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Map<Integer, String> nodeMapping;
порядок нод на всех нодах гарантируется тем, что сначала выполняется сортировка:
```java
final ArrayList<String> urls = new ArrayList<>(topology);
urls.sort(String::compareTo);
```

А затем уже неважно в каком порядке ноды лежат в мапе, потому что доступ всегда выполняется по ключу, а ключ равен индексу в исходном отсортированном массиве

2020-10-31 14:42 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Map<Integer, String> nodeMapping;
Нет причин использовать SortedMap, да и вообще любой Map. Достаточно массива, будет и проще и эффективнее

2020-10-31 14:43 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public synchronized void get(final @Param("id") String idParam,
зачем здесь и в других местах появился `synchronized` ?

2020-10-31 14:45 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomExecutor.java
> +    private void send503Error(final HttpSession errorSession) {
Мухи отдельно, котлеты отдельно 

Single Responsibility Principle

ExecutorService точно не должен отправлять ответ клиенту по http

2020-10-31 14:50 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Map<String, HttpClient> clients = new ConcurrentHashMap<>();
Можно на этапе создания данного класса сразу сформировать обычную HashMap с клиентами. Модификаций в дальнейшем не будет, поэтому это безопасно. Не будет оверхэда от ConcurrentHashMap (хоть он и небольшой)

2020-10-31 14:52 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            final ConnectionString connectionString = new ConnectionString(strUrl);
дефолтный таймаут 3 секунды. устраивает ли это нас, когда мы стремимся к сильно меньшим задержкам?

2020-10-31 14:54 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            executorService.awaitTermination(10L, TimeUnit.MILLISECONDS);
Наверное, 10 мс как-то мало, тогда можно было и без этого обойтись)

2020-10-31 15:00 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final int hash = abs < 0 ? -abs : abs;
на лекции был предложен более изящный способ: можно занулить старший бит числа, как раз отвечающий за знак, при помощи 1 битовой операции. чисто на заметку

2020-10-31 19:17 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public synchronized void get(final @Param("id") String idParam,
Чтобы сессия на которую отправится потенциальный 503 была одинакова.

2020-10-31 19:17 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomExecutor.java
> +    private void send503Error(final HttpSession errorSession) {
перенес

2020-10-31 19:17 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            final ConnectionString connectionString = new ConnectionString(strUrl);
убрал метод

2020-10-31 19:18 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +        final int hash = abs < 0 ? -abs : abs;
Хорошо, учту

2020-10-31 19:19 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            executorService.awaitTermination(10L, TimeUnit.MILLISECONDS);
до 200 увеличил

2020-10-31 19:33 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public synchronized void get(final @Param("id") String idParam,
О как, понял. Просто это же дополнительные локи на каждый клиентский запрос. Не проще ли вместо того, чтобы на каждый клиентский запрос устанавливать новый обработчик, просто ловить исключение:
```java
try {
    executor.execute(() -> {})
} catch (RejectedExecutionException e) {
    session.send503();
}
```

Тогда заодно решится проблема с тем, что Executor знает что-то об http сессии

2020-10-31 19:38 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    public synchronized void get(final @Param("id") String idParam,
Точно, не подумал об этом, пофиксил

2020-10-31 19:38 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Map<String, HttpClient> clients = new ConcurrentHashMap<>();
Переделал

2020-11-02 11:53 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomExecutor.java
> +    }
остался ненужный метод

2020-11-02 11:55 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            }
Данное исключение выбрасывается методом executorService.execute. Соответственно текущая обработка некорректна

2020-11-02 11:58 UTC, lamtev requested changes
Остался ряд неисправленных недочетов:
1. RejectedExecutionException не обрабатывается
2. IOException от dao.get/put/delete и от session.sendResponse обрабатывается одинаково: отправкой ответа через session.sendResponse. Соответственно если в первый раз исключение было из session.sendResponse, то будет попытка повторно отправить ответ
3. Дополнительная сложность в виде Map<NodeIndexInSortedArray, NodeUrl>

2020-11-03 18:28 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomExecutor.java
> +    }
Выпилил

2020-11-03 18:29 UTC, StasyanOi commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +            }
Переделал обработку. Теперь от executor ловит

2020-11-03 18:31 UTC, StasyanOi commented
@lamtev, TreeMap поменял на хэшмапу. Теперь ошибка IOException от dao и от session обрабатываются раздельно. Переделал обработку RejectedExecutionException

2020-11-03 18:41 UTC, lamtev approved these changes
Принято! 
Но опять же отмечу, что Map индексов нод на урлы легко заменяется обычным массивом

2020-11-03 18:41 UTC, lamtev commented on src/main/java/ru/mail/polis/service/stasyanoi/CustomServer.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass());
обычно логгер делают статическим

2020-11-03 18:41 UTC, closed without merging