Stage4
polis-mail-ru/2020-highload-dht pull request #89
Opened 2020-10-18 14:39 UTC by mariarheon

2020-10-20 12:14 UTC, incubos requested changes
- Рандеву-хэширование -- это здорово!
- Есть ряд замечаний по коду, особенно в части обработки ошибок
- Не хватает анализа результатов профилирования

2020-10-20 12:14 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +            logger.error(SERV_UN, ex);
Кроме логгирования нужно чем-то ответить клиенту.

2020-10-20 12:14 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                session.sendResponse(new ZeroResponse(Response.INTERNAL_ERROR));
Тут `IOException` может прилететь из `session.sendResponse()` выше, в таком случае, мы отправим ещё один `Response`.

2020-10-20 12:14 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +            final var resp = sharding.passOn(reqNode, request);
Предлагаю оставить в `try ... catch` только проксирование, иначе есть 2 места возникновения ошибок.

2020-10-20 12:14 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                session.sendResponse(new ZeroResponse(Response.INTERNAL_ERROR));
Сюда мы тоже можем попасть из-за `IOException` из `sendResponse()` выше и отправим **два ответа**.

2020-10-20 12:14 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/AsyncServiceImpl.java
> +                session.sendResponse(new ZeroResponse(Response.INTERNAL_ERROR));
Это применимо и к методам `put()` и `get()` выше.

2020-10-20 12:14 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/RendezvousSharding.java
> +                clients.put(node, new HttpClient(new ConnectionString(node + "?timeout=100")));
Довольно жёсткий таймаут. Давайте вынесем его в параметр конструктора или константу? Литералов в коде быть не должно.

2020-10-20 12:14 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/RendezvousSharding.java
> +        synchronized (this) {
Зачем этот `synchronized`? `HttpClient` является потокобезопасным.

2020-10-20 12:14 UTC, incubos commented on wrk/delete.lua
> +    wrk.method = "DELETE"
Вы же не обстреливаете `DELETE`ами, зачем это?

2020-10-20 12:16 UTC, mariarheon commented on highload-analysis.md
> +### PUT
Обязательно добавлю. Планировала сегодня успеть догрузить как раз до дедлайна.

2020-10-20 12:18 UTC, mariarheon commented on wrk/delete.lua
> +    wrk.method = "DELETE"
Не удалила на одном из этапов похоже.

2020-10-22 09:40 UTC, incubos requested changes
- Есть замечания по коду
- Требуется качественный анализ результатов, а не количественный
- Есть подозрение, что `lock` профилировались с `synhronized` на `HttpClient`

2020-10-22 09:40 UTC, incubos commented on highload-analysis.md
> +Блокировки потоков работы отнимают практически 100%.
Профилировали до устранения `synchronized` на `HttpClient`?

2020-10-22 09:40 UTC, incubos commented on highload-analysis.md
> +Итоги:
Интересует не количественный summary, а качественный анализ, например: появилась пересылка запросов и она отнимает процессорные ресурсы (20%), по сравнению со стрельбой предыдущего этапа ухудшились/улучшились перцентили времени ответа (почему?) и т.д.
Конкретные цифры легко извлечь из FlameGraph, а вам в будущей работе предстоит искать узкие места в вашей системе, оптимизировать их и объяснять коллегам проделанные оптимизации.

2020-10-22 09:40 UTC, incubos commented on src/main/java/ru/mail/polis/service/mariarheon/RendezvousSharding.java
> +    private static final String TIMEOUT_SUFFIX = "?timeout=100";
Тут мы отсвечиваем спецификой `HttpClient`. Читателю будет понятнее `Duration.ofMillis(100)`, а в конструкторе ниже его значение уже подставится в `timeout=`.

2020-10-26 17:38 UTC, incubos commented
Принято с замечаниями по отчёту.

2020-10-26 17:38 UTC, closed without merging

2020-10-26 18:50 UTC, mariarheon commented
> Принято с замечаниями по отчёту.

А можно уточнить какие замечания?