Stage 1
polis-mail-ru/2020-highload-dht pull request #9
Opened 2020-09-27 12:43 UTC by makaryb

Добрый день!
Отправляю решение по заданию 1.

![img0](https://user-images.githubusercontent.com/36387962/94365273-19293900-00d8-11eb-8887-5e220c0ec2c9.png)
![im1](https://user-images.githubusercontent.com/36387962/94365275-1b8b9300-00d8-11eb-8941-a800d0475f24.png)
![img2](https://user-images.githubusercontent.com/36387962/94365277-1d555680-00d8-11eb-80b8-33875b61a37e.png)
![cpu](https://user-images.githubusercontent.com/36387962/94365279-1e868380-00d8-11eb-880a-3fc7a4738c4f.png)

2020-10-04 10:12 UTC, dormidon commented on profiling_results_stage1/wrk_t1_c1_d10m_s_wrk_get-lua_latency_localhost-8080
> +Running 10m test @ http://127.0.0.1:8080
Очень подозрительные результаты. 
1. Тут не указан HTTP-ресурс, куда шла "стрельба" (при стрельбе по status он указан)
2. Цифры совершенно не реальные - 90% микросекунды - очень странно, да и результаты get и put "хуже", чем на status - это очень странно (скорее всего, в status мы не напоролись на GC ибо 10 секунд тест был), а тут тесты по 10 минут и на небольшой GC мы успевали напороться.

Выглядит так, что нужно перестрелять по правильным методам.

И еще можно немного переформатировать отчет, вставив SVG-шки прямо в README - так сильно быстрее и удобнее воспринимается.

2020-10-04 10:13 UTC, dormidon requested changes
См. комменты. 
Скорее всего, со стрельбами что-то не то.

2020-10-04 11:33 UTC, dormidon commented on profiling_results_stage1/wrk_t1_c1_d10m_s_wrk_get-lua_latency_localhost-8080
> +Running 10m test @ http://127.0.0.1:8080
Ну или нужно приложить тогда конфигурацию железа, на котором производилось нагрузочное тестирование.
Может быть, цифры и норм для довольно мощной железяки, но мне в них все равно слабо верится.
Если можно, было бы здорово получить более детальные процентили. 
Ибо 90 и 99 слишком грубо. Нужно больше девяток :)

2020-10-04 11:43 UTC, dormidon commented on profiling_results_stage1/wrk_t1_c1_d10m_s_wrk_get-lua_latency_localhost-8080
> +Running 10m test @ http://127.0.0.1:8080
В общем, мне не очень понятны чиселки итоговые - профили приложения вообще отличные, видно, что делается ровно то, что надо. Но оно как-то слишком хорошо по цифиркам :)

2020-10-04 17:14 UTC, makaryb commented
Добрый вечер!

Пострелял теперь с утилитой _wrk2_. 

**Для PUT**:

```
wrk2 -t1 -c1 -d10m -R20000 -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/put.lua --latency http://127.0.0.1:8080

Running 10m test @ http://127.0.0.1:8080
  1 threads and 1 connections
  Thread calibration: mean lat.: 3.318ms, rate sampling interval: 10ms
^C  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   453.96ms  646.65ms   2.48s    79.68%
    Req/Sec    21.15k    13.00k   48.67k    59.82%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.20ms
 75.000%  886.27ms
 90.000%    1.58s 
 99.000%    2.05s 
 99.900%    2.40s 
 99.990%    2.47s 
 99.999%    2.48s 
100.000%    2.48s 

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.020     0.000000            2         1.00
       0.257     0.100000       432871         1.11
       0.481     0.200000       864436         1.25
       0.703     0.300000      1296424         1.43
       0.921     0.400000      1728755         1.67
       1.202     0.500000      2160099         2.00
       2.081     0.550000      2376077         2.22
     191.743     0.600000      2592149         2.50
     427.775     0.650000      2808267         2.86
     656.383     0.700000      3024116         3.33
     886.271     0.750000      3240129         4.00
     999.935     0.775000      3348123         4.44
    1116.159     0.800000      3456182         5.00
    1231.871     0.825000      3564400         5.71
    1348.607     0.850000      3672359         6.67
    1467.391     0.875000      3780962         8.00
    1525.759     0.887500      3834219         8.89
    1583.103     0.900000      3888158        10.00
    1641.471     0.912500      3942195        11.43
    1700.863     0.925000      3996349        13.33
    1760.255     0.937500      4050388        16.00
    1789.951     0.943750      4077348        17.78
    1819.647     0.950000      4104841        20.00
    1847.295     0.956250      4131751        22.86
    1874.943     0.962500      4158840        26.67
    1903.615     0.968750      4185391        32.00
    1918.975     0.971875      4199222        35.56
    1933.311     0.975000      4212080        40.00
    1950.719     0.978125      4225804        45.71
    1970.175     0.981250      4239488        53.33
    1990.655     0.984375      4253156        64.00
    2002.943     0.985938      4259765        71.11
    2017.279     0.987500      4266316        80.00
    2034.687     0.989062      4273195        91.43
    2055.167     0.990625      4279580       106.67
    2080.767     0.992188      4286559       128.00
    2094.079     0.992969      4289714       142.22
    2115.583     0.993750      4293420       160.00
    2134.015     0.994531      4296498       182.86
    2154.495     0.995313      4299877       213.33
    2177.023     0.996094      4303284       256.00
    2195.455     0.996484      4305039       284.44
    2213.887     0.996875      4306674       320.00
    2250.751     0.997266      4308288       365.71
    2291.711     0.997656      4309984       426.67
    2334.719     0.998047      4311695       512.00
    2355.199     0.998242      4312518       568.89
    2373.631     0.998437      4313443       640.00
    2385.919     0.998633      4314276       731.43
    2396.159     0.998828      4315209       853.33
    2402.303     0.999023      4315925      1024.00
    2410.495     0.999121      4316304      1137.78
    2420.735     0.999219      4316779      1280.00
    2428.927     0.999316      4317161      1462.86
    2439.167     0.999414      4317623      1706.67
    2447.359     0.999512      4317995      2048.00
    2451.455     0.999561      4318267      2275.56
    2453.503     0.999609      4318394      2560.00
    2457.599     0.999658      4318712      2925.71
    2459.647     0.999707      4318906      3413.33
    2461.695     0.999756      4319016      4096.00
    2463.743     0.999780      4319154      4551.11
    2465.791     0.999805      4319270      5120.00
    2467.839     0.999829      4319393      5851.43
    2469.887     0.999854      4319532      6826.67
    2471.935     0.999878      4319654      8192.00
    2471.935     0.999890      4319654      9102.22
    2471.935     0.999902      4319654     10240.00
    2473.983     0.999915      4319781     11702.86
    2473.983     0.999927      4319781     13653.33
    2476.031     0.999939      4320032     16384.00
    2476.031     0.999945      4320032     18204.44
    2476.031     0.999951      4320032     20480.00
    2476.031     0.999957      4320032     23405.71
    2476.031     0.999963      4320032     27306.67
    2476.031     0.999969      4320032     32768.00
    2476.031     0.999973      4320032     36408.89
    2476.031     0.999976      4320032     40960.00
    2476.031     0.999979      4320032     46811.43
    2476.031     0.999982      4320032     54613.33
    2476.031     0.999985      4320032     65536.00
    2476.031     0.999986      4320032     72817.78
    2476.031     0.999988      4320032     81920.00
    2476.031     0.999989      4320032     93622.86
    2476.031     0.999991      4320032    109226.67
    2478.079     0.999992      4320070    131072.00
    2478.079     1.000000      4320070          inf
#[Mean    =      453.960, StdDeviation   =      646.653]
#[Max     =     2476.032, Total count    =      4320070]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  4520155 requests in 3.77m, 288.82MB read
  Socket errors: connect 0, read 0, write 0, timeout 2
Requests/sec:  19999.89
Transfer/sec:      1.28MB
```

**Профиль**:

![cpu-put](https://user-images.githubusercontent.com/36387962/95020908-9c1d3700-0676-11eb-9cae-af2611c26824.png)

**Для GET**:

```
wrk2 -t1 -c1 -d10m -R20000 -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/get.lua --latency http://127.0.0.1:8080

Running 10m test @ http://127.0.0.1:8080
  1 threads and 1 connections
  Thread calibration: mean lat.: 2025.298ms, rate sampling interval: 5107ms
^C  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.62s     6.95s   25.87s    54.74%
    Req/Sec    17.28k   513.73    18.08k    66.67%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%   14.52s 
 75.000%   21.02s 
 90.000%   24.17s 
 99.000%   25.74s 
 99.900%   25.87s 
 99.990%   25.89s 
 99.999%   25.89s 
100.000%   25.89s 

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

    2648.063     0.000000          115         1.00
    5115.903     0.100000       298694         1.11
    7352.319     0.200000       595620         1.25
    9666.559     0.300000       893279         1.43
   12435.455     0.400000      1190749         1.67
   14516.223     0.500000      1487844         2.00
   15892.479     0.550000      1637151         2.22
   17088.511     0.600000      1786346         2.50
   18153.471     0.650000      1935652         2.86
   19529.727     0.700000      2083192         3.33
   21020.671     0.750000      2231803         4.00
   21676.031     0.775000      2306796         4.44
   22102.015     0.800000      2381073         5.00
   22757.375     0.825000      2455112         5.71
   23166.975     0.850000      2529558         6.67
   23707.647     0.875000      2604067         8.00
   23986.175     0.887500      2640640         8.89
   24166.399     0.900000      2678077        10.00
   24379.391     0.912500      2715215        11.43
   24641.535     0.925000      2752666        13.33
   24854.527     0.937500      2790999        16.00
   24936.447     0.943750      2809484        17.78
   25051.135     0.950000      2828142        20.00
   25149.439     0.956250      2845460        22.86
   25280.511     0.962500      2867163        26.67
   25378.815     0.968750      2884034        32.00
   25411.583     0.971875      2891733        35.56
   25477.119      [...]

2020-10-04 17:21 UTC, makaryb commented on profiling_results_stage1/wrk_t1_c1_d10m_s_wrk_get-lua_latency_localhost-8080
> +Running 10m test @ http://127.0.0.1:8080
Добавил новые результаты профилирования ниже в комментарии.

Здесь приложу скрин _лекционного материала_ - там также: "Тут не указан HTTP-ресурс, куда шла "стрельба" (при стрельбе по status он указан)":

![Selection_010](https://user-images.githubusercontent.com/36387962/95022293-0043f900-067f-11eb-871b-57809635d01b.png)

Свои дейтсвия производил подобным образом, как в _лекции_

2020-10-05 08:32 UTC, dormidon commented on profiling_results_stage1/wrk_t1_c1_d10m_s_wrk_get-lua_latency_localhost-8080
> +Running 10m test @ http://127.0.0.1:8080
Да, все так. Я просто по старой памяти подумал, что он ресурс пишет, а этот ресурс у нас в скрипте осел.

2020-10-05 08:41 UTC, dormidon commented
Цифры с wrk2 более правдоподобны.
Если интересны детали, можно почитать https://github.com/giltene/wrk2, чем именно wrk2 отличается от wrk. А так же глянуть интересный доклад от создателя wrk2 (и основателя Azul) - https://www.youtube.com/watch?v=lJ8ydIuPFeU

Другое дело, что время на чтение стало каким-то совсем худым. Возможно, это из-за высокой нагрузки с обработки одним потоком - куча запросов стоят на очереди wrk2, хотя по плану они должны были быть отправлены, и wrk2 как раз учитывает это время в задержке (в отличие от wrk). 

Я бы рекомендовал попробовать поиграться с нагрузкой - сначала почитать 1000 запросов в секунду, посмотреть распределение, потом 2000, 5000 и т.д. Где-то должна быть та грань, когда один поток перестает справляться и начинает копиться очередь, в связи с чем процентили растут до десятков секунд.

А так выглядит все очень хорошо, хороший отчет, красивые профили без всего лишнего. 
Давайте найдем причину долгих ответов get (скорее всего, дело в слишком большой нагрузке в 20К prs). Ну или если не в ней, то внимательнее смотреть в профиль и оптимизировать самые "жирные" методы.

2020-10-05 09:15 UTC, dormidon requested changes
Давайте еще чуть-чуть поиграем с нагрузкой с wrk2, чтобы наверняка понять природу такого запредельного времени ответа.

2020-10-05 12:16 UTC, makaryb commented
Добрый день!

Провел сравнительный анализ результатов для _R1000_, _R2000_, _R5000_, _R8000_, _R9000_, _R10000_ и _R12000_.

Результаты выглядят следующим образом:

**Для 1-2-5-8-9-10-12**:

![output--1-2-5-8-9-10-12](https://user-images.githubusercontent.com/36387962/95077978-156f6500-071d-11eb-9afd-03cb5afaa183.png)

**Для 1-2-5-8-9-10**:

![output-1-2-5-8-9-10](https://user-images.githubusercontent.com/36387962/95078013-20c29080-071d-11eb-96b4-b3e99757f5a1.png)

**Для 1-2-5-8-9**:

![output-1-2-5-8-9](https://user-images.githubusercontent.com/36387962/95078036-2c15bc00-071d-11eb-83ee-feb2a5e96a67.png)

**Для 1-2-5-8**:

![output-1-2-5-8](https://user-images.githubusercontent.com/36387962/95078059-33d56080-071d-11eb-8905-507856a64090.png)

**Для 1-2-5**:

![output-1-2-5](https://user-images.githubusercontent.com/36387962/95078098-43ed4000-071d-11eb-992b-07e6608d95b9.png)

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Можно видеть, что адекватное время ответа для моего случая (реализации и железа) сохраняется при 1 соединении до R9000.

Таким образом, можно утверждать, что дело, дейтсвительно, в слишком большой нагрузке в 20К prs для 1 соединения. В моем случае при такой реализации необходимо 8-9 K prs

2020-10-05 13:50 UTC, dormidon commented
Да, все это очень похоже на правду. 
Действительно, эти большие задержки на большой нагрузке из-за особенностей (точнее, более правильного) подсчета задержки wrk2 против wrk.

Отличная работа! Засчитано полностью.
🔥

2020-10-05 13:51 UTC, dormidon approved these changes

2020-10-05 14:05 UTC, closed without merging