Task 4
polis-mail-ru/2020-highload-dht pull request #90
Opened 2020-10-18 17:02 UTC by nik27090

2020-10-20 12:27 UTC, incubos requested changes
- Rendezvous hashing это отлично, а MurMur3 совсем огонь!
- Есть небольшие замечания по коду, особенно в части обработки ошибок
- Отсутствуют результаты нагрузочного тестирования, профилирования и их анализ

2020-10-20 12:27 UTC, incubos commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +            final HttpClient client = new HttpClient(new ConnectionString(node + "?timeout=1000"));
Лучше вынести таймаут в константу или параметр конструктора.

2020-10-20 12:27 UTC, incubos commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +            sendResponse(session, new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Сюда мы можем попасть из-за исключения в `sendResponse()` выше и попытаемся отправить **два ответа**.

2020-10-20 12:27 UTC, incubos commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +            sendResponse(session, new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Сюда мы можем попасть из-за исключения в `sendResponse()` выше и попытаемся отправить **два ответа**.

2020-10-20 12:27 UTC, incubos commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +            sendResponse(session, new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Сюда мы можем попасть из-за исключения в `sendResponse()` выше и попытаемся отправить **два ответа**.

2020-10-20 12:38 UTC, nik27090 commented
Возможно дал мало нагрузки потому что 100% запросов выполняются в пределах 30ms, полную аналитику и исправление замечаний постараюсь залить до дедлайна

2020-10-20 18:29 UTC, nik27090 commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +            sendResponse(session, new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Разве? В методе sendResponse я же отлавливаю IOException и расчитываю что он не пробрасывается наверх.

2020-10-22 10:31 UTC, incubos commented on src/main/java/ru/mail/polis/service/nik27090/ServiceImpl.java
> +            sendResponse(session, new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Верно, прошу прощения. Перепутал с `session.sendResponse()`.

2020-10-22 10:50 UTC, incubos requested changes
Есть замечание по коду и вопросы по отчёту.

2020-10-22 10:50 UTC, incubos commented on highloadTest/readme.md
> +В данной конфигурацией за 40 сек было выполнено 399829 запросов. В среднем по 25800 req/s и с задержкой в 848us.
Это не анализ. Все цифры уже приведены в выводе `wrk2`. Сравните качественно перцентили времён ответа с предыдущим этапом -- стало ли медленнее с т.з. клиента?

2020-10-22 10:50 UTC, incubos commented on highloadTest/readme.md
> +На данных графиках появился процесс 'proxy'(19%), который переадресовывает запрос на соответсвующую ноду кластера.
Это же не "процессы", а обычные методы.

2020-10-22 10:50 UTC, incubos commented on highloadTest/readme.md
> +Аналогично графикам CPU можно также заметить новые графы. Но отношения их ресурсопотребление сильно отличается 19/1% и 23/17%.
По сравнению с чем "ресурсопотребление сильно отличается"?

2020-10-22 10:50 UTC, incubos commented on highloadTest/readme.md
> +![Alt text](./async-profiler/alloc/putAllocWithThreadsV4.svg)
Здесь и везде `*WithThreads*` уже можно не профилировать. Зачем на них тратить время? Мы уже поняли, что запросы обслуживаются на отдельном пуле воркеров.

2020-10-22 10:50 UTC, incubos commented on highloadTest/readme.md
> +Потокобезопасность обеспечивается контролем доступа к общим данным экземпляром ReentrantLock и блокировками на чтение и запись данных.
Что означает эта абстрактная фраза? У вас в профиле все блокировки возникают на очереди между селекторами HTTP сервера и пулом потоков-воркеров -- вот что важно.

2020-10-22 10:50 UTC, incubos commented on highloadTest/readme.md
> +В данной конфигурацией за 40 сек было выполнено 399822 запроса. В среднем по 25700 req/s и с задержкой в 843us.
Опять же нужен не количественный, а качественный анализ -- это хорошо или плохо? У вас же есть данные за предыдущий этап. Кстати, средняя задержка не самая показательная вещь -- используйте перцентили 99%, 99.9% и т.д.

2020-10-22 10:50 UTC, incubos commented on highloadTest/readme.md
> +В данной конфигурацией за 40 сек было выполнено 399822 запроса. В среднем по 25700 req/s и с задержкой в 843us.
Что означает "В среднем по 25700 req/s"?

2020-10-22 10:50 UTC, incubos commented on highloadTest/readme.md
> +Потокобезопасность обеспечивается контролем доступа к общим данным экземпляром ReentrantLock и блокировками на чтение и запись данных.
См. замечание выше.

2020-10-22 10:50 UTC, incubos commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +                "?timeout=1000",
Следуя принципам ООМ, здесь должно быть число (millis) или `Duration`, а не кастомный параметр `HttpClient`.

2020-10-27 09:33 UTC, incubos commented
Здесь ждать исправлений (до конца сегодняшнего дня) или принимаем за часть баллов?

2020-10-27 09:34 UTC, nik27090 commented
> Здесь ждать исправлений (до конца сегодняшнего дня) или принимаем за часть баллов?

Ждать!)

2020-10-27 19:22 UTC, nik27090 commented on highloadTest/readme.md
> +![Alt text](./async-profiler/alloc/putAllocWithThreadsV4.svg)
В прошлой дз, я не строил графики withThreads, не успел и потерял баллы. Решил в этой сделать.

2020-10-27 19:24 UTC, nik27090 commented on highloadTest/readme.md
> +На данных графиках появился процесс 'proxy'(19%), который переадресовывает запрос на соответсвующую ноду кластера.
поправил

2020-10-27 19:29 UTC, nik27090 commented on highloadTest/readme.md
> +В данной конфигурацией за 40 сек было выполнено 399822 запроса. В среднем по 25700 req/s и с задержкой в 843us.
"В среднем по 25700 request per seconds", поправил

2020-10-27 19:55 UTC, nik27090 commented on highloadTest/readme.md
> +Потокобезопасность обеспечивается контролем доступа к общим данным экземпляром ReentrantLock и блокировками на чтение и запись данных.
Понял:)

2020-10-27 19:59 UTC, nik27090 commented on highloadTest/readme.md
> +Аналогично графикам CPU можно также заметить новые графы. Но отношения их ресурсопотребление сильно отличается 19/1% и 23/17%.
пояснил

2020-10-28 09:49 UTC, incubos commented
Принято с небольшими замечаниями.

2020-10-28 09:49 UTC, closed without merging