Stage 4
polis-mail-ru/2020-highload-dht pull request #92
Opened 2020-10-19 10:27 UTC by makaryb

Добрый день!

Отправляю решение к этапу 4.

## 1. Нагрузка:

**Для PUT**:

```
wrk2 -t64 -c64 -d2m -R* -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/put.lua --latency http://127.0.0.1:8080
```

![output-put-all](https://user-images.githubusercontent.com/36387962/96428517-82e4c080-1208-11eb-8621-dbffed2b659c.png)

**Для GET**:

```
wrk2 -t64 -c64 -d2m -R* -s /home/makary/Documents/technopolis/2020-highload-dht/wrk/get.lua --latency http://127.0.0.1:8080
```

5k-6k-7k-8k-10k:

![output-get-all](https://user-images.githubusercontent.com/36387962/96428802-deaf4980-1208-11eb-8077-2b31931c10ef.png)

5k-6k-7k-8k:

![output-get-many](https://user-images.githubusercontent.com/36387962/96428876-f38bdd00-1208-11eb-96df-ea33118c3039.png)

5k-6k-7k:

![output-get-many-before2](https://user-images.githubusercontent.com/36387962/96428893-f981be00-1208-11eb-8730-6e4630b5be83.png)

Видно, что R до 7 тыс кластер выдерживает без проблем.

## 2. Профилирование:

```
sudo ./profiler.sh -d 30 -t -f /tmp/cpu-threads.svg <PID>

sudo ./profiler.sh -d 30 -f /tmp/cpu.svg <PID>
```

**Для PUT**:

_CPU_:

![put-cpu](https://user-images.githubusercontent.com/36387962/96429406-93496b00-1209-11eb-825a-1159699db5f1.png)

![put-cpu-only](https://user-images.githubusercontent.com/36387962/96429473-a5c3a480-1209-11eb-9988-cb3fdbed3a26.png)

Нагрузка на первый узел была больше, чем нагрузка на две остальных ноды кластера, так что назвать сбалансированной нагрузку в данном случае нельзя.

Вставка в каждом из воркеров заняла - _2.02%_; теперь тратится на проксирование запроса - _34.91%_.

_alloc_:

![put-alloc](https://user-images.githubusercontent.com/36387962/96429507-b116d000-1209-11eb-99f7-44cb26fb2035.png)

![put-alloc-only](https://user-images.githubusercontent.com/36387962/96429528-b542ed80-1209-11eb-9547-fd72382c59c0.png)

Аллокация памяти происходила в большей части при проксировании запроса - _30.50%_.

_lock_:

![put-lock](https://user-images.githubusercontent.com/36387962/96429547-bb38ce80-1209-11eb-9b0d-4e10b1df260a.png)

![put-lock-only](https://user-images.githubusercontent.com/36387962/96429551-bd9b2880-1209-11eb-89fc-844b96c904b6.png)

Селекторы блокируются, что отдать задачу в пул потоков.

Воркеры блокировались, чтобы: записать данные в хранилище; взять задачу на обработку.

**Для GET**:

_CPU_:

![get-cpu](https://user-images.githubusercontent.com/36387962/96429689-e7ece600-1209-11eb-9ec9-ad503fd62c91.png)

![get-only-cpu](https://user-images.githubusercontent.com/36387962/96429705-ecb19a00-1209-11eb-9feb-8803230dd7ca.png)

Видно, что воркеров стало в три раза больше и все занимают примерно одно время, то есть распределение нагрузки можно назвать сбалансированным.

На воркере большую часть времени занимает получение итератора - _58.70%_; проксирование занимает - _11.98%_.

_alloc_:

![get-alloc](https://user-images.githubusercontent.com/36387962/96429732-f63b0200-1209-11eb-8b1f-b5b759b36597.png)

![get-only-alloc](https://user-images.githubusercontent.com/36387962/96429751-faffb600-1209-11eb-88d7-b151c028493a.png)

На воркере на проксирование запроса памяти выделяется - _23.75%_; 

_lock_ (PUT+GET):

![get_put-only-lock](https://user-images.githubusercontent.com/36387962/96430193-88430a80-120a-11eb-8006-08ef0bbbb818.png)

![get_put-lock](https://user-images.githubusercontent.com/36387962/96430197-8aa56480-120a-11eb-9fe3-bae01b8d1ac0.png)

Селекторы также блокируются: чтобы отдать задачу в пул потоков.

Воркеры блокируются, чтобы: взять задачу на обработку.

2020-10-25 23:14 UTC, lamtev requested changes
## Реализация

Оставил пару замечаний. Ну и нужно будет подтянуть исправления от прошлого этапа (RejectedExecutionException ...)

## Профилирование

Все хорошо, только вот проглядел момент с запросами на другие ноды с потоков селектора. К сожалению, нет исходных svg файлов в репозитоии, и я не смог сам посмотреть. Но там точно должно быть видно этот момент

2020-10-27 09:29 UTC, makaryb commented
Добавил .svg-оригиналы профилирования [здесь](https://github.com/makaryb/2020-highload-dht/tree/feature/task4/profiling_results_stage4).

2020-10-28 19:14 UTC, lamtev approved these changes

2020-10-28 19:14 UTC, lamtev commented
Принято

2020-10-28 19:14 UTC, closed without merging