Stage #4
polis-mail-ru/2020-highload-dht pull request #94
Opened 2020-10-19 12:56 UTC by ScriptoMax

Итоги выполнения аналитического задания изложены в [отчёте](https://github.com/ScriptoMax/2020-highload-dht/blob/stage_4/resources/report.md) (resources/report.md).

2020-10-20 12:46 UTC, incubos requested changes
- Нагрузочное тестирование ОК
- Имеются замечания и вопросы по коду
- Объясните, пожалуйста, откуда появился lua-скрипт, генерирующий запросы к `/v0/entities`?

2020-10-20 12:46 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAO.java
> +
Зачем эти пустые строки?

2020-10-20 12:46 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAO.java
> +
Здесь и в других файлах.

2020-10-20 12:46 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            final HttpClient client = new HttpClient(new ConnectionString(node + "?timeout=1000"));
Лучше избегать литералов в коде. Давайте вынесем значение таймаута в константу или параметр конструктора?

2020-10-20 12:46 UTC, incubos commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                    session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Мы можем попасть сюда из-за ошибки в `sendResponse()` выше и таким образом попытаемся отправить **два ответа**.

2020-10-20 12:46 UTC, incubos commented on src/profiling/wrk_scripts/start_end_get.lua
> +    path = string.format("/v0/entities?start=%d&end=%d", counter, counter + 1)
Что это?

2020-10-20 18:43 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/dao/DAO.java
> +
Замечания устранены

2020-10-20 18:43 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +            final HttpClient client = new HttpClient(new ConnectionString(node + "?timeout=1000"));
Замечание устранено

2020-10-20 18:43 UTC, ScriptoMax commented on src/main/java/ru/mail/polis/service/codearound/AsyncService.java
> +                    session.sendResponse(new Response(Response.INTERNAL_ERROR, Response.EMPTY));
Замечание устранено

2020-10-20 19:20 UTC, ScriptoMax commented on src/profiling/wrk_scripts/start_end_get.lua
> +    path = string.format("/v0/entities?start=%d&end=%d", counter, counter + 1)
![Screenshot from 2020-10-20 22-47-26](https://user-images.githubusercontent.com/55311053/96630824-3ab7c200-131e-11eb-9937-d7282040e586.png)

Это скрипт для выполнения одного из заданий 3-го этапа в 2019-ом. Во время каникул, ориентируясь на общедоступный проект прошлого года, я решил на практике прочувствовать суть highload - чтобы у студента среднего уровня и без энтерпрайз-истории за плечами сам предмет с самого начала не вызвал бы, мягко говоря, серьёзное беспокойство. Занялся написанием кода, тестами, профилированием самостоятельно (благо и на ютубе, и на портале технополиса в видео недостатка не было). Такая тренировка в приближенных к боевым условиях (опять же, чтобы обошлось без шока и сильных эмоций осенью). <br/>Скрипт, послуживший поводом для Вашего вопроса, составил тогда же, а в свой форк добавил на автомате, вместе с другими скриптами для стресс-тестов. Третий этап уже миновали, и да - вижу, что именно этот код не понадобился. Перед следующим реквестом приведу эту часть исходников в порядок, т.е. оставлю конкретно этот сюжет с чанками где-нибудь на локальной машине. Всё об этом недоразумении.

2020-10-20 19:33 UTC, ScriptoMax commented
Указанные недочёты устранены, необходимые комментарии предоставлены. Пожалуйста, проведите повторное ревью.

2020-10-22 11:58 UTC, incubos commented
Принято.

2020-10-22 11:58 UTC, closed without merging