stage 4
polis-mail-ru/2020-highload-dht pull request #95
Opened 2020-10-19 14:22 UTC by gogun

Нагрузочное тестирование в процессе

2020-10-23 17:26 UTC, vaddya requested changes
С профилированием хорошо, несколько предложений по реализации.

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/gogun/ConsistentHashing.java
> +package ru.mail.polis.dao.gogun;
Это разве к DAO отношение имеет, не к сервису?

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/gogun/ConsistentHashing.java
> +        numOfNodes = nodes.size();
Вариант вроде рабочий, но вообще это число является параметром для `ConsistentHashing` и называется `vnodes`. То есть сколько виртуальных нод будет в нашем кольце вместо настоящих. Обычно это число на порядки больше реального числа над (100, 200), чтобы обеспечить более равномерное распределение ключей по нодам.

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/dao/gogun/ConsistentHashing.java
> +        if (!circle.containsKey(hash)) {
Кажется, что без этой проверки ничего не сломается. Или это оптимизация, чтобы не создавать `tailMap`? В этом случае лучше заменить интерфейс на `NavigableMap` и заюзать `ceilingEntry`.

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            if (nodeClients.get(node) != null) {
Кажется, что `containsKey` как-то более явно выражает намерение.

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            log.error(e.getMessage());
`log.error("Status error", e)`?

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            log.error("Error sending response in method get {}", e.getMessage());
`log.error("Error sending response in method get", e);`, а то теряем весь стектрейс

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            case Request.METHOD_PUT:
Метод разросся как-то, давайте тела `case` веток вынесем в методы с говорящими именами и ограниченным числом параметров?

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +                               final int requestType) throws IOException {
Не проще использовать `request.getMethod()`?

2020-10-23 17:26 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +                32,
Лучше не хардкодить, а вынести в константы. И очередь в 32 элемента -- это маленькая очередь, любой небольшой всплеск в числе запросов и сразу реджекты пойдут.

2020-10-25 13:54 UTC, gogun commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            case Request.METHOD_PUT:
codeclimate не пускал, вылезал за 250 строк класс, пришлось ужимать

2020-10-25 14:41 UTC, vaddya commented on src/main/java/ru/mail/polis/service/gogun/AsyncServiceImpl.java
> +            case Request.METHOD_PUT:
Ну читаемостью точно жертвовать не стоит. Можно `getArray` вынести в какой-нибудь утильный класс. Ну или создание конфига на крайняк вынести в `ServiceFactory`.

2020-10-25 16:01 UTC, vaddya requested changes

2020-10-25 16:58 UTC, vaddya commented
У вас теперь 3 одинаковых хендлера по одному и тому же пути. Можно оставить один.

2020-10-25 17:13 UTC, vaddya approved these changes
Принято.

2020-10-25 17:14 UTC, closed without merging