Task4
polis-mail-ru/2020-highload-dht pull request #96
Opened 2020-10-19 16:25 UTC by IvanovAndrey

2020-10-19 18:33 UTC, IvanovAndrey commented
[Результаты профилирования](https://github.com/IvanovAndrey/2020-highload-dht/blob/task4/async/report_task4.md)

2020-10-26 00:12 UTC, lamtev requested changes
## Реализация

Оставил замечания. Плюс замечания из предыдущего этапа

## Профилирование

> Локи присутствуют, почти все возникают во время SelectorThread.

Можно было бы поподробнее сказать, где там локи случаются

2020-11-01 23:57 UTC, IvanovAndrey commented
Еще раз прошу прощения за задержку, переделал

2020-11-02 12:04 UTC, lamtev requested changes
Нужно поправить замечания, тянущиеся из прошлого этапа

2020-11-05 21:12 UTC, lamtev commented
Принято с замечаниями

2020-11-05 21:12 UTC, closed without merging