Stage4
polis-mail-ru/2020-highload-dht pull request #97
Opened 2020-10-19 18:36 UTC by zvladn7

2020-10-19 20:20 UTC, zvladn7 commented
Отчет по профилированию будет добавлен немного позже

2020-10-20 13:20 UTC, incubos requested changes
- Consistent hashing огонь!
- А вот кеш теперь придётся или выпилить, или переделать
- Не хватает результатов нагрузочного тестирования, профилирования и анализа
- Есть ряд небольших замечаний/вопросов по коду

2020-10-20 13:20 UTC, incubos commented on src/main/java/ru/mail/polis/dao/zvladn7/TransactionalDAOImpl.java
> +final class TransactionalDAOImpl implements TransactionalDAO {
Что это?

2020-10-20 13:20 UTC, incubos commented on src/main/java/ru/mail/polis/dao/zvladn7/TransactionalDAOImpl.java
> +final class TransactionalDAOImpl implements TransactionalDAO {
В данном проекте транзакций не будет.

2020-10-20 13:20 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceHelper.java
> +        this.cache = CacheBuilder.newBuilder()
Это здорово, что такая мысль пришла в голову, но к сожалению, в распределённой системе такой кеш уже работать не будет, потому что очень быстро станет неконсистентным. Если непонятно почему, пишите в личку -- обсудим.

2020-10-20 13:20 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +            hashRing.put((node + i).hashCode(), node);
Хорошо бы проверить коллизии.

2020-10-20 13:20 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceHelper.java
> +    private static final Logger log = LoggerFactory.getLogger(AsyncService.class);
Неправильный класс.

2020-10-20 19:44 UTC, zvladn7 commented
[анализ нагрузочного тестирования](https://github.com/zvladn7/2020-highload-dht/blob/stage4/report/hw4.md)

2020-10-20 19:44 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceHelper.java
> +    private static final Logger log = LoggerFactory.getLogger(AsyncService.class);
ой) поправил

2020-10-20 19:45 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +            hashRing.put((node + i).hashCode(), node);
теперь учитываю коллизии, спасибо)

2020-10-20 19:46 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceHelper.java
> +        this.cache = CacheBuilder.newBuilder()
в итоге убрал кэш

2020-10-20 19:46 UTC, zvladn7 commented on src/main/java/ru/mail/polis/dao/zvladn7/TransactionalDAOImpl.java
> +final class TransactionalDAOImpl implements TransactionalDAO {
это осталось с курса прошлого семестра, удалил, чтобы не мешалось)

2020-10-22 12:08 UTC, incubos requested changes
Ждём результатов по кластерной конфигурации, а не однонодовой.

2020-10-22 12:08 UTC, incubos commented on report/hw4.md
> +# Нагрузочное тестирование с помощью wrk2
В результатах профилирования нет `HttpClient`. Видимо, вы нагружали однонодовую конфигурацию (`Server`), а не кластерную (`Cluster`), поэтому никакого проксирования не было. Нужно всё перемерять.

2020-10-22 12:08 UTC, incubos commented on report/hw4.md
> +В целом видно, что распределение CPU к выполнению каждого действия по сравнению с предыдущим этапом
См. замечание к началу отчёта.

2020-10-22 12:08 UTC, incubos commented on report/hw4.md
> + По сравнению с предыдущим этапом выделение памяти в Session.process увеличилось, поскольку необходимо проксировать
Где проксирование в профиле? См. замечание к началу отчёта.

2020-10-22 20:46 UTC, zvladn7 commented
Вообщем-то проблема была немного в другом. Нагружал я кластерную конфигурацию, однако распределение на `hash ring` было написано плохо, поэтому получалось так, что все данные записывались на одну ноду (по счастливой случайности это оказалась именно та нода, которую я нагружал, поэтому HttpClient на flame graph и не проявлялся). Переписал распределение по хэш кольцу, теперь оно достаточно хорошее, и все работает как надо, так что все ноды нагружаются приблизительно одинаково, что я протестировал, поочередно нагрузив их и попрофилировав их. [Обновил анализ нагрузочного тестирования](https://github.com/zvladn7/2020-highload-dht/blob/stage4/report/hw4.md)

2020-10-22 20:47 UTC, zvladn7 commented on report/hw4.md
> +В целом видно, что распределение CPU к выполнению каждого действия по сравнению с предыдущим этапом
поправил отчет

2020-10-22 20:47 UTC, zvladn7 commented on report/hw4.md
> + По сравнению с предыдущим этапом выделение памяти в Session.process увеличилось, поскольку необходимо проксировать
поправил отчет

2020-10-22 20:48 UTC, zvladn7 commented on report/hw4.md
> +# Нагрузочное тестирование с помощью wrk2
Была кластерная, однако были проблемы с распределением по хэш кольцу, поэтому все данные писались на одну ноду

2020-10-24 14:56 UTC, zvladn7 commented
Понял, что прошлым коммитом случайно сломал build, заметил, когда приступил к 5 этапу) Сейчас все ок)

2020-10-25 12:33 UTC, incubos requested changes
- Непонятен алгоритм `ServiceTopology` -- нужны пояснения
- Непонятно, почему подозрение в отчёте пало на GC, всё гораздо проще -- в случае проксирования приходится делать больше работы

2020-10-25 12:33 UTC, incubos commented on report/hw4.md
> +работы `GC`, поскольку в данном случае некоторые запросы необходимо проксировать, а значит
Что именно указывает на GC?

2020-10-25 12:33 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +    private static final int HASH_STEP_VALUE = 2121;
Что это за магическая константа?

2020-10-25 12:33 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +    private static final Logger log = LoggerFactory.getLogger(AsyncService.class);
Неправильный класс.

2020-10-25 12:33 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        final StringBuilder virtualNode = new StringBuilder(node).insert(OFFSET_FOR_NODE_HASH_VALUE, hashValue);
Я не смог понять, что здесь происходит. Можете прокомментировать построчно?

2020-10-25 12:33 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
>              hashRing.put(hash, node);
Коллизий по `hash` быть не может?

2020-10-25 14:34 UTC, zvladn7 commented on report/hw4.md
> +работы `GC`, поскольку в данном случае некоторые запросы необходимо проксировать, а значит
В начале отчёта я указал, что по сравнению с предыдущим этапом количество запросов в секунду уменьшил в 2 раза, понимая, что около 2/3 запросов будут проксироваться на другие ноды(ну и также проверив экспериментально, что такой большой `rate` сервер просто не выдерживает). Собственно, как я думал, что это и есть признак, который выскакивает за счёт проксирования. Также, насколько я понимаю `GangWorker::loop` на `flame graph` - это же GC? Он по сравнению с предыдущим этапом увеличился немного больше, чем в 2 раза на CPU flame graph'e. И еще один факт, который стал меня наталкивать на то, что это все таки GC это то, что при 100% на `Latency Distribution ` в данном этапе получилось `200ms` (иногда получалось поменьше, но не на много) в сравнении с `41ms` на прошлом этапе. По логике, если даже представить, что все запросы проксируются на другие ноды, то есть заново происходит вызов всех методов, то увеличении `latency` должно было быть примерно в  2 раза(возможно чуть больше, так как стало немного больше исполняемого кода по пути), то есть около `80ms`, однако фактически я получил 4-5 кратный прирост.

2020-10-25 14:37 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +    private static final int HASH_STEP_VALUE = 2121;
Рандомно взятое число, которое необходимо для более хорошего хэш распределния

2020-10-25 14:41 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +    private static final Logger log = LoggerFactory.getLogger(AsyncService.class);
исправил

2020-10-25 14:42 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
>              hashRing.put(hash, node);
нет, в методе `calculateHash` в цикле `while` проверяется возможность коллизий, и если она происходит, то `hash` пересчитывается, соответственно на выходе получаем уникальный хэш, которого в `hashRing` еще не было

2020-10-25 14:51 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        final StringBuilder virtualNode = new StringBuilder(node).insert(OFFSET_FOR_NODE_HASH_VALUE, hashValue);
Берем url ноды и вствляем в нее на `OFFSET_FOR_NODE_HASH_VALUE=10`  `hashValue` - это рандомно выбранное мной число(2121), которое умноженно на порядковый номер ноды, прикрепляемой на `hashRing  `

2020-10-25 14:51 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        virtualNode.insert(i, i);
для разброса виртуальных нод одной ноды в каждую из них вставляю порядковый номер этой виртуальной ноды. Если бы вставлял просто число в начало или конец, то хэш коды всех виртуальных нод были бы очень похожи

2020-10-25 14:51 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        int hash = virtualNode.toString().hashCode();
соответственно беру хэш код от преобразованной строки

2020-10-25 14:51 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        while (hashRing.containsKey(hash)) {
В случае если есть коллизия, то пересчитываю хэш код, изменяя при этом строку еще раз вставляя порядковый номер виртуальный ноды(фактически повторяю второй шаг метода)

2020-10-25 14:51 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        final StringBuilder virtualNode = new StringBuilder(node).insert(OFFSET_FOR_NODE_HASH_VALUE, hashValue);
да. сейчас попробую. Вообщем-то, наверное, действительно не самое очевидное решение)
Описал решение ниже.

2020-10-27 09:40 UTC, incubos commented on report/hw4.md
> +работы `GC`, поскольку в данном случае некоторые запросы необходимо проксировать, а значит
Именно такие рассуждения и хочется видеть в отчёте.

2020-10-27 10:41 UTC, incubos commented on report/hw4.md
> +По результатам профилирования видно, что расход CPU по сравнению с предыдущим этапом вырос
Нужно прояснить, пока не поздно, что расход CPU не "вырос", а **перераспределился**. `async-profiler` как и все остальные сэмплирующие профайлеры просто регулярно снимает stack trace потоков, которые находятся на CPU, и представляет сагрегированные результаты, которые позволяют нам понять, какой код исполнялся, но ничего не говорят о расходе CPU как таковом.

2020-10-27 10:41 UTC, incubos commented on report/hw4.md
> +этапом. 12.28% `sendResponse` в `ServiceHelper.proxy` говорит нам о том, что чуть меньше половины
Поясните, пожалуйста, как вы перевели долю CPU сэмплов `process()` и `proxy()` в количество отпроксированных запросов?

2020-10-27 10:41 UTC, incubos commented on report/hw4.md
> +лишь результатом увеличения общего значения использования CPU, а значит и знаменателя при их расчете.
Мы ведь ничего не знаем про увеличение "общего значения использования CPU" или вы как-то оценивали общее потребление CPU другими тулами?

2020-10-27 10:41 UTC, incubos commented on report/hw4.md
> +По сравнению с предыдущим этапом появилась значительная блокировка, 13.27%) при ожидании ответа на запросы
Почему вы так решили? Блокировка возникает не при ожидании ответа на запросы, а при попытке получить соединение из пула (`Pool.borrowObject()`) и вернуть соединение в пул (`Pool.returnObject()`). У вас же есть код `one-nio`.

2020-10-27 10:41 UTC, incubos commented on report/hw4.md
> +в прошлом же этапе наблюдался более спокойный рост(что опять же можно списать на работу сборщика).
Всё-таки, я бы не списывал всё на GC (хоть отчасти это и верно) -- это слишком удобно. В случае проксирования всё становится гораздо сложнее, потому что на задержку обработки клиентского запроса уже влияют переходные процессы **в двух нодах** (в т.ч. GC), а также взаимодействие между ними.

2020-10-27 10:41 UTC, incubos commented on report/hw4.md
> +запросы приходится проксировать на другие сервисы, а, следовательно, иногда обрабатывать дважды.
Можете пояснить про "иногда обрабатывать дважды"? Вы же профилируете ноду, по которой стреляете через `wrk2`? Она в такой конфигурации обрабатывает только запросы от клиента (т.е. `wrk2`), разве нет?

2020-10-27 10:41 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +    private static final int HASH_STEP_VALUE = 2121;
Давайте упростим?

2020-10-27 10:41 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        final StringBuilder virtualNode = new StringBuilder(node).insert(OFFSET_FOR_NODE_HASH_VALUE, hashValue);
Давайте упростим?

2020-10-27 10:41 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
>              hashRing.put(hash, node);
Давайте упростим?

2020-10-27 10:41 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        final StringBuilder virtualNode = new StringBuilder(node).insert(OFFSET_FOR_NODE_HASH_VALUE, hashValue);
Давайте упростим?

2020-10-27 10:41 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        virtualNode.insert(i, i);
Давайте упростим?

2020-10-27 10:41 UTC, incubos commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
> +        while (hashRing.containsKey(hash)) {
Давайте упростим?

2020-10-27 10:42 UTC, incubos commented on report/hw4.md
> +сократилось в 2 раза. Также видно, что 1% запросов требует большей задержки, чем 99%. Можно предположить,
Видимо, здесь имелось в виду что-то другое и просто выбрана неудачная формулировка?

2020-10-27 10:44 UTC, incubos requested changes
- Есть вопросы по отчёту -- ждём разъяснений
- Реализацию `ConstentHashing` нужно упростить -- см. замечания (перестреливать не нужно, достаточно прогнать тесты -- в следующем этапе обстреляем)

2020-10-27 10:49 UTC, incubos commented
> * Есть вопросы по отчёту -- ждём разъяснений
> * Реализацию `ConstentHashing` нужно упростить -- см. замечания (перестреливать не нужно, достаточно прогнать тесты -- в следующем этапе обстреляем)

Ждать исправлений до конца дня или принимаем с замечаниями за меньшие баллы?

2020-10-27 10:53 UTC, zvladn7 commented
> > * Есть вопросы по отчёту -- ждём разъяснений
> > * Реализацию `ConstentHashing` нужно упростить -- см. замечания (перестреливать не нужно, достаточно прогнать тесты -- в следующем этапе обстреляем)
> 
> Ждать исправлений до конца дня или принимаем с замечаниями за меньшие баллы?

Постараюсь исправить, как до дома из Универа доберусь

2020-10-27 17:28 UTC, zvladn7 commented on report/hw4.md
> +этапом количество запросов, обрабатываемых за секунду и укладывающихся в приемлемый `latency`
да, именно так

2020-10-27 17:31 UTC, zvladn7 commented on report/hw4.md
> +этапом количество запросов, обрабатываемых за секунду и укладывающихся в приемлемый `latency`
Насколько я для себя представляю - это, когда 99% запросов укладываются в секунду. Почему-то у меня это в голове отложилось: либо где-то вычитал, либо на лекции какой-то кто-то говорил. Ну и наверное, это все таки логично, потому что пользователь вряд ли будет пользоваться таким сервисом, где регулярно ответы приходят с задержкой > 1s

2020-10-27 17:35 UTC, zvladn7 commented on report/hw4.md
> +сократилось в 2 раза. Также видно, что 1% запросов требует большей задержки, чем 99%. Можно предположить,
Вообщем-то да, имелось в виду немного другое. Я хотел сказать, что на этом и предыдущим этапе 99% запросов имели схожие распределения, в то время как оставшийся 1% достаточно явно изменился.

2020-10-27 17:48 UTC, zvladn7 commented on report/hw4.md
> +этапом. 12.28% `sendResponse` в `ServiceHelper.proxy` говорит нам о том, что чуть меньше половины
По результатам профилирования видим, что sendResponse в методе  process - это 13.93%, в методе proxy - 12.28%. Соответственно, так как предположительно для отправки ответа требуется примерно одинаковая доля CPU, то сопоставив две величины можно заметить, что 12.28/(13.93+12.28) * 100% ~ 47%. Или так лучше тоже не рассчитывать ничего?

2020-10-27 18:01 UTC, zvladn7 commented on report/hw4.md
> +лишь результатом увеличения общего значения использования CPU, а значит и знаменателя при их расчете.
Мне показалось это очевидным, так как по флейм графу видно, что достаточно большую долю CPU занимает ServiceHelper.proxy, в том числе HttpClient.invoke, чего на прошлом этапе не было.

2020-10-27 18:01 UTC, zvladn7 commented on report/hw4.md
> +лишь результатом увеличения общего значения использования CPU, а значит и знаменателя при их расчете.
Дополнительными тулами не обследовал

2020-10-27 18:12 UTC, zvladn7 commented on report/hw4.md
> +запросы приходится проксировать на другие сервисы, а, следовательно, иногда обрабатывать дважды.
Обрабатывать дважды - не буквально, я имею в виду то, что при проксировании  все вызовы методов повторяются. Да действительно стреляем мы по одной ноде с помощью wrk2. Но профилируем же мы не отдельную ноду, а целый процесс java, в котором находятся все 3 ноды, соответственно, насколько я понимаю, на flame graph видна общая картина.

2020-10-27 18:12 UTC, zvladn7 commented on report/hw4.md
> +запросы приходится проксировать на другие сервисы, а, следовательно, иногда обрабатывать дважды.
Или есть какая-то возможность профилировать одну ноду?

2020-10-27 18:32 UTC, zvladn7 commented on report/hw4.md
> +По сравнению с предыдущим этапом появилась значительная блокировка, 13.27%) при ожидании ответа на запросы
Да, действительно, разобрался, спасибо! как то я оплошал, когда комментировал данный flame graph

2020-10-27 18:33 UTC, zvladn7 commented on report/hw4.md
> +в прошлом же этапе наблюдался более спокойный рост(что опять же можно списать на работу сборщика).
хорошо, учту в следующих этапах

2020-10-27 18:33 UTC, zvladn7 commented on src/main/java/ru/mail/polis/service/zvladn7/ServiceTopology.java
>          for (final String node : nodeSet) {
обсудили данный момент в личных сообщениях, теперь использую мур мур из `one-nio`

2020-10-28 09:52 UTC, incubos commented on report/hw4.md
> +запросы приходится проксировать на другие сервисы, а, следовательно, иногда обрабатывать дважды.
Да, всё верно. Вопрос снят.

2020-10-28 09:52 UTC, incubos commented
Принято.

2020-10-28 09:52 UTC, closed without merging