Stage 4
polis-mail-ru/2020-highload-dht pull request #98
Opened 2020-10-19 19:01 UTC by suhova

2020-10-20 13:36 UTC, incubos requested changes
- Rendezvous hashing огонь!
- Отсутствуют результаты нагрузочного тестирования, профилирования и их анализ
- Есть небольшие замечания по коду

2020-10-20 13:36 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> - * Copyright 2020 (c) Odnoklassniki
Зачем это? :)

2020-10-20 13:36 UTC, incubos commented on src/main/java/ru/mail/polis/dao/Record.java
> -public final class Record implements Comparable<Record> {
Вы собираетесь наследоваться?

2020-10-20 13:36 UTC, incubos commented on src/main/java/ru/mail/polis/dao/Record.java
> +    Record(
Есть же factory-метод `of()`.

2020-10-20 13:36 UTC, incubos commented on src/main/java/ru/mail/polis/service/ServiceFactory.java
> +        return new MoribundService(
Держимся!

2020-10-20 13:36 UTC, incubos commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +        executor.execute(() -> {
Метод очень легковесный, поэтому мало смысла отправлять его обработку в пул потоков.

2020-10-20 13:36 UTC, incubos commented on src/main/java/ru/mail/polis/service/suhova/MoribundService.java
> +        executor.execute(() -> {
Аналогично `status()`.

2020-10-20 13:36 UTC, incubos commented on src/test/java/ru/mail/polis/dao/BasicTest.java
> -import ru.mail.polis.Record;
Лучше reference классы вообще не трогать. Изменения тестов в PR привлекают чрезмерное внимание на ревью.

2020-10-20 13:42 UTC, suhova commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> - * Copyright 2020 (c) Odnoklassniki
Последствия переноса кода с того семестра, я полагаю)

2020-10-20 13:55 UTC, suhova commented on src/test/java/ru/mail/polis/dao/BasicTest.java
> -import ru.mail.polis.Record;
Не совсем поняла, как тогда быть, есть путь в импорте изменился?

2020-10-20 17:44 UTC, suhova commented
### Результаты профилирования
**Обстрел put-ами**
Параметры: -t64 -c64 -R8000

```
 Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.60ms  656.08us  13.54ms   65.35%
    Req/Sec   132.07     50.15   300.00     70.63%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.58ms
 75.000%    2.07ms
 90.000%    2.50ms
 99.000%    3.08ms
 99.900%    3.42ms
 99.990%    5.21ms
 99.999%    8.73ms
100.000%   13.54ms
----------------------------------------------------------
 960037 requests in 2.00m, 69.99MB read
Requests/sec:   8000.40
Transfer/sec:    597.22KB
```
По времени, по сравнению с прошлым этапом, значимой просадки не наблюдаются. 8000 запросов в секунду вывозит, но из 9000 осиливает только ~8400. 100.000% -  13.54ms вполне приемлемое время.

ALLOC
11% - выяснение ноды по ключу, рандеву хэширование (на этапе с шардированием станет больше, но пока живём)
13% - формирование респонса
15% - вставка в DAO
46% - доля сетевого взаимодействия не особо изменилась при добавлении проксирования. Видимо здесь промежуток времени, когда proxy() вызывался не очень часто (см. ALLOC при обстреле get-ами) и тем самым не откусил свой процент.
<img width="1378" alt="allocput4" src="https://user-images.githubusercontent.com/45993488/96606853-65931d80-1300-11eb-8ad4-9dd06136f4cc.png">

CPU
1% - вставка в DAO (каждый раз забавно, что при обстреле путами, пут отжирает минимум cpu)
6% - формирование респонса
11% - чтение из сокета
22% - обеспечение работы пула экзекуторов (опять не прикольно, что работа экзекутора - 7%, а обёртка их в BlockingQueue - в 3 раза больше)
26% - отправка респонса
За несколько прогонов не было построено графа, который значимо бы отличался по CPU от прошлого этапа -> разбивка по трём нодам погоды не сделала.
<img width="1417" alt="cpuput4" src="https://user-images.githubusercontent.com/45993488/96606856-66c44a80-1300-11eb-9f6d-2b4feda4e32e.png">

LOCK
54% - под локом на каком-то из экзекуторов сервис пытается отослать респонс
46% - ArrayBlockingQueue, в которой лежат экзекуторы
<img width="1397" alt="lockput4" src="https://user-images.githubusercontent.com/45993488/96606859-675ce100-1300-11eb-880b-c93719668c78.png">

Обстрел get-ами
Параметры: -t16 -c16 -R8000

```
 Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.60ms  657.38us   9.22ms   65.00%
    Req/Sec   132.05     50.22   222.00     70.58%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.58ms
 75.000%    2.08ms
 90.000%    2.50ms
 99.000%    3.07ms
 99.900%    3.39ms
 99.990%    4.57ms
 99.999%    7.59ms
100.000%    9.23ms
----------------------------------------------------------
  960031 requests in 2.00m, 74.19MB read
Requests/sec:   8000.53
Transfer/sec:    633.11KB
```
8000 requests/sec из 8000 обещанных. _SUCCESS

ALLOC
3% - выяснение ноды по ключу
5% - формирование реквеста
11% - поиск в DAO
31% - чтения из селекторов
49% - проксирование... Казалось бы, это просто метод, дублирующий запрос на указанный порт, но видимо invoke() для установки соединения нужно нормально так отхватить памяти. Вообще неожиданно, что будет такая большая доля.
<img width="1392" alt="allocget4" src="https://user-images.githubusercontent.com/45993488/96606838-62982d00-1300-11eb-90a5-1095f16dc1de.png">

CPU
Искала следы проксирования на CPU, но картинка аналогичная прошлому этапу, зацепиться вроде бы не за что.
<img width="1369" alt="cpuget4" src="https://user-images.githubusercontent.com/45993488/96606855-662bb400-1300-11eb-8d5e-863f4844522c.png">

LOCK
Тут тоже ничего нового. Под локами работают пул экзекуторов, сам get и отправка респонса.
<img width="1400" alt="lockget4" src="https://user-images.githubusercontent.com/45993488/96606857-675ce100-1300-11eb-8934-af31bd3810d3.png">

2020-10-22 12:11 UTC, incubos commented on src/test/java/ru/mail/polis/dao/BasicTest.java
> -import ru.mail.polis.Record;
Разве не вы переместили класс `Record`? Тут он лежит на своём месте: https://github.com/polis-mail-ru/2020-highload-dht/blob/master/src/main/java/ru/mail/polis/Record.java

2020-10-22 12:13 UTC, incubos commented
> ### Результаты профилирования
> ...
> <img alt="lockget4" width="1400" src="https://user-images.githubusercontent.com/45993488/96606857-675ce100-1300-11eb-8934-af31bd3810d3.png">

Вкомитьте, пожалуйста, отчёт отдельным файлом в MarkDown, чтобы можно было комментировать построчно. Кроме того, можно не тратить время на PNG и вставлять ссылки прямо на SVG -- они нормально рендерятся в браузере.

2020-10-22 12:20 UTC, incubos requested changes
> ### Результаты профилирования

- Интересует также качественный анализ перцентилей времени ответа по сравнению с предыдущим этапом (про throughput вы написали)
- Ждём отчёт в markdown -- есть что обсудить

2020-10-22 12:20 UTC, incubos commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> -/*
Удалить copyright -- это мощно.

2020-10-22 19:12 UTC, suhova commented
[добавлены результаты профилирования или прощай зелёная галочка](https://github.com/suhova/2020-highload-dht/blob/stage4/reports/stage4.md)

2020-10-22 19:16 UTC, suhova commented on src/main/java/ru/mail/polis/dao/DAOFactory.java
> -/*
Вернула, хоть теперь на меня повышает голос codeclimate.

2020-10-25 13:01 UTC, incubos requested changes
На профилях `PUT` нагрузки не видно проксирования -- это вызывает вопросы (тем более, что на `GET` нагрузке всё предсказуемо). Попробуйте отладить или добавить логов, ибо что-то идёт не так.

2020-10-25 17:45 UTC, suhova commented on reports/stage4.md
> +46% - доля сетевого взаимодействия не особо изменилась при добавлении проксирования. Видимо здесь промежуток времени, когда proxy() вызывался не очень часто (см. ALLOC при обстреле get-ами) и тем сам
Функция выбора ноды по ключу почти всегда возвращала одну и ту же ноду. После её исправления проблема ушла. Скрипты и правда не закоммитились, теперь добавила https://github.com/suhova/2020-highload-dht/tree/stage4/wrk

2020-10-25 17:48 UTC, suhova commented
[Новые результаты профилирования после изменения способа вычисления хэшкодов](https://github.com/suhova/2020-highload-dht/blob/stage4/reports/stage4.md)

2020-10-25 17:50 UTC, suhova commented on reports/stage4.md
> +С шардированием get замедлился процентов на 20-30. Тут разница побольше, но ведь терпимо же?)
Результаты после исправления и предположение, почему возникала разница во времени в новом отчёте :)

2020-10-26 17:41 UTC, incubos commented
Принято.

2020-10-26 17:41 UTC, closed without merging