Task 4
polis-mail-ru/2020-highload-dht pull request #99
Opened 2020-10-19 19:45 UTC by PolinaShneider

2020-10-22 18:15 UTC, vaddya requested changes
В целом все хорошо, небольшие замечания по реализации.

По профилированию:
- Давайте дальше профилировать без разделения на потоки (`-t`) в `async-profiler`.
- Немного напрягает деградация на порядок latency PUT-запросов, при том что GET-запросы не изменились. Интересно, с чем это связано

2020-10-22 18:15 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Topology.java
> +    Boolean isSelfId(@NotNull final String nodeId) {
`boolean`?

2020-10-22 18:15 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Topology.java
> +    private final List<String> clusterNode;
`clusterNodes`? Или просто `nodes`

2020-10-22 18:15 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Topology.java
> +        return clusterNode.get((key.hashCode() & Integer.MAX_VALUE) % clusterNode.size());
А зачем `& Integer.MAX_VALUE` делать?

2020-10-22 18:15 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceAsyncImpl.java
> +            request.addHeader("X-Proxy-For: " + nodeId);
Давайте литерал в константы вынесем (`private static final`)

2020-10-22 18:15 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceAsyncImpl.java
> +                clientMap.put(node, new HttpClient(new ConnectionString(node + "?timeout=100")));
Лучше избегать литералов в коде, давайте вынесем значение таймаута в константу?

2020-10-22 18:15 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceAsyncImpl.java
> +                case Request.METHOD_GET: {
По [гугловым стайлгайдам](https://google.github.io/styleguide/javaguide.html#s4.8.4-switch) кейсы не надо оборачивать в скоуп (`{}`), предлагаю этого придерживаться. Ну и будет симметрично с веткой `default`.

2020-10-22 18:15 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceAsyncImpl.java
> +        this.executor.execute(() -> {
Здесь может прилететь `RejectedExecutionException` из-за ограниченной очереди, и клиент не получит никакого ответа. Это же справедливо для `put`/`delete`

2020-10-22 18:15 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceAsyncImpl.java
> +            } catch (IOException e) {
```java
dao.upsert(...);
session.sendResponse(...);
```
И первая, и вторая строка могут бросить `IOException`. Но исключение из первой строки мы хотим поймать и вернуть клиенту 500 (`handleError`), это явно ошибка на стороне DAO. А исключение из второй строчки скорее нужно только залогировать, потому что нам явно не удается отправить ответ (сокет закрыт?) и нет смысла отправлять ещё один. Предлагаю разделить эти два сценария обоработки ошибок.

2020-10-23 18:10 UTC, PolinaShneider commented on src/main/java/ru/mail/polis/service/Topology.java
> +        return clusterNode.get((key.hashCode() & Integer.MAX_VALUE) % clusterNode.size());
На случай, если `key.hashCode()` отрицательным будет. Говорилось об этом в лекции (примерно 1:05:00).

![image](https://user-images.githubusercontent.com/15448200/97038775-ff163580-1573-11eb-8438-731327aaed4f.png)

2020-10-23 18:11 UTC, vaddya commented on src/main/java/ru/mail/polis/service/Topology.java
> +        return clusterNode.get((key.hashCode() & Integer.MAX_VALUE) % clusterNode.size());
Все так

2020-10-23 21:47 UTC, PolinaShneider commented
Замечания поправила, в том числе и отчет. После повторных пушей в ветку стали падать тесты в трависе, даже если откатить изменения, и вернуть версию, которая была «зеленой». Локально с тестами и сборкой все ок.

2020-10-24 09:49 UTC, vaddya approved these changes
Хороший анализ результатов профилирования. Несколько минорных замечаний, поправьте их к следующему этапу, пожалуйста.

Принято.

2020-10-24 09:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceAsyncImpl.java
> +        this.executor.execute(() -> {
Все хорошо, только исключение вылетет при вызове `execute`, а не внутри него.
То есть надо
```java
try {
    this.executor.execute(() -> {
        ...
    }
} catch (RejectedExecutionException e) {
    ...
}
```

2020-10-24 09:49 UTC, vaddya commented on src/main/java/ru/mail/polis/service/ServiceAsyncImpl.java
> +    private static final String PROXY_HEADER = "X-Proxy-For:";
Статик поля лучше размещать выше пропертей (нестатических полей).

2020-10-24 09:50 UTC, closed without merging